### ISSUE TITLE
Cannot `brew update`

### ISSUE THREAD

**Issue by Jamesking56** [Homebrew/homebrew-core#10067]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

When I run `brew update` it reads back:

````
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Library/Taps/flutter/homebrew-flutter failed!
````

This also occurs when running `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`

**Comment by ilovezfs** [comment]
Sounds like a messed up ~/.gitconfig or ~/.ssh/config

**Comment by Jamesking56** [comment]
@ilovezfs is there any way I can syntax check them?

**Comment by ilovezfs** [comment]
@Jamesking56 well I'd start out with the sledgehammer.

mv ~/.gitconfig ~/gitconfig
mv ~/.ssh/config ~/sshconfig

and try again

**Comment by Jamesking56** [comment]
I ran those two commands and now got this (same error but more output?):

````
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/flutter/homebrew-flutter failed!
Updated 1 tap (homebrew/core).
==> Updated Formulae
go                                                                  godep                                                               govendor
````

**Comment by ilovezfs** [comment]
try `brew untap flutter/flutter` and then try again.

**Comment by Jamesking56** [comment]
@ilovezfs Yes! Now I get:

`Already up-to-date.` when running `brew update`

**Comment by ilovezfs** [comment]
Great. Looks like the cause is that they deleted the tap.

https://github.com/flutter/homebrew-flutter no longer exists

**Comment by Jamesking56** [comment]
Thanks for the help. Closing 👍

**Comment by JoeCostanzo** [comment]
@ilovezfs 's comment is prescient because you'd be AMAZED how frequently it's completely OMITTED to just show an explicit error message.

"Fetching `x` failed" is NOT the same as saying "`x` no longer exists.".. if the error message would just say that, (or even better, automatically clean up the out-of-date dependency),  we could a lot further without searching around aimlessly for why something isn't updating.

**Comment by MikeMcQuaid** [comment]
@JoeCostanzo Please watch your tone. Homebrew is made by volunteers in our spare time and available as-is; bugs and all. If you'd like to submit a pull request to improve that behaviour: please go ahead and I'll review it.

**Comment by JoeCostanzo** [comment]
@MikeMcQuaid my apologies.. I just was a little frustrated, because in my case brew update was failing looking for `...Taps/homebrew/homebrew-science`.

Whether that formulæ even exists anymore, the above comment helped me out because I had been searching for eons as to why brew wouldn't just update, but instead was giving this ambiguous error. Upon seeing @ilovezfs 's message, it occurred that I can just uninstall that formulæ altogether and not have to worry about any errors, because I don't recall why I needed it to being with, and I wasn't using it.

Maybe one day I'll have time to look into doing a PR like that. Thanks.

**Comment by MikeMcQuaid** [comment]
@JoeCostanzo Thanks, we appreciate the apology ❤️
