### ISSUE TITLE
Upgrade GnuPG to stable

### ISSUE THREAD

**Issue by infusion** [Homebrew/homebrew-core#1018]
Hi,

could you please upgrade the GnuPG formula to stable (2.0) or modern (2.1) instead of classic (1.4)? Thunderbird doesn't support the legacy version anymore and I don't want to use Mac GPG instead, when brew is capable of installing it as well.

Thanks
Robert

**Comment by DomT4** [comment]
You're looking for either:

`brew install gnupg2` or `brew install homebrew/versions/gnupg21` depending on whether you want 2.x or 2.1.x.

The vanilla `gnupg` formula will likely be moved off classic eventually but there's still a fair bit of demand for the "no-dependencies" version of GnuPG.

**Comment by maletor** [comment]
Judging from the number of issues and comments it seems like all the demand is for the modern GPG -- version 2.1.

**Comment by DomT4** [comment]
Pretty sure there have been less than a handful of Issues, and maybe 10-15 comments on the situation, compared to 6k `gnupg2` installations over the last few months and ~800 `gnupg21` installations. _"All the demand"_ may be a touch of an overstatement.

**Comment by infusion** [comment]
I'm fine with the `gnupg2` - but you have to know it and it's quite unintuitive. Are there any plans on upgrading the main line any time in the future?

**Comment by DomT4** [comment]
To be fair, I'm not sure GnuPG is ever simple, even with the newer version. It's not exactly the easiest software to get into bed with, as much as I use it & encourage others to use it.

It's unlikely to take the `gnupg2` formula name for quite some time because it's a mighty pain for users to reverse if they don't like the changes, particularly around the keychain format. That's a large part of why we haven't forced it onto everyone yet.

In the short-to-medium term `gnupg21` is likely to move to `homebrew/core` rather than `homebrew/versions`, along with some other versions as we tweak our policy there, but that's a work in progress & there are steps necessary to take around our core code to make reverse migration _(tap to core, rather than the standard core to tap)_ gentler on users.

**Comment by maletor** [comment]
> In the short-to-medium term gnupg21 is likely to move to homebrew/core rather than homebrew/versions

This sounds about right. Thanks, @DomT4.
