### ISSUE TITLE
Bazaar package doesn't include Python library (like the Canonical release does)

### ISSUE THREAD

**Issue by joedborg** [Homebrew/homebrew-core#10249]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

The package `bazaar` does not include the Python libraries, as the Canonical release does.  This means, you cannot use `bzrlib`

```
import bzrlib
    ImportError: No module named bzrlib
```

**Comment by JCount** [comment]
I think that the `bazaar` formula does include the Python libraries. (Assuming you have your HOMEBREW_PREFIX set to `/usr/local`), try looking in `/usr/local/opt/bazaar/libexec/bzrlib/`.

**Comment by joedborg** [comment]
Hi @JCount, you're right, thanks.  Should it, therefore, be a bug that the install doesn't put this in the PYTHONPATH?

**Comment by JCount** [comment]
In this case, I personally think not, simply because the formula is designed to install `bazaar` to be used through a command line interface, and it is set up to be compatible with plugins. I am not certain how many users use/would use it the way you are by directly importing it in python. However, if you disagree, feel free to open a PR to do something like that, and it can more properly be discussed there.
