### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: location

### ISSUE THREAD

**Issue by myzinsky** [Homebrew/homebrew-core#102555]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

When I want to compile an application using the qt5 formulae I run into the following error:

```shell
Project ERROR: Unknown module(s) in QT: location
```

Is this location package missing in the Qt5 formulae

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to compile an application using the qt5 formulae

### What happened (include all command output)?

```
Project ERROR: Unknown module(s) in QT: location
```

### What did you expect to happen?

That it compiles

### Step-by-step reproduction instructions (by running `brew` commands)

Get:

```shell
git clone --recursive https://github.com/myzinsky/cloudLogOffline.git
cd cloudLogOffline/
mkdir build
qmake ../CloudLogOffline.pro
make -j
```

**Comment by SMillerDev** [comment]
Why do you think this is a homebrew bug?

**Comment by myzinsky** [comment]
I think that the Qt package in Home-brew is not complete.

**Comment by danielnachun** [comment]
Just to be clear, `qt` in Homebrew is now Qt6, while `qt@5` is for Qt5.  I don't know which version of Qt is required by https://github.com/myzinsky/cloudLogOffline, but I do see in the build logs for Qt 6.3.0 that we did not build `qtlocation`:
```
CMake Warning at qttranslations/translations/CMakeLists.txt:37 (message):
  Directory
  '/tmp/qt-20220524-35736-b56vre/qt-everywhere-src-6.3.0/qttranslations/translations/../../qtlocation/src'
  for qtlocation does not exist.  Skipping...
Call Stack (most recent call first):
  qttranslations/translations/CMakeLists.txt:105 (add_ts_targets)


CMake Warning at qttranslations/translations/CMakeLists.txt:44 (message):
  No source files located for qtlocation, skipping target creation
Call Stack (most recent call first):
  qttranslations/translations/CMakeLists.txt:105 (add_ts_targets)
```
It's very possible something similar happened with Qt5, and this does seem like something we should fix, though I don't have an explanation yet as to why those files are missing.  We are due for an upgrade of Qt5 to 5.15.4 so this is something we should take a look at when we work on that.

**Comment by myzinsky** [comment]
Yes, it's using qt5. So it would be very appreciated if you could add this :-)

**Comment by danielnachun** [comment]
Do you happen to have both the `qt` and `qt@5` formulae installed?  The reason I ask is because I tried to build cloudLogOffline with `qt@5` and it works on both macOS and Linux.  However, the tricky thing here is that `qt@5` is keg-only, so to invoke `qmake` for `qt@5`, you have to run `$(brew --prefix)/opt/qt@5/bin/qmake` instead of `qmake`.  If you also have `qt` installed and you just use `qmake`, it will try to use `qmake` from Qt6 instead, and as I posted above, we know `qtlocation` isn't being built for Qt6.  

Indeed on my macOS installation I do have `qt` and `qt@5` installed, and if I just run `qt`, I get the exact same error as you reported.  The good news here is that it probably means nothing is wrong with `qt@5`, you just have to make sure you use `$(brew --prefix)/opt/qt@5/bin/qmake` instead of `qmake`.  Ironically if we had built `qtlocation` for Qt6, you would likely have encountered other problems because cloudLogOffline requires Qt5.  Let me know if my suggested solution works and we can close this if that resolves the problems.
