### ISSUE TITLE
rock-runtime-php54 failed to build on 10.9.5

### ISSUE THREAD

**Issue by PSchwisow** [Homebrew/homebrew-core#1026]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [N/A] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Encountered error `Error: undefined method "cached_download' for #<ResourceStageContext:0x007fee12c3cd48>` while attempting to install rock-runtime-php54

Git of the brew logs: https://gist.github.com/PSchwisow/f090f1400985a0843cabac371fca6ca0

The tap being used is private, but the formula is the same as https://github.com/silas/rock/blob/master/contrib/homebrew/rock-runtime-php54.rb

**Comment by UniqMartin** [comment]
The failing formula is using a method (`Resource#cached_download`) that is not part of our public API, as is evident from the fact that it is undocumented. We cannot guarantee the stability of these undocumented methods. Essentially you're using a detail of our implementation that has changed recently.

Sorry, but because of this you will have to adapt the formula yourself to make it work without using that method, even more so because it is private (and the other public formula isn't maintained by us either). It is possible to work around this, but I'm not going to say how, because we cannot encourage this kind of usage. Please stick to our public and documented interfaces!

cc @apjanke as he authored the change and may be interested nonetheless (nothing actionable here).

**Comment by PSchwisow** [comment]
@UniqMartin I'm sorry, but it appears to be documented here: http://www.rubydoc.info/github/Homebrew/brew/Resource#cached_download-instance_method. If that is not the correct documentation for the public API, could you you provide a link to the correct documentation. I have been unable to find any useful information on how to replace this part of the formula with a supported equivalent.

**Comment by UniqMartin** [comment]
> I'm sorry, but it appears to be documented here: http://www.rubydoc.info/github/Homebrew/brew/Resource#cached_download-instance_method. If that is not the correct documentation for the public API, could you you provide a link to the correct documentation.

Yes, this is the official documentation. I'd say the method in question only appears there as part of an automatically generated listing, but there's not a single word that describes it. Admittedly, our documentation is not the best (both for our own use and for use by our formula authors) and thus we didn't actively hide the method or mark it as private. Help improving it is always welcome.

> I have been unable to find any useful information on how to replace this part of the formula with a supported equivalent.

I'm sorry to hear that. Resources are normally staged to a temporary directory or to a directory you specify to the `stage` method. Then you take the contents from there. What you're currently doing is trying to circumvent this mechanism and access the downloaded file directly. That's an implementation detail that could change in the future.

Also, have a look at <http://www.rubydoc.info/github/Homebrew/brew/>. There's this paragraph:

> The main class you should look at is the Formula class (and classes linked from there). That's the class that's used to create Homebrew formulae (i.e. package descriptions). Assume anything else you stumble upon is private.

**Comment by PSchwisow** [comment]
@UniqMartin Sorry, but I still don't understand how you "take the contents from there". How can I get the path for the downloaded file?

**Comment by UniqMartin** [comment]
> How can I get the path for the downloaded file?

You're not supposed to access the downloaded file directly. The supported way to do this is to stage your resource into your build directory (or wherever you need it) and then work from there. You have basically two options:

```ruby
# Option 1:
resource("name-of-resource").stage "target-directory"
```

This will extract the resource (which is usually some archive format like `.tar.gz`) into the given directory. If the resource is a file that isn't recognized as an archive, it is simply copied to the target directory.

```ruby
# Option 2:
resource("name-of-resource").stage do
  # Do things with the staged resource.
end
```

This will do the same like above, but instead of the specified target directory a temporary directory is used and before entering the code between `do` and `end` Homebrew will change to that directory. Thus you can use relative paths to access the file(s), run a `./configure` that might be contained in the resource or whatever else you need to do with it. Once the end of the block is reached, you're returned back to the previous directory and the temporary directory with everything that was extracted there is removed.

You'll find plenty of usage examples if you search for `stage` in our core formulae in <https://github.com/Homebrew/homebrew-core/tree/master/Formula>.
