### ISSUE TITLE
cpanminus Formula incorrectly uses System Perl

### ISSUE THREAD

**Issue by theory** [Homebrew/homebrew-core#103511]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config    
HOMEBREW_VERSION: 3.5.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2258ba5797c1ea8149a49673b5c080011c366237
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f21faeec4f43569420c680b88883799f6aaaecbe
Core tap last commit: 58 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
$ brew doctor
Your system is ready to brew.
```

As of 32916ec, the [cpanminus formula](Formula/cpanminus.rb) installs cpanm against the System Perl:

https://github.com/Homebrew/homebrew-core/blob/f21faeec4f43569420c680b88883799f6aaaecbe/Formula/cpanminus.rb#L21

This can break things. The [sqitch formula](/sqitchers/homebrew-sqitch/blob/main/Formula/sqitch.rb), for example, depends on the Hombrew perl and the cpanminus formula, installs some modules with cpanm, then when it uses the Homebrew Perl cannot find those modules. Note that `cpanm`'s shebang line points to the system perl:

``` shell
$ which 
head -1 /opt/homebrew/bin/cpanm

#!/usr/bin/perl5.30
``` 

I think this change either should be reverted or there needs to be a way to have `cpanm` use the Homebrew Perl instead of the system Perl.

Discovered while investigating sqitchers/homebrew-sqitch#55.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use cpanminus to install modules, including Module::Build, into the Homebrew Perl's INC paths rather than the system Perl. Or, more specifically, into a temporary directory (`"#{buildpath}/instutil"`) during a build/install. The Sqitch formula uses this technique to install modules it requires to build Sqitch.

### What happened (include all command output)?

cpanm reported Module::Build as already installed, because it's included with the system Perl.

### What did you expect to happen?

For `cpanm` to install perl Modules against the Perl in the path. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install cpanm perl
Warning: cpanminus 1.7046 is already installed and up-to-date.
To reinstall 1.7046, run:
  brew reinstall cpanminus
Warning: perl 5.34.0 is already installed and up-to-date.
To reinstall 5.34.0, run:
  brew reinstall perl
➜  homebrew-sqitch git:(main|✚1 cpanm --local-lib foo --notest Module::Build
Module::Build is up to date. (0.4231)
➜  homebrew-sqitch git:(main|✚1 perldoc -l Module::Build
No documentation found for "Module::Build".
```

**Comment by theory** [comment]
Note that the cpm formula still requires the Homebrew Perl:

https://github.com/Homebrew/homebrew-core/blob/8e1ba79e84f6959207cbe4db44526088b0962215/Formula/cpm.rb#L18

**Comment by SMillerDev** [comment]
I'm not sure where the homebrew core bug is here. It mostly seems like "homebrew core doesn't work the way I want my tap to work"

**Comment by theory** [comment]
It used to be that `cpanm` used the Homebrew Perl, and now it doesn't. This may be surprising to people who have relied on it to install modules against the Homebrew Perl up to now, including formulas like mine, which have relied on this behavior for many years. I've worked around it by switching to the cpm formula, but be aware that these to Perl module installers now have different behavior.

**Comment by carlocab** [comment]
Thoughts here, @Bo98?

**Comment by Bo98** [comment]
> It used to be that cpanm used the Homebrew Perl

I don't think so - I think it just had a shebang that used whatever the first Perl on the path was and this will have been system PErl in our CI. Recent builds will have enforced this further in the shebang.

I do agree that this particular formula can benefit from having a looser shebang than it is now, and the change of behaviour can be seen as not ideal. This formula is more of an exception rather than the norm, which is why you see what you see.

> there needs to be a way to have cpanm use the Homebrew Perl instead of the system Perl.

There is, due to how shebangs work. Under controlled build scripts where you have a fixed absolute path to Perl (e.g. via `configure` script), I generally recommend doing so anyway. But for the general case yeah it's probably better if we can make the shebang `/usr/bin/env perl`.

Not entirely sure the best way we'd do that however. I'd like to do it in a way that's not special cased for one particular formula. In general pinning to a specific Perl is intentional since there is often compatibility conerns if different versions of Perl are used.

**Comment by Bo98** [comment]
The behaviour _might_ be able to be avoided if it's `depend_on "perl"` in `on_linux` rather than `uses_from_macos` but I've not tested that.

**Comment by cho-m** [comment]
> The behaviour _might_ be able to be avoided if it's `depends_on "perl"` in `on_linux` rather than `uses_from_macos` but I've not tested that.

Not sure if that would work since issue is partly due to MakeMaker behavior.

MakeMaker is designed to do the same shebang modification as Homebrew. The CPAN tarball contains a script with `#!perl` and it gets overwritten to build-time perl (`#!/usr/bin/perl`). Homebrew then does another shebang rewrite and changes this to versioned path (`#!/usr/bin/perl5.30`). So, even if we avoid Homebrew's rewrite, it still points to system perl unless we manually rewrite it to PATH perl.

The only script that contains `#!/usr/bin/env perl` is from GitHub repo, which upstreams modifies to `#!perl` in Makefile.PL to feed into MakeMaker https://github.com/miyagawa/cpanminus/blob/devel/App-cpanminus/Makefile.PL#L17

**Comment by theory** [comment]
I think the behavior should be well-defined and documented, one way or the other.

**Comment by sidney** [comment]
I use the homebrew perl, installed some modules using cpan, switched to cpanminus, installed more modules. With this change in behavior, I don't have a way of running cpanm instead of cpan any more. Is the solution to use local::lib to put all modules in ~/perl5 and do a one-time reinstall of all modules? Is that the best practice anyway to make upgrades of the brew-installed perl version easier? If it is, then this issue should be addressed in documentation. For now, this breaks making the brew install of cpanminus being a simple switch from running cpan.

**Comment by theory** [comment]
Thank you!
