### ISSUE TITLE
Question: history of node formula using custom npm

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/homebrew-core#10485]
I'm trying to look into the history of issues with node's bundled npm; so as to understand why homebrew builds its own. However, the best I can find is a comment that merely [references](https://github.com/Homebrew/legacy-homebrew/issues/46131#issuecomment-157851654) a long history.

I've searched through issues on both homebrew-core and brew repos, without finding much that accurately describes the rationale for using a custom npm. (Other than Issues/PRs that continually refer to some heretofore long history.)

Are some of the issues that lead to this decision still documented somewhere? I'd like to look into whether these issues remain. Especially now that node has sufficiently stabilized since the wild west of pre 0.12 (and of course _The Days of the Fork, IOJS_).

**Comment by DomT4** [comment]
The skinny of the problem is that every time Homebrew has conceded some control over `npm` it has blown up in Homebrew's face, and that pattern being repeated over a period of years made it consistently undesirable to give away control. At least, there would have to be a fairly punchy reason for me to recommend doing so if ILZ pinged me and asked for my thoughts 😄.

I think it would be perfectly possible to something like:
```diff
diff --git a/Formula/node.rb b/Formula/node.rb
index eb3bcddb4c..10ae80da22 100644
--- a/Formula/node.rb
+++ b/Formula/node.rb
@@ -32,17 +32,9 @@ class Node < Formula
     fails_with :gcc => n
   end
 
-  # We track major/minor from upstream Node releases.
-  # We will accept *important* npm patch releases when necessary.
-  # https://github.com/Homebrew/homebrew/pull/46098#issuecomment-157802319
-  resource "npm" do
-    url "https://registry.npmjs.org/npm/-/npm-4.1.2.tgz"
-    sha256 "87f2c95f98ac53d14d9e2c506f8ecfe1d891cd7c970450c74bf0daff24d65cfd"
-  end
-
   def install
     # Never install the bundled "npm", always prefer our
-    # installation from tarball for better packaging control.
+    # installation for better packaging control.
     args = %W[--prefix=#{prefix} --without-npm]
     args << "--debug" if build.with? "debug"
     args << "--with-intl=system-icu" if build.with? "icu4c"
@@ -53,8 +45,6 @@ class Node < Formula
     system "make", "install"
 
     if build.with? "npm"
-      resource("npm").stage buildpath/"npm_install"
-
       # make sure npm can find node
       ENV.prepend_path "PATH", bin
       # set log level temporarily for npm's `make install`
@@ -62,22 +52,18 @@ class Node < Formula
       # unset prefix temporarily for npm's `make install`
       ENV.delete "NPM_CONFIG_PREFIX"
 
-      cd buildpath/"npm_install" do
+      cd buildpath/"deps/npm" do
         system "./configure", "--prefix=#{libexec}/npm"
         system "make", "install"
         # `package.json` has relative paths to the npm_install directory.
         # This copies back over the vanilla `package.json` that is expected.
         # https://github.com/Homebrew/homebrew/issues/46131#issuecomment-157845008
-        cp buildpath/"npm_install/package.json", libexec/"npm/lib/node_modules/npm"
+        cp "package.json", libexec/"npm/lib/node_modules/npm"
         # Remove manpage symlinks from the buildpath, they are breaking bottle
         # creation. The real manpages are living in libexec/npm/lib/node_modules/npm/man/
         # https://github.com/Homebrew/homebrew/pull/47081#issuecomment-165280470
         rm_rf libexec/"npm/share/"
-      end
-
-      if build.with? "completion"
-        bash_completion.install \
-          buildpath/"npm_install/lib/utils/completion.sh" => "npm"
+        bash_completion.install "lib/utils/completion.sh" => "npm" if build.with? "completion"
       end
     end
   end
```

But I'm not sure what the gain is there. You gain not having to download `npm`, but at the same time lose the ability to apply `npm` updates out-of-band, which has happened in the past such as https://github.com/Homebrew/legacy-homebrew/commit/1386e806fea5a87bcd6237b642b322a73421ca6d on a security issue, which Homebrew applied [11 days](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V012.md#2015-05-13-version-0123-stable) before `node` cut a release for the `0.12` branch Homebrew was using at the time.

Doing it that way also seems to open up some network usage during install for some reason:
```
npm verb request uri https://registry.npmjs.org/marked
npm verb request no auth needed
npm info attempt registry request try #1 at 6:00:03 PM
npm http request GET https://registry.npmjs.org/marked
npm http 200 https://registry.npmjs.org/marked
```

If you scrapped being able to apply out-of-band updates & manual configuration you could scrap almost everything and use the bundled `npm` and let `make install` dump it in `prefix/lib/node_modules`, which means you then need logic to handle that, which doesn't eliminate Homebrew's long-term collection of hacks to keep things stable & functioning.

**Comment by jasonkarns** [comment]
> updates out-of-band

Gotcha, so being able to apply updates out-of-band seems to be the biggest value-add.

Originally, the primary issue that got me down this line of research is recent behavior of npm run-script that issues warnings when the node binary that npm itself is running under is different than the node binary that the npm script is running under.

Separate from any of this, I was initially surprised that npm (and other global modules) are installed outside of the node installation. This behavior contradicts binary installs from nodejs itself (naturally), but also node version managers like nvm, nodenv, and nvs which all place global packages (like npm) _within_ the node installation directory itself.

That's not to say it's without good reason, but having the rationale documented is helpful. I do want to float the idea of allowing the user the option to use the bundled npm. Or to continue leaving homebrew in control of which npm is installed; but to install it in the node installation directory (conventional location). Both of these having their own drawbacks that warrant their own threads.

**Comment by DomT4** [comment]
>  I was initially surprised that npm (and other global modules) are installed outside of the node installation.

It's one of the few things that violates Homebrew's rules around this, but for a fair while trying to get `npm` to play completely nice in non-default locations was... not easy. Package managers packaging other package managers has an uncommon layer of complication, and where that happens generally it's rarely simple 😓.

The `lua` formulae for example are _way way_ too complicated in terms of providing `luarocks`, and even that doesn't work consistently; when Homebrew switched to allowing `/usr/local` to remain `root`-owned it effectively broke `luarocks`.

> This behavior contradicts binary installs from nodejs itself (naturally)

Aye, but as you allude to, `node` is operating by default under a globally-available prefix that's present in the `$PATH` by default, rather than being tucked away in a corner and then symlinked elsewhere. Homebrew has some unusual hurdles around that due to intentional design choices.

> but also node version managers like nvm, nodenv, and nvs which all place global packages (like npm) within the node installation directory itself.

These tools (almost?) universally play with the `$PATH` too though, which partly enables this behaviour. `nvm`'s general pattern of behaviour for example is something like `nvm install 7.7.0`, where that version is then glued to the front of your `$PATH`, and the only way that version changes is if you either explicitly run `nvm use xyz` or `nvm uninstall xyz`.

That kind of on-the-fly `$PATH` manipulation is something Homebrew doesn't do outside of `brew install` or `brew test`. Killing your old `node` installation with Homebrew is as simple as a `brew upgrade && brew cleanup`, which plenty of people have hardcoded as an alias for better or worse.

**Comment by jasonkarns** [comment]
> These tools (almost?) universally play with the $PATH too though, which partly enables this behaviour.

eh, seems a stretch. the only role the path manipulation plays is in determining what the NODE_PREFIX should be. from there, the available bins are those in `NODE_PREFIX/bin`. It doesn't do anything special with PATH and NODE_PREFIX/lib/node_modules. In that sense, it's very much like a typical install (symlink whatever is in PREFIX/bin into /usr/local/bin).

Which would mean that homebrew could just as easily install npm (presumably still the version it chooses, not necessarily the bundled one) to `NODE_PREFIX/lib/node_modules`, right? The */.bins within there are automatically symlinked into `NODE_PREFIX/bin` by npm. (I'm not quite sure how brew-installed npm knows to symlink subsequent global modules into `/usr/local/bin` from `/usr/local/lib/node_modules`. But presumably it would be the same even when those modules are installed into `NODE_PREFIX/lib/node_modules`.

> Killing your old node installation with Homebrew is as simple as a brew upgrade && brew cleanup

This isn't really true, since it leaves `/usr/local/lib/node_modules`, right?


I guess I'm wondering what the pros/cons are to installing npm to `NODE_PREFIX/lib/node_modules`.

Pros:
- follows convention of distributed node and node version managers;
- cleaned up automatically when node itself is removed
- inherently ties an npm with its associated node (thinking cellared, non-linked nodes)

Cons:
- global modules installed by npm don't carry between node versions (almost seems a Pro to me)
- probably missing something else...

**Comment by MikeMcQuaid** [comment]
If we can install `npm` inside the prefix, have it linked to `/usr/local/bin`, install our own version, allow it be upgradeable with `npm install -g npm` but keep node_modules in `HOMEBREW_PREFIX/lib/node_modules` that would be the best thing. @jasonkarns feel free to give that a go if it seems possible and piques your interest.

**Comment by DomT4** [comment]
> Which would mean that homebrew could just as easily install npm (presumably still the version it chooses, not necessarily the bundled one) to NODE_PREFIX/lib/node_modules, right?

Aye.

> (I'm not quite sure how brew-installed npm knows to symlink subsequent global modules into /usr/local/bin from /usr/local/lib/node_modules.

```ruby
npm_root = node_modules/"npm"
npmrc = npm_root/"npmrc"
npmrc.atomic_write("prefix = #{HOMEBREW_PREFIX}\n")
```

With the system you broadly suggested here If you were to `npm install -g xyz` that `xyz` package would end up in `/usr/local/Cellar/node/blah/lib/node_modules/blah` and then be symlinked to `/usr/local/Cellar/node/blah/bin` which of course is not in the `$PATH` by default and Homebrew doesn't go "_Oh there's a new file in bin, let's symlink that to HOMEBREW_PREFIX/bin automatically_", for better or worse.

That's what I was referring to with the Node version managers; they handle switching the paths around sensibly and quietly without user intervention; Homebrew does not, and beyond that, Homebrew is trying to push most caveats out of the door, so it's easy to foresee a situation where it's not really explained that to use Node like the version managers you have to manually play with your `$PATH`.

Now, Homebrew _could_ steal a page out of something like `nvm` and essentially write a source script for each version of `node` that when placed in your shell profile then handled ensuring the desired `node` and any `npm` packages installed were in your `$PATH` and I actually think that'd be a really cool system, but I think if I suggested that I might get glared at by both Mike and ILZ 😸.

> This isn't really true, since it leaves /usr/local/lib/node_modules, right?

Sorry, I was unclear here. I meant that under your proposed system without any further modifications a simple `brew upgrade && brew cleanup` would kill everything you'd installed with `npm` because it resided within the Cellar, even though you perhaps didn't specifically intend to upgrade `node` or even know there was a `node` upgrade pending.

> If we can install npm inside the prefix, have it linked to /usr/local/bin, install our own version, allow it be upgradeable with npm install -g npm but keep node_modules in HOMEBREW_PREFIX/lib/node_modules that would be the best thing.

This is a more easily obtained system. I'm unsure on how the dynamics of `npm install -g npm` here would play out if you were to `brew install node && npm install -g npm && brew unlink node && brew link node` since I don't think Homebrew would know it's safe to then overwrite the non-symlink `npm` in `HOMEBREW_PREFIX/bin`, but certainly I don't think it would be too much trouble, relatively.

**Comment by MikeMcQuaid** [comment]
> the non-symlink npm in HOMEBREW_PREFIX/bin

and to add to my list: `npm install -g npm` should somehow know that it should use the original npm location and not stick stuff in `/usr/local/bin` (`$PREFIX/bin` seems fine)
