### ISSUE TITLE
Too many formulae declare `fails_with :gcc`.

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-core#105130]
There are 355 formulae that build using a Homebrew compiler on Linux:

```
❯ rg 'fails_with.*gcc' -l | wc -l
355
```

All but 11 have a run-time dependency on `gcc`:

```
❯ rg 'depends_on "gcc" =' $(rg 'fails_with.*gcc' -l) -l | wc -l
11
```

This means that the `gcc` formula has an additional 344 immediate dependents on
Linux, and probably many more recursive dependents. As a consequence, we have
excessively long CI runs and encounter great difficulty in shipping major
version bumps to `gcc` (see, for example, #100411).

For reference, there are only 30 formulae that require a Homebrew compiler on
macOS:

```
❯ rg 'fails_with.*clang' -l | wc -l
30
```

I'd strongly prefer for the CI impact of using a Homebrew compiler on Linux to
be no larger than it is on macOS.

I can see a few ways to do this:

1. Build with a compiler newer than what is shipped by the distro we use in
   Linux CI.

2. Test fewer GCC dependents on Linux, or otherwise reduce coverage of Linux CI.

3. Be much more selective about bottling formulae that don't build with the host
   compiler provided by the Linux distro used in our CI. In particular, we
   should be bottling only up to 30 of the 355 formulae that currently build
   using a Homebrew compiler.

All of these alternatives can make life a bit more painful for users, but I
think what we save in CI and maintainer time/effort could be worth it here. Of
course, I'm very much open to other suggestions.

**Comment by danielnachun** [comment]
I think the answer here is very clearly that we simply need to use always use brewed GCC and treat it as a mandatory dependency the way the CLT is a dependency on macOS.  I do not think whatever disk space we save users by not installing brewed GCC is worth the trouble this causes us on the maintenance side.

There is concern that some older C++ formulae will not build with the newest version of GCC.  I have two thoughts on this:
1) I consider packages that don't build with the latest compiler to have a bug, and whenever possible these should be fixed upstream.
2) We can still build with an older GCC at compile time, and because `libstdc++` is backwards compatible, we can use `libstdc++` from the newest GCC at run time and it will still work.

I think this will actually be less work than trying to go back and rebuild all the packages already built with GCC 11 with GCC 7 when we migrate to Ubuntu 18.04.

In the longer term I'd like to see us migrate to using brewed `glibc` as well, and always using the latest version too.  While it will take a bit of work to make this work for bootstrapping on older systems (I do have a plan for how to make that work even if `glibc` isn't relocatable in the near term), this would completely decouple us from the host toolchain and allow us to migrate our host CI image to the latest Ubuntu LTS as soon as it comes out.  As with GCC, some older formulae may have API compatibility issues with the latest version of `glibc` but we can just use an older version of `glibc` at build time and the backwards compatibility provided by `glibc` means we can still use the latest version at run time.

This approach would spare us the need for any dependent testing of GCC and `glibc` on upgrades, and it would mean we will never have to worry about "playing catch up" with `gcc` and `glibc` versions that start to get too old.  The only long-term consequence of this is that our CI image will be a bit bigger due to installing brewed GCC and `glibc`, and the disk space requirements would go up for our users.  Given how cheap disk space is these days, I don't find that to be a convincing argument against this approach.

**Comment by danielnachun** [comment]
As an addendum to this, we may actually be able to get around these issues even quicker is to just link GCC 12 to `HOMEBREW_PREFIX/{lib,include,bin}` on Linux.  This would save us the trouble of having to rebuild any packages as `libstdc++` and the other GCC run time libraries are backwards compatible.  We'd need some way to express in the formula DSL "build with brewed GCC and make sure the user has it installed but skip dependent testing" as there is no need to do dependent testing.  We'd also have change our procedure on systems with a host GCC that is too old so that instead of linking `gcc@5` to `HOMEBREW_PREFIX/{lib,include,bin}` we link `gcc`, but that should be rather simple to achieve.

**Comment by carlocab** [comment]
> As an addendum to this, we may actually be able to get around these issues even quicker is to just link GCC 12 to `HOMEBREW_PREFIX/{lib,include,bin}` on Linux.

I suggest, instead, that we symlink `gcc.lib/"gcc"/gcc.version.major` to `gcc.lib/"gcc/current"`, and point dependent formulae to use the `current` directory. I find this a little more elegant, and we don't need to handle different cases across different OSs.

**Comment by danielnachun** [comment]
> I suggest, instead, that we symlink `gcc.lib/"gcc"/gcc.version.major` to `gcc.lib/"gcc/current"`, and point dependent formulae to use the `current` directory. I find this a little more elegant, and we don't need to handle different cases across different OSs.

This is a reasonable idea, but it will require rebuilding all GCC dependents because they don't currently have that path in their RPATH.  As long as we leave GCC at 11 until the migration is complete we should be able to do this for each formula individually.  Otherwise we'd have to worry about dependencies needing a newer `libstdc++` than their dependents, which breaks things.

I suppose the starting point for this is to set up the right logic in `brew` to make these symlinks so they can't be deleted by `brew unlink`.  The GCC spec and compiler shim will need to be updated as well so they include `gcc.lib/"gcc/current"` in the RPATH and LDFLAGS and make sure it precedes `HOMEBREW_PREFIX/lib`.

**Comment by MikeMcQuaid** [comment]
> I suppose the starting point for this is to set up the right logic in `brew` to make these symlinks so they can't be deleted by `brew unlink`. The GCC spec and compiler shim will need to be updated as well so they include `gcc.lib/"gcc/current"` in the RPATH and LDFLAGS and make sure it precedes `HOMEBREW_PREFIX/lib`.

Can we use an `opt` link for this instead? That feels like more in keeping with what we already do.

Feels like this is something we should do for all GCCs regardless of linked/unlinked/keg-only/versioned/non-versioned.



> I think the answer here is very clearly that we simply need to use always use brewed GCC and treat it as a mandatory dependency the way the CLT is a dependency on macOS. I do not think whatever disk space we save users by not installing brewed GCC is worth the trouble this causes us on the maintenance side.

Any reasons we can't use the system GCC when the major/minor version matches?

**Comment by carlocab** [comment]
> Can we use an `opt` link for this instead? That feels like more in keeping with what we already do.

I think we do rely on `opt` links for GCC dependents already. In fact, I had taken this for granted that when I said `gcc.lib` I actually meant `gcc.opt_lib`. Unless you meant something else about using an `opt` link?

> Any reasons we can't use the system GCC when the major/minor version matches?

I think we can use the system GCC whenever it is not older than the GCC used during the build.

In fact, I think we can use the system GCC whenever its major version is not older than the build GCC's major version (so you can actually have a lower minor/patch version).

**Comment by Bo98** [comment]
> the CLT is a dependency on macOS

To clarify:

- On Intel:
   - Building from source:
     - Latest macOS: any development tool (either Xcode or CLT, some formulae may require Xcode).
     - Older macOS: CLT (some formulae may _also_ need Xcode).
   - Using bottles:
     - No development tools are required (unless it's one of the few formulae which currently mandate it).
- On arm64:
  - Building from source:
    - Same as Intel
  - Using bottles:
    - Any development tool (Xcode or CLT) is required. This requirement can only go away if we do codesigning using `ruby-macho` or whatever.

Sorry, this was probably beside the point.

**Comment by MikeMcQuaid** [comment]
> I think we do rely on `opt` links for GCC dependents already. In fact, I had taken this for granted that when I said `gcc.lib` I actually meant `gcc.opt_lib`. Unless you meant something else about using an `opt` link?

I guess I'm thinking we have some sort of magic `opt/gcc-current` or something link that can be static even when we change GCC versions for backwards compatibility. I realise we could use `opt/gcc` for this but we might need something that doesn't rely on the latest GCC at all times.

> In fact, I think we can use the system GCC whenever its major version is not older than the build GCC's major version (so you can actually have a lower minor/patch version).

Yeh, this makes sense to me. It feels like it would be an improvement to e.g. pin the GCC version we support to a shipped OS e.g. the latest Ubuntu LTS or stable release or Debian stable. This also gives us a regular, planned timescale for upgrading, too.

> * Any development tool (Xcode or CLT) is required. This requirement can only go away if we do codesigning using `ruby-macho` or whatever. Or build our own `codesign_allocate` I guess (it's open source).

This feels like it'd be nice to have and perhaps @woodruffw could be nerd-sniped into it 😁. Then again, no-one's actually asking for it so it's not high priority.

**Comment by carlocab** [comment]
Closing in favour of Homebrew/brew#13619.
