### ISSUE TITLE
opam failed to build on 10.11 and 10.12

### ISSUE THREAD

**Issue by mcastil7** [Homebrew/homebrew-core#10568]
Aside from options not operational, `brew install opam --without-ocaml` fails. Below is the output I get on two machines. Here's the gist I get with `brew gist-logs opam`: 

https://gist.github.com/5c0e5190e2a704df11103b0fe8ad53bb

``
==> make cold CONFIGURE_ARGS=--prefix /usr/local/Cellar/opam/1.2.2_2 --mandir /usr/local/Cellar/opam/1.2.2_2/share/man
Last 15 lines from /Users/200016210/Library/Logs/Homebrew/opam/01.make:
/Library/Developer/CommandLineTools/usr/bin/make -C src_ext lib-ext
[ -e  extlib-1.5.3.tar.gz ] || curl  -OL http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1586  100  1586    0     0  20615      0 --:--:-- --:--:-- --:--:-- 20868
ocaml ../shell/md5check.ml extlib-1.5.3.tar.gz 3de5f4e0a95fda7b2f3819c4a655b17c
MD5 for extlib-1.5.3.tar.gz differ:
  expected: 3de5f4e0a95fda7b2f3819c4a655b17c
    actual: a0830b6fd2439ba2e924e08ba9e82a79
mkdir -p tmp
cd tmp && tar xfz ../extlib-1.5.3.tar.gz
tar: Error opening archive: Failed to open '../extlib-1.5.3.tar.gz'
make[2]: *** [extlib.stamp] Error 1
make[1]: *** [lib-ext] Error 2
make: *** [cold] Error 2
``

**Comment by JCount** [comment]
The options are in fact operational, and ironically that is seems to be why your build breaks. Since you are specifying that `opam` not be built with `ocaml` as a dependency, `opam`'s build system uses a bootstrap and it appears that at least one of the resources for that bootstrap has a dead url, killing the build. Specifically http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz Until there is a new stable release from `opam`'s upstream, the only reasonable workaround is probably to just build it with the `ocaml` dependency. (You could try building the HEAD version but be warned there are no guarantees of usability or stability.)

**Comment by mcastil7** [comment]
Thanks  @JCount! I need to install a specific version of OCaml. I found a "minimalistic" workaround by downloading [an opam binary](https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Darwin).

**Comment by JCount** [comment]
I'm glad you found a solution. That being the case I will close this as being resolved.
