### ISSUE TITLE
No available cask for android-ndk

### ISSUE THREAD

**Issue by unindented** [Homebrew/homebrew-core#11770]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Cannot install `android-ndk` with neither `brew install android-ndk` nor `brew cask install android-ndk`. This was working a couple of days ago.

```
$ brew config
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9a9314048790087db3ba6e7507302953a3971f9d
Core tap last commit: 16 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/daniel/.rbenv/shims/ruby => /Users/daniel/.rbenv/versions/2.4.1/bin/ruby
Java: 1.8.0_121
macOS: 10.12.4-x86_64
Xcode: 8.3
CLT: 8.3.0.0.1.1490382677
X11: 2.7.11 => /opt/X11
```

```
$ brew doctor
Your system is ready to brew.
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:homebrew-core joe$ grep android tap_migrations.json 
  "android-ndk": "caskroom/cask/android-sdk",
  "android-platform-tools": "caskroom/cask/android-sdk",
  "android-sdk": "caskroom/cask",
```
So I think you want `brew cask install android-sdk`

**Comment by mkatsevVR** [comment]
standalone android-sdk does not contain android-ndk, so this doesn't work

**Comment by ilovezfs** [comment]
In that case someone will need to open a pull request for the ndk here: https://github.com/caskroom/homebrew-cask/pulls.

**Comment by mkatsevVR** [comment]
Do you think that maybe deleting packages from core before they can be added as casks is a bad idea for the homebrew users? Especially considering that there are technical difficulties with making these packages into casks, which means that it will not be possible for anyone to install them for indeterminate amount of time https://github.com/caskroom/homebrew-cask/issues/31234

Why not revert 69c948752356aa56e7f1653366accb1262d124ea until this is resolved?

**Comment by donkaban** [comment]
'android-ndk' package unavailable from core and cask now. All our scripts in CI is destroyed, thanks

**Comment by MikeMcQuaid** [comment]
> 'android-ndk' package unavailable from core and cask now. All our scripts in CI is destroyed, thanks

People who post comments like this get banned from Homebrew (including @donkaban).

**Comment by MikeMcQuaid** [comment]
@mkatsevVR Posting the same questions in multiple issues doesn't get them fixed any quicker. I'd suggest that people who want Android NDK work on getting it included in Caskroom.

`android-sdk` has been marked for rejection since 18th February and the update stalled since December: https://github.com/Homebrew/homebrew-core/pull/7860. This is a community run package manager. It's no-one's job to work on this stuff. If you want things to get better you need to submit the PRs to do so and these PRs will now be in Caskroom.

**Comment by MikeMcQuaid** [comment]
> Why not revert 69c9487 until this is resolved?

To answer this specifically: because then we will still have outdated, binary packages that no-one will have any incentive to improve. If you need those formulae as-is: please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!
