### ISSUE TITLE
podman service fails to start on macOS

### ISSUE THREAD

**Issue by jfoy** [Homebrew/homebrew-core#118717]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
local:~ $ brew config
HOMEBREW_VERSION: 3.6.16-2-gf679990
ORIGIN: https://github.com/Homebrew/brew
HEAD: f679990d7918d9f99d9c6c99b7bec504bc4088fe
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ef78c6f3fc65c97c272ac000b598767543f72d77
Core tap last commit: 32 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.0 => /opt/homebrew/opt/git/bin/git
Curl: 7.86.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 12.6.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
local:~ $ brew doctor
Your system is ready to brew.
local:~ $
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'd like to automatically start `podman machine` in order to run Linux containers on macOS. There is a Homebrew service included with `podman`, but it fails to start on macOS. 

### What happened (include all command output)?

```
local:~ $ brew services start podman
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/503 /Users/jfoy/Library/LaunchAgents/homebrew.mxcl.podman.plist` exited with 5.
local:~ $ cat ~/Library/LaunchAgents/homebrew.mxcl.podman.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin</string>
	</dict>
	<key>Label</key>
	<string>homebrew.mxcl.podman</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/opt/podman/bin/podman</string>
		<string>system</string>
		<string>service</string>
		<string>--time=0</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>WorkingDirectory</key>
	<string>/opt/homebrew</string>
</dict>
</plist>
local:~ $ /opt/homebrew/opt/podman/bin/podman system service --time=0
Error: unknown flag: --time
See 'podman system --help'
local:~ $
```

### What did you expect to happen?

Since `podman-remote` is installed as `podman` under macOS, service startup should probably look a lot like the formula's test block and run `podman machine` using a legal image: 

```
    if OS.mac?
      out = shell_output("#{bin}/podman-remote machine init --image-path fake-testi123 fake-testvm 2>&1", 125)
      assert_match "Error: open fake-testi123: no such file or directory", out
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# Under macOS
brew install podman
brew services start podman
```

**Comment by dawidd6** [comment]
This "legal image" you are talking about, which one should it be?

**Comment by agsimeonov** [comment]
I am also facing this same issue.  Same error with `brew services start podman`. When I run `brew services restart podman` I get:

```
Stopping `podman`... (might take a while)
==> Successfully stopped `podman` (label: homebrew.mxcl.podman)
==> Successfully started `podman` (label: homebrew.mxcl.podman)
```

However `brew services list` returns:

```
Name    Status       User     File
podman  error  32000 UserName ~/Library/LaunchAgents/homebrew.mxcl.podman.plist
```

**Comment by shivansh-13** [comment]
Following the same steps to reproduce bug in my Mac OS ventura, it ran successfully.

`shivanshshrivastava@Shivanshs-MacBook-Air ~ % brew services start podman
==> Successfully started `podman` (label: homebrew.mxcl.podman)`

**Comment by agsimeonov** [comment]
@shivansh-13 I wonder if it is a thing on Monteray and older.  I am on macOS 12.6.2 just like @jfoy is above and I get the same errors he does.

**Comment by jfoy** [comment]
@shivansh-13 Very strange. What do you see from `cat ~/Library/LaunchAgents/homebrew.mxcl.podman.plist`, `which podman`, and `podman help system`?

**Comment by shivansh-13** [comment]
@jfoy 

> shivanshshrivastava@Shivanshs-MacBook-Air ~ % c`at ~/Library/LaunchAgents/homebrew.mxcl.podman.plist`
> cat: /Users/shivanshshrivastava/Library/LaunchAgents/homebrew.mxcl.podman.plist: No such file or directory
> shivanshshrivastava@Shivanshs-MacBook-Air ~ %` which podman`
> /usr/local/bin/podman
> shivanshshrivastava@Shivanshs-MacBook-Air ~ % `podman help system`
> Manage podman
> 
> Description:
>   Manage podman
> 
> Usage:
>   podman system [command]
> 
> Available Commands:
>   connection  Manage remote API service destinations
>   df          Show podman disk usage
>   info        Display podman system information
>   prune       Remove unused data
> 
> shivanshshrivastava@Shivanshs-MacBook-Air ~ %

**Comment by SMillerDev** [comment]
If that is when podman is running you didn't install it with Homebrew

**Comment by artginzburg** [comment]
Me and some other people had this problem at artginzburg/sudo-touchid#8. We obviously can use SMAppService API to fix it, but I would like everything to be done using a single terminal command, without apps or any further user interaction (like it worked in e.g. macOS Big Sur), so that users can integrate sudo-touchid into their automated system builds.

Apple always finds a way to mess with you :)

So I'm also looking for a solution to the problem. Open to discussions

**Comment by jfoy** [comment]
@artginzburg Wrong issue?

**Comment by SMillerDev** [comment]
No, that's a very different issue that has nothing to do with podman or any Homebrew code.

**Comment by dljsjr** [comment]
The service block in Homebrew for `podman` won't work on macOS; the `podman-system-service` binary isn't available in setups that rely on Podman Machine because that service relies on a unix domain socket that lives in the VM.

The issue is two-fold:

1. `podman machine init` needs to be called if a VM hasn't been created yet;
2. `podman machine start` needs to be called after `init` has been called.

I think that the macOS launchd configuration will need a wrapper script to make this work, because [the official upstream stance is that this is the job of Podman Desktop](https://github.com/containers/podman/issues/15579)

**Comment by SMillerDev** [comment]
> podman machine init needs to be called if a VM hasn't been created yet;

That's up to the user to do before enabling the service. We don't setup an nginx website for you before running the service.

> The service block probably needs to take in to consideration situations with multiple Podman VM's since it is totally legit to have setups with more than one podman machine.

No it doesn't have to, people can manage complicated setups on their own.

**Comment by dljsjr** [comment]
> > podman machine init needs to be called if a VM hasn't been created yet;
> 
> That's up to the user to do before enabling the service. We don't setup an nginx website for you before running the service.

That's totally different though. If you don't have any static files for nginx to serve, the service will still start. If `podman machine init` isn't run first, the service won't start. It could ostensibly just be documented that you need to call `podman machine init` before `brew service start podman` but going back to using a wrapper script I think it wouldn't be that hard to make sure that's been done, right? But if it seems like that's doing "too much" then it should definitely I think be documented that the service won't work unless the machine has been started.

> No it doesn't have to, people can manage complicated setups on their own.

I didn't necessarily mean that the startup block should take options or anything like that; I meant that it shouldn't necessarily assume that a machine with a specific name exists because people could deviate from that.

I've actually already started playing with a version of the launchd config here that uses a wrapper script and I dont' think it's going to be that difficult.

1. Have the service look for an existing machine using `podman machine list --format json`. To make it multiple-machine-aware or to avoid assuming that the default machine is used, canonicalize on a name like `podman-machine-default` which is what would be created with an empty `podman machine init`.
2. If the machine does not exist, create it.
3. Once the machine is running, `podman machine start`

The bigger issue I think is that `podman machine start` doesn't create a foreground process with a trackable PID the way `podman system service --time 0` does for `systemd`. I don't really know much about homebrew services, I only stumbled on to this because I wanted to get a `podman` service w/out needing Podman Desktop and I wanted to do some dilligence before coming to the issue tracker. I'm just working on scripting it and haven't integrated it really in to `launchctl` yet, and I'm not super familiar with it, so I don't know if that's going to be a problem or not.

**Comment by SMillerDev** [comment]
> podman machine init isn't run first, the service won't start. It could ostensibly just be documented that you need to call podman machine init before brew service start podman

Upstream has documentation to that extend, brew doesn't have to explain people how to use podman.

As for the wrapper, unless it's included in upstream brew shouldn't distribute it.

**Comment by dljsjr** [comment]
In that case then I don't think there can be a launchctl file for podman, no? Especially if upstream's position is that this is the responsiblity of Podman Desktop?

**Comment by SMillerDev** [comment]
The launchd file is generated by brew based on the service block that defines "this command should be ran". It's not specific to podman, and the maintenance is done on a global level. A wrapper script would essentially add a brew specific patch to podman, which is something we actively avoid.

**Comment by dljsjr** [comment]
No I understand that, what I mean is that the fact that `podman system service` doesn't exist on macOS means that without diverging logic this will never work on macOS whether someone takes care of starting `podman machine` or not.

**Comment by SMillerDev** [comment]
That's not an issue though, we just need to find a command that does work on macOS.

**Comment by dljsjr** [comment]
I'm not incredibly familiar w/ `launchd`/`launchctl`; is it a requirement that the command executed be a foreground command?

**Comment by dljsjr** [comment]
>  I think the right way to address this issue directly is to suppress the brew service on macOS, so we don't have a service that's literally unstartable

That seems like the right option to me; there is no command that creates a foreground process or an observable PID on the macOS side of things at all. We could do a fire-and-forget on `podman machine start` I suppose but there wouldn't be an easy way to get service status.

**Comment by jfoy** [comment]
@dawidd6 Would you be willing to confirm that #120184 doesn't break the service under Linux?

**Comment by dawidd6** [comment]
@jfoy it does break. This change is invalid.

**Comment by jfoy** [comment]
Thanks for your testing, @dawidd6
