### ISSUE TITLE
libmtp: Not including header files (e.g. ptp.h)

### ISSUE THREAD

**Issue by arrmo** [Homebrew/homebrew-core#122639]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Tried this, `brew gist-logs libmtp`

Error: No logs.
```

So then, `brew config`
```
HOMEBREW_VERSION: 3.6.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 932d2cf3b77c9439a57b6a43577fc8d3b6399a62
Last commit: 8 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fc6d7734f8d7b6c7145cbecd5b9df0e0fd9551b2
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

Also, `brew doctor`
```
Your system is ready to brew.
```
```


### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to build [subsurface ](https://github.com/subsurface/subsurface) - it requires (fails due to) `ptp.h` (missing). I found that this is part of `libmtp`, so I installed this with brew ... but still don't seem to have `ptp.h`.


### What happened (include all command output)?

```
../../examples/files.c:24:10: fatal error: 'ptp.h' file not found
#include "ptp.h"
```

### What did you expect to happen?

After installing `libmtp`, I expected to have `ptp.h` available.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libmtp
find /opt/homebrew/include/* -name "ptp*"
=> nothing found
```

**Comment by carlocab** [comment]
I don't think `libmtp` is supposed to provide `ptp.h`. The formula just does `./configure && make install`

https://github.com/Homebrew/homebrew-core/blob/66e600d9e6a20a2a00f8b2bf21058f052974a9c2/Formula/libmtp.rb#L23-L27

so whatever headers are installed are the ones chosen by upstream. In this case, that's `libmtp.h`.

The [latest commit](https://github.com/libmtp/libmtp/commit/1dc3e21f1a625cfb399e27f2fa8b17f951d5c069) for `ptp.h` in the [`libmtp` repository](https://github.com/libmtp/libmtp) also suggests that this is a third-party header, so I'd say it's expected behaviour for `libmtp` to not provide `ptp.h`.

**Comment by arrmo** [comment]
That makes sense, no argument here - was wondering if it was me misinterpreting or not (which it seems it is 😆). Hmmm ... not sure what / how to get ptp.h installed then, as it seems to be "part" of libmtp.

Thanks!

**Comment by carlocab** [comment]
I suggest asking the Subsurface devs where they expect `ptp.h` to come from.

If you're in a pinch, you can do something like
```sh
cd /tmp
brew unpack libmtp
mkdir include
cp libmtp-1.1.20/src/ptp.h include
export CFLAGS=-I/tmp/include
```
to use the `ptp.h` that was used to build `libmtp`.

**Comment by arrmo** [comment]
Thanks!

**Comment by gromgit** [comment]
From https://github.com/libmtp/libmtp/blob/master/README:

> `libmtp` is based on several ancestors:
> [...]
> * `libgphoto2` by Mariusz Woloszyn and Marcus Meissner was used at a later stage since it was (is) more actively maintained. `libmtp` tracks the PTP implementation in `libgphoto2` and considers it an upstream project. We will try to submit anything generally useful back to `libgphoto2` and not make double efforts. In practice this means we use `ptp.c`, `ptp.h` and `ptp-pack.c` verbatim from the `libgphoto2` source code. If you need to change things in these files, make sure it is so general that `libgphoto2` will want to merge it to their codebase too. You find `libgphoto2` as part of gPhoto: https://gphoto.sourceforge.net/

So `libmtp` basically vendors `libgphoto2`. Also, `libgphoto2` doesn't export `ptp.h` either, so I'm inclined to believed that this header file is an internal implementation detail rather than an official API.

So the answer to your question here, and the original issue you raised [on the `subsurface` repo](https://github.com/subsurface/subsurface/issues/3577)) is to do what @carlocab suggested: build the `subsurface` examples while `#include`ing from the `subsurface` source.

**Comment by arrmo** [comment]
Makes sense, will dig into it. Thanks!
