### ISSUE TITLE
`cargo-nextest` formula needlessly installs Rust, shadowing existing rustup installations

### ISSUE THREAD

**Issue by pvditto** [Homebrew/homebrew-core#124998]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`$ brew config`


HOMEBREW_VERSION: 4.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: b1ef41c25d12795dc93975e337e8644d0974b53c
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5e0663926ddcb3ec5f4bfec7f8745b0928498a0f
Core tap last commit: 11 days ago
Core tap branch: master
Core tap JSON: 07 Mar 10:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```
```
`$ brew doctor`

(This contains a warning because I have removed the brew-installed rust previous to running this in order to solve this problem)

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install rust

Run `brew missing` for more details.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install `cargo-nextest` to run tests in the Rust project I'm working on

### What happened (include all command output)?

My project fails to build because the `cargo-nextest` formula has a rust dependency that conflicts with existing `rustup`-installed binaries.

### What did you expect to happen?

Installing `cargo-nextest` only installs binaries for that tool and doesn't add a Rust installation to my system.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# Having previously installed Rust using rustup
$ brew install cargo-nextest
```

**Comment by rami3l** [comment]
+1.

Original comment from  https://github.com/Homebrew/homebrew-core/pull/121847#discussion_r1118011998:

> There are at least 2 ways to install `cargo` with `brew`: with `rust` directly, or via `rustup-init` (like what I did).
> 
> Due to how `cargo-*` binaries work, both approaches should work properly, but now with this change, I also installed `rust` without any practical use at all...
> 
> 
> A quick look at other similar binaries like [`cargo-watch`](https://github.com/Homebrew/homebrew-core/blob/17aa4a59969dc7ba12430a84b8b8723ea931a544/Formula/cargo-watch.rb) and [`cargo-udeps`](https://github.com/Homebrew/homebrew-core/blob/17aa4a59969dc7ba12430a84b8b8723ea931a544/Formula/cargo-udeps.rb) further convinced me that this change should not happen. What do you think? 
> 
> Many thanks!
> 
> ---
> 
> Just made a quick search:
> 
> ```fish
> fish> for i in (brew search cargo-); if contains rust (brew deps $i); echo $i; end; end
> cargo-about
> cargo-bloat
> cargo-deny
> cargo-edit
> cargo-llvm-lines
> cargo-make
> cargo-nextest
> cargo-outdated
> cargo-release
> cargo-zigbuild
> ```
> 
> This makes up half (10 out of 18) of current `cargo-*` formulae...

**Comment by saedyousef** [comment]
Based on the error message, it seems like the issue is that cargo-nextest depends on a different version of Rust than the one you have installed through rustup. One possible solution would be to install the required version of Rust through Homebrew, rather than rustup.

Here's how you can do that:

1. Uninstall the existing Rust installation:

    ```sh
    rustup self uninstall
    ```

2. Install Rust through Homebrew:

    ```sh
    brew install rust
    ```

3. Check the installed version of Rust:

    ```sh
    rustc --version
    ```

   Make sure that the version matches the one required by cargo-nextest.

4. Install cargo-nextest:

    ```sh
    brew install cargo-nextest
    ```

   This should install only the binaries for cargo-nextest without adding a new Rust installation to your system.

5. Run cargo-nextest:

    ```sh
    cargo nextest --help
    ```

   This should verify that cargo-nextest is working correctly.

**Comment by phatblat** [comment]
Is there any way to invoke commands outside the Homebrew sandbox during install? Attempting to run `command --query cargo` from the formula doesn't find an existing installation.

```ruby
depends_on "rust" unless system "command", "--query", "cargo"
```

**Comment by gromgit** [comment]
> One possible solution would be to install the required version of Rust through Homebrew, rather than rustup.
> ...

1. Homebrew builds and tests `cargo-nextest` bottles (prebuilt binaries) with Homebrew `rust`, so the two formulae are a "matched pair" by definition.
2. OP's complaint is that Homebrew `rust` _is_ being installed alongside `cargo-nextest`...but they don't want it.

So none of the steps you suggest are necessary.

> Based on the error message, it seems like the issue is that cargo-nextest depends on a different version of Rust than the one you have installed through rustup.

I don't know which error message you're talking about, but if that's true, then that's an argument _against_ the OP's wishes. Homebrew _and_ `nextest` maintainers would probably not appreciate a slew of "hey, `cargo nextest` doesn't work", that turned out to be a mismatched Rust runtime.

**Comment by rami3l** [comment]
Still needed.

**Comment by nerosnm** [comment]
Still needed

**Comment by pvditto** [comment]
A temporary solution to this issue is installing `cargo-nextest` with

```bash
brew install cargo-nextest --ignore-dependencies
```

However, brew will [ignore this flag ](https://github.com/Homebrew/brew/issues/2345)when running `brew upgrade` and add the `rust` dependency silently. 

I have recommended that the cargo-nextest project put a disclaimer on their documentation not to use this formula.

**Comment by sunshowers** [comment]
Hi, maintainer of cargo-nextest here. I agree with the OP that this is really surprising, and in my professional opinion I don't think homebrew's recipe for nextest should install Rust.

> hey, cargo nextest doesn't work" complaints, that turned out to be a mismatched Rust runtime.

This isn't a problem with nextest, because nextest is not tightly bound to the version or toolchain of Rust that compiled it. It is an independent, static binary that will work with any version of Rust from at least the last 24 months and also foreseeably in the future.

The fact that nextest is invoked as a cargo plugin is mostly an implementation detail. At some point I want to rename the binary to just `nextest`, once I add support for non-Cargo build systems.

**Comment by rami3l** [comment]
Following @sunshowers' comment and my previous explanation in https://github.com/Homebrew/homebrew-core/pull/125151#issuecomment-1461572486 that `cargo-*` binaries don't directly depend on a specific Rust toolchain itself, I think it would be reasonable to:

* Change `cargo-nextest`'s dependency to match the following: https://github.com/Homebrew/homebrew-core/blob/17aa4a59969dc7ba12430a84b8b8723ea931a544/Formula/cargo-udeps.rb#L19

* Gradually make corresponding changes to other relevant `cargo-*` binaries, such as those listed in https://github.com/Homebrew/homebrew-core/issues/124998#issuecomment-1458089110.

**Comment by nerosnm** [comment]
This is not stale.

**Comment by carlocab** [comment]
This should be resolved now. You may need to `brew update && brew reinstall cargo-nextest` to make `brew` stop complaining about you trying to do `brew uninstall rust`.

Thanks @rami3l!
