### ISSUE TITLE
llvm and openmp

### ISSUE THREAD

**Issue by autosquid** [Homebrew/homebrew-core#1254]
There are both a `clang-omp` formular and `llvm` formular with `--with-clang` option now.

I checked `clang-omp`, finding it is based on llvm 3.5. (And the `llvm` formular is based on llvm 3.6).

However, accoding to  [openmp official:](openmp.llvm.org)

> With the release of Clang 3.8.0, OpenMP 3.1 support is enabled in Clang by default, and the OpenMP runtime is therefore built as a normal part of the Clang build, and distributed with the binary distributions.

My question is: why not adding the `openmp` option into the `llvm` formula? or do we just need an update of `clang-omp`?

**Comment by mikemcquaid** [comment]
> My question is: why not adding the openmp option into the llvm formula? or do we just need an update of clang-omp?

Adding that option and removing `clang-omp` seems like a good idea 👍

**Comment by xu-cheng** [comment]
> Adding that option and removing clang-omp seems like a good idea 👍

We don't need to add extra option. Once we update `llvm` to 3.8, we can safely remove the clang-omp formula.

**Comment by autosquid** [comment]
So, is there any thing stopping us from updating it?   @xu-cheng

**Comment by xu-cheng** [comment]
I'm not sure the current state of llvm formula. probably need to cc @DomT4

**Comment by DomT4** [comment]
The last attempt died for the standard reason in that things that use LLVM update/release significantly slower than LLVM themselves do. We could see if this has changed, but I'd be surprised.

What may need to be done here if we want to move on this soon is to introduce `llvm38` as a core formula, remove the `clang-omp` formula and alias `clang-omp` onto `llvm38`. I'm not sure how/if that would impact local installations of the existing `clang-omp` formula, though.

**Comment by xu-cheng** [comment]
I believe we should just boneyard clang-omp when the time comes.

**Comment by maxim-belkin** [comment]
I'm very much interested in updating `llvm` formula: I need it for the `mesa` package in `linuxbrew/homebrew-xorg` repo. Hence, I can devote some of my free time to update it.

But, I do need to know why  `llvm` embodies all the resources  instead of depending on separate packages. I can imagine why `libcxx` and `libcxx` *can* be bundled together [1](http://stackoverflow.com/questions/25840088/how-to-build-libcxx-and-libcxxabi-by-clang-on-centos-7) [2](http://libcxx.llvm.org/docs/BuildingLibcxx.html#id4). But what about the rest? Individual formulas will be lighter and easier to update. Can anyone shed a light onto the reasoning behind the current way of building `llvm`?

**Comment by DomT4** [comment]
> Hence, I can devote some of my free time to update it.

It's not really time that's the problem, as something of a warning. It's more that other packages that use `llvm` don't keep pace with the upstream release process, which means we're constantly playing a waiting game for that compatibility to bleed through the ecosystem. The sane thing to do is probably just move a `llvm38` formula here, given the `llvm` formula in the core is `keg_only` regardless.

> But, I do need to know why llvm embodies all the resources instead of depending on separate packages.

There's not a huge use case for them to be used outside of LLVM, they are part of LLVM effectively. Having them separate would also mean every LLVM release had to update 6/7/8 formulae to be compatible with each other in the same PR. That's a lot more maintenance for both us and contributors, sadly.

**Comment by maxim-belkin** [comment]
> It's more that other packages that use `llvm` don't keep pace with the upstream release process,

If some package doesn't keep pace with the `llvm` release cycle, make it use an `llvm` revision rather than delaying an update of the main formula. I'm pretty sure no one except Homebrew developers know why the provided `llvm` is almost a year old.
`llvm38` formula uses a `configure/make` rather than `cmake/make`. I'm not a fan of `cmake`, but for consistency purposes it should be the same as before because those who installed `llvm` in the past will expect that.

Also note that `libstcxxabi` was removed from `llvm` for no apparent (to me) reason. Not sure what happened there. `Mesa` needs `llvm` and needs so I'd like to help whoever is going to update `llvm`.

**Comment by MikeMcQuaid** [comment]
@maxim-belkin It's not as simple as that due to how we've previously and currently handle versions but we are working on rectifying this situation.

**Comment by DomT4** [comment]
> I'm pretty sure no one (except Homebrew developers) knows why the provided llvm is almost a year old.

Both newer versions are supported in the Versions tap and that's where people who very quickly want the latest & greatest on compilers have come to look, because yeah, updating things like LLVM & GCC gets hairy very easily.

> llvm38 formula uses a configure/make rather than cmake/make. I'm not a fan of cmake, but for consistency purposes it should be the same as before because those who installed llvm in the past will expect that.

I agree. I've been asking people to help migrate the Versions CMake formulae over to CMake for a while. Sadly interest in Versions is considerably lower than interest in the core, partly because it's less visible to users. If you'd like to migrate all the LLVM versions that should be using CMake over to that system I'd be very appreciative, to say the least!

> Also note that libstcxxabi was removed from llvm for no apparent (to me) reason. Not sure what happened there.

It was mentioned in the commit log: https://github.com/Homebrew/homebrew-core/commit/9e173d707d33a0df5b530dc7bd8a99ee30098c89.

**Comment by maxim-belkin** [comment]
@DomT4: that commit references issue [47149](https://github.com/Homebrew/legacy-homebrew/issues/47149) the solution to which seems [googleable](http://stackoverflow.com/questions/13040652/stdterminate-undefined-in-cocoa-app) -- he should have added `-lc++`, not `-lc++abi`.

**Comment by maxim-belkin** [comment]
And here is how he should have invoked it: [ref](http://libcxx.llvm.org/docs/UsingLibcxx.html)

**Comment by maxim-belkin** [comment]
> Sadly interest in Versions is considerably lower than interest in the core, partly because it's less visible to users.

I think versions tap is 'less interesting' because it is positioned more like a step towards the `boneyard` tap (or whatever it is called), rather than something that WILL become a standard in the future homebrew releases. Hence, lack of activity there. I completely disagree that `versions` tap should have versions of the formula that are no further than 2 revisions away from the corresponding formula in the main `core` repo: it costs practically nothing to store the formula and a bit of human time to update it once something changes. The formula should go away if and only if it is no longer possible to build it neither on a Mac, nor on a Linux computer.

**Comment by DomT4** [comment]
>  it costs practically nothing to store the formula and a bit of human time to update it once something changes. 

Excuse my bluntness here, but please tell me more about your experience maintaining Versions with your zero commits. If you have PRs, we welcome them, but otherwise I can live without being told why the tap I've spent over a year maintaining almost by myself for long, long periods is fine and our decisions there aren't informed by any rationality or experience. Thanks.

**Comment by MikeMcQuaid** [comment]
@maxim-belkin Pull requests to fix issues are always welcome.

**Comment by autosquid** [comment]
Indeed if we update the llvm formula, it may break a lot otherr; if we always  an old version of llvm, it may also stop developers from updating their formulars, too.

> What may need to be done here if we want to move on this soon is to introduce llvm38 as a core formula, remove the clang-omp formula and alias clang-omp onto llvm38. 

The original idea by @DomT4 of making `llvm38` a core formula seems a good idea.

 As a core formula it *may* encourage people to move on to llvm38  (,and maybe later versions) faster, and will it satisfy your needs @maxim-belkin ? 

> I'm not sure how/if that would impact local installations of the existing clang-omp formula, though.

Is there a way to determine how much formulas will be affected by updating llvm (if that were possible) and renaming llvm-opm?

**Comment by DomT4** [comment]
Ref: https://github.com/Homebrew/homebrew-core/pull/3028

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/3028 being merged.

**Comment by GitZChen** [comment]
Not sure if this is the right place to ask this question, but we are trying to use openMP in Xcode -> actually compiling a C++ project that uses Eigen for iOS. After clang-omp has been moved to boneyard, the steps/config outlined in the [clang-omp doc](https://clang-omp.github.io/) are no longer valid. So we are wondering if anyone would be willing to offer a new tutorial to use the latest llvm and OpenMP package with Xcode？ Thank you!

Currently, we have tried adding `i386;arm` to `-DLIBOMP_ARCH=x86_64;` in the llvm formula, then `brew install llvm --universal --with-all-targets --with-clang --with-lldb --with-toolchain` and finally use the llvm 3.8.1 toolchain in Xcode, but it's not working for iOS or Simulator. 

Would you guys consider offering an option to build llvm for iOS' architectures in homebrew? @DomT4  @MikeMcQuaid 

Thank you for your hard work！
Zachary
