### ISSUE TITLE
Fortune errors due to missing dictionary

### ISSUE THREAD

**Issue by peterwwillis** [Homebrew/homebrew-core#127119]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
[user@host ~]$ brew config
HOMEBREW_VERSION: 4.0.10-84-gb0e349e
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0e349efe18251e939d8432a4d01a8ee48522d57
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 87fd5959b5797d5392232609473ccb3e234eff26
Core tap last commit: 8 weeks ago
Core tap branch: master
Core tap JSON: 30 Mar 17:57 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.YlmBaD3Bp4/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

```
[user@host ~]$ brew doctor
Your system is ready to brew.
```
```


### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run fortune with `-o` option to see additional fortunes

### What happened (include all command output)?

```
[user@host ~]$ fortune -o
/opt/homebrew/Cellar/fortune/9708/share/games/fortunes/off: No such file or directory
```

### What did you expect to happen?

A fortune is outputted

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Run `fortune -o`
```

**Comment by issyl0** [comment]
We [deliberately do not ship the offensive quotes](https://github.com/Homebrew/homebrew-core/pull/61706). I will look into why this is failing with args, though.

**Comment by issyl0** [comment]
Ah, I see, the `-o` option tries to select from the offensive quotes which we don't ship (as above). The `-a` option tries to select from both standard and offensive quotes, the latter of which we don't ship, so it doesn't work.

Since `OFFENSIVE=0` is able to be set in the `make` step of the build process to not ship offensive quotes, I'd say this is an upstream bug that needs a better error message if the offensive directory is unavailable. I have no idea how one asks the `fortune` maintainers to fix this bug, since this is ancient UNIX software. I'l leave that as an exercise for the reader.
