### ISSUE TITLE
brew cask install caskroom/cask/brew-cask does not work

### ISSUE THREAD

**Issue by yazhouy** [Homebrew/homebrew-core#131]
I try ''brew install caskroom/cask/brew-cask'' on my OS X 11.04 system. I meet the following problem. I have tried brew update and brew doctor, no warning and no error show up. But I still get the same issue.  What is the problem?

brew cask install caskroom/cask/brew-cask
Error: No available Cask for caskroom/cask/brew-cask
Error: nothing to install

**Comment by DomT4** [comment]
It used to be `brew install caskroom/cask/brew-cask`, so `brew` rather than `brew cask` in the initial step. These days that's no longer necessary, as per [this README notation](https://github.com/caskroom/homebrew-cask/#important-december-2015-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

Just execute `brew cask` and you'll have it installed now, and it'll update automatically with every `brew update`.

**Comment by yazhouy** [comment]
Thank you so much! I will try that!
