### ISSUE TITLE
`mu --with-emacs` compilation fails on macOS El Capitan 10.11.6 

### ISSUE THREAD

**Issue by neurolit** [Homebrew/homebrew-core#13213]
- [X] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Hi!

I tried`brew install mu --with-emacs` but it doesn't work. `glib-sharp-2.0` seems to be missing:

```
configure: error: Package requirements (glib-sharp-2.0 >= 2.4.0) were not met:

No package 'glib-sharp-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLIB_SHARP_CFLAGS
and GLIB_SHARP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

You can find more information (created with `brew gist-logs`) in this Gist: https://gist.github.com/anonymous/dc986397f900042da9f45e4bfb5cb773

`brew update` and `brew doctor` didn't solve anything.

**Comment by neurolit** [comment]
Related to #11476

**Comment by neurolit** [comment]
OK, I think I found a way to solve this issue: installing [Mono](http://www.mono-project.com/download/) solved it.

**Comment by KryDos** [comment]
https://github.com/Homebrew/homebrew-core/issues/11476#issuecomment-299645313 - here I tried to install it without Mono. Please take a look if Mono is unnecessary for you.

**Comment by peyapaspeya** [comment]
I spent quite a bit of time trying to install m4ue on OSX but keep getting the same error : 
https://gist.github.com/anonymous/ebf1b05a2b2d25e233192b13139fcd7f

gmime is installed but configure keeps crashing  : 
./configure --prefix=/usr/local/Cellar/mu/HEAD-34d5c61_1 --with-lispdir=/usr/local/Cellar/mu/HEAD-34d5c61_1/share/emacs/
==> make
Last 15 lines from /Users/pierrem/Library/Logs/Homebrew/mu/05.make:
In file included from mu-msg-crypto.c:27:
./mu-msg-priv.h:29:10: fatal error: 'gmime/gmime.h' file not found
#include <gmime/gmime.h>
         ^
1 error generated.
make[3]: *** [mu-msg-crypto.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
mu-msg-file.c:29:10: fatal error: 'gmime/gmime.h' file not found
#include <gmime/gmime.h>
         ^
1 error generated.
make[3]: *** [mu-msg-file.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by KryDos** [comment]
@peyapaspeya try to remove gmine and let the package (mu) install it as a dependency. Maybe it will help, but it's just a guess.

**Comment by peyapaspeya** [comment]
Same error. 
brew automatically pulls gmime version 2.6.23 regardless when installing mu. 
Maybe something around PATH ? 
This is the output of brew install gmime : 

pierrem$ brew install gmime
==> Installing dependencies for gmime: libpng, freetype, fontconfig, pixman, cairo, readline, sqlite, gdbm, python, gobject-introspection
==> Installing gmime dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.29.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libpng-1.6.29.sierra.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/libpng/1.6.29: 26 files, 1.2MB
==> Installing gmime dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.8.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring freetype-2.8.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.8: 63 files, 2.6MB
==> Installing gmime dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.12.1_2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring fontconfig-2.12.1_2.sierra.bottle.tar.gz
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/fontconfig/2.12.1_2/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.12.1_2: 486 files, 3.1MB
==> Installing gmime dependency: pixman
==> Downloading https://homebrew.bintray.com/bottles/pixman-0.34.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring pixman-0.34.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pixman/0.34.0: 12 files, 1.2MB
==> Installing gmime dependency: cairo
==> Downloading https://homebrew.bintray.com/bottles/cairo-1.14.8.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cairo-1.14.8.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/cairo/1.14.8: 119 files, 5.9MB
==> Installing gmime dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-7.0.3_1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring readline-7.0.3_1.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only..

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/7.0.3_1: 46 files, 1.5MB
==> Installing gmime dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.18.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sqlite-3.18.0.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/sqlite/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/sqlite/3.18.0: 11 files, 3.0MB
==> Installing gmime dependency: gdbm
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.13.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gdbm-1.13.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gdbm/1.13: 19 files, 554.4KB
==> Installing gmime dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-2.7.13.sierra.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring python-2.7.13.sierra.bottle.1.tar.gz
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/us
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/us
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/us
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: http://docs.brew.sh/Homebrew-and-Python.html
==> Summary
🍺  /usr/local/Cellar/python/2.7.13: 3,526 files, 48MB
==> Installing gmime dependency: gobject-introspection
==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.52.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gobject-introspection-1.52.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gobject-introspection/1.52.1: 172 files, 9.7MB
==> Installing gmime
==> Downloading https://homebrew.bintray.com/bottles/gmime-3.0.0.sierra.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring gmime-3.0.0.sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/gmime/3.0.0: 171 files, 3.6MB

So I have gmime 3.0 installed in /usr/local/Cellar/gmime but brew install mu --with-emacs will pull 2.6.23 and give me an error ?

**Comment by peyapaspeya** [comment]
brew uninstall gmime followed by brew install mu --with-emacs solved my issue.

**Comment by brabalan** [comment]
I have the same issue with notmuch. Uninstalling gmime does not change anything, as the formula pulls an older gmime:
```
==> Upgrading 1 outdated package, with result:
notmuch 0.24.1_1
==> Upgrading notmuch
==> Using the sandbox
==> Downloading https://notmuchmail.org/releases/notmuch-0.24.1.tar.gz
Already downloaded: /Users/schmitta/Library/Caches/Homebrew/notmuch-0.24.1.tar.gz
==> Patching
patching file bindings/python/notmuch/globals.py
==> Downloading https://download.gnome.org/sources/gmime/2.6/gmime-2.6.23.tar.xz
Already downloaded: /Users/schmitta/Library/Caches/Homebrew/notmuch--gmime-2.6.23.tar.xz
==> ./configure --prefix=/usr/local/Cellar/notmuch/0.24.1_1/gmime --disable-introspection
Last 15 lines from /Users/schmitta/Library/Logs/Homebrew/notmuch/01.configure:
checking for GPGME pthread - version >= 1.1.6... no
checking for mcs... /usr/local/bin/mcs
checking whether /usr/local/bin/mcs is GNU Mono... yes
checking for gacutil... /usr/local/bin/gacutil
checking for GLIB_SHARP... no
configure: error: Package requirements (glib-sharp-2.0 >= 2.4.0) were not met:

No package 'glib-sharp-2.0' found
```

**Comment by KryDos** [comment]
@brabalan you can `brew edit notmuch` and update gmime compilation option with `--disable-mono`. 
Maybe `brew install mono` also should help.

**Comment by brabalan** [comment]
@KryDos Thank you for the suggestion, it worked with the `--disable-mono` option. I already have mono installed, so the problem does not come from there.

**Comment by xuning97** [comment]
problem still exist, the final solution is to use brew edit notmuch?
