### ISSUE TITLE
boost: build stuck on OS X 10.11.4

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-core#133]
_From @mdelmans on April 7, 2016 14:19_

Installation of boost with

`brew install boost --c++11`

hangs at 

`...updated 13743 targets...`

been like this for ~12 hours.

_Copied from original issue: Homebrew/brew#43_

**Comment by tdsmith** [comment]
_From @mikemcquaid on April 7, 2016 14:24_

Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by tdsmith** [comment]
_From @mdelmans on April 7, 2016 15:10_

Sorry I did't follow the protocol.

I ran` brew update` (twice)
I fixed all warnings (apart from unbowed headers I believe are from node.js)
My command line tools are up to date (OS is to the latest update as well)

Still stuck at

`...updated 13743 targets...`

Gist logs:
https://gist.github.com/3f391e758d751c78ecc62fbef9f99033

**Comment by tdsmith** [comment]
_From @UniqMartin on April 7, 2016 19:6_

This seems to be a legitimate bug. I'm able to reproduce it locally, though I haven't isolated the problem yet. Stay tuned …

**Comment by tdsmith** [comment]
We get reports about this on IRC occasionally. I've never been able to reproduce; I think it might be hardware-linked? I don't have a problem on a 16gb MacBookPro11,5.

```
CPU: 8-core 64-bit haswell
OS X: 10.11.4-x86_64
Xcode: 7.3
CLT: 7.3.0.0.1.1457485338
Clang: 7.3 build 703
```

**Comment by tdsmith** [comment]
Incidentally `--c++11` is a no-op on ≥ 10.9; you can almost certainly work around this by not passing any options and just using the bottle.

Removing the `bug` label since this is not obviously a Homebrew bug.

**Comment by UniqMartin** [comment]
It's a legitimate bug, I reproduced it locally, and am preparing a fix right now. It's triggered by `boost` but isn't immediately related to that formula (other formulae are probably also affected).

**Comment by apjanke** [comment]
Do you know where the hang happens? Is it right toward the end of installation before "Cleaning" and "Finishing up" should happen? Seems like it might be, since "...updated 13743 targets..." sounds like a status message output at the end of a `make` pass

I was just working on [a hang in `install` under `brew test-bot`](https://github.com/Homebrew/homebrew-core/pull/88) that seems possibly related to `env :userpaths`, and `boost` is one of the few other formulae to use that.

**Comment by tdsmith** [comment]
Incidentally, this is why boost has `env :userpaths`: https://github.com/Homebrew/legacy-homebrew/pull/15689

I think that may no longer be necessary.

**Comment by DomT4** [comment]
I'm not convinced `nginx` needs it any more either. I presume it was added because `nginx` [used to](https://github.com/Homebrew/homebrew-core/blob/8af0e9701434c9aef005f93e452f5a8a8edf0b61/Formula/nginx.rb) pluck the first `passenger-config` out of the `$PATH` if building with that option but for a fair while now it has been chained to the `passenger` formula instead via an option.

**Comment by UniqMartin** [comment]
A tentative fix is to be found in Homebrew/brew#46. Sorry I completely missed basically the same issue (and thorough analysis of it) that had already happened in #88.

**Comment by apjanke** [comment]
> Sorry I completely missed basically the same issue (and thorough analysis of it) that had already happened in #88.

No worries: no reason you should have known about it, unless you had been exhaustively watching all the comments on the core repo and made the connection. That wasn't even posted as an issue, just some trouble in a formula bump PR. I just saw the connection because you happened to mention the hang issue while I had been working on the other one.

I was *about* to post it as a new Issue to homebrew/brew, which is when you would have seen it, but you already had a fix out before I finished writing up the bug report.

**Comment by UniqMartin** [comment]
@mdelmans Try again after a `brew update`. This should have been fixed by https://github.com/Homebrew/brew/commit/d7aa0c0335dd67e4151503f3a29d7089c57059c3.

**Comment by mdelmans** [comment]
Thanks guys. Works like a charm.
