### ISSUE TITLE
Migrate remaining formulae away from OpenSSL 1.1

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-core#135527]
The following pull requests have stalled. We should try to get them merged as soon as possible:

- [x] #134851
- [x] #114543
- [x] #134821
- [x] #134775
- [x] #134749
- [ ] #134613
- [ ] #134599
- [x] #134593 - #154834
- [x] #134587 - #154584
- [x] #133524
- [x] #134914
- [ ] #134636
- [x] #134408

We should also remove formulae from [`versioned_dependencies_conflicts_allowlist.json`](https://github.com/Homebrew/homebrew-core/blob/1ee4cc64305cb89ec539f182492783e1628b083c/audit_exceptions/versioned_dependencies_conflicts_allowlist.json) as we're able to migrate them to `openssl@3`. Most formulae listed there come from having both `openssl@1.1` and `openssl@3` in their dependency trees.

**Comment by cho-m** [comment]
Going to close this given we deprecated all remaining formulae in #152278.

Formulae that will probably remain deprecated:
- `mono` won't build with OpenSSL 3 until F# is updated by Mono upstream which probably won't happen in near future.
- `sslyze` hasn't built for a while and uses its own copies of OpenSSL 1.0 and 1.1 for `nassl`.

Only `minimal-racket` may be possible to restore if we upstream changes to prioritize OpenSSL 3. If someone wants to restore `minimal-racket` then they can do so. Otherwise, it can undergo standard removal cycle and users can install full Cask instead.
