### ISSUE TITLE
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/irssi.rb no perl support ?

### ISSUE THREAD

**Issue by jHackenthal** [Homebrew/homebrew-core#138415]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
irssi.rb currently has --with-perl=no

This has been a common functionality that literally almost nobody wants to be without.

What is the logic of this ?

And when will it be turned back on ?

```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

enable perl

### What happened (include all command output)?

no perl !

### What did you expect to happen?

with perl !

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install irssi

exec /script
```

**Comment by jHackenthal** [comment]
ive reached out to Chen about an hour ago to bring it to his attention but have not received a response

**Comment by jHackenthal** [comment]
Chen is currently responding and working through the issue.

**Comment by jHackenthal** [comment]
HOMEBREW_VERSION: 4.1.4-18-gd313e8b
ORIGIN: https://github.com/Homebrew/brew
HEAD: d313e8b02752588b3f19a9729e6c0eac3765b23d
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c71bdecfd1d034143e7e4a70dd987651b85daf71
Core tap last commit: 75 minutes ago
Core tap branch: master
Core tap JSON: 08 Aug 13:22 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/vim
HOMEBREW_GIT_EMAIL: jhellenthal@DataIX.net
HOMEBREW_GIT_NAME: J. Hellenthal
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_COLOR: set
HOMEBREW_NO_EMOJI: set
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.41.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 11.7.9-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1

---

brew doctor
Your system is ready to brew.

**Comment by SMillerDev** [comment]
That is correct, perl is disabled. Since you are requesting a feature, please do so in a pull request.

**Comment by matsaman** [comment]
>That is correct, perl is disabled. Since you are requesting a feature, please do so in a pull request.

This isn't a feature request, it's a regression. Perl used to work and now it does not.

Now yes, obviously someone has to do the work, and if nobody is able to do new work that has to be done because something changed and Perl is newly not working with irssi, that is a roadblock.

But this here, is a regression. Filing the bug is the first step. The next step is *not* telling people to fix it. Respectfully, that kind of response defeats the entire purpose of an issue tracker. Even only saying 'Yes, it is broken.' would be more useful. But talking about how it is now broken would be even more useful. We're *tracking* issues here, for open source software, so that we can all do less work and benefit more rapidly. The goal is not for everyone to have to fix every single broken thing completely on their own. That is the opposite of the goal.

Perl support was either disabled accidentally or for a reason. In either case, the best next step is for that to be talked about, here, in an *open* bug.

**Comment by SMillerDev** [comment]
> This isn't a feature request, it's a regression. Perl used to work and now it does not.

Which is nowhere in the issue until now. 

> Filing the bug is the first step. 

Including the required information to assess the situation. Not just "gimme perl".
> The next step is not telling people to fix it. Respectfully, that kind of response defeats the entire purpose of an issue tracker.

If they just request a feature, that is absolutely the policy of Homebrew.

> Perl support was either disabled accidentally or for a reason. In either case, the best next step is for that to be talked about, here, in an open bug.

https://github.com/Homebrew/homebrew-core/pull/136747 says it didn't build, so the issue should be filed with irssi.

**Comment by matsaman** [comment]
> #136747 says it didn't build, so the issue should be filed with irssi.

Thank you. Now this issue — which will not be found only by myself — is actually useful. This is the way.
