### ISSUE TITLE
Capture maintainer info in commit message for bottle dispatch PRs

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#144071]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Right now, we dont capture maintainer information in the commit message but rather having BrewTestBot as committer for all bottle dispatch PRs (including sonoma bottle PRs)
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

good to show contributions/efforts from homebrew maintainers

### What happened (include all command output)?

n/a

### What did you expect to happen?

n/a

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
n/a
```

**Comment by ZhongRuoyu** [comment]
We could probably fix this by removing the `username` override here:

https://github.com/Homebrew/homebrew-core/blob/a4cbfc87dda873965044d9a942d667016e6ba032/.github/workflows/dispatch-build-bottle.yml#L161-L165

According to https://github.com/Homebrew/actions/tree/master/git-user-config#usage, the `username` defaults to `github.actor`, the one who dispatched the workflow.

Also note that this was first changed in 0f6e60214ff4f68c669d2ffea0307c8bcb848a38. From the commit message, it seems that this change was intentional and "based on feedback on Slack and elsewhere". Have we changed our opinion on this matter?

> the challenge with adding co-author text to the dispatch-build-bottle commit message is that we only have access to the username (github.actor) and ID (github.actor_id) of the person who initiated the workflow run and would seemingly need to make an authenticated API call to fetch the user information (the response contains name, email, etc.)

It seems that [this line](https://github.com/Homebrew/actions/blob/ddd69f8b758cbdf30d473b56b6fd963313853ae1/git-user-config/main.js#L16) already takes care of that.

> One thing we would need to confirm is that adding co-author text to the commit doesn't conflict with the "last pusher" restriction.

This should be fine, since @BrewTestBot is always the pusher (and @github-actions the reviewer).
