### ISSUE TITLE
libtiff (4.0.6_1) failing build on 10.11.5

### ISSUE THREAD

**Issue by pramodhegde** [Homebrew/homebrew-core#1472]
### Bug reports:

libtiff (4.0.6_1) failing build on 10.11.5
https://gist.github.com/pramodhegde/8f631240ac0fda518acfc11b363724b7

**Comment by UniqMartin** [comment]
Please follow the advice provided by `brew doctor` and move as much of the stuff it is complaining about outside of `/use/local`. I'm pretty sure the build failure is caused by `/usr/local/lib/libc++.1.0.dylib` and other related files being there.

**Comment by dannymichel** [comment]
Brew doctor doesn't complain about anything, and /usr/local/lib/libc++.1.0.dylib doesnt exist

**Comment by UniqMartin** [comment]
Closing this for a lack of response (issue is fixed?), but happy to reopen once there's some activity here.

> Brew doctor doesn't complain about anything, and /usr/local/lib/libc++.1.0.dylib doesnt exist

This advice did apply to the original posters problem and the logs they provided. It obviously can't apply to every case. Please open a new issue if you are having trouble and provide the information that will be requested in the issue template, so that we can try to help you. Thanks!
