### ISSUE TITLE
Minisat bottle not working

### ISSUE THREAD

**Issue by cdehnert** [Homebrew/homebrew-core#14778]
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I also tried building minisat from source (by providing `--build-from-source`), which would fail. The gist-logs output shows these compilation issues. However, this compilation problem is **not** the core of the issue report, it is the bottle (that also appears to be broken).

`https://gist.github.com/2c9fd4cf9c35f974927e02d7a5a8633e`

- What you were trying to do (and why)
Install minisat to use it.
- What happened (include command output)
Minisat installed properly (via bottle). However, on running minisat I get:
```
$ minisat
dyld: Symbol not found: __ZdlPvm
  Referenced from: /usr/local/bin/minisat
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/bin/minisat
[1]    19903 abort      minisat
```

- What you expected to happen
I expected it to run without linker issues.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install minisat
$ minisat
```

**Comment by ilovezfs** [comment]
@cdehnert Thanks for reporting this! It should be fixed now.

**Comment by cdehnert** [comment]
I can confirm that it works now, thanks! However, now minisat has gcc as a dependency, which is a bit annoying and unnecessary. With a very minor patch, I was able to build minisat from source using clang. If this could be done for minisat in brew, this would take away the gcc dependency and simultaneously enable builds from source. Of course, if this is out-of-scope, I am also happy with the current solution.

**Comment by ilovezfs** [comment]
@cdeccio gcc was always a dependency. Now it is explicit. Previously, it was implicit due to the `fails_with :clang` in the formula. The fact that it was implicit not explicit is why this broke because it didn't get the proper revision bump when gcc was upgraded.

You locally have llvm installed, which caused the `fails_with` clang not to prompt a gcc installation, which is why the source build failed in addition to the bottle having already become a dud.

We'd be happy to look at a PR for a patch that gets rid of the gcc dependency as long as the patch also get reported to upstream.

**Comment by ilovezfs** [comment]
@cdehnert gcc was always a dependency. Now it is explicit. Previously, it was implicit due to the `fails_with :clang` in the formula. The fact that it was implicit not explicit is why this broke because it didn't get the proper revision bump when gcc was upgraded.

You locally have llvm installed, which caused the `fails_with :clang` not to prompt a gcc installation, which is why the source build failed in addition to the bottle having already become a dud.

We'd be happy to look at a PR for a patch that gets rid of the gcc dependency as long as the patch also gets reported to upstream.

**Comment by cdehnert** [comment]
Sadly, the issue is addressed (and fixed) in multiple pull requests for minisat. However, the authors appear to be oblivious of this. Given the date of the last release, I'd say minisat is not maintained any more. Is there still a way to have this patched, e.g. by using the patches provided in the pull requests for minisat?
