### ISSUE TITLE
[Feature request] Make `brew upgrade` fail without arguments (and add an `--all` option)

### ISSUE THREAD

**Issue by gwerbin** [Homebrew/homebrew-core#1519]
As the title says. Right now, it's too easy to accidentally upgrade everything all at once.

I know for _important_ versioned dependencies you can `pin` them. But even so I would prefer the safety of this change. I'd make a PR but I don't know a lick of Ruby.

What do you guys think?

**Comment by DomT4** [comment]
Oh-oh, this subject again 😄.

So, we actually [introduced this](https://github.com/Homebrew/legacy-homebrew/pull/38572) a while ago now (You can still find it used [all over GitHub](https://github.com/search?q=brew+upgrade+--all&type=Code&utf8=%E2%9C%93)) and people effectively threw a small riot about it. Fairly soon after, it was [reverted](https://github.com/Homebrew/legacy-homebrew/pull/40372).

I don't have a strong objection to it being implemented as an optional feature this time around, but I think last time effectively showed it's probably too late to make major eventually-breaking changes to the `upgrade` command without causing lasting confusion.

**Comment by gwerbin** [comment]
Sorry, I did a search but it wasn't too thorough.  Yeah, as a compromise maybe there could be an option with an environment variable or something?

**Comment by ilovezfs** [comment]
Pinning is only really effective on formulae that are leaves, since any upgrade of a reverse dependency of the pinned formula will cause it to be upgraded despite the pin. Once something is upgraded in master it's only truly considered installed if the latest version is installed. In other words, brew is currently inherently built around the idea that everything is always being upgraded to the latest version, and that's the only version of the formula that we support at any given time.

A feature that actively makes it easier for people to treat upgrades as opt-in only is for some other package manager, but not brew.

**Comment by MikeMcQuaid** [comment]
We considered this in the past but at this point this is behaviour that cannot be changed without annoying the majority of existing Homebrew users. If you have dependencies you need to rely on not being upgraded I'd strongly suggest [creating your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Sorry and thanks!
