### ISSUE TITLE
openshift-cli needs version pinning

### ISSUE THREAD

**Issue by miztroh** [Homebrew/homebrew-core#157271]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
The openshift-cli has a showstopping bug present since 4.11 (currently on 4.14).  It would be really great to be able to install pinned versions of this package (e.g. brew install openshift-cli@4.10).

See details here.  Search for "x509: certificate is not standards compliant"
https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run the ``oc login --token=<token> --server=<server>`` command.

### What happened (include all command output)?

error: x509: “<hostname>” certificate is not standards compliant

### What did you expect to happen?

I expected the package the command to log me in.  While the issue is on the package maintainer's side, brew could greatly aid in a workaround by providing pinned versions (e.g. brew install openshift-cli@4.10).  Currently, there are no pinned versions and so the only solution is to go and find an older (4.10.x or older) openshift-cli binary from the package maintainer's archive.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openshift-cli
oc login... (see above)
```

**Comment by SMillerDev** [comment]
Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions)?

Because it doesn't seem like upstream is concerned enough with your bug to stop releasing.

**Comment by Bo98** [comment]
This is a change on Go's side since 1.18. oc 4.11 just happened to be the first version that OpenShift shifted their own builds to use ago 1.18, so if you use their precompiled binaries then you will see a difference there.

We do not use precompiled binaries so 4.10 under a newer Go would have the same issue. We will not be switching all the way back to Go 1.17 - that would bring security issues on its own and we have already deprecated that version. This also aligns with the direction upstream has decided to take.

Note that the breakage only affects certain environments. The breakage is due to stricter certificate requirements. The certificate you are working with must comply with these two documents:

* https://support.apple.com/en-gb/103214 (note however that Go might only support embedded SCTs rather than the TLS extension)
* https://support.apple.com/en-gb/102028

If you are unable to adjust the certificate to meet those requirements, your best option is either downloading an older precompiled binary release or building your own Go 1.17 and compiling a oc build in your own tap.
