### ISSUE TITLE
Texlive license is not exactly ":public_domain"

### ISSUE THREAD

**Issue by thomwiggers** [Homebrew/homebrew-core#157357]
The texlive package specifies the "public domain" license. While that is true for some parts of TeX, it's certainly not true for many packages distributed in CTAN and Texlive, for example, ChkTeX has the GPL license. Other things are under the https://en.wikipedia.org/wiki/LaTeX_Project_Public_License, and https://tug.org/texlive/copying.html states:

> LICENSING FOR NEW PACKAGES:
>
>Finally, we have been asked what license to use for new work.  To be
>considered for inclusion on TeX Live, a package must use a free software
>license, such as the LaTeX Project Public License, the GNU General
>Public License, the modified BSD license, etc.  (Please use an existing
>license instead of making up your own.)  Furthermore, all sources must
>be available, including for documentation files.  Please see
>https://tug.org/texlive/pkgcontrib.html for more information, and other
>considerations.

I'm not sure what exactly is the best way to specify this strange situation though. The Arch Linux project seems to have settled on "GPL", Debian ships a custom license https://metadata.ftp-master.debian.org/changelogs//main/t/texlive-base/texlive-base_2022.20230122-3_copyright

**Comment by fxcoudert** [comment]
Our textlive distribution includes texlive-texmf, which has **a lot** of differently licensed files, including: LaTex Project Public License (LPPL), GNU Public License v2 (GPLv2), GNU Public License v2 or later (GPLv2+), Public Domain.

I suggest we use `license :cannot_represent`, simply because nothing else would be true. (I think most complex pieces of software are under very complex license terms and should actually be tagged `license :cannot_represent`.)
