### ISSUE TITLE
openbaton-client fails to install on MacOs 10.12.6-x86_64

### ISSUE THREAD

**Issue by marcellom** [Homebrew/homebrew-core#17376]
- What I am trying to do (and why):  

I am trying to install my formula. I want to put this formula in the public repo so that I can install it with "brew install openbaton-client"
- What happened (include command output):  

I run "brew install --build-from-source openbaton-client.rb" and it shows operation not permitted. This is the **brew gist-logs**: https://gist.github.com/marcellom/9bb36b41ad039544ab08927c0001dd13
- What I expected to happen:  

Open Baton client installs correctly without errors.
- Step-by-step reproduction instructions (by running `brew install` commands):  

You can reproduce it running the following commands:
```bash
wget https://raw.githubusercontent.com/marcellom/homebrew-core/openbaton-client4.0.0/Formula/openbaton-client.rb
brew install --build-from-source openbaton-client.rb
```

**Note**: I already know about the sandbox (https://github.com/Homebrew/brew/pull/2898) but how am I supposed to test the formula locally?

**Comment by DomT4** [comment]
Try sticking `ENV.java_cache` inside your `def install` block.

**Comment by marcellom** [comment]
Thanks a lot, it fixes the problem. Can you briefly explain me why before I close this issue? I didn't find this hint in the doc.

**Comment by DomT4** [comment]
Aye, sure. It's semi not-documented because the implementation isn't necessarily final.

Java has its own method of finding the user's home path, and consequently although Homebrew temporarily redirects `HOME` during install & `test do` it bypasses that and tries to write outside the sandbox, which is blocked.

Setting `ENV.java_cache` appends `-Duser.home=#{HOMEBREW_CACHE}/java_cache` onto `_JAVA_OPTIONS`, which is a location the sandbox will allow writing to during build/testing.

**Comment by marcellom** [comment]
ok thanks for the explanation. I can close the issue.
