### ISSUE TITLE
mkvtoolnix GUI not appearing as an Application

### ISSUE THREAD

**Issue by paulb** [Homebrew/homebrew-core#1805]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

- Installed mkvtoolnix using `brew install --with-qt5 mkvtoolnix`
- Installation appears successful
- mkvtoolnix-gui exists at /usr/local/bin/mkvtoolnix-gui
- I can run this in a terminal and it opens the gui. Closing the gui returns me to the terminal and the process exits.

I cannot get mkvtoolnix gui to link/run as a regular app.

`brew linkapps mkvtoolnix` gives no output, nor any failure messages (but I presume no output is an indication of failure as it should list apps successfully linked, as it does when I run `brew linkapps qt5`.)

Output from `brew gist-logs mkvtoolnix`:

https://gist.github.com/504a816908f9515b92dfe8bec0eac64d

Have I done something wrong or missed a step?

**Comment by UniqMartin** [comment]
> `brew linkapps mkvtoolnix` gives no output, nor any failure messages (but I presume no output is an indication of failure as it should list apps successfully linked, as it does when I run `brew linkapps qt5`.)

No, an empty output simply means that there was nothing to be done. If there was an error, it would have been printed.

> Have I done something wrong or missed a step?

You haven't done anything wrong. The GUI built by `mkvtoolnix` is just a binary, whereas the applications provided by `qt5` are true application bundles (directories with special structure and `.app` extension). Making `mkvtoolnix` build an app bundle probably won't be that difficult, but that's something that needs to be done as part of the upstream `mkvtoolnix` project. Homebrew is just packaging what is provided.

(Because the upstream developer doesn't work with OS X, some contributor of that project will need to step up, do the work, talk upstream into accepting the change, and thus make this happen.)
