### ISSUE TITLE
Brew install fails with error "undefined method 'default_spec_cache_dir'"

### ISSUE THREAD

**Issue by coryfklein** [Homebrew/homebrew-core#1827]
I've upgraded, updated, doctored, and permissioned brew:

```
$ brew upgrade
$ brew update
Already up-to-date.
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
$ sudo chown -R $(whoami) $(brew --prefix)
Password:
$
```

### Bug reports:

Some `brew install` commands fail with the error `Error: undefined method 'default_spec_cache_dir' for Gem:Module`

```
$ brew install Caskroom/cask/brew-cask
==> brew cask install Caskroom/cask/brew-cask
Error: undefined method `default_spec_cache_dir' for Gem:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/Library/Ruby/Site/2.0.0/rubygems/path_support.rb:38:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:357:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:357:in `paths'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:379:in `path'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:794:in `dirs'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:658:in `each_normal'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:669:in `_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:864:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:864:in `find_inactive_by_path'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:175:in `try_activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:61:in `<main>'
```

I tried to resolve this by upgrading the version of ruby that brew uses, since `2.0.0` releases can often be unstable.

Looking at `/usr/local/Library/brew.rb`, it is clear that without setting `HOMEBREW_DEVELOPER`, brew will use the version of ruby defined in `/System/Library/Frameworks/Ruby.framework/Versions/Current`. Most sources online recommend using `rvm` to manage ruby installation versions, but brew provides no way to use rvm installed ruby versions instead of the OS X default version.

OS X also does not allow updating its current version of Ruby.

```
$ sudo rm -rf /System/Library/Frameworks/Ruby.framework/Versions/Current
rm: /System/Library/Frameworks/Ruby.framework/Versions/Current: Operation not permitted
```

What do you think about updating `/usr/local/Library/brew.rb` to **not** be hard-coded to the OS X system default ruby version?

Reproduced on OS X El Capitan 10.11.5

**Comment by coryfklein** [comment]
Modifying `brew.rb` like so resolved the issue for me:

```
if [[ -z "$HOMEBREW_RUBY_PATH" ]]
then
  HOMEBREW_RUBY_PATH="$(which ruby)"
  if [[ -z "$HOMEBREW_RUBY_PATH" ]]
  then
    odie "No Ruby found, cannot proceed."
  fi
fi
```

In my case, the rvm installed `ruby` executable was on my path, so the `$(which ruby)` succeeded. Maybe a better modification would be:

```
if [[ -z "$HOMEBREW_RUBY_PATH" ]]
then
  HOMEBREW_RUBY_PATH="$(which ruby)"
  if [[ -z "$HOMEBREW_RUBY_PATH" ]]
  then
    HOMEBREW_RUBY_PATH="/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby"
  fi

  if [[ -z "$HOMEBREW_RUBY_PATH" ]]
  then
    odie "No Ruby found, cannot proceed."
  fi
fi
```

That may do a better job of using the `ruby` on the path if available, and otherwise falling back to the system level executable.

**Comment by UniqMartin** [comment]
We intentionally use the system Ruby because it has been proven to be much more stable and reliable than Ruby versions installed by users via `rvm` and similar tools. That's why we hard-code the system Ruby for normal users. Please don't modify `Library/brew.sh` and don't try to mess with the system-provided Ruby—or if you do, you're really on your own as that's not a configuration we support.

I suppose the error you are seeing is because you have modified some file like `~/.gemrc` in a way that isn't compatible with the older Ruby 2.0.0 provided by OS X. Or maybe you have `RUBYOPT` and/or `RUBYLIB` set in your environment? Please try to backtrack on those modifications and see which one causes this issue. (I suspect you will see a similar error when you do something as simple as running the system-provided `/usr/bin/irb`.) You could also consider moving aside `/Library/Ruby/Site/2.0.0/rubygems` as that's where the error is coming from and this directory doesn't exist on a pristine OS X installation. Maybe you have updated the RubyGems used by the system Ruby in the past?

Finally, `brew install Caskroom/cask/brew-cask` is not something you normally want to do. There's no need to install the `brew-cask` formula. You just start using `brew cask` commands and it will automatically tap the required repository, or if you want to be a bit more explicit, you can issues `brew tap Caskroom/cask`. That's all you need to do.

**Comment by coryfklein** [comment]
I reverted my modifications to `/usr/local/Library/brew.rb`.

I haven't modified `RUBYOPT` or `RUBYLIB` and `~/.gemrc` doesn't exist.

```
$ echo $RUBYOPT

$ echo $RUBYLIB

$ ls ~/.gemrc
ls: /Users/coryklein/.gemrc: No such file or directory
```

Running `/usr/bin/irb` does reproduce the issue:

```
$ /usr/bin/irb
/Library/Ruby/Site/2.0.0/rubygems/path_support.rb:38:in `initialize': undefined method `default_spec_cache_dir' for Gem:Module (NoMethodError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:357:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:357:in `paths'
### SNIP ###
```

## Solution

In my case, moving `rubygems` resolved the problem

```
mv /Library/Ruby/Site/2.0.0/rubygems /Library/Ruby/Site/2.0.0/rubygems.bak
```

@UniqMartin Thanks for your help.
