### ISSUE TITLE
Update wxWidgets --devel with 3 developer-supplied patches

### ISSUE THREAD

**Issue by TheZoc** [Homebrew/homebrew-core#1830]
Hello,

I'm willing to install wxWidgets 3.1 (--devel flag) on my osx, but I noticed there's 3 patches supplied by the developer that aren't in the formula, as stated on their [release information for the v3.1.0.](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.1.0):

- Creating ```wxComboCtrl``` without ```wxTE_PROCESS_ENTER``` style results in an assert. [Fix here](https://github.com/wxWidgets/wxWidgets/commit/cee3188c1abaa5b222c57b87cc94064e56921db8)
- Building under OS X in C++11 mode for i386 architecture (but not amd64) results in an error about narrowing conversion. [Fix here](https://github.com/wxWidgets/wxWidgets/commit/ee486dba32d02c744ae4007940f41a5b24b8c574)
- Building under OS X in C++11 results in several ```-Winconsistent-missing-override``` warnings. [Fix here](https://github.com/wxWidgets/wxWidgets/commit/173ecd77c4280e48541c33bdfe499985852935ba)

These patches are pretty simple, but I don't know how to specify a second ```:DATA``` section on the formula, to apply only on the 3.1.0 (```--devel``` flag) version. Is that even possible? :smiley:

Thank you very much!

**Comment by rakkesh** [comment]
```rb
devel do
    url "https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2"
    sha256 "e082460fb6bf14b7dd6e8ac142598d1d3d0b08a7b5ba402fdbf8711da7e66da8"

    # you can have multiple patches in the following format,
    patch do
      url ""
      sha256 ""
    end
  end

**Comment by UniqMartin** [comment]
Pretty much what @rakkesh said. If those commits apply cleanly, just append `.patch` to the URLs to get the URLs you can use as an argument to `url` in the `patch do` blocks. Multiple `:DATA` patches are not supported and we try to avoid using inline patches nowadays because their formatting is often broken by text editors when formulae are edited. Please [create a pull request](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) with these changes to the `wxmac` formula and we'll happily guide you through the rest of the process. Thanks!
