### ISSUE TITLE
go@1.4 fails to build on High Sierra

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#18465]
Full logs here: https://gist.github.com/ed85c4f2ea944ea7bd37b028f04b79fb

```
failed MSpanList_Insert 0x463000 0x141d2c56a364 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x3ee5eb)
        /usr/local/Cellar/go@1.4/1.4.3/libexec/src/runtime/panic.go:491 +0xad fp=0x7ffeefbfea10 sp=0x7ffeefbfe9e0
runtime.MSpanList_Insert(0x40f368, 0x463000)
        /usr/local/Cellar/go@1.4/1.4.3/libexec/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbfea38 sp=0x7ffeefbfea10
MHeap_FreeSpanLocked(0x40bf60, 0x463000, 0x100)
        /usr/local/Cellar/go@1.4/1.4.3/libexec/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbfea78 sp=0x7ffeefbfea38
MHeap_Grow(0x40bf60, 0x8, 0x0)
```

**Comment by fxcoudert** [comment]
Same failure is observed with `--cc=gcc-7`

**Comment by ilovezfs** [comment]
The above issue should be fixable with backports or just with using the bootstrap tarball.

Unlike the error above, the bootstrap version _does_ build successfully, but only with CGO disabled, which is sufficient then to build e.g. go@1.7.

If CGO is enabled you get
```
clang: error: no such file or directory: '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/lib/darwin17.0.0/libclang_rt.builtins-x86_64.a'
```

See
https://github.com/golang/go/issues/21908
https://trac.macports.org/ticket/54797

Both describe it as a High Sierra problem though it's actually an Xcode 9 and CLT 9 problem.

In https://github.com/golang/go/issues/21908 upstream seems to take the position that the fact that CGO doesn't build is irrelevant, since CGO disabled is all that's needed for a bootstrap compiler. That nugget doesn't seem to have made it over to https://trac.macports.org/ticket/54797 yet, which might be a good thing since someone might be inspired to fix it :)

Also, it's unclear to me that upstream realizes this is a regression and didn't affect < Xcode 9.

CC @DomT4 for thoughts.

**Comment by DomT4** [comment]
> Also, it's unclear to me that upstream realizes this is a regression and didn't affect < Xcode 9.

Yeah, I'm not sure they're getting this, for whatever reason. IMO, it's a not-completely-hideous compromise to make at this point to use a git checkout of https://github.com/golang/go/commit/d76c7d5a31ffaba3134f16981abd5f891fa2d805 & tweak the formula accordingly.

Beside from bootstrapping I'm not sure what practical use Go 1.4 would have at this point in the wild.

**Comment by DomT4** [comment]
PoC: https://github.com/Homebrew/homebrew-core/pull/18479
