### ISSUE TITLE
qt5 5.6.1 problems when used with py2app

### ISSUE THREAD

**Issue by muammar** [Homebrew/homebrew-core#1917]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

After the recent upgrade of **qt5** in homebrew, issues of the type `Class SOMETHING is implemented in both my.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore and /usr/local/Cellar/qt5/5.6.1/lib/QtCore.framework/Versions/5/QtCore. One of the two will be used. Which one is undefined` are not fixed by `macdeployqt`. 

Normally one has to copy `/usr/local/Cellar/qt5/$VERSION/plugins/` to `my.app/Contents/PlugIns` and run `/usr/local/Cellar/qt5/$VERSION/bin/macdeployqt`

I solved the problem by installing **qt5** `5.6.0`:

```
brew -v install https://raw.githubusercontent.com/Homebrew/homebrew-core/7f5799fd2178001b715827e3a84e021923d357c2/Formula/qt5.rb
```

and running the steps described previously. 

Has this something to do with the build in homebrew?. Please feel free to close this report if it is an issue related to the new **qt5** version.

Thanks.

**Comment by UniqMartin** [comment]
This almost certainly must be related to a change introduced between Qt 5.6.0 and 5.6.1, as there has literally been no change in the Homebrew formula itself aside from the version bump.

I'm not sure I fully understand the problem you are describing here, but there haven't been very many changes to `macdeployqt` in the quoted time span, so checking out the following changes might help you find out if those changes are somehow related to your problem:

- https://codereview.qt-project.org/#/c/149693/
- https://codereview.qt-project.org/#/c/156453/
- https://codereview.qt-project.org/#/c/159930/

Maybe also check out the linked issues on the Qt bug tracker. The only notable difference from the official binaries in how we build Qt is that we use the `-no-rpath` option, so that frameworks etc. get a absolute install name identical to the path where they will be installed whereas the official binaries use relative paths and `@rpath` to make the frameworks and libraries relocatable without any need for adjustment.

Closing as I guess this is not a Homebrew issue and there's not much more I can help with. Thanks!

**Comment by muammar** [comment]
@UniqMartin Thanks for your reply.  I reported  here first because I am using the brew formula. But it makes sense that if anything has changed recently the problem is upstream's. I will check there. Cheers.
