### ISSUE TITLE
Qt 5.6.1 fails to build with '--with-examples'

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#1948]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?  (N/A)  

My logs are [here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Qt/First%20Attempt) and [here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Qt/Second%20Attempt).  My [first attempt](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Qt/First%20Attempt)'s logs are just those created by Homebrew itself upon failure, but my [second attempt](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Qt/Second%20Attempt)'s logs also include the following files:  

* [`reinstall.log`](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/blob/master/Qt/Second%20Attempt/reinstall.log)
* [`doctor.log`](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/blob/master/Qt/Second%20Attempt/doctor.log)
* [`config.log`](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/blob/master/Qt/Second%20Attempt/config.log)

These files contain the results of redirecting standard output and standard error to them from the commands…:  

* `HOMEBREW_MAKE_JOBS=1 brew reinstall -vd --build-from-source qt5 --with-dbus --with-docs --with-examples --with-mysql`
* `brew doctor -vd`
* `brew config`

…, respectively.

**Comment by cjrh** [comment]
Same error during make:

```
make[2]: *** [sub-widgets-make_first] Error 2
make[1]: *** [sub-examples-make_first] Error 2
make: *** [module-qtbase-make_first] Error 2
```

**Comment by UniqMartin** [comment]
@RandomDSdevel Both failures can be attributed to the same cause, it's just that due to parallel build the error is a bit more difficult to spot in the first log file. In both cases the build should be fine if you remove `--with-examples` from your invocation.

Apparently a regression has been introduced in 5.6.1 that causes the build of the examples to fail, which is with 99% certainty an upstream bug. I'd encourage you to check with upstream whether this is a known problem and whether there's already a fix and if not, file a bug report.

@cjrh Quite possible this has the same cause and the same workaround, but with this little information that's really just a wild guess. Only if you can provide the information as requested in our [Troubleshooting guide](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) I can try to provide a more satisfying answer.

**Comment by cjrh** [comment]
@UniqMartin I reckon your analysis is correct regarding examples.  This behaviour is certainly new and I agree it's most likely an upstream problem.

**Comment by RandomDSdevel** [comment]
@UniqMartin:  I did a few searches of [Qt's bug tracker](https://bugreports.qt.io/secure/Dashboard.jspa) but wasn't able to find any upstream mentions of this bug.  Either nobody's filed it yet or I just didn't find it.

**Comment by RandomDSdevel** [comment]
@UniqMartin:  Now that I've had time to do a somewhat more extensive search of [Qt's bug tracker] to see if anybody else had already filed the upstream bug corresponding to this issue, it turns out that my and @cjrh's problem was fixed in [commit 58408ffa1b9c0b42a1719d3c8a4d4c62dec4fce6](https://codereview.qt-project.org/#/c/161001/) in response to [QTBUG-54110](https://bugreports.qt.io/browse/QTBUG-54110).  Would modifying the `qt5` formula so that it applies this patch be something easy that I could do myself, or do Homebrew maintainers like yourself usually manage Qt formula updates?

**Comment by UniqMartin** [comment]
@RandomDSdevel Thanks for finding that! If you feel comfortable preparing a PR for that, go ahead (and let me know). The fix is still needed for Qt 5.7.0 (currently being prepared in #2087), so we would need to apply it anyway. Otherwise I wouldn't mind extracting that patch and fixing it directly myself as this isn't part of the default configuration and thus doesn't need to go through the build bot and all that stuff.

**Comment by RandomDSdevel** [comment]
@UniqMartin:  You're welcome!  Yes, I do feel comfortable preparing and submitting a PR for this as soon as I can since the changes I'll need to make look simple enough for even a Homebrew novice like myself to contribute, so I'll get around to doing that as soon as I can, then.

**Comment by RandomDSdevel** [comment]
@UniqMartin:  As you can see by the notification that GitHub produced above when I referenced this issue from my pull request,, it is now ready!  I'll need some help refining my contribution, though, since the patch doesn't get applied properly (perhaps we're missing some prerequisite commits from upstream here?)

**Comment by UniqMartin** [comment]
Build with `--with-examples` should now succeed after updating the formula via the usual `brew update`. Thanks to @RandomDSdevel for contributing a PR after finding the relevant bug report and matching fix!

**Comment by RandomDSdevel** [comment]
@UniqMartin:  Once again, you're very welcome!
