### ISSUE TITLE
install qscintilla2 error

### ISSUE THREAD

**Issue by bennytrill** [Homebrew/homebrew-core#1953]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Currently running into this issue when running `install qscintilla2`, not sure what the issue is. Help would be much appreciated.

Error:
https://gist.github.com/da558092bb655b302ea9110ef65e9a49.git

**Comment by UniqMartin** [comment]
> Error:
> https://gist.github.com/da558092bb655b302ea9110ef65e9a49.git

I'm sorry, but this doesn't contain enough information. It doesn't even show the error that caused the build to fail. Please follow all of the steps in our [Troubleshooting Guide](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) and post the requested information, particularly the output of `brew gist-logs qscintilla2`. Otherwise we can't help you.

**Comment by DomT4** [comment]
Please let us know if we can help further here, Thanks!
