### ISSUE TITLE
`ant` has option to install `ivy`

### ISSUE THREAD

**Issue by s172262** [Homebrew/homebrew-core#19888]
`ant` has a option to install `ivy`.  Of course, `ivy` installs `ivy`. Because both Formulas installs `ivy` into another location, both aren't conflicting now.
Is this design? Which location of `ivy` is correct?
```
$ brew info ant
ant: stable 1.10.1 (bottled), HEAD
Java build tool
https://ant.apache.org/
/usr/local/Cellar/ant/1.10.1 (1,630 files, 38.6MB) *
  Built from source on 2017-10-16 at 20:22:27 with: --with-bcel --with-ivy
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ant.rb
==> Requirements
Required: java >= 1.8 ✔
==> Options
--with-bcel
	Install Byte Code Engineering Library
--with-ivy
	Install ivy dependency manager
--HEAD
	Install HEAD version
```
```
$ brew info ivy
ivy: stable 2.4.0
Agile dependency manager
https://ant.apache.org/ivy/
/usr/local/Cellar/ivy/2.4.0 (982 files, 18.8MB) *
  Built from source on 2017-10-26 at 22:37:50
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ivy.rb
```
In `ant`
```
  resource "ivy" do
    url "https://www.apache.org/dyn/closer.cgi?path=ant/ivy/2.4.0/apache-ivy-2.4.0-bin.tar.gz"
    sha256 "7a3d13a80b69d71608191463dfc2a74fff8ef638ce0208e70d54d28ba9785ee9"
  end
```
In `def install` of `ant`
```
    if build.with? "ivy"
      resource("ivy").stage do
        (libexec/"lib").install Dir["ivy-*.jar"]
      end
    end
```
In `ivy`
```
class Ivy < Formula
  desc "Agile dependency manager"
  homepage "https://ant.apache.org/ivy/"
  url "https://www.apache.org/dyn/closer.cgi?path=ant/ivy/2.4.0/apache-ivy-2.4.0-bin.tar.gz"
  sha256 "7a3d13a80b69d71608191463dfc2a74fff8ef638ce0208e70d54d28ba9785ee9"

  bottle :unneeded

  def install
    libexec.install Dir["ivy*"]
    doc.install Dir["doc/*"]
    bin.write_jar_script libexec/"ivy-#{version}.jar", "ivy", "$JAVA_OPTS"
  end
end
```

**Comment by ilovezfs** [comment]
@apjanke any thoughts here?

**Comment by s172262** [comment]
What's this?
```
$ brew uninstall ivy
Error: Refusing to uninstall /usr/local/Cellar/ivy/2.4.0
because it is required by ant 1.10.1, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies ivy
```

**Comment by ilovezfs** [comment]
If you `brew install --with-ivy ant`, then `ivy` is a dependency that cannot be uninstalled until you first uninstall ant.

**Comment by s172262** [comment]
But `ivy` is independent from `ant` in actuality.

**Comment by ilovezfs** [comment]
@s172262 which could be an argument for removing the option from ant.

**Comment by s172262** [comment]
I am confusion.

**Comment by apjanke** [comment]
I'm not an Ivy expert, but the current formula definition looks reasonable.

Ivy and Ant are projects which can each run standalone, but there is Ant/Ivy integration that allows Ivy tasks to run from within Ant, and I think that's what the `--with-ivy` option is addressing.

Think of it what you will, this existing design is consistent with the deployment model for Java applications that use external libraries or tools/programs that integrate at runtime. There's no standard way for Java applications to discover centrally-installed shared libraries; it's more typical for a Java application to ship with local copies of all its dependencies, or expect you to install them manually. It's kind of like how we vendor all the libraries for Go programs, I think.

So, we probably could fiddle with the installation to make the brewed `ant` installation aware of the brewed `ivy` installation. Maybe there's some search path we could edit, or we could just make a symlink from the `Cellar/ant` installation to the `opt/ivy` installation and rely on it doing something reasonable in the case of a broken symlink, but that's not a given, and it's probably not supported by upstream. The problem is that `brew` makes all its decisions at install time, not run time, and Java doesn't have good conventions for doing that run-time dependency discovery, aside from what applications themselves provide.

(I also don't see why `brew uninstall ivy` is complaining; looking at the current formula and recent changelog, there's no dependency between the two formulae; there's just an `ivy` resource within the `ant` formula. I tested it locally with current brew, and no errors.)

**Comment by apjanke** [comment]
The more I look at this, the more I wonder how that `Refusing to uninstall /usr/local/Cellar/ivy/2.4.0` is happening.

@s172262, are you sure you don't have a locally-modified `ant` formula?

**Comment by s172262** [comment]
I'm sorry, I forget that I edited `ant.rb` for trying to make a PR of this ploblem.

**Comment by s172262** [comment]
If there is no custom of  arranging `*.jar`, is it not necessary to pay attention to the following words?
```
$ brew list |xargs brew audit

berkeley-db:
  * JARs were installed to "/usr/local/opt/berkeley-db/lib"
    Installing JARs to "lib" can cause conflicts between packages.
    For Java software, it is typically better for the formula to
    install to "libexec" and then symlink or wrap binaries into "bin".
    See "activemq", "jruby", etc. for examples.
    The offending files are:
      /usr/local/opt/berkeley-db/lib/db.jar

open-mpi:
  * JARs were installed to "/usr/local/opt/open-mpi/lib"
    Installing JARs to "lib" can cause conflicts between packages.
    For Java software, it is typically better for the formula to
    install to "libexec" and then symlink or wrap binaries into "bin".
    See "activemq", "jruby", etc. for examples.
    The offending files are:
      /usr/local/opt/open-mpi/lib/mpi.jar
```

**Comment by apjanke** [comment]
Maybe, but I'm not sure what we should do aside from issuing that warning. It looks like placing the JAR files there is part of upstream's installation process, so other software might be relying on them being there.

Maybe it should be reported as part of the caveats for those formulae; right now it only shows up during the installation process and if you do `brew audit`, but not for `brew info`. Or perhaps if these instances are known to be expected and "safe" (though I don't know how we'd check that), they could be whitelisted.

**Comment by s172262** [comment]
O.K. I would not change the location of `*.jar` now.
