### ISSUE TITLE
Building somthing from source using libbase64 requires -I and -L to be manually set

### ISSUE THREAD

**Issue by DavidGriffith** [Homebrew/homebrew-core#202410]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Not applicable
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Over at https://gitlab.com/DavidGriffith/minipro/-/issues/335 it was brought to my attention that building Minipro on macOS (M1) requires `-L /opt/homebrew/Cellar/libb64/1.2.1_1/lib -lb64` and `-I/opt/homebrew/Cellar/libb64/1.2.1_1/include` flags to be explicitly set when it comes to linking to libbase64.  Shouldn't Homebrew be picking up on where libbase64 lives?

### What happened (include all command output)?

This is what was posted to the minipro Gitlab page:

```
$ make
...
src/database.c:27:10: fatal error: 'b64/cdecode.h' file not found
```

### What did you expect to happen?

The compile should have concluded with something like this:

```
gcc  src/xml.o src/jedec.o src/ihex.o src/srec.o src/database.o src/bitbang.o src/prom.o src/minipro.o src/tl866a.o src/tl866iiplus.o src/t48.o src/t56.o src/version.o src/usb_nix.o src/main.o -lusb-1.0  -lz  -lb64  -o minipro
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I don't know the specific steps as I don't run Homebrew.  I'm just passing along what was reported to me.  libusb and libb64 are required to build and run minipro.  libz also is needed, but I believe macOS includes that by default and so Homebrew doesn't need to install it.
```

**Comment by carlocab** [comment]
> ```shell
> Not applicable
> ```

This is always applicable.

Please provide the output of `brew config` and `brew doctor`. We require this information from all bug reports at Homebrew.

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

We can reopen this issue when you've provided the requested information.

**Comment by alebcay** [comment]
To offer a bit more insight on the original question:

> Over at [gitlab.com/DavidGriffith/minipro/-/issues/335](https://gitlab.com/DavidGriffith/minipro/-/issues/335) it was brought to my attention that building Minipro on macOS (M1) requires -L /opt/homebrew/Cellar/libb64/1.2.1_1/lib -lb64 and -I/opt/homebrew/Cellar/libb64/1.2.1_1/include flags to be explicitly set when it comes to linking to libbase64. Shouldn't Homebrew be picking up on where libbase64 lives?

Homebrew does know where libbase64 lives. In fact, Homebrew packages Minipro as well, and within the packaging/build environment, Homebrew sets the appropriate include paths/link paths in the environment to allow the toolchain to find other Homebrew-installed dependencies.

Looking at the GitLab issue you linked, it seems like the issue that is arising is when the end user is building software outside of Homebrew (minipro), using Homebrew-installed dependency (libbase64). In this case, manual steps are needed to help the user's toolchain find the dependencies; it is an intentional choice for Homebrew not to modify the user's toolchain configuration.

(Note that a similar issue would arise when using other package managers on macOS, whose installation prefixes are not in the default search paths)

As was further discussed in the linked issue, it would be best if the dependency package (libbase64) leveraged pkg-config and/or cmake to make itself discoverable - this reduces the friction when users want to build against Homebrew-installed dependencies. But this is something we rely on the upstream developers to provide.

**Comment by DavidGriffith** [comment]
For some reason `pkg-config` wouldn't find libbase64.  So I punted and put back the base64 code into minipro.
