### ISSUE TITLE
xdot 0.7 fails to start with "unknown signal name: draw"

### ISSUE THREAD

**Issue by fgsch** [Homebrew/homebrew-core#20969]
After installing xdot and try to run it I get:

```
$ xdot
2017-11-23 10:51:20.736 Python[39105:7322664] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
/usr/local/lib/python2.7/site-packages/gi/overrides/Gtk.py:48: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:35: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:39: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
Traceback (most recent call last):
  File "/usr/local/Cellar/xdot/0.7_1/libexec/bin/xdot", line 11, in <module>
    load_entry_point('xdot==0.7', 'gui_scripts', 'xdot')()
  File "/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py", line 2152, in main
    win = DotWindow()
  File "/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py", line 1961, in __init__
    self.dotwidget = widget or DotWidget()
  File "/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py", line 1539, in __init__
    self.connect("draw", self.on_draw)
TypeError: <xdot.DotWidget object at 0x107fc4b40 (xdot+DotWidget at 0x7f8442a00b10)>: unknown signal name: draw
```

brew config output:
```
HOMEBREW_VERSION: 1.3.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 236b0172306a6f4b233d374fcc20adce5c3e3261
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e21e1160c9fba5a667f19df93f198886f6199197
Core tap last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: N/A
macOS: 10.13.1-x86_64
Xcode: N/A
CLT: 9.1.0.0.1.1508540944
X11: N/A
```

**Comment by apjanke** [comment]
I can reproduce this error on High Sierra, but not Sierra. On Sierra, `xdot` emits a bunch of warnings, but still runs. Sounds like this is specific to the OS version.

On Sierra:

```
$ xdot
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:35: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:39: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo

(xdot:33063): Gtk-WARNING **: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(xdot:33063): Gtk-WARNING **: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(xdot:33063): Gtk-WARNING **: Error loading theme icon 'document-print' for stock: Icon 'document-print' not present in theme Adwaita
...
```

The warning about `You have imported the Gtk 2.0 module.  Because Gtk 2.0...` is absent; maybe that's related.

Also weird that in my Sierra runs, I get this:
```
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:35: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```
referring to Gtk 3.0, where the High Sierra runs get this warning referencing Gtk 2.0:
```
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:35: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```

Maybe someone more familiar with Python and GTK would know why apparently different library versions are getting loaded on Sierra and High Sierra?

**Comment by ilovezfs** [comment]
Happy to review a PR fixing this.

**Comment by rainchen** [comment]
I have the same problem:

```
TypeError: <xdot.DotWidget object at 0x10a1bd5f0 (xdot+DotWidget at 0x7febfa88db10)>: unknown signal name: draw
```

my macOS: 10.12.6-x86_64, HOMEBREW_VERSION: 1.5.2

**Comment by swingingsimian** [comment]
Same problem here too on high sierra:

`2018-02-23 09:36:25.566 Python[5698:559217] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
/usr/local/lib/python2.7/site-packages/gi/overrides/Gtk.py:48: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:35: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py:39: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
Traceback (most recent call last):
  File "/usr/local/Cellar/xdot/0.7_1/libexec/bin/xdot", line 11, in <module>
    load_entry_point('xdot==0.7', 'gui_scripts', 'xdot')()
  File "/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py", line 2152, in main
    win = DotWindow()
  File "/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py", line 1961, in __init__
    self.dotwidget = widget or DotWidget()
  File "/usr/local/Cellar/xdot/0.7_1/libexec/lib/python2.7/site-packages/xdot.py", line 1539, in __init__
    self.connect("draw", self.on_draw)
TypeError: <xdot.DotWidget object at 0x10e539fa0 (xdot+DotWidget at 0x7fa79608fb10)>: unknown signal name: draw`

Brew config:

'HOMEBREW_VERSION: 1.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 021fe22e3c982b08346422d1e7897e929a709380
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 454a9495ee85763526e6920837cef0c9dc946bb6
Core tap last commit: 42 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A'

**Comment by dnlggr** [comment]
`brew install gtk+3` fixed it for me on High Sierra.

**Comment by ilovezfs** [comment]
This should be fixed via https://github.com/Homebrew/homebrew-core/pull/25433 if you `brew upgrade xdot`
