### ISSUE TITLE
Don't --disable-debug for gtk+3

### ISSUE THREAD

**Issue by kennytm** [Homebrew/homebrew-core#2142]
Currently the `gtk+3` formula is [configured with `--disable-debug`](https://github.com/Homebrew/homebrew-core/blob/07b80486ad2cf90db351b026d1b4fae43fbcb253/Formula/gtk%2B3.rb#L49), but according to [the GTK+ 3 manual](https://developer.gnome.org/gtk3/stable/gtk-building.html#extra-configuration-options), a stable release should use `--enable-debug=minimal` (the default setting) instead:

> ### --enable-debug
>
> Turns on various amounts of debugging support. Setting this to 'no' disables `g_assert()`, `g_return_if_fail()`, `g_return_val_if_fail()` and all cast checks between different object types. Setting it to 'minimum' disables only cast checks. Setting it to 'yes' enables runtime debugging. **The default is 'minimum'.** Note that 'no' is fast, but dangerous as it tends to destabilize even mostly bug-free software by changing the effect of many bugs from simple warnings into fatal crashes. **Thus `--enable-debug=no` should *not* be used for stable releases of GTK+.**
>

I think this configuration should be removed. Would this be okay?

**Comment by DomT4** [comment]
I suspect it was set initially because it's used pretty much everywhere else to mean the obvious thing. I don't think I've ever seen this raised or discussed in regards to `gtk+3` before this Issue, presumably because it is rather buried.

Changing the arg to `--enable-debug=minimal` with perhaps a short comment explaining why `--disable-debug` isn't a good idea seems reasonable.
