### ISSUE TITLE
mingw-w64 formula is built with win32 thread model which prevents C++11 compliance

### ISSUE THREAD

**Issue by jakepetroules** [Homebrew/homebrew-core#21706]
The mingw-w64 formula builds gcc using the (presumably default) win32 thread model, which prevents full C++11 compliance due to the fact that std::mutex and std::thread are unavailable when using the win32 thread model.

The GCC configure script provides an option to select the thread model at GCC build time, --enable-threads=_lib_

Should we pass `--enable-threads=posix`, or at the very least, add an option to select the posix thread model instead of the Windows one? I'm not sure if it's possible, but it would be nice to have a bottle for that as well since I imagine this selection might be a rather popular one...

**Comment by fxcoudert** [comment]
Thanks @jakepetroules for the report. We're trying to ship mingw/gcc as close as the mingw-w64 maintainers themselves ship it. We could migrate to another thread model (and we do build and ship winpthreads as part of that formula).

Could you provide some information with what the mingw-w64 maintainers consider the "standard" or recommended thread model?

**Comment by jakepetroules** [comment]
Well, like I said, since it ends up with the win32 thread model and I don't see any build options in the formula that explicitly select one, I imagine that's the default and therefore the "standard" one.

As I said I'd like to see the ability to install the posix version since the win32 thread model does not enable full C++11 compliance.

**Comment by fxcoudert** [comment]
I think `--enable-threads=posix` would severely complicate the build, since we need the compiler to build winpthreads, and we need winpthreads to build the compiler (unless I am mistaken). So we would need a bootstrap compiler to be built first, which makes the formula harder to maintain for what I think may be a rare use case.

It would also make the formula very long to build, and would not provide users with bottles. Maybe a self-hosted formula (in a personal tap) is a better solution for your specific needs?
