### ISSUE TITLE
sane-backends failed to build on 10.11

### ISSUE THREAD

**Issue by moreka** [Homebrew/homebrew-core#2257]
### Bug reports:

sane-backends fails to build because it cannot find libusb, but I have installed libusb-compat successfully. So now I'm in trouble installing wine!

https://gist.github.com/fd395de0fdc42db6c1256fc8fa8970cf

**Comment by UniqMartin** [comment]
Please update your Xcode to the latest version (7.3.1) as suggested by `brew doctor`. I'm rather confident that this will resolve the build issue. The build is failing because a library, that should have been part of Xcode 7.2, is missing and causes unrelated `./configure` checks to fail (`libusb` isn't the problem).

**Comment by Lumbi** [comment]
Had the same issues and updating Xcode to 7.3.1 worked thanks @UniqMartin !

**Comment by moreka** [comment]
I'll install the new Xcode and report the result. Thanks for response @UniqMartin

**Comment by DomT4** [comment]
Any update here?

**Comment by moreka** [comment]
Fixed by updating Xcode to 7.3
Closing
