### ISSUE TITLE
ImageMagick's OpenMP support is broken

### ISSUE THREAD

**Issue by adah1972** [Homebrew/homebrew-core#23461]
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/363bd7deaef10034e7a3de5fc0f66a74
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I have found `convert` does not utilize multi-core as it used to do (I currently have these options set: `--with-gcc --without-libtiff --with-little-cms2`; I believe `--with-gcc` used to be `--with-openmp`).

The issue seems to be introduced in d3f7c0c6e8c8256341de10f696b6a6aa857ac0a8.

**Comment by adah1972** [comment]
Hi guys, you missed the `needs :openmp if build.with? "gcc"` part (admittedly, I do not understand it very well). According to my test, it is necessary…

@DomT4 @ilovezfs

**Comment by DomT4** [comment]
`fails_with :clang if build.with? "openmp"` seems possible, looking at other formulae.

Are you still seeing the issue if you do `brew reinstall imagemagick` locally?

**Comment by ilovezfs** [comment]
I think you mean
```
fails_with :clang if build.with? "gcc"
```
(or we could rename the option back to openmp for everyone's sanity)

Same wonderfulness needed in imagemagick@6.

**Comment by DomT4** [comment]
Yeah I do, well spotted. I literally lifted the line from another formula 🙈.

> (or we could rename the option back to openmp for everyone's sanity)

Either way is pretty ugly. I don't think we're going to get beauty here whichever way this is handled, alas.

**Comment by DomT4** [comment]
I'm also a bit confused by https://github.com/Homebrew/brew/commit/3e4544025d664fe381be96bf2526f08b7464e3cb#diff-170833a90b8b2d765544fc2166af6bf5. Maybe we should be enforcing using `llvm` instead of `gcc` where `openmp` support is necessary. I don't know.

**Comment by ilovezfs** [comment]
I think that was later overturned. In any case, `needs :openmp` had effectively been a synonym for `fails_with :clang` for quite a while, but led to people leaving out the `depends_on "gcc"` for the bottles, which were then broken on pour, which is what led to the deprecation.

**Comment by DomT4** [comment]
Ah I hadn't looked at the current code there yet, just went checking to confirm my suspicion that `needs :openmp` was 💀 either way now. I remember the fun around `gcc` and bottles, and `gcc` being declared a `build` dep when actual linkage was there.

If we can decide what the option name should be, I'll file an updated PR for both the Imagemagick formulae.

**Comment by ilovezfs** [comment]
>I remember the fun around gcc and bottles, and gcc being declared a build dep when actual linkage was there.

Right. We could have test-bot automatically pour llvm instead of gcc on a `needs :openmp` (or fix `brew` so that it adds the dependency automatically) and undeprecate `needs :openmp`, plus do something like https://github.com/Homebrew/homebrew-core/pull/10456 along with the corresponding superenv changes (or do a superenv-only fix as I'd recommended in https://github.com/Homebrew/homebrew-core/pull/10456), but I'm not sure much would be gained by doing all of that.


>If we can decide what the option name should be, I'll file an updated PR for both the Imagemagick formulae.

I'd call the option "with-openmp"

**Comment by DomT4** [comment]
>  I'm not sure much would be gained by doing all of that.

Yeah, I'm with ya. It's not the system before was beautiful & flawless, so reintroducing it in a slightly different format with bits glued on is going to remain as unwieldy & mysterious as it was before. Not an obvious upside.

> I'd call the option "with-openmp"

👍.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/23652

**Comment by DomT4** [comment]
Will check. I have a vanilla `imagemagick` installation & I don't use `pstoedit` so I can screw them both up and restore to a default easily enough.

**Comment by DomT4** [comment]
```
Warning: imagemagick dependency libtiff was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
```

```
Warning: pstoedit dependency imagemagick was built with a different C++ standard
library (libstdc++ from gcc-7). This may cause problems at runtime.
==> Summary
🍺  /usr/local/Cellar/pstoedit/3.70_2: 39 files, 1.9MB, built in 55 seconds
```
And `brew test pstoedit` passes fine too.

So the usual set of warnings but no fireworks.

**Comment by ilovezfs** [comment]
Interesting. @fxcoudert or @aw1621107 may know when/what fixed that.

**Comment by ilovezfs** [comment]
@adah1972 it should be ok now

**Comment by adah1972** [comment]
Terrific. Rebuilt and everything looks OK.

**Comment by aw1621107** [comment]
Sorry, I've been out of the Homebrew scene. Unfortunately, I have no clue when this was fixed, since I haven't messed with Homebrew formulae in ages.

>>Clang should be preferred over gcc because using gcc meant linking
against libstdc++, which is ABI incompatible with libc++. This may be
unnoticeable for some users, but it causes other builds to fail, e.g.
pstoedit when imagemagick was built with OpenMP. pstoedit is required
for the octave formula, so for some users this could be a significant
problem.
>
>I wonder if this is still a problem. I'm still having trouble believing gcc is really that brittle.

In theory, it's always has the potential to be a problem, based on my reading of [this Stack Overflow answer](https://stackoverflow.com/a/17454642).

It's not that gcc is brittle, it's that libstdc++ and libc++ define the internals of some standard library types differently. If any of the types in the public interface use stdlib stuff internally, this would  effectively result in the same type defined two different ways, depending on which `<string>` the compiler includes, thus violating the One Definition Rule and invoking the dreaded ghost of C++ -- Undefined Behavior. Not sure how likely one is to run into this sort of thing, but it's probably better to play it safe and stick with libc++ if possible.

I submitted a PR to try to resolve this in [brew/pull/3840](https://github.com/Homebrew/brew/pull/3840).

**Comment by rgov** [comment]
I believe it should be possible to use a brewed libomp and the system clang with:

    libomp = Formula["libomp"]
    ENV.append_to_cflags "-I#{libomp.opt_include} -Xpreprocessor -fopenmp"
    ENV.append "LDFLAGS", "-L#{libomp.opt_lib} -lomp"

This correctly gets through `configure`, which says the OpenMP feature will be built, and the binaries do get linked against libomp, but `convert -version` does not list support.
