### ISSUE TITLE
brew install opencv --without-numpy ignored

### ISSUE THREAD

**Issue by ernestyao** [Homebrew/homebrew-core#24396]
After opencv migrated to homebrew-core, the option "--without-numpy" is ignored. I wonder how could I use numpy pre-installed through pip instead of homebrew? There's no new option for it now.

If I `brew install numpy`, it'll be lots of file conflict messages. I think it's between Homebrew and pip.

OS: macOS 10.13.3

**Comment by fxcoudert** [comment]
In order to reduce the number of builds from source, to provide the majority of users with the best experience and to reduce maintenance and issues, we ship opencv with brewed python2 and python3, as well as Homebrew numpy.

You can look at hosting a specific formula for it in a personal tap if you want, starting from the last version of opencv in homebrew-science: https://github.com/Homebrew/homebrew-science/commit/6c38af15f22ff24e2b398970bc4eb102bfa2b7d2
