### ISSUE TITLE
Lua 5.2 should be re-added

### ISSUE THREAD

**Issue by sdegutis** [Homebrew/homebrew-core#24409]
I don't know when it was removed, but many Mjolnir users depend on Lua 5.2 being installable by a third party app (brew or macports). It's understandable that Lua 5.3 should be the default `lua` formula since it's the latest version, but it would be helpful to several of our users if Lua 5.2 were re-added as `lua@5.2` or something. Considering Lua 5.1 is still there (as `lua@5.1`) it seems like this isn't too far out there of a request.

**Comment by ilovezfs** [comment]
Please see the [guidelines for versioned formulae](https://github.com/Homebrew/brew/blob/master/docs/Versions.md). Upstream has indicated that there will be no further releases for 5.2 so we will not be adding it to Homebrew/homebrew-core. You'll need to update your software to support 5.3 or maintain 5.2 in [your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap).

**Comment by cmsj** [comment]
@ilovezfs fwiw Lua consumers tend to be very conservative about updating (likely why 5.1 is still present, since many users have no intention of moving to a more recent version, plus it's the only version directly comparable to LuaJIT, which has stated previously that it will not support some of the newer features in 5.2/5.3) so this may not necessarily be the most helpful interpretation of the guidelines.
