### ISSUE TITLE
Python upgrade problems on Mac OS

### ISSUE THREAD

**Issue by sunilshah** [Homebrew/homebrew-core#24767]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

Latest change to python3 and python@2 formulae seems to have created a problems. 

As per documentation I expect to see: 

https://docs.brew.sh/Homebrew-and-Python

Python 2.x or Python 3.x
Homebrew provides one formula for Python 2.7.x and another for Python 3.x. The executables are organized as follows so that Python 2 and Python 3 can both be installed without conflict:

python points to the macOS system Python (with no manual PATH modification)
python2 points to Homebrew’s Python 2.7.x (if installed)
python3 points to Homebrew’s Python 3.x (if installed)
pip2 points to Homebrew’s Python 2.7.x’s pip (if installed)
pip3 points to Homebrew’s Python 3.x’s pip (if installed)

Instead, now python has been symlinked to brew's python3.  This is a major problem for programs that rely on system python (2.7.10).

**Comment by hyiltiz** [comment]
Python2 and python3 are treated as alternative:

> This formula is keg-only, which means it was not symlinked into /usr/local, because this is an alternate version of another formula

That is false. Python 2 and Python 3 are two different programming languages with different standard libraries. Please stop treating them as alternatives and messing with the environment.

**Comment by sunilshah** [comment]
Hi Hyiltiz,

Where did you find the quote about Python2 and python3 as alternatives?  Please elaborate.  I am not sure it is in my original post anywhere.

If you think that the changes to python3 formula need to be reversed, please indicate so.

**Comment by ilovezfs** [comment]
@sunilshah see https://github.com/Homebrew/brew/pull/3863 for the documentation updates.

**Comment by ilovezfs** [comment]
@hyiltiz Python is now treated the same as other languages in Homebrew.

ruby (with an alias ruby@2.5)
ruby@2.3
ruby@2.2
ruby@2.0
ruby@1.8

node (with an alias node@9)
node@8
node@6
node@4

python (with an alias python@3)
python@2

**Comment by hyiltiz** [comment]
Now that they are called python@2 instead of python2, please then update the docs (links to this doc is also displayed when running `brew link pythonXYZ`):
https://docs.brew.sh/Homebrew-and-Python

I tend to think of python2 and python3 as two different languages, but that is not a very clear cut distinction and I barely see any point arguing if it is. However, we do need a definite procedure to follow to get back to a working system setup. It seems only one of the pythons are linked by Homebrew now.

**Comment by ilovezfs** [comment]
@hyiltiz right "python3" was renamed to python. So you now only have python3. If you also need python 2, then `brew install python@2` for the 🆕 python@2 formula.

**Comment by hyiltiz** [comment]
Huh? I did install it back in. I originally had python2 *and* python3 installed and managed by Homebrew, linked to /usr/local/bin. So somehow I had to re-install what I already had in the system? Maybe what I remember was wrong, and that python2 that was present in my system has always been what Apple provided. Anyway, simply reinstalling both python@2 and python@3 fixed the issues. 

Thanks for the explanation! I see the docs page is still not updated about the new naming (preferring python@2 etc.), not sure if it was intentional.
