### ISSUE TITLE
"The bottle needs the Xcode CLT to be installed" logged when Xcode CLT are installed

### ISSUE THREAD

**Issue by jab** [Homebrew/homebrew-core#2502]
```
$ which xcodebuild
/usr/bin/xcodebuild
$ brew upgrade python3
==> Upgrading 1 outdated package, with result:
python3 3.5.2
==> Upgrading python3
Warning: Building python3 from source:
  The bottle needs the Xcode CLT to be installed.
==> Downloading https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
...
```
![screen shot 2016-06-29 at 22 14 34](https://cloud.githubusercontent.com/assets/64992/16474724/1332bca4-3e47-11e6-9396-7c0e8e9a3033.png)

**Comment by DomT4** [comment]
There's a distinction in this case between the Command Line Tools shipped inside Xcode and Apple's Command Line Tools package. That explanatory message about the bottle is perhaps badly worded.

`brew config` will show whether Homebrew considers CLT installed or not.

**Comment by jab** [comment]
Thanks, that was confusing. `brew config` indeed showed `CLT: N/A` until I installed the package from https://developer.apple.com/download/more/; now it shows `CLT: 7.3.1.0.1.1461711523`. So I guess I won't have this problem in the future. +1 for improving the wording, ideally including a hint as to how to fix.

**Comment by DomT4** [comment]
Updated both `python` and `python3` to be a little clearer. Hopefully helps. Thanks for letting us know you found this confusing!

**Comment by jab** [comment]
Thanks @DomT4, and thanks for all your great work on Homebrew!

**Comment by jiahaoliuliu** [comment]
Try to run the follow command in the terminal:

`xcode-select --install`

It works for me:

CLT: 8.1.0.0.1.1476494586

**Comment by liuliangsir** [comment]
thx ~ @jiahaoliuliu

**Comment by orefalo** [comment]
Had the same, issue - installing the package fixed it.

**Comment by tloredo** [comment]
I had this issue with an installation requiring gcc, whose bottle required the CLT. I interrupted the installation. I had recently upgraded Xcode but hadn't launched it, so I launched it, with the usual dialog appearing offering to install tools. Afterwards, the brew upgrade had the same issue, which led me here.  `xcode-select --install` fixed it.

Before running `xcode-select`, I ran `brew doctor`, and there was no warning about the CLT status (perhaps because it does not affect all formulae).

I think this situation is confusing. `doctor` indicates there is nothing amiss with the user's setup, but some formulae indicate there is a problem. The error message does not clearly indicate the solution. Perhaps the python formulae address this, but it seems a more global solution is needed.
