### ISSUE TITLE
Python3: `sys.prefix` different between installation and execution causes `data_files` to be unreachable.

### ISSUE THREAD

**Issue by rappdw** [Homebrew/homebrew-core#25592]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/c8b81eebf205902f1b0715379f381596

- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

With a python3 install of brew, there are oddities/bugs in the handling of sys.prefix during installation as compared to run time. This perhaps can be best demonstrated by pip installing the example module found here: https://github.com/rappdw/brew-python-bug

This is due to the distutils.cfg specified in the formula overriding `sys.prefix`, setting it to `/usr/local` for installation.

In accordance with [Python Docs - Setup Script](https://docs.python.org/3/distutils/setupscript.html), data_files "... [directory specified] is interpreted relative to the installation prefix (Python’s sys.prefix for pure-Python packages, sys.exec_prefix for packages that contain extension modules)". 

This allows the data_file to be referenced in the installed module as:

```
import sys
import os

with open(os.path.join(sys.prefix, <file_spec from setup.py>)) as f:
    ...
```

Unfortunately, the override of `sys.prefix` prevents this for modules installed into the system site package space (virtual environments work fine).

- What happened (include command output)
(following the steps outlined below to reproduce) 

The first issue is the inability of the module's setup to write into /usr/local/config due to default OSX permissions (see log file attached)

Once that issue is circumvented, the underlying problem/bug is produced, namily, the datafile is installed into a `/usr/local/config` rather than`sys.prefix + \config`, rendering the data file unreachable by python code under execution.

- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
1. brew install python3
2. git clone https://github.com/rappdw/brew-python-bug.git
3. cd brew-python-bug
4. pip3 install -U pip
5. pip3 install .

This results in error1.log (attached). To work around this, do the following:

1. pip3 uninstall brew-python-bug
2. sudo mkdir /usr/local/config
3. sudo chmod a+w /usr/local/config
4. pip3 install .

This results in success1.log. Now to demonstrate the second issue caused by this, do the following:

1. python3 -m brew_python_bug

This results in: `Unable to find file where expected: /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/config/data.json`

**Comment by ilovezfs** [comment]
@zmwangx any ideas here?

**Comment by zmwangx** [comment]
Sorry, this is not a Homebrew Python bug. I wouldn't even call it a Python bug, it's just the unfortunate way `data_files` work — there's no standard way to access them post-install. They are even treated differently by different tools (distutils, setuptools, wheel, pip) and I never bothered to understand the differences; you may read up on that if you want to. [1] might be of some use in this regard (didn't check). In fact, if you use `python setup.py install` instead of `pip install`, you may find your data files zipped up in the egg and not unpacked to the filesystem at all. Also, `install.prefix` in `distutils.cfg` is just equivalent to `--prefix` on the `setup.py install` command line, which is a perfectly valid option to specify by the user.

I would recommend `package_data`[2] instead.

By the way, you may have noticed that you've been reading "Distributing Python Modules (Legacy version)". Since you're already using setuptools, read the setuptools documentation instead.

[1] https://github.com/pypa/python-packaging-user-guide/pull/212
[2] https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files

**Comment by ilovezfs** [comment]
@rappdw Thanks for the carefully crafted issue report. I'm closing this based on the comments from @zmwangx above.
