### ISSUE TITLE
jdk 9/10 for mac high_sierra? 

### ISSUE THREAD

**Issue by Pratish-minted** [Homebrew/homebrew-core#25941]
Is there a formula for jdk 9/10 in mac high_sierra available to use? 
Thanks

**Comment by Jahhein** [comment]
You can find the jdk for java through the [homebrew-cask](https://caskroom.github.io) extension to brew. 

Please use the brew.sh and https://caskroom.github.io to search for packages, or even the brew package manager (which is why its there) to search for it from the command line. `brew search java` would have found it from the CLI.

**Comment by ilovezfs** [comment]
```
brew cask install java
```
