### ISSUE TITLE
PHP SNMP extension

### ISSUE THREAD

**Issue by simPod** [Homebrew/homebrew-core#26004]
After the migration of homebrew-php to core, the php-snmp extension has been removed. According to this comment https://github.com/Homebrew/homebrew-php/pull/4798#issuecomment-377681986 it crashes Apache. 

Will it ever be back? I wonder whether it couldn't be marked as optional and installed after passing optional argument when installing at least? People who used it with previous versions before migration and relied on it might be unpleasantly suprised when the extension disappears after upgrade and that there's no easy way to get it back.

**Comment by SMillerDev** [comment]
You can maintain a separate Formula in a personal tap that has SNMP enabled. Or even better, you could find out how to get it to be more stable and then we can enable it in the core formula again.

**Comment by ilovezfs** [comment]
The upstream issue is here: https://bz.apache.org/bugzilla/show_bug.cgi?id=62115

**Comment by kabel** [comment]
The issue is that macOS system libs are linked/[loaded](https://gist.github.com/kabel/72ad23220c571a257162b814298349c2) in httpd _before_ the mod_ssl shared module is loaded. So, certain crypto symbols get used from the macOS libraries rather than the shared openssl library. This currently only affects High Sierra, as it lazy loads boringssl when these symbols are used.

If you accept the risk, I have put a [tap](https://github.com/kabel/homebrew-php-ext) together that has the core php extensions that didn't make the cut for Homebrew/core inclusion, including SNMP.
