### ISSUE TITLE
How do I install PHP packages after the deprecation

### ISSUE THREAD

**Issue by designermonkey** [Homebrew/homebrew-core#26362]
>>Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**The above message is a little rude as my problem has nothing to do with any of the data your checklist asks for. I have no issue with the brew runtime, but a question related to the now deprecated `homebrew-php` repo.**

Up until today (re-installed mac), I had formula installed and running from the deprecated repo:

```
- php72
- php72-ast
- php72-ds
- php72-imagick
- php72-mongodb
- php72-mustache
- php72-tidy
- php72-timezonedb
- php72-xdebug
- phpunit
```

Can someone explain to me how I am meant to install these now that the repo is deprecated and archived?

Are there alternatives available? Any information at all other than 'the repo is deprecated'?

**Comment by njt1982** [comment]
Not on your list, but #26338 mentions that mcrypt is included in the binary... (which I can see in the list with `php -m`)...

For me, memcache seems missing.

**Comment by ilovezfs** [comment]
>The above message is a little rude as my problem has nothing to do with any of the data your checklist asks for.

Please leave the determination of what's relevant to our judgment and always fill out the template.

You'll need to use `pecl` for whatever isn't listed by `php -m`

**Comment by SMillerDev** [comment]
@bcalik homebrew isn't really in the bussiness of writing guides. Luckily some PHP developers are and wrote a guide for the standard way to install php packages: https://secure.php.net/manual/en/install.pecl.intro.php

**Comment by bcalik** [comment]
@SMillerDev Then they should not delete everything suddenly, because everybody may not be ready to waste hours for this.

**Comment by SMillerDev** [comment]
There was a 2 month notice and multiple publications about it. Suddenly is hardly a good description here.

**Comment by bcalik** [comment]
So 2 months notice is really what you understand by backward compatibility? Why not make a "php-legacy" named tap so we can still use it? You guys don't really need to delete everything. So we could upgrade whenever we need it, or have time for it.

Btw, I follow homebrew official twitter page, but the first notice was on 9 March. So its not even a month. It must be at least 3 months. So a few weeks is "suddenly" for me.

**Comment by ilovezfs** [comment]
It was announced January 19 https://brew.sh/2018/01/19/homebrew-1.5.0/

>Why not make a "php-legacy" named tap so we can still use it?

It's still here in the Git history https://github.com/Homebrew/homebrew-php/commits/master

**Comment by bcalik** [comment]
So "do it yourself" isn't really helpful too.  
I can already do all my myself anyway, why would I need homebrew at all then?

> It was announced January 19 https://brew.sh/2018/01/19/homebrew-1.5.0/  

Sorry sir I don't check your blog page every day.

**Comment by ilovezfs** [comment]
@bcalik I'm not sure what response you're looking for. We're not going to undeprecate the tap, so you'll need to figure out something that works for you.

**Comment by njt1982** [comment]
I think the point your community is trying to make to you here is that next time this needs to be handled better/differently.

Not everyone subscribed to your blog feed (I don’t!)

Nobody will expect brew to update and blow away all their extensions and break so badly. In my case I had to completely uninstall and reinstall it.

Obviously what is done is done. You’re right, you can’t undeprecate it.

But next time you can respect that thousands of people have wasted thousands of billable hours due to the approach used in deprecating what seemed to be a fantastic and perfectly good brew tap for what appears to be a worse one (from a consumer point of view).

Homebrew exists and is successful not just due to clever people like the maintainers but also due to a community following. If you start making changes like this “common practice” then you’ll loose support of the community and the project will die. Nobody wants that.

So instead of replying to your community in such defensive and passive-aggressive tones, maybe listen to them and consider what happened and how to avoid it in the future?

What’s done is done. The “answer” is that your community now has to deal with PECL again. Personally, I see this as a step back. I liked brew because it meant I didn’t need to deal with yet another package manager.
Also PECL doesn’t seem to happily work with multiple installs of PHP under brew.

**Comment by MikeMcQuaid** [comment]
> thousands of people have wasted thousands of billable hours

@njt1982 I believe what you were trying to say was "thanks Homebrew for helping me make money!" and/or "thousands of people have learned to better manage systems that they rely on for billable hours".

> Homebrew exists and is successful not just due to clever people like the maintainers but also due to a community following.

Homebrew exists due to maintainers (mostly) and contributors. It does not exist due to a community of people who use it and complain when it doesn't work.

Finally, it's worth noting that literally every person who is complaining is capable of learning what's required to copy all the PHP formulae from the homebrew-php Git history and running their own tap. That they choose not to do so is up to them. This post helps explain why you don't really get to complain to the people who spend their free time building a tool that helps make you money: https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/
