### ISSUE TITLE
I can't upgrade npm with node@6

### ISSUE THREAD

**Issue by tom10271** [Homebrew/homebrew-core#27048]
I have installed node@6, it comes with npm 3.10.10. I need to use npm 5 at least.

Supposedly I should be able to upgrade npm with `npm i npm@5 -g`, it ran successfully but when I ran `npm -v` it is still npm 3.10.10

**Comment by chrmoritz** [comment]
Because npm lives in the Cellar of every versioned node formula since https://github.com/Homebrew/homebrew-core/pull/24349, upgrading a npm from a forced linked versioned node formula  isn't as easy anymore. You have basically 3 options if you don't want to use the npm version which ships with the versioned formula:

1. Use any node version manager (like nvm) to install older node versions
3. Use `npm i -g npm --prefix=/usr/local/opt/node@6` to update npm in the Cellar, but it will the destroyed (reverted to the one which ships with this node version) on every update of the `node@6` formula.
