### ISSUE TITLE
Use 'depends_on "python@2"' instead

### ISSUE THREAD

**Issue by HakChealKim** [Homebrew/homebrew-core#28267]
I am trying to install thrift version 0.10.0 but default brew install will install version0.11.0
so I just wanna check out an old version of the homebrew-core repository
but find few issues;
1.depends_on python is disabled;
to fix it I am trying   depends_on "python@2" => :optional
2.<<-EOS is disabled
to fix it I am trying <<~EOS
this works for my mac

**Comment by HakChealKim** [comment]
can i create an PR?

**Comment by fxcoudert** [comment]
Dear @HakChealKim it is not exactly clear what is your question?

**Comment by apjanke** [comment]
This sounds like you're trying to install Thrift 0.10.0 by using an older version of the `thrift.rb` formula in conjunction with the current version of `brew`. Unfortunately, there are some compatibility issues; the `thrift` formula has changed to keep up with new `brew` conventions/restrictions since the update to `thrift` 0.11.0, so just rewinding the formula to a previous point in time won't work.

```
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula on ⇄ master]
$ git log --oneline thrift.rb | cat
f2f012f236 thrift: update git repo (#26403)
a64beb753c thrift: remove homebrew/php references.
4f42176969 thrift: add test
6412d1b79a thrift: rename python@2 optional dependency
9f81309a1b thrift: fix Java build
58f6238717 thrift: depend on python instead of :python
eee08e2dc4 thrift: update 0.11.0 bottle.
2141928c71 thrift 0.11.0
```

If you want `thrift` version 0.10.0 at this point, what you probably really need is a `thrift@0.10` formula. 

`homebrew/core` currently provides current and 0.9 versions of `thrift`, but not 0.10.

```
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula on ⇄ master]
$ ls thrift*
thrift.rb  thrift@0.9.rb
```

There was a [previous PR for a thrift@0.10 formula](https://github.com/Homebrew/homebrew-core/pull/25639) that was rejected due to upstream maintenance requirements.

So I think if you need specifically Thrift 0.10, at this point, you need to to [create your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for it, or ask the Thrift maintainers to do so.
