### ISSUE TITLE
Naming collision in package yq

### ISSUE THREAD

**Issue by kislyuk** [Homebrew/homebrew-core#29529]
Hello,

The package distributed as `yq` by homebrew-core (from https://github.com/mikefarah/yq) conflicts with https://github.com/kislyuk/yq. (The package at https://github.com/mikefarah/yq was renamed to its current name in December 2017, while development of https://github.com/kislyuk/yq in its current form was started in January 2017.)

I'd like to distribute https://github.com/kislyuk/yq in Homebrew. What's the proper procedure for deconflicting naming collisions like this?

**Comment by kislyuk** [comment]
OK, thanks. I understand, but the original yq formula was self-submitted by its author, @mikefarah: https://github.com/Homebrew/homebrew-core/commit/67bc619d656021d6cb2429a045876144d834fb8c.

The problem that I face now is that users of this other piece of software (which as I mentioned was renamed to yq about a year after I started development) now come to me for support.

So it would be great if either the homebrew `yq` was removed, or renamed, or both formulas could be distributed under deconflicted names using `conflicts_with`, or something like that.

**Comment by ilovezfs** [comment]
Maybe you could rename your project to pyyq or pypi-yq or similar? Or one of the two projects could rename to yaml-query or yquery? The original problem was @mikefarah's project was just named `yaml` so I suggested `yq` but didn't notice the PyPI version (sorry). I don't think either project is entitled to the `yq` name; your project may be older but @mikefarah's already has more stars on GitHub (and there was another project older than both).  It would be great if you two could come to an agreement on how best to deconflict the project names. I'd just ask that mikefarah's not be renamed back to `yaml` since that's so generic.

**Comment by mikefarah** [comment]
I'm sorry that it conflicts with your repo name - I didn't notice it either at them time :( That said there are other projects called YQ too, as ilovezfs pointed out.

As they say naming things is the hardest thing in computer science.

I've already gone through the renaming process - and it would be harder to do it now as it's quite a bit more popular than it was a year ago, and it's now distributed in snapcraft, docker, debian packages, homebrew and github.  As far as I'm concerned the cat's already out of the bag.

Maybe you could name your package to reflect that it wraps jq? 

Or, because it wraps jq, it would have more features than my yq: yq-plus?  yqp? yqpy?

How many issues are you getting against your project that are mine?

**Comment by ilovezfs** [comment]
also relevant

https://repology.org/metapackage/yq/versions
https://repology.org/metapackage/yq-mikefarah/versions

**Comment by kislyuk** [comment]
@ilovezfs the other project that was older than both (https://github.com/abesto/yq) was the project that ceased to be maintained, and I offered and got permission to take over maintainership.

I named my project the way I did by analogy with jq's naming.

If you want to do this as a popularity contest by stars, I understand, I can come back later. Other than that, I can't think of a good way to deconflict. Perhaps homebrew could have two recipes, `yq-mikefarah` and `yq-kislyuk`.

**Comment by kislyuk** [comment]
I suppose we could also publish a homebrew formula under `python-yq`. But since @mikefarah's package was self-submitted, I think it should be OK then for me to write a formula for it, if nobody else wants to. Would that work?

**Comment by ilovezfs** [comment]
I have no objection to packaging both. I don't think we should name the formulae by people's names. We generally don't want to prepend a language name to a formula name unless it's actually the name of the project, though.

**Comment by kislyuk** [comment]
OK, do you have any ideas what we should call them?

**Comment by kislyuk** [comment]
I suggested `python-yq` because that is Debian/Ubuntu's convention for packages that are pulled in from language specific package managers.

**Comment by ilovezfs** [comment]
@kislyuk OK. I hope that at some point you and @mikefarah can come to an agreement on using different project names from one another but here we go: https://github.com/Homebrew/homebrew-core/pull/29776

**Comment by kislyuk** [comment]
@ilovezfs thank you so much for your work on this!

**Comment by ilovezfs** [comment]
@kislyuk you're welcome! `python-yq` has now shipped.
