### ISSUE TITLE
openconnect no longer builds

### ISSUE THREAD

**Issue by netheril96** [Homebrew/homebrew-core#2991]
- [✓] Ran `brew update` and retried your prior step?
- [✓] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [✓] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

The gist log is at https://gist.github.com/netheril96/d1d4157a6c527d724c2d037eff10e9dd. The build errors out with `<libxml/tree.h>` not found, but I have never had similar build problems with older versions. In fact, I have openconnect 7.06_1 installed, and only have this problem when trying to build 7.07, the latest version at homebrew-core now.

**Comment by DomT4** [comment]
Argh, I know what we've broken. The maintainer who pushed the change is almost certainly currently asleep. I'll take a look, but I may just end up pinging it to them for the morning as I'm sadly not capable of reading their mind on the changes & how intentional the specific line removals were in this case.

**Comment by DomT4** [comment]
Please `brew update` and try the installation again, Thanks!

**Comment by netheril96** [comment]
It indeed fixes the build issue.

**Comment by DomT4** [comment]
Thanks for the confirmation!
