### ISSUE TITLE
OpenSceneGraph 3.4.0 from bottle is built with QT, but osgQt is not included. 

### ISSUE THREAD

**Issue by yn** [Homebrew/homebrew-core#3039]

**Comment by UniqMartin** [comment]
Can you explain how you came up with the conclusion that is stated in your issue title? The `openscenegraph` formula has dependencies on both `qt` (legacy Qt 4.8.7) and `qt5` (currently Qt 5.6.1-1), but both are optional and thus the `openscrenegraph` bottle shouldn't be built with and linked to either of them. Thus `osgQt` isn't included, but that's expected.

**Comment by yn** [comment]
I guess I must be confused about what the check box means on the "Optional:" line: if "qt" has a checkbox next to it, that just means that it is installed, not that open-scene-graph was compiled with it when it was bottled?

∴ brew info openscenegraph
open-scene-graph: stable 3.4.0 (bottled), HEAD
3D graphics toolkit
http://www.openscenegraph.org/projects/osg
/usr/local/Cellar/open-scene-graph/3.4.0_1 (767 files, 32.7M) *
  Poured from bottle on 2016-07-15 at 16:56:00
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/open-scene-graph.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: jpeg ✔, wget ✔, gtkglext ✔, freetype ✔
Optional: gdal ✘, jasper ✔, openexr ✘, dcmtk ✘, librsvg ✘, collada-dom ✔, gnuplot ✘, ffmpeg ✘, qt5 ✘, qt ✔

**Comment by UniqMartin** [comment]
Yes, that's correct. The check mark just means that the dependency (no matter if optional or not) is currently installed in your Homebrew. You would have to install `openscenegraph` as follows to include the optional Qt 4 support:

```
brew install openscenegraph --with-qt
```

This will download the source code and build it from source and while doing that, it will be configured to also use the Qt installation that would otherwise be ignored.

The bottle is really just one specific build of the formula with the default set of options (none) and thus with only support for the required and recommended dependencies built in.

**Comment by UniqMartin** [comment]
(Feel free to close the issue if that answers your question and resolves the problem.)

**Comment by yn** [comment]
Thanks, that works.
