### ISSUE TITLE
Discussion: ideal CI workflow

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-core#31511]
⚠️  As this is a rare open discussion in a GitHub issue: please feel free to unwatch this issue if you aren't interested in what's being said here ⚠️ 

We're considering new CI providers and I think that's a good chance to start talking about what the ideal CI and maintainer workflow would look like for maintaining Homebrew/homebrew-core. Post your thoughts in the comments.

**Comment by chdiza** [comment]
> Yes, that means we'll have merge commits in the history

Doesn't it mean we'll have a *gigantic* number of these (one for every formula commit), and that they will obscure the commits we care about?  That means looking at the github commits page for `homebrew-core` will be absolutely brutal.  Then the user will have to drop into the terminal to do a `git log` that omits merge commits.

**Comment by SMillerDev** [comment]
> Doesn't it mean we'll have a gigantic number of these (one for every formula commit)
I'd say only if there can't be a fast forward merge?

I'm very much in favour of this workflow, I do a lot of PR checks from my phone so for me this would be great.

**Comment by MikeMcQuaid** [comment]
> Doesn't it mean we'll have a gigantic number of these (one for every formula commit)

Yes.

> Then the user will have to drop into the terminal to do a git log that omits merge commits.

Or `brew log` which can be configured to not use merge commits.

---

It's worth noting that this is how pretty much every other GitHub project works at this point, I'm not forcing it on anyone but personally I need a better reason than "the commit history is clean" to justify a workflow that requires every maintainer to drop to the terminal to merge most PRs. We should optimise for the maintainer workflow.

**Comment by chdiza** [comment]
I'm surprised that dropping into the terminal is such a pain.

> We should optimise for the maintainer workflow.

At the expense of UX?

**Comment by MikeMcQuaid** [comment]
> At the expense of UX?

At the expense of `git log` UX for power-users who care about its aesthetics: yes.

**Comment by chdiza** [comment]
> At the expense of git log UX for power-users who care about its aesthetics: yes.

I was thinking more of non-power users who would first go to the github page instead of messing with git.  And the concern isn't aesthetic, but is one of usability.  It's hard to see the commits that count when they're lost in a sea of other stuff.

**Comment by chdiza** [comment]
A totally separate question: would the new proposed workflow for homebrew-core make it so that the first `brew update` (following the first installation of Homebrew itself) would wreck the shallow clone that the install procedure created?  Or is that instead related to tags, like in the `brew` repo?  (I think that in that repo, a shallow clone is wrecked as soon as a new tag is pulled.)

A full clone of `homebrew-core` often takes a long time (~170+ MB), so it would be bad UX to have a simple `brew update` result in a long lag while fetching ancient commits that have nothing to do with the `update`.

**Comment by claui** [comment]
Interesting workflow-vs.-usability discussion!

To address the UX concerns, I could imagine @BrewTestBot to automatically squash and rebase the commits right before it creates the bottle commit. That way, both commits could be ff’ed without affecting maintainer workflow.

Alternatively, we could configure homebrew-core so it presents a _Rebase and merge_ button by default instead of today’s _Squash and merge._ I figure that would have a similar effect.

I recognize people have different needs and ways to cope with cognitive load but as a relatively new maintainer, I’d feel overwhelmed by having to remember when to use `brew log` and when vanilla `git log`. If we can get a clean `master` branch virtually for free, then maybe we want to do just that instead of filtering stuff later.

**Comment by amyspark** [comment]
> To address the UX concerns, I could imagine @BrewTestBot to automatically squash and rebase the commits right before it creates the bottle commit. That way, both commits could be ff’ed without affecting maintainer workflow.

Personally, it's the workflow I use here. I recognise this is a philosophical point, but I find a single, clean ff'ed commit to be far more pleasant than a merge commit.

**Comment by sjackman** [comment]
> Alternatively, we could configure homebrew-core so it presents a Rebase and merge button by default instead of today’s Squash and merge. I figure that would have a similar effect.

:+1: for rebase and merge.

**Comment by sjackman** [comment]
This suggested workflow sounds grand to me!

**Comment by sjackman** [comment]
> When the maintainer approves the PR @BrewTestBot pushes a commit to the PR with the bottles and publishes them

One minor downside is that a maintainer won't be able to use the "Approve" button to say "I like this PR" without it triggering the bot to publish. For example, on a not-so-simple PR, a developer may want to "Approve" the PR and then request review from another maintainer for confirmation. Possible fixes: the bot could ignore a PR that is tagged "do not merge", or that has unanswered requested reviews from another maintainer.

**Comment by sjackman** [comment]
> Rebase and merge is still the non-default GitHub behaviour and prevents us from requiring GPG signing now or in future.

If we were to choose rebase over merge today, that choice does not prevent us from revisiting that choice in the future.

> It also means that it's not possible from the Git logs to identify what PR a given commit came from (which would be a step back in some respects from brew pull).

That information could be in the log message of the bottle commit.

> Reminder here that we're talking about the ideal CI workflow rather than ideal Git workflow.

The two are quite related. It's difficult to discuss one without the other.

**Comment by scpeters** [comment]
I currently use a similar workflow in the [osrf/simulation](https://github.com/osrf/homebrew-simulation) tap, in which bottles are uploaded immediately after they are built and then bottle hashes are updated in the formula pull request. The last travis CI job tests the bottles, but all the earlier travis jobs fail because the bottles haven't been updated.

I'm sure there's a reason, but I guess I don't know why there is a two-step process of uploading and then publishing bottles. Our approach is to just upload bottles when they are built, and they won't get used unless the formula gets merged. Now that I think about it, maybe you're worried that the current bottles will get overwritten if the file name is the same? I think the bottle revision is supposed to get bumped, but if there's a bug there, then I guess the deployed bottles would be at risk.

Regarding merge vs rebase/squash vs `brew pull`: I use squash and merge on my tap because I like the clean history, and I don't know enough about security or GPG to have my own opinion about the value of signing commits (which are only preserved with merge commits), but people I respect have varying opinions about its value.

If possible, I think it would be helpful to try to start with decoupled discussion about the two issues (developer workflow with squash/rebase vs merge vs `brew pull`, and security value of GPG-signed commits). Hopefully we could reach consensus on what the consequences are for each separate issue, and after that we'll have to make a tough decision involving trade-offs, in which consensus might be hard to reach. If possible, it would be nice to start the trade-off discussion with some consensus about the consequences of the decision.

**Comment by jonchang** [comment]
I've thought about this for a while, and I think the correct solution is something like [bors](https://bors.tech/).

The proposed workflow is below. The numbered items are what people have to do, the bullet points are done by machines.

1. Contributor opens a pull request.
    * `brew-bors` builds and tests the new bottle on all supported platforms.

2. Maintainer checks the test output and approves the pull request by typing `@brewtestbot r+` or similar.
    * `brew-bors` opens an `auto` branch and brings in the pull request's commits plus the bottle commit.
    * `brew-bors` checks that nothing bad was introduced in the bottle commit, publishes the bottles, checks their sha256 hash again. (This is what `brew pull --bottle` does now).
    * `brew-bors` merges the `auto` branch into `master`. (This is what `git push` does now).
    * Github notices the commits from the PR are now in master and automatically resolves the PR as merged.

Advantages:
* no terminal needed by anyone
* maintainers do not need to keep their keys sitting around, `brew-bors` would do both publishing and upload
* pull requests are properly marked as merged

Disadvantages:
* test bot becomes a more enticing attack vector
* what are the security implications of github comments controlling release of binaries to our users
* maintainers cannot personally gpg sign commits without test-bot holding maintainer keys

**Comment by MikeMcQuaid** [comment]
> I guess I don't know why there is a two-step process of uploading and then publishing bottles.

It's a Bintray thing, basically. We upload a bunch of bottles that don't need to be published. For example, if you change a Ruby comment on a formula it'll still build and upload a new bottle even although the contents is unchanged. When a bottle has been published after a certain period of time (30 days iirc) it becomes immutable. When a bottle hasn't been published after a certain period of time (7 days) it gets deleted. This workflow is pretty good for ensuring we don't waste space or bandwidth on Bintray or their CDN.

> I've thought about this for a while, and I think the correct solution is something like [bors](https://bors.tech/).

I like your proposed solution. Whether we do rebase/squash/merge commit/whatever I think it's definitely appealing to be able to drop `brew pull --bottle` as a manual terminal command to run.

Re: my comments about GPG: other options that would boost security a bit in this tap would be requiring green CI before merge and/or requiring a PR review before merge. The latter might be nice anyway to avoid maintainers merging all their own PRs and having more of a code review culture (but please feel free to disagree).

**Comment by MikeMcQuaid** [comment]
Another thing I haven't mentioned here: one of the reasons I'd love to have a workflow that doesn't require too much deviation from GitHub norms is so we can have a Homebrew/homebrew-core CI/bottling workflow that taps can adopt easily and similarly.

**Comment by sjackman** [comment]
Mike said elsewhere: Bottles can be stored on GitHub releases for taps that don't use Bintray.

**Comment by scpeters** [comment]
>> I guess I don't know why there is a two-step process of uploading and then publishing bottles.

> It's a Bintray thing, basically. We upload a bunch of bottles that don't need to be published. For example, if you change a Ruby comment on a formula it'll still build and upload a new bottle even although the contents is unchanged. When a bottle has been published after a certain period of time (30 days iirc) it becomes immutable. When a bottle hasn't been published after a certain period of time (7 days) it gets deleted. This workflow is pretty good for ensuring we don't waste space or bandwidth on Bintray or their CDN.

Thanks for the explanation. I guess it's just up to the maintainers to know whether a pull request needs `brew pull --bottle` or whether `brew pull` will suffice.

**Comment by sjackman** [comment]
> I guess it's just up to the maintainers to know whether a pull request needs brew pull --bottle or whether brew pull will suffice.

Pretty much, yes. If you're modifying say just the `test do` block or the `homepage`, then you don't need to build a new bottle. When in doubt, bump the revision and build a new bottle.

**Comment by MikeMcQuaid** [comment]
Closing because discussion here has stopped and we've got the information we needed ✌️.
