### ISSUE TITLE
gdal --HEAD version on 10.11.6 - install trouble

### ISSUE THREAD

**Issue by rdzur** [Homebrew/homebrew-core#3203]
Hi 

I am running in to trouble building gdal --HEAD version on 10.11.6;  things appear to run well until a fatal error finding gdal_utils.h comes up.  gist-log ... https://gist.github.com/bfb2a38d51ae7ce147bebb334e60c95f

gdal_wrap.o
extensions/gdal_wrap.cpp:5929:10: fatal error: 'gdal_utils.h' file not found
#include "gdal_utils.h"
         ^
1 error generated.
error: command 'clang' failed with exit status 1

Appreciate any assistance in troubleshooting.

Thanks,

Rob
--

**Comment by DomT4** [comment]
Unless this doesn't reproduce outside of Homebrew, please report this upstream to GDAL. There's extremely little we can do to support `HEAD` build failures given how frequently they (by design) change, sadly.

If it turns out this doesn't reproduce outside of Homebrew please shout & we'll look at this again. Thanks.
