### ISSUE TITLE
What about create new brew to support most recent version? (ex. python3.6)

### ISSUE THREAD

**Issue by YBHwang** [Homebrew/homebrew-core#32790]
## Status

`python@2`
> 2.7.15 (latest)

`python`
> 3.7.0 (latest)

## Many developer tools stay in 3.6.x version (like Tensorflow).

> What about support most recent version?
For example If python 3.7.x available then 3.6.x available too!

In this case, `python@3` can be a `3.6.x` and `python` can be a `3.7.x(latest)`.

**Comment by fxcoudert** [comment]
We cannot support every combination of Python version. Already supporting both Python 2 and 3 is often a headache. The tensorflow bug about Python 3.7 support was opened 4 months ago, it is really on the tensorflow developers/community to fix it (especially as the fix is very simple, renaming variables named `async`).

**Comment by MikeMcQuaid** [comment]
See `brew extract` to help you maintain your own version.
