### ISSUE TITLE
ruby-2.5.3 fails to build on macOS 10.13.6

### ISSUE THREAD

**Issue by kmhofmann** [Homebrew/homebrew-core#33196]
I am trying to run brew upgrade, which wants to install ruby-2.5.3 (from previously ruby-2.5.1).

Expected behavior: the command succeeds, and ruby is built.

What actually happens:

```
Michaels-MacBook-Pro:~ michael$ brew upgrade
==> Upgrading 1 outdated package:
ruby 2.5.1 -> 2.5.3
==> Upgrading ruby
==> Downloading https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.xz
Already downloaded: /Users/michael/Library/Caches/Homebrew/downloads/ca345cc891c2d63b381e3a34b972cf76b1eeb3f7803bae6ac73ee8485252c859--ruby-2.5.3.tar.xz
==> ./configure --prefix=/Users/michael/homebrew/Cellar/ruby/2.5.3 --enable-shared --disable-silent-rules --with-sitedir=/Users/michael/homebrew/lib/ruby/site_ruby --with-vendordir=/Users/michael/homebrew/lib
==> make
Last 15 lines from /Users/michael/Library/Logs/Homebrew/ruby/02.make:
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
compiling ./main.c
compiling dmydln.c
compiling miniinit.c
compiling dmyext.c
compiling miniprelude.c
translating probes probes.d
compiling bignum.c
compiling class.c
error: error reading '/dev/fd/6'
1 error generated.
clang: error: unable to remove file: Operation not permitted
dtrace: failed to compile script probes.d: Preprocessor failed to process input program
make: *** [probes.h] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://docs.brew.sh/Troubleshooting
```

Any prescribed troubleshooting (running brew update or brew doctor, etc.) did not help; the error remains the same. (Only the number of the file descriptor might be different from 6.)

See also this gist log:
https://gist.github.com/ee51cb288011180c6bac334630646f34

**Comment by fxcoudert** [comment]
We don't see this error on our CI machines… and `error: error reading '/dev/fd/6'` is a very strange, low-level error saying that the compiler could not pass information to the assembler or linker. This is very unlikely to be related to Homebrew, I am sorry to say. It has been reported multiple times to various Ruby projects, Google tells me.

- It can the due to antivirus software running: https://github.com/rvm/rvm/issues/4313#issuecomment-374020379
- Or to a `dtrace` permission issue, in which case fixing that permission could help: https://github.com/rbenv/ruby-build/issues/1061#issuecomment-366127345
- Finally, another option if the above fails could be to disable dtrace altogether: edit the `ruby.rb` formula to change that line:

```
args << "--disable-dtrace" unless MacOS::CLT.installed?
```

into 

```
args << "--disable-dtrace"
```

**Comment by kmhofmann** [comment]
Thanks for the info. Disabling the anti-virus software fixed the issue.
