### ISSUE TITLE
Help wanted with dotnet formulae

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#3395]
I want to create formulae for dotnet, but [upstream](https://github.com/dotnet/coreclr/blob/master/Documentation/building/osx-instructions.md) seems like using custom wrapper script around cmake, not to mention requirement to link openssl and icu4c with `--force`. How can we elaborate a formulae that will not require `--force` linking of mentioned formulas?

Should we use upstream script or pass our own commands to cmake?

**Comment by rakkesh** [comment]
Force-linking of formulae should be required only when building outside of `Homebrew`.

for your formula, this should work -
```
depends_on "cmake" => :build
depends_on "openssl"
depends_on "icu4c"
```

As per the build instructions, you can use `./build.sh`, which creates three files - `corerun`, `libcoreclr.dylib` and `mscorlib.dll` under `bin/Product/OSX.x64.Debug` (you probably have to change build to `Release` mode instead of `Debug`) and install them to `bin` and `lib` accordingly. There is also a framework build you might want to look into.

**Comment by DomT4** [comment]
> seems like using custom wrapper script around cmake

As long as that wrapper behaves sanely, this is fine. There's already quite a few formulae in Homebrew using wrappers around `cmake`, so not a problem.

> How can we elaborate a formulae that will not require --force linking of mentioned formulas?

It's unlikely they'll need that _inside_ Homebrew's build environment because we set things up automagically. Let us know if that doesn't prove the case or we can help further, Thanks!
