### ISSUE TITLE
ocamlbuild: GitHub repository not notable enough

### ISSUE THREAD

**Issue by miguelarauj1o** [Homebrew/homebrew-core#3440]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

```brew audit --strict --online ocamlbuild``` returns:

```ocamlbuild:
* GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
Error: 1 Error in 1 formula
```
What should I do? Can I remove it?

**Comment by DomT4** [comment]
Ignore `not notable enough` errors on existing formulae.

In this case `ocamlbuild` was accepted because it was pulled out of `ocaml` upstream, so the codebase it was based off was mature but the GitHub repo itself wasn't of much separate interest to people.

The `--online` part of the audit can be considered more recommendation than outright problem, for now.

**Comment by miguelarauj1o** [comment]
@DomT4, thanks!

**Comment by DomT4** [comment]
No worries.

Apologies it's a little confusing to nudge people to run `--online` and then shrug parts of it off for existing formulae. We're considering our options there, but yeah, the notability element is fine to ignore on formulae that already exist.
