### ISSUE TITLE
Some builds fail due to the "m" in Versions/3.7/include/python3.7m

### ISSUE THREAD

**Issue by Zyrsha** [Homebrew/homebrew-core#34485]
I've had a couple builds fail because of the 'm' in the path:
`/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m`

For example, when attempting to build Boost:
```
./bootstrap.sh --with-toolset=clang --with-python=/usr/local/bin/python3 --with-python-root=/usr/local/bin/python3 --with-python-version=3.7
./b2 -q --debug-configuration toolset=clang cxxflags="-stdlib=libc++ -std=c++17" linkflags="-stdlib=libc++ -std=c++17"
```

It will produce:
```
notice: [python-cfg] Configuring python...
notice: [python-cfg]   user-specified version: "3.7"
notice: [python-cfg]   user-specified cmd-or-prefix: "/usr/local/bin/python3"
notice: [python-cfg] Checking interpreter command "/usr/local/bin/python3"...
notice: [python-cfg] running command '/usr/local/bin/python3 -c "from sys import *; print('version=%d.%d\nplatform=%s\nprefix=%s\nexec_prefix=%s\nexecutable=%s' % (version_info[0],version_info[1],platform,prefix,exec_prefix,executable))" 2>&1'
notice: [python-cfg] ...requested configuration matched!
notice: [python-cfg] Details of this Python configuration:
notice: [python-cfg]   interpreter command: "/usr/local/bin/python3"
notice: [python-cfg]   include path: "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7"
notice: [python-cfg]   library path: "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config" "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib"
```

This will cause the build to fail, because `"include path: "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7"` without the 'm' is a nonexistent path.

**Comment by SMillerDev** [comment]
Please fill out the issue template. It's needed to help us debug your issues. I'll close this until you change the issue to include the template.

**Comment by maxim-belkin** [comment]
@Zyrsha, thank you for spending your valuable time with us. Looks like you've got a few things going on here:

1. you are trying to build `boost` outside of Homebrew after installing Python with Homebrew
2. you installed an old version of Python (3.7.0) and right now Homebrew has `3.7.1`. Make sure to upgrade to he latest Homebrew version with `brew update && brew upgrade`.

Also, I've just installed `python3` with Homebrew on my macOS Mojave and I _do_ see both files:
```
/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/bin/python3.7
/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/bin/python3.7m
```

You can get a listing of all files that belong to `python3` with `brew list -v python3`. Make sure you see `3.7.1` as well as both files I list above.

Also, double-check what you get when you execute `type -a python3-config` - perhaps, you need to tweak your PATH?

Another note: You could try installing `boost` with `brew install -vds boost`... Otherwise, Homebrew guys can not help you with the installation as it is performed outside of Homebrew's super environment.

Hope to hear from you soon!

**Comment by SMillerDev** [comment]
The duplicate thread got a little out of hand so locking this one too.
