### ISSUE TITLE
Discussion: Ensure that projects are rebuild if upstream decides to retag

### ISSUE THREAD

**Issue by leonklingele** [Homebrew/homebrew-core#34779]
[Retags](#18048), [unfortunately](#15663), [are](#15059) [a](#13792) [thing](#34771) and happen from time to time.
For those unaware of the issue: Tags of projects tracked by Homebrew sometimes are pushed to their upstream repository, removed shortly after, and are then re-pushed in a slightly different form (e.g. to include supposedly important fixes). Most likely a lot of those "emergency" retags go without notice, yet it happens that Homebrew maintainers are quick enough to spot the initial tag, issuing a new "Homebrew release" of that project. As Homebrew formulae include the checksum of the project's release tarball and this checksum changes after a retag, installations from source via Homebrew will yield a `checksum mismatch` error. The checksum of those formula will eventually be fixed, making source-builds succeed again.

It so happens that Homebrew end users can be quick enough to build the initial release tag (by running `brew upgrade` before the retag was issued). Those users will continue to use a build made using the outdated release if no [revision bump](https://github.com/Homebrew/brew/blob/c89f6c8f8c60c52a9278ccb035dadf73d999df13/docs/Formula-Cookbook.md#formulae-revisions) was made. Revisions of Homebrew formulae are only issued if the retag appears to be changed in a significant way (e.g. if changes to the source code are made). Yet source code changes are not the _only_ reason why a rebuild might be required.

Take #25845 as an example where `libjpeg` retagged their most recent `v9c` release, [apparently](https://github.com/Homebrew/homebrew-core/issues/25845#issuecomment-376645802) only removing a seemingly unimportant, empty file (`jpeg-9c/.directory`) which couldn't possibly result in a different build, therefore an increase of revision [was not made](#25918). Well, this empty file could actually cause a completely different build if the build process somehow depends on it. How was it verified that this is not the case? Did the `libjpeg` authors bless the retag? A revision bump is available in #34767.

Here is a list of some other checksum fixes which did not receive a revision bump:

- #18048 – the checksums of 94 formulas were fixed. Most of the mismatches are likely caused by [GitHub applying a bugfix to their internal Git version](https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745). It remains unknown whether some of those projects retagged a release before the issue was introduced by GitHub. There's no easy way to find out if the new tarballs ship with an important fix.
- #23852, the initial release [misses a part of the changelog](https://github.com/Homebrew/homebrew-core/pull/23665#issuecomment-363899728). (How) was it verified that this changelog file doesn't affect the build process? A revision bump is available in #34766.
- #31767 – no information is available on what actually changed inside the release tarball. A revision bump is available in #34768.
- #15663 – project maintainer assures that [no code changes have been made to the modified tar.gz files](https://github.com/Exiv2/exiv2/issues/19#issuecomment-315563564), yet this doesn't imply that the build itself will not be a different.
- #31790 – although the project's author confirmed that no code but only a `NEWS` file was changed, he didn't assert that this file is not used inside the build process, possibly causing a different build to be made. A revision bump is available in #34769.
- #32042 – some Windows build scripts were altered. Does this affect builds on other platforms? If not, how was this verified? A revision bump is available in #34770.
- #32043 – changes to the README. While this file most likely is not used inside the build process, how was this _verified_? A revision bump is available in #34771.
- #31948 – apparently a patch's checksum changed, although the patch itself wasn't. Does this possibly affect the build process in any way? A revision bump is available in #34773.
- #32060 – no information available on what changed. A revision bump is available in #34772.

Humans, by their very nature, make mistakes. As it is easy to _not_ rely on humans to decide whether forcing a rebuild is sensible or not and most formulae don't take hours to build, I ask to simply _always_ enforce rebuilds (this includes bottles as well) by revision bumping formulas after any of their included checksums change for whatever reason.

**Comment by fxcoudert** [comment]
First, retags should _not_ happen in projects following semantic versioning (version numbers should uniquely identify a given state of the source and its distribution). Moreover, when they happen it is because upstream deemed it unnecessary to issue a new release and force all users to update. In other words: a retag is, by its very definition, _not_ a new version but the same version, i.e. the same state of the software.

Our current policy is the following:
1. The change of checksum with identical version number is treated as suspicious, since it could be malicious (someone took control of the repository or file server, and switched the sources)
2. Once we confirm that the change in sources is intentional (usually by contacting upstream and asking them), we fix the checksum in Homebrew
3. The maintainer merging the retag then makes an informed decision about the necessity for pulling new bottles and bumping revision. Pulling new bottles cannot really hurt, but bumping revision has a cost: it will make all users upgrade, i.e. download new bottles or rebuild from source. So:
   - _Unless there was something seriously wrong with the previous build_, we do not bump the revision number.
   - We do, however, bump the revision number if the previous software was broken in significant way: for example, if the retag is actually a hot fix, because the maintainer realised they shipped a buggy tarball.
4. We advise all upstream projects to stick to semantic versioning, and rather than retag, change the version number in a minor way to indicate the bug fix, when one is made.

**Comment by MikeMcQuaid** [comment]
Agreed with @fxcoudert. Closing but feel free to continue discussion here.

**Comment by SMillerDev** [comment]
The git tarbal issue weren't retags as is stated in the linked issue. A retag is the same release though, 6.0.0 is the exact same as 6.0.0. If we can't trust that to be the case we're better off giving up on versioning altogether and just building the software from the latest upstream locally on install.

**Comment by leonklingele** [comment]
> The git tarbal issue weren't retags as is stated in the linked issue.

What makes you so sure about that? Have all the tarballs been checked for diffs? Just because GitHub had some issues which caused different tarballs to be available doesn't mean those projects didn't retag just minutes before / after that. You see, I'm just speculating here. But given that 94 formulae were updated it's not so unlikely that a retag was amongst them.

**Comment by SMillerDev** [comment]
Issue https://github.com/Homebrew/homebrew-core/issues/18044 which is referenced in the PR you linked mentions the checks people did to make sure there weren't any retags in there.

**Comment by MikeMcQuaid** [comment]
> Sure, rebuilding sucks, but end users shouldn't blame Homebrew for that.

Regardless of whether they should or will: it makes the experience of using Homebrew worse for those users for no good reason so we're not going to do it.

> What do you think of adding support for a new env var, e.g. `HOMEBREW_REBUILD_RETAGS`, which will enforce software rebuilds on retags? Similar to `revision [NUM]` there could be a `retag [NUM]`.

I would want to see many more users (and maintainers for whom the work will fall to keep up with that) asking for something like this before it would be even considered. 

> What makes you so sure about that?

Because: we're running a package manager, do a lot of work behind that scenes that's not always make public, we have two GitHub employees as maintainers and many other reasons.

I appreciate your contributions to Homebrew but I don't like your tone in this issue. Please address it in future issues to sound less like you are trying to teach people who are successfully running a package manager how to do so. Issues like this based on speculation are not helpful. Contributions to Homebrew are useful and if you contribute enough you may be able to become a maintainer in future and have influence over how the project is run.
