### ISSUE TITLE
Triple SHA1 deprecation warning

### ISSUE THREAD

**Issue by daenney** [Homebrew/homebrew-core#3506]
I ran a `brew outdated` to figure out if I needed to update anything and I got greeted by 3 deprecation warnings which all stem from the same issue, a formula using `sha1`. Though I think it's good to give a clear deprecation warning, signed in triplicate is a bit much and creates a lot of noise:

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/spotify/homebrew-internal/hmtools.rb:7:in `<class:Hmtools>'
Please report this to the spotify/internal tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/spotify/homebrew-internal/hmtools.rb:7:in `<class:Hmtools>'
Please report this to the spotify/internal tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/spotify/homebrew-internal/hmtools.rb:7:in `<class:Hmtools>'
Please report this to the spotify/internal tap!
```

I'll fix our Formula but it might be nice to emit a single warning per location.

**Comment by dcwar** [comment]
This is also occurring with homebrew/boneyard (see partial console output of `brew update --verbose` from a 10.8 system below).

> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /usr/local/Library/Taps/homebrew/homebrew-boneyard/attica.rb:6:in 'load_formula'
> Please report this to the homebrew/boneyard tap!
> 
> Warning: Calling SoftwareSpec#sha1 is deprecated!
> Use SoftwareSpec#sha256 instead.
> /usr/local/Library/Taps/homebrew/homebrew-boneyard/attica.rb:6:in `load_formula'
> Please report this to the homebrew/boneyard tap!
> 
> Warning: Calling Resource#sha1 is deprecated!
> Use Resource#sha256 instead.
> /usr/local/Library/Taps/homebrew/homebrew-boneyard/attica.rb:6:in 'load_formula'
> Please report this to the homebrew/boneyard tap!
> 
> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /usr/local/Library/Taps/homebrew/homebrew-boneyard/cdf.rb:6:in `load_formula'
> Please report this to the homebrew/boneyard tap!
> 
> Warning: Calling SoftwareSpec#sha1 is deprecated!
> Use SoftwareSpec#sha256 instead.
> /usr/local/Library/Taps/homebrew/homebrew-boneyard/cdf.rb:6:in 'load_formula'
> Please report this to the homebrew/boneyard tap!
> 
> Warning: Calling Resource#sha1 is deprecated!
> Use Resource#sha256 instead.
> /usr/local/Library/Taps/homebrew/homebrew-boneyard/cdf.rb:6:in 'load_formula'
> Please report this to the homebrew/boneyard tap!
> 
> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /usr/local/Library/Taps/homebrew/homebrew-boneyard/dbslayer.rb:7:in 'load_formula'
> Please report this to the homebrew/boneyard tap!

**Comment by DomT4** [comment]
You may wish to glance through https://github.com/Homebrew/brew/issues/606 which details that change a little further.

We're considering what to do IRT the `boneyard`, because obviously, those formulae are unsupported. My desire there is to upgrade the checksums where the upstream tarball is still available to SHA256 & outright delete the formula that no longer have an upstream download available.

> I'll fix our Formula but it might be nice to emit a single warning per location.

Thoughts on this @UniqMartin?

**Comment by ilovezfs** [comment]
>My desire there is to upgrade the checksums where the upstream tarball is still available to SHA256 & outright delete the formula 

@DomT4 I already did all of them: https://github.com/Homebrew/homebrew-boneyard/pull/137

**Comment by ilovezfs** [comment]
@dcwar regarding the ones in the boneyard, you need to brew update, since those were all fixed before this issue was even opened.

**Comment by dcwar** [comment]
@ilovezfs Although I didn't mention it, I came here because I experienced the issue after running brew update. Having run brew update again, all is well. :) Thank you.

**Comment by ilovezfs** [comment]
@dcwar you're welcome. Unfortunately, the "Warning: Calling Resource#sha1 is deprecated!" is particularly annoying because the fix here https://github.com/Homebrew/brew/commit/19a77c816ebb66301b7a74fea513245043ba5aae is only useful if you have HOMEBREW_DEVELOPER, which causes it raise an exception not a warning, and then that exception is deliberately ignored, but if you don't have HOMEBREW_DEVELOPER set, then it only prints the warning and there is no exception to ignore, so we'll have to come up with something else to hush up that warning.

**Comment by MikeMcQuaid** [comment]
Thanks for filing the issue but I can't see a way we can ensure this message is only printed once but also guarantees it's printed in each of those individual cases too. We'd accept a PR for this if you can figure it out.
