### ISSUE TITLE
Request: qt@lts

### ISSUE THREAD

**Issue by tooomm** [Homebrew/homebrew-core#35883]
Which would currently be Qt 5.9.7 LTS ideally, as the newest Qt 5.12.0 (which is also an LTS build, but very new and x.x.0 versions often had some issues in the past) has problems as well, and we run into a bug.
If you can't use any alternative, fallback version, or go the safe route and always stick with a stable LTS versions it's not good. I could easily imagine that many users would love to use a more stable qt@lts version if it gets updated in time (and skips x.x.0 releases maybe 😄).
It's now the second or third time we have this problem with Qt from homebrew...

Linking older requests which got denied: https://github.com/Homebrew/homebrew-core/issues/23234 & https://github.com/Homebrew/homebrew-core/issues/29471

---

>PR for discussion: #36114

**Comment by ZeldaZach** [comment]
Ran into an issue with DPI images being blown out of proportion in a program with QT5.12.0, but was not an issue in 5.9.7 or 5.11.2. Having fallback QT versions already committed would be great

**Comment by SMillerDev** [comment]
Personally I wouldn't favor keeping an LTS version around in case something breaks but we'll see if opinions differ with other maintainers.

**Comment by tooomm** [comment]
To be honest, I would use it as default personally... and not "in case something breaks". :)
As long as you don't depend on newest features of course.

**Comment by SMillerDev** [comment]
That's not what brew versions are for, they're really only available for things like language versions where users might not have an option to use a newer version due to external issues. For QT it just sounds like the Qt team needs to test x.x.0 releases better.

**Comment by ctrlaltca** [comment]
A bit of background: a lot of projects are using homebrew to automatically build and deploy packages using eg. Travis CI. In this case, since the new Qt5 version 5.12 has some bugs, the resulting packages are unusable.
This is surely not a problem in the homebrew formula: Qt has to fix the problem (and hopefully do better testing in the future).
Still, imho it would be handy to be able to stick with an exact version when installing a formula.
As far as i know [homebrew-versions](https://github.com/Homebrew/homebrew-versions) existed in the past but is now deprecated.
Some new formulas like qt@5.9, qt@5.11 could be created, but this would probably be hard to maintain.
Checking out an old version of the formula from git and build it locally could be a viable solution for a small project, but incompatible with Qt on the limited resources available on Travis.
Maybe someone with more knowledge has a better solution for this use case?

**Comment by apjanke** [comment]
This is something I'd probably use myself, with my work on [Octave.app](http://octave-app.org). As a matter of fact, I'm running into a Qt 5.12 bug there myself. It would be really handy to have an LTS Qt bottle available so I could build against that without having to go through the whole Qt build process: a couple hours on the build box to save developers a couple hours during interactive work seems like a good tradeoff. Adding a +1 to indicate interest.

**Comment by MikeMcQuaid** [comment]
Can someone link to a page detailing the Qt LTS policy and versions? Despite the previous versions we may be willing to do this.

**Comment by apjanke** [comment]
From http://blog.qt.io/blog/2017/06/07/renewed-qt-support-services/:

> By default, releases from Qt 5.6 and onward are supported for one year and LTS releases are supported for three years starting from the 5.x.0 release.

Which gives us:

| Qt Version | Release Date | Supported Until | Currently in Support? |
| ---------- | ------------- | -------------- | ------- |
| 5.9.x LTS |   2017-05-31      | 2020-05-31 | Yes ("Strict") |
| 5.10.x | 2017-11-30 | 2018-10-30 | No |
| 5.11.x | 2018-05-22 | 2019-05-22 | Yes |
| 5.12.x LTS | 2018-12-05 | 2021-12-05 | Yes |

I've sent them an email asking about when the "Strict" phase ("important bug fixes only") happens, since that doesn't seem to be detailed on any public posts.

Given their six-month historical release cycle, I'd expect Qt 5.13 around June 2019.

Wikipedia includes the support end dates in their Qt release history list: https://en.wikipedia.org/wiki/Qt_version_history

**Comment by MikeMcQuaid** [comment]
@apjanke I'd be 👍 on including a previous LTS release in that case.

**Comment by apjanke** [comment]
Y'all are right. Does not contradict https://docs.brew.sh/Versions; a description and comment in the formula should suffice.

I'm off to bed soon; look for a PR tomorrow.

**Comment by apjanke** [comment]
Here's a PR for discussion: https://github.com/Homebrew/homebrew-core/pull/36114

Adds a `qt@5.9` formula with notes in comments and `description` about LTS.

It passes `audit --strict` but I haven't built it locally during the wait time; figured I'd leave that to the CI boxes so the discussion can proceed more quickly.

Did not add a `qt@lts` alias; I'm not sure how valuable that is, considering that it's prone to large version jumps when the prior LTS rolls off. Probably better to just remove old unsupported formulae and break the build straight out so downstream clients know they have to adapt their build to a (much) newer Qt version.

**Comment by tamlok** [comment]
@apjanke Thanks for your great work! I have been using a tricky `git checkout` to stay in Qt 5.9.3 for my [project](https://github.com/tamlok/vnote/blob/1675b944c48a2ba9713c520522301ac75fd36c8c/.travis_macos.sh#L13) for a long long long time.

Qt's newer versions seem to always will introduce new bugs and break something! ~~~

**Comment by tamlok** [comment]
What a pity!

**Comment by fxcoudert** [comment]
PR #36114 was opened, and discussion is now taking place there.
