### ISSUE TITLE
brew install moreutils --without-parallel stopped working

### ISSUE THREAD

**Issue by SsnL** [Homebrew/homebrew-core#36678]
Starting today, `brew install moreutils --without-parallel` started throwing `Error: invalid option: --with-parallel`. Are there any workaround?

**Comment by SMillerDev** [comment]
No, issues in homebrew core have been removed. You'll have to maintain your own version if you want a non default configuration.

**Comment by slhck** [comment]
> No, issues in homebrew core have been removed. 

You mean "options" have been removed?

Particularly for `moreutils`/`parallel`, the naming clash is quite annoying, as it prevents you from installing either of the (very useful) tools. Such an option would have enabled users to get the best of both formulae. Right now, you get the worst user experience. Over the past 90 days, about 15% of installs have been with the `--without-parallel` option. Also, I don't see that this option has ever caused issues.

**Comment by slhck** [comment]
Would it make sense to create a tap for a `moreutils-without-parallel` formula (that name, argh), and mention that in a caveat of the official `moreutils` formula?

Or just duplicate the formula in homebrew-core so that it can be tested and shipped?

It's all about user discoverabililty—you don't want to send people off doing a web search for a possible solution to installing both `moreutils` **and** `parallel`, and that leads them to some Q&A post, some random issue, perhaps a tap that is maintained (who knows?)…

**Comment by SMillerDev** [comment]
Whoops, yeah I meant options indeed. It's really the source build it triggers that causes issues though.

**Comment by slhck** [comment]
What issue is a source build causing?

Disclaimer: I don't know a lot about the pipeline you're using. I understand that the main goal with these changes is to only build and ship bottles—which you cannot do for formulae with options enabled. But wouldn't this simply cause the formula to be built from source on the user side?

**Comment by SMillerDev** [comment]
Yes and users have all kinds of weird things interacting with the builds which can cause them to fail.

**Comment by slhck** [comment]
I know this is the *general* feeling about builds and not wanting to maintain them, but what particular problem could be caused by optionally *not* installing one binary within a formula? Or is the problem that you cannot trust the user system to build *anything* reliable? (If it is the latter, maybe I'm one step closer to understanding what the rationale behind this decision was.)

**Comment by SMillerDev** [comment]
It's really the latter. This is why homebrew is moving to become a binary package manager.

**Comment by slhck** [comment]
Thanks for the information. I was hoping that this would not become the case but I understand that that's the way it is and it's not going to be changed.

So, given the quite significant usage of `--without-parallel` (and seeing that people keep posting issues), how do you suggest moving forward?

Could a second formula be integrated into `homebrew-core`?

**Comment by SMillerDev** [comment]
Probably not, you can pretty easily put it in a tap though.

**Comment by slhck** [comment]
I know, and I've seen this general recommendation in different threads. I created a tap here: https://github.com/slhck/homebrew-moreutils

But when it comes to having users discover these taps, how can we do that, particularly for formulae were about every fifth user definitely wants moreutils **and** parallel at the same time?
