### ISSUE TITLE
Consider adding Recommended dependencies to gperftools

### ISSUE THREAD

**Issue by jacobcvt12** [Homebrew/homebrew-core#3716]
I installed `gperftools` a few days ago and came across a few issues. It would be simpler if `binutils` (for `objdump`) and `graphviz` (for `dot`) were added as recommended dependencies. Both are required for visualizing profiles via `pprof`. To visualize a profiled run as text or as a gif, these "dependencies" were needed.

**Comment by MikeMcQuaid** [comment]
Let's add them as optional rather than recommended to start with. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by ilovezfs** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
