### ISSUE TITLE
brews unlink after reinsatll

### ISSUE THREAD

**Issue by grosch** [Homebrew/homebrew-core#3726]
Periodically I do a "brew update && brew upgrade && brew cleanup".  Whenever I do that, things that I have force linked, like curl, disappear from /usr/local/bin.  How do I make brew automatically recreate links for things like curl and openssl which I WANT linked into /usr/local/bin so that I'm not using the system version by default?

Homebrew 0.9.9 (git revision 8ec59; last commit 2016-08-06)
Homebrew/homebrew-core (git revision 4911; last commit 2016-08-06)

**Comment by tdsmith** [comment]
The most straightforward way is to add e.g. `$(brew --prefix)/curl/bin` to PATH in your shell initialization script; I do this for the openssl CLI.

Because Apple's [clang and ld have different default search paths](https://langui.sh/2015/07/24/osx-clang-include-lib-search-paths/) force-linking openssl can cause serious and non-obvious compilation problems for third-party software so we don't allow it even with --force anymore.

Maintaining force-linked packages in a force-linked state on upgrade sounds like a useful behavior but I don't know that it would be easy to implement.

**Comment by grosch** [comment]
@tdsmith - That path doesn't work.  I think you mean `brew --cellar` but even with that, the /usr/local/Cellar/curl directory has a version number before the bin path exists.

**Comment by tdsmith** [comment]
Oh, you're right; I meant `$(brew --prefix curl)/bin`. Sorry for the mistake; that path should be version-independent.

**Comment by grosch** [comment]
Brew does not put a bin directory there.

**Comment by tdsmith** [comment]
It does! But why do you say so?

**Comment by grosch** [comment]
Ah, I see.  You didn't use cellar, you use prefix with a name.  OK, that works.  Thanks!
