### ISSUE TITLE
pkg-config doesn't find nspr

### ISSUE THREAD

**Issue by luser** [Homebrew/homebrew-core#3798]
This was reported a few years ago:
https://github.com/Homebrew/legacy-homebrew/issues/478

but closed because there was no `nspr.pc` at the time. The current version of NSPR does include a `nspr.pc`:
```
$ brew ls nspr | grep nspr.pc
/usr/local/Cellar/nspr/4.12/lib/pkgconfig/nspr.pc
```

...it's just not in the right place for pkg-config to find it, which is annoying. I would guess that putting that file in the right place isn't hard, but I don't know any Ruby and haven't edited Homebrew formulas before so the solution isn't obvious to me.

**Comment by DomT4** [comment]
This is expected due to the `keg_only` status, which is due to an upstream Firefox issue as detailed [here](https://github.com/Homebrew/homebrew-core/blob/568a93e72a1fc7959e2a390a874d411f5aa322a2/Formula/nspr.rb#L14-L19). There's not a lot actionable on our side here; it's something that will need handling upstream.

Your best bet if you need to use it outside of Homebrew is to edit your `PKG_CONFIG_PATH` temporarily, as detailed in [this document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-build-software-outside-Homebrew-with-Homebrew-keg-only-dependencies.md#pkg-config-detection) if that's useful at all.

**Comment by luser** [comment]
I understand why it's not linked, but I don't understand why we can't put the .pc file in the usual location so that applications that want to link against the Homebrew copy can use pkg-config to find it as usual. Especially given that the .pc file is installed in a path with a version number in it, that's quite the hassle.

**Comment by luser** [comment]
FYI, I'm also the NSPR maintainer these days (unfortunately), so if there's something that I could change upstream to make this easier that would be fine.

**Comment by DomT4** [comment]
>  I don't understand why we can't put the .pc file in the usual location so that applications that want to link against the Homebrew copy can use pkg-config to find it as usual.

We don't really have the concept of a partial `keg_only`, because generally allowing things to find formulae via `pkg-config` rather than checking the default header/library search paths is just as problematic. Exceptions to every rule, but they've proven rare enough to not merit rewriting that mechanism.

> Especially given that the .pc file is installed in a path with a version number in it, that's quite the hassle.

Everything linked via Homebrew offers an unversioned path, FWIW.
```
$(brew --prefix)/opt/qt5
```
for example resolves to:
```
$(brew --prefix)Cellar/qt5/5.6.1-1/
```

> if there's something that I could change upstream to make this easier that would be fine.

I'm not sure there is, to be honest, unless you've enough political muscle to get action from the Firefox team in terms of restricting where libraries can be loaded from to certain known-safe paths. There's a proposal for that open [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1143733) but it seems to have gone silent.

**Comment by luser** [comment]
Oh, so, in the intervening years we also changed how Firefox builds its local copy of NSPR so that we no longer ship a libnspr4.dylib ([as of Firefox 22](https://bugzilla.mozilla.org/show_bug.cgi?id=648407)). It should actually be fine to link the Homebrew copy of NSPR nowadays.

**Comment by DomT4** [comment]
Interesting. Thanks for that detail.

It looks like `nss` itself is still problematic & would need to remain `keg_only` but indeed I can no longer reproduce the original crash with `nspr` alone not locked inside its prefix. If you wanted to submit a PR to remove the `keg_only` status of `nspr` we'd likely accept it.

**Comment by luser** [comment]
https://github.com/Homebrew/homebrew-core/pull/3802
