### ISSUE TITLE
Please re-enable or provide non-breaking migration for --with-default-names

### ISSUE THREAD

**Issue by amknapp** [Homebrew/homebrew-core#38943]
Recently --with-default-names was deprecated/removed. This leaves me in a position where I now have to manually manage my path post install for every package I add, looking into /usr/local/opt/$(name)/libexec/gnubin which is massively painful to keep maintained properly or to remember to do.

More painful yet, is the mishmash of pre/post removal package installations where some need this manual treatment and some just work.

Please consider some option where I can go to get *all* my gnu tools by adding links to a single spot into my bash file instead of this error prone, per-install process.

For others running into this, here's a oneliner to run post install(s) to fix this gap:

find /usr/local/opt -follow -path '\*/gnubin/\*' -exec ln -s {} /usr/local/bin/ \\;

**Comment by jonchang** [comment]
**Please always fill out the issue template.** We won't be re-adding options until the problems outlined in https://github.com/Homebrew/homebrew-core/issues/31510 can be addressed. See also my post on the Discourse: https://discourse.brew.sh/t/why-was-with-default-names-removed/4405/6; we might look into a pull request for this but fewer than 0.3% of formula are affected. Also suggest you add to your PATH rather than use links.

**Comment by amknapp** [comment]
You've got an interesting problem here with BSD vs GNU. You have two binaries that are entirely incompatible, but claim to publish the same thing.

What's the scalable plan here when two places publish incompatible binary <foo>?  How will you let users choose between the multiple options without having to muck around after the fact?

>> 0.3% of formula
What is the percentage for formula where BSD and GNU versions are incompatible?  My guess would be north of 80%. 

>>  Also suggest you add to your PATH rather than use links.
Sadly, sometimes, I change shells, or spin up a new machine.  Things that survive that by persisting on the file system are preferable.
