### ISSUE TITLE
ncmpcpp failing on launch

### ISSUE THREAD

**Issue by knutaldrin** [Homebrew/homebrew-core#395]
On trying to run ncmpcpp, I am just getting:

dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.56.1.dylib
  Referenced from: /usr/local/opt/boost/lib/libboost_locale-mt.dylib
  Reason: image not found
fish: 'ncmpcpp' terminated by signal SIGTRAP (Trace or breakpoint trap)

I tried both reinstalling, installing an old version, old version of icu4c, compiling from source. None of them seems to fix the issue.

This started happening a couple of days ago, so apparently some package in brew was updated, breaking the build?

**Comment by DomT4** [comment]
This should have been fixed by https://github.com/Homebrew/homebrew-core/commit/afcf7e23afcab454ecb4d74fcbc6cfdd086d9428. Have you tried `brew update && brew upgrade ncmpcpp`?

**Comment by knutaldrin** [comment]
Unfortunately, no. I had updated and reinstalled just before posting the issue.

It did appear to me also that icu4c is pulled in by boost, and there seems to be some linking problem.

**Comment by UniqMartin** [comment]
@knutaldrin Indeed, the error here is because of Boost. You should be able to fix this by rebuilding it via `brew reinstall boost`. (Boost gets built from source instead of using the bottle because `ncmpcpp` depends on it with the non-standard `--with-icu4c` option.)

----

@DomT4 Should we bump the revision of `boost`? It seems to be a bit silly because that's not going to change the bottles we build (those don't link to `icu4c`). This would also mean we'd be forcing a useless rebuild or bottle download on those who have a non-ICU Boost installation.

But without the revision bump, issues like this one will probably continue to come up, because there's no other way to trigger a rebuild for users that have installed Boost with `--with-icu4c` (either explicitly or as a dependency like in this case). :crying_cat_face:

**Comment by DomT4** [comment]
> Should we bump the revision of boost? 

Normally I'd be a little "eh" about doing it for optional dependencies until we get some firm numbers to play with, but boost is `cellar :any` so the impact on users would be fairly minimal. No objection in this case, personally.

**Comment by UniqMartin** [comment]
Bumped `boost`'s revision in #441.
