### ISSUE TITLE
Installing libcurl from source produces illegal instructions

### ISSUE THREAD

**Issue by dottedquad** [Homebrew/homebrew-core#4027]
We are installing with with "brew install curl --with-libressl" which causes it to be built from source. 

When it's built on an i7 MacBook Pro, the static library (/usr/local/opt/curl/lib/libcurl.a) includes BEXTR instructions. These work fine on the same machine, but if we publish a binary that links against this library, it fails on machines with older architectures (Core2).
`otool -tV /usr/local/opt/curl/lib/libcurl.a | grep bext`

I've attempted to edit the brew formula and add a "-march=core2" CFLAG. The flag seems to make it to the build (shows up ad a flag in the verbose make output), but the binaries still have the offending instructions.

If I run: 
`brew unpack curl &&\`
`cd curl-7.50.0 &&\`
`./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/usr/local/Cellar/curl/7.50.0 --with-ssl=/usr/local/opt/libressl --with-ca-bundle=/usr/local/etc/libressl/cert.pem --without-libssh2 --without-libidn --without-libmetalink --without-gssapi --without-librtmp --disable-ares CC=clang &&\`
`make install &&\`
`brew switch curl 7.50.0`

Then the BEXTR instructions are not included. This should be almost exactly what brew does internally. In fact, I copied the autoconf command directly from brew install's debug output. There are no extra flags. Just by avoiding brew's build system, it prevents the instructions from being added.

Does anyone know what's going on? Is there something I'm missing?

Thanks.

**Comment by mistydemeo** [comment]
When building from source, by default Homebrew optimizes for the same machine on which it was built. If you're planning on redistributing the binaries, you can use the `--build-bottle` argument to `brew install`; that passes `-march=core2`, and is the same way we build our binary packages for redistribution.

The reason that editing the formula doesn't work is because Homebrew wraps the compiler with scripts which massage the arguments being passed to the underlying tool, and Homebrew controls which arch is requested.
