### ISSUE TITLE
Geany

### ISSUE THREAD

**Issue by asmittal** [Homebrew/homebrew-core#41197]
https://brewformulas.org/geany page says - To install geany use brew install geany

But on giving this command there is error: 
No available formula with the name "geany"
Found a cask named "geany" instead.

On using brew cask reinstall geany
==> Satisfying dependencies
==> Downloading https://download.geany.org/geany-1.35_osx.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'geany'.
Error: Cask 'geany' definition is invalid: invalid 'depends_on macos' value: ":lion"

**Comment by SMillerDev** [comment]
https://brewformulas.org/ is not associated with homebrew so anything there is potentially harmful. There is formulae.brew.sh if you want to find a formula. As for issues with casks. This is the wrong place for that. You should report those to homebrew/homebrew-cask, but I believe you can fix this by removing and installing the cask instead of reinstalling it.

**Comment by asmittal** [comment]
Updated the issue with the required information as per the template.

**Comment by asmittal** [comment]
> https://brewformulas.org/ is not associated with homebrew so anything there is potentially harmful. There is formulae.brew.sh if you want to find a formula. As for issues with casks. This is the wrong place for that. You should report those to homebrew/homebrew-cask, but I believe you can fix this by removing and installing the cask instead of reinstalling it.

Thanks for response. The page is misleading further by saying on top: 
Homepage   https://geany.org/

I did try to remove cask but there also error. Anyways will put that in the cask issue.
