### ISSUE TITLE
how to install mongodb use brew?

### ISSUE THREAD

**Issue by lvan-zhang** [Homebrew/homebrew-core#44044]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ yes] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [yes ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [yes ] ran `brew update` and can still reproduce the problem?
- [yes ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [yes ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [yes ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
how to install mongodb use brew? 
- What happened (include command output)
![image](https://user-images.githubusercontent.com/17745287/64518434-bcb87780-d324-11e9-9ad4-c0b6a3f57b9e.png)

- What you expected to happen
is likely empty mongodb in brew-core
- Step-by-step reproduction instructions (by running `brew install` commands)
ok

**Comment by fxcoudert** [comment]
MongoDB is not open source anymore, and was removed from Homebrew core: https://github.com/Homebrew/homebrew-core/pull/43770

To install it, check the options offered by the MongoDB project: https://github.com/mongodb/homebrew-brew

**Comment by jhabdas** [comment]
> MongoDB is not open source anymore, and was removed from Homebrew core: #43770

With all due respect, please [educate yourself](https://writing.kemitchell.com/2019/06/13/SSPL-Not-Commons-Clause.html) before laying down any claims about the SSPL @fxcoudert. For those of us who build for 4 freedoms, Mongo ought to be considered a beacon of light.

**Comment by SMillerDev** [comment]
>> MongoDB is not open source anymore, and was removed from Homebrew core: #43770 ...

@jhabdas it's not an OSI approved license. So it's not open source. That's the definition homebrew maintains, regardless of your personal ideas about it.

**Comment by jhabdas** [comment]
Small clarification, and I'll save you a pull quote as the context in a linear thread should be clear: SSPL not an OSI-approved license. Therefore it _may not_ adhere to OSI's [Open Source Definition](https://web.archive.org/web/20191001150514/https://opensource.org/osd) which clearly states:

> 5. No Discrimination Against Persons or Groups

An [issue raised](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/IQIOBOGWJ247JGKX2WD6N27TZNZZNM6C/) by **an attorney** on behalf of Fedora Legal without substantive justification.

One could surmise most licenses in use today in the "open-source" community violate rule 5 in that they discriminate against the layperson through colorful and abundant use of legalese—just the kind of thing that keeps a lawyers client's coming through that revolving door.

Furthermore, "open source" as a concept unto its own contains a _subset_ of licenses with 4 freedoms otherwise known as "free software". Therefore, if Homebrew Core cares about software freedom as inasmuch as it seems outwardly, I compel you and your team to look inside yourselves and make the right decision.

OSI is not open source. It's a mafia.

**Comment by SMillerDev** [comment]
If you have a better measure to judge licenses by you can propose changes to the documentation in homebrew/brew to change the rules. But you can't possibly expect us to judge a couple hundred of pull requests a week by how you feel about their license.
