### ISSUE TITLE
proxychains

### ISSUE THREAD

**Issue by leebaird** [Homebrew/homebrew-core#4426]
brew install proxychains
Installs ok.

proxychains4 nmap -iL targets.txt -Pn -n -T4 --open -p- --stats-every 10s -oA nmap
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
dyld: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' because no suitable image found. Did find:
/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: mach-o, but wrong architecture

Trace/BPT trap: 5
============================================

Contacted the author and he said, 
"tell the brew package maintainers to add --fat-binary when they call configure.

https://github.com/rofl0r/proxychains-ng/issues/138

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
We do add `--fat-binary` if you use the `:universal` option, but don't otherwise. Is upstream saying this should _always_ be a universal binary, or?

**Comment by leebaird** [comment]
yes

—

Lee

**Comment by MikeMcQuaid** [comment]
That's not correct.

**Comment by Red54** [comment]
I met a different problem.

$ brew config
HOMEBREW_VERSION: 1.0.7-7-g6be6ce3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6be6ce33e0e5967f8e67801875bff6ab3f99b1ef
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e130cbafee3cee086d517558d82068ae9fa8cde1
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
X11: 2.7.9 => /opt/X11

$ proxychains4 git clone https://bitbucket.org/superr/superrs-kitchen.git
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.11
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' into library validated process because no suitable image found. Did find:
/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib'
Cloning into 'superrs-kitchen'...
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' into library validated process because no suitable image found. Did find:
/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib'
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' into library validated process because no suitable image found. Did find:
/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib'
remote: Counting objects: 582, done.
remote: Compressing objects: 100% (500/500), done.
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' into library validated process because no suitable image found. Did find:
/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib'
Receiving objects: 12% (70/582), 1.72 MiB | 29.00 KiB/s

**Comment by MikeMcQuaid** [comment]
@Red54 What's your `brew doctor` say?

**Comment by Red54** [comment]
$ brew doctor
Your system is ready to brew.

**Comment by dunn** [comment]
Is there anything actionable here?

**Comment by MikeMcQuaid** [comment]
Doesn't seem so.

**Comment by zzz6519003** [comment]
@MikeMcQuaid 
➜  em-midori git:(master) ✗ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: /usr/local is not writable.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami) /usr/local

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.

You should probably `sudo chown -R $(whoami)` them:
    /usr/local/share/man/man8

Warning: /usr/local is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. For example, upgrading
to OS X El Capitan has been known to do this. Some versions of the
"InstantOn" component of Airfoil or running Cocktail cleanup/optimizations
are known to do this as well.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami) /usr/local

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Broken symlinks were found. Remove them with `brew prune`:
    /usr/local/bin/electron
    /usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/ext/ffi_c/libffi-x86_64-darwin16/include/ffitarget.h

**Comment by MikeMcQuaid** [comment]
@zzz6519003 Those `brew doctor` warnings are likely the cause of your problems. Additionally, it looks like you were hit by the update bug so run these commands: https://github.com/Homebrew/homebrew-core#update-bug

**Comment by zzz6519003** [comment]
thanks, I gave you a heart reaction, but you don't receive it through notification right? XD

**Comment by MikeMcQuaid** [comment]
@zzz6519003 Thanks!
