### ISSUE TITLE
unbound is required by gnupg, gnutls, gpgme and mutt?

### ISSUE THREAD

**Issue by poige** [Homebrew/homebrew-core#44647]
```
% brew uninstall unbound
Error: Refusing to uninstall /usr/local/Cellar/unbound/1.9.3
because it is required by gnupg, gnutls, gpgme and mutt, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies unbound
```

**Comment by poige** [comment]
> to help you

They're helping me here. \@

**Comment by karelbemelmans** [comment]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?



## What you were trying to do (and why)

I installed gnupg and gnutls and it also installed unbound. Removing unbound is not possible to also remove gnupg and gnutls.
Unbound is a DNS resolver, why is that required for gnupg and gnutls?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  09:23 $ brew remove unbound
  Error: Refusing to uninstall /usr/local/Cellar/unbound/1.9.5
  because it is required by gnupg and gnutls, which are currently installed.
  You can override this and force removal with:
    brew uninstall --ignore-dependencies unbound
  </pre>
</details>

## What you expected to happen

Unbound should not be a hard requirement for these packages.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install gnupg
brew remove unbound

**Comment by karelbemelmans** [comment]
I added the required bug template here, even though it's not a bug, but I guess that's how this issue support system works. I hope someone picks this up now.

**Comment by SMillerDev** [comment]
AFAIK it's required to build basic functions.
