### ISSUE TITLE
mariadb-10.4.9.tar.gz can't download from official site

### ISSUE THREAD

**Issue by Excepti0nasE** [Homebrew/homebrew-core#46453]
When I run brew upgrade mariadb , download can't complete. It get the 404 error. And I copy the download link into browser, it shows the same result , 404 .Please be sure to check whether the file is still there, thanks.

**Comment by Bo98** [comment]
The 10.4.9 source was unfortunately later pulled after the Homebrew formula was updated to use it. I'm currently waiting for 10.4.10 which should be out this week. If not, we can discuss on what steps to take. This has all suddenly developed over the last few hours, after several Linux repos had also updated to use 10.4.9.

The precompiled bottles should however be working. Which version of macOS are you on?

(Having said all this, be cautious on upgrading if you use InnoDB databases with both foreign keys and `FULLTEXT INDEX` - I didn't even know `FULLTEXT` existed so you may well not have such a database, but crashing under such a setup is the reason the update was pulled.)

**Comment by fxcoudert** [comment]
<img width="783" alt="Capture d’écran 2019-11-07 à 06 44 37" src="https://user-images.githubusercontent.com/1980544/68363130-19b88a00-012a-11ea-9fe6-9bccaf998648.png">

What's the timeline on a 10.4.10 release?

**Comment by Bo98** [comment]
"Shortly" is basically the answer to that. Apart from that, their release process is not very transparent at all. They've got a patch up on GitHub but have said nothing since. cPanel have been trying to get an answer to that same question on a timeline but got no response.

The last time this happened, the turnaround time was 3 days.

Usually it goes up on mariadb.com (which doesn't have a million mirrors) before it does on mariadb.org.

**Comment by chenrui333** [comment]
@Excepti0nasE Just merged #46512, please test and verify it.
