### ISSUE TITLE
Homebrew Fails to Upgrade GNU TLS from v3.4.14 to v3.4.15 When Both Are Built From Source on OS X v10.11.6 'El Capitan'

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#4710]
### Please follow the general troubleshooting steps first:

- [x] Ran `brew update` (twice) and retried your prior step?
- [x] Ran `brew doctor` (twice,) fixed as many issues as possible, and retried your prior step?
- [ ] ~~If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?~~ N/A

### Bug report:

Running `brew upgrade -vd --build-from-source gnutls` (or even `brew upgrade --all -vd --build-from-source` when GNU TLS is the only thing left to upgrade, for that matter,) on OS X 10.11.6 'El Capitan' fails somewhere in the middle of the installation phase of the GNU TLS build and installation process hosted by Homebrew.  [Here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/GNU%20TLS) are the logs, but please note that these were generated _before_ I tried the steps outlined in Troubleshooting.md, though I _did_ try again after them and got the same results&thinsp;—&thinsp;that is, a failed build.

**Comment by RandomDSdevel** [comment]
Please also note that the previous version of GNU TLS (v3.4.14) that the new version (v3.4.15) would replace was _also_ built from source when it was originally installed.

**Comment by DomT4** [comment]
Oh, you're building `--with-guile` enabled, which apparently has a sandbox issue. Will check it out.

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/commit/f061d864d99da4064a763ba51a37ecf3cff8943c.

**Comment by RandomDSdevel** [comment]
OK, thanks a lot, @DomT4!

**Comment by RandomDSdevel** [comment]
@DomT4:  Apparently, the install-time equivalent of `brew link gnutls` failed.  When I run `brew doctor`, it spews out the following message:  

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    gnutls
```

When I try to run `brew link gnutls` separately, it errors out like so:  

```
Linking /usr/local/Cellar/gnutls/3.4.15... 
Error: Could not symlink share/guile/site/gnutls/extra.scm
Target /usr/local/share/guile/site/gnutls/extra.scm
is a symlink belonging to guile. You can unlink it:
  brew unlink guile

To force the link and overwrite all conflicting files:
  brew link --overwrite gnutls

To list all files that would be deleted:
  brew link --overwrite --dry-run gnutls
```

Running that last suggested command notifies me that not doing a `--dry-run` of it would overwrite the following files, …:  

```
Would remove:
/usr/local/share/guile/site/gnutls/extra.scm -> /usr/local/Cellar/guile/2.0.11_2/share/guile/site/gnutls/extra.scm
/usr/local/share/guile/site/gnutls.scm -> /usr/local/Cellar/guile/2.0.11_2/share/guile/site/gnutls.scm
```

…which, given the output that plain old `brew link gnutls` gave me, I know are most likely from my Homebrew GNU Guile installation.  The fact that both Guile _and_ GNU TLS install these _same_ files seems somewhat odd to me at best; do you know what might be going on here?  Could these be from a previous GNU TLS installation prior to your linkage fix when the prior code still somehow worked (which was, as I recall, in the version of GNU TLS prior to the most current one?)  If so, then would it be safe to `brew link --overwrite gnutls`?

**Comment by RandomDSdevel** [comment]
In the meantime, I did this:  

```
brew unlink guile
brew link gnutls
brew link --overwrite guile
```

Hopefully, that wasn't a naïve, overly presumptive mistake on my part.  Strangely enough, the `-vd` output of the last command seemed to link some stuff _from GNU TLS_ even though one would _think_ that Guile wouldn't even _know_ about any of its dependencies!

**Comment by DomT4** [comment]
Working on the underlying issue, but forcing the overwrite is absolutely fine there.

Basically the problem is that pre-sandbox `gnutls` installed its `guile` elements directly into the `guile` Cellar, so those then "belonged" to `guile`, so the change here essentially stole those files back off `guile` in favour of the `gnutls` ones, but brew doesn't know that's a safe overwrite so it blocks.

**Comment by RandomDSdevel** [comment]
@DomT4:  Ah, phew!  I'm glad that my impromptu fix was OK, then.  Could you possibly forward me a link to your proposed fix, though, so that I can follow your work on it since I'm interested in seeing it move forward?

**Comment by DomT4** [comment]
Heh. Potentially difficult to explain without going into a wad of detail about Homebrew's symlink structure, but https://github.com/Homebrew/brew/pull/939 made the directory we want global guile schemes to be installed into a real folder rather than a symlink back to either `guile`'s Cellar or indeed `gnutls`' Cellar. 

https://github.com/Homebrew/homebrew-core/pull/4741 bumped the revision to clear out stuff dumped into the `guile` Cellar incorrectly in the pre-sandbox days.

That may not be the case for you until you next `reinstall` or `upgrade` `gnutls`, but it's not a major issue. Just something nice to prevent from happening again in future, and establish somewhere for global guile schemes to live that won't get killed every `guile` update.

**Comment by RandomDSdevel** [comment]
@DomT4:  OK, thanks!
