### ISSUE TITLE
brew postgresql-upgrade-database fails 11 -> 12

### ISSUE THREAD

**Issue by masterkain** [Homebrew/homebrew-core#47110]
`brew upgrade` brought postgres to version 12, I then tried to upgrade database (11 always installed with homebrew)

```
kain@kain-osx-qemu ~ %   brew postgresql-upgrade-database

==> brew install postgresql@11
==> Downloading https://homebrew.bintray.com/bottles/postgresql@11-11.6.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c9/c91e358723fd5f700f059a0a1beff478d3e4aaa2ec40a3a166e946ff130d9fd0?__gda__=exp=1574543536~hmac=e5f9295e6f3bbb12eeea300d5b5b3e483e86de1e2f9935fbf4913f2a8fda82b9&response-content-disposition
######################################################################## 100.0%
==> Pouring postgresql@11-11.6.catalina.bottle.tar.gz
==> /usr/local/Cellar/postgresql@11/11.6/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@11
==> Caveats
To migrate existing data from a previous major version of PostgreSQL run:
  brew postgresql-upgrade-database

postgresql@11 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have postgresql@11 first in your PATH run:
  echo 'export PATH="/usr/local/opt/postgresql@11/bin:$PATH"' >> ~/.zshrc

For compilers to find postgresql@11 you may need to set:
  export LDFLAGS="-L/usr/local/opt/postgresql@11/lib"
  export CPPFLAGS="-I/usr/local/opt/postgresql@11/include"

For pkg-config to find postgresql@11 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/postgresql@11/lib/pkgconfig"


To have launchd start postgresql@11 now and restart at login:
  brew services start postgresql@11
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/Formulary::FormulaNamespacea6ceaa77ba5ad5656e6f12a514598ab0::PostgresqlAT11 start
==> Summary
🍺  /usr/local/Cellar/postgresql@11/11.6: 3,191 files, 36.4MB
==> Upgrading postgresql data from 11 to 12...
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
waiting for server to shut down............................................................... failed
pg_ctl: server does not shut down
==> Moving postgresql data from /usr/local/var/postgres to /usr/local/var/postgres.old...
The files belonging to this database system will be owned by user "kain".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/postgres ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Rome
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/local/opt/postgresql/bin/pg_ctl -D /usr/local/var/postgres -l logfile start

Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for tables WITH OIDS                               ok
Checking for invalid "sql_identifier" user columns          ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok

lc_ctype values for database "postgres" do not match:  old "UTF-8", new "en_US.UTF-8"
Failure, exiting
Error: Upgrading postgresql data from 11 to 12 failed!
==> Removing empty postgresql initdb database...
==> Moving postgresql data back from /usr/local/var/postgres.old to /usr/local/var/postgres...
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
Error: Failure while executing; `/usr/local/opt/postgresql/bin/pg_upgrade -r -b /usr/local/Cellar/postgresql@11/11.6/bin -B /usr/local/opt/postgresql/bin -d /usr/local/var/postgres.old -D /usr/local/var/postgres -j 4` exited with 1.
```

maybe we need to tweak `initdb --locale=C -E UTF-8`?

**Comment by Bo98** [comment]
Copying over my original question with slightly tweaked commands since `postgres.old` won't exist.

Can you show me the output of `psql -l`?

```
/usr/local/opt/postgresql@11/bin/pg_ctl -D /usr/local/var/postgres start
/usr/local/opt/postgresql@11/bin/psql -l
/usr/local/opt/postgresql@11/bin/pg_ctl -D /usr/local/var/postgres stop
```

**Comment by masterkain** [comment]
```
kain@kain-osx-qemu ~ % /usr/local/opt/postgresql@11/bin/psql -l
                                 List of databases
           Name            | Owner | Encoding | Collate | Ctype | Access privileges
---------------------------+-------+----------+---------+-------+-------------------
 postgres                  | kain  | UTF8     | en_US   | UTF-8 |
 scraper_development       | kain  | UTF8     | en_US   | UTF-8 |
 scraper_test              | kain  | UTF8     | en_US   | UTF-8 |
 template0                 | kain  | UTF8     | en_US   | UTF-8 | =c/kain          +
                           |       |          |         |       | kain=CTc/kain
 template1                 | kain  | UTF8     | en_US   | UTF-8 | =c/kain          +
                           |       |          |         |       | kain=CTc/kain

```

**Comment by Bo98** [comment]
Can you also show `psql -c "SELECT name, setting FROM pg_settings WHERE category ~ 'Locale';"` (on the old DB)?

**Comment by masterkain** [comment]
```
kain@kain-osx-qemu ~ % psql postgres -c "SELECT name, setting FROM pg_settings WHERE category ~ 'Locale';"
            name            |      setting
----------------------------+-------------------
 client_encoding            | UTF8
 DateStyle                  | ISO, MDY
 default_text_search_config | pg_catalog.simple
 extra_float_digits         | 0
 IntervalStyle              | postgres
 lc_collate                 | en_US
 lc_ctype                   | UTF-8
 lc_messages                | en_US
 lc_monetary                | en_US
 lc_numeric                 | en_US
 lc_time                    | en_US
 server_encoding            | UTF8
 TimeZone                   | Europe/Rome
 timezone_abbreviations     | Default
```

**Comment by Bo98** [comment]
Nothing unexpected I can see.

The issue for you is basically this part isn't running properly: https://github.com/Homebrew/homebrew-core/blob/935b431e7568508602a66c49ae9532f61bb554c2/cmd/brew-postgresql-upgrade-database.rb#L65-L71

`lc_ctype` is empty and is not getting passed into the `initdb`. It seems to work for me locally.

I do see this though in your logs though:

> ```
> pg_ctl: server does not shut down
> ```

Can I see `brew services list`?

**Comment by zsoltion** [comment]
I'm actually having the same issue:

`brew postgresql-upgrade-database
==> brew install postgresql@11
==> Downloading https://homebrew.bintray.com/bottles/postgresql@11-11.6.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c9/c91e358723fd5f700f059a0a1beff478d3e4aaa2ec40a3a166e946ff130d9fd0?__gda__=exp=1574591536
######################################################################## 100.0%
==> Pouring postgresql@11-11.6.catalina.bottle.tar.gz
==> /usr/local/Cellar/postgresql@11/11.6/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@11
==> Caveats
To migrate existing data from a previous major version of PostgreSQL run:
  brew postgresql-upgrade-database

postgresql@11 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have postgresql@11 first in your PATH run:
  echo 'export PATH="/usr/local/opt/postgresql@11/bin:$PATH"' >> ~/.zshrc

For compilers to find postgresql@11 you may need to set:
  export LDFLAGS="-L/usr/local/opt/postgresql@11/lib"
  export CPPFLAGS="-I/usr/local/opt/postgresql@11/include"


To have launchd start postgresql@11 now and restart at login:
  brew services start postgresql@11
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/Formulary::FormulaNamespacea6ceaa77ba5ad5656e6f12a514598ab0::PostgresqlAT11 start
==> Summary
🍺  /usr/local/Cellar/postgresql@11/11.6: 3,191 files, 36.4MB
==> Upgrading postgresql data from 11 to 12...
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
waiting for server to shut down............................................................... failed
pg_ctl: server does not shut down
==> Moving postgresql data from /usr/local/var/postgres to /usr/local/var/postgres.old...
The files belonging to this database system will be owned by user "user".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/postgres ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Budapest
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/local/opt/postgresql/bin/pg_ctl -D /usr/local/var/postgres -l logfile start

Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for tables WITH OIDS                               ok
Checking for invalid "sql_identifier" user columns          ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok

lc_collate values for database "postgres" do not match:  old "C", new "en_US.UTF-8"
Failure, exiting
Error: Upgrading postgresql data from 11 to 12 failed!
==> Removing empty postgresql initdb database...
==> Moving postgresql data back from /usr/local/var/postgres.old to /usr/local/var/postgres...
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
Error: Failure while executing; `/usr/local/opt/postgresql/bin/pg_upgrade -r -b /usr/local/Cellar/postgresql@11/11.6/bin -B /usr/local/opt/postgresql/bin -d /usr/local/var/postgres.old -D /usr/local/var/postgres -j 8` exited with 1.`

After running it again, a different error showed up:

`brew postgresql-upgrade-databaseó


==> Upgrading postgresql data from 11 to 12...
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
waiting for server to start....2019-11-24 11:25:49.875 CET [56766] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-11-24 11:25:49.875 CET [56766] LOG:  listening on IPv6 address "::1", port 5432
2019-11-24 11:25:49.876 CET [56766] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-11-24 11:25:49.887 CET [56767] LOG:  database system was shut down at 2019-11-24 11:24:14 CET
2019-11-24 11:25:49.891 CET [56766] LOG:  database system is ready to accept connections
 done
server started
waiting for server to shut down...2019-11-24 11:25:50.006 CET [56766] LOG:  received fast shutdown request
.2019-11-24 11:25:50.007 CET [56766] LOG:  aborting any active transactions
2019-11-24 11:25:50.008 CET [56766] LOG:  background worker "logical replication launcher" (PID 56773) exited with exit code 1
2019-11-24 11:25:50.008 CET [56768] LOG:  shutting down
2019-11-24 11:25:50.016 CET [56766] LOG:  database system is shut down
 done
server stopped
==> Moving postgresql data from /usr/local/var/postgres to /usr/local/var/postgres.old...
The files belonging to this database system will be owned by user "user".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  C
  CTYPE:    C
  MESSAGES: en_US.UTF-8
  MONETARY: en_US.UTF-8
  NUMERIC:  en_US.UTF-8
  TIME:     en_US.UTF-8
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/postgres ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Budapest
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/local/opt/postgresql/bin/pg_ctl -D /usr/local/var/postgres -l logfile start

Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for tables WITH OIDS                               ok
Checking for invalid "sql_identifier" user columns          ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok

encodings for database "postgres" do not match:  old "UTF8", new "SQL_ASCII"
Failure, exiting
Error: Upgrading postgresql data from 11 to 12 failed!
==> Removing empty postgresql initdb database...
==> Moving postgresql data back from /usr/local/var/postgres.old to /usr/local/var/postgres...
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
Error: Failure while executing; `/usr/local/opt/postgresql/bin/pg_upgrade -r -b /usr/local/Cellar/postgresql@11/11.6/bin -B /usr/local/opt/postgresql/bin -d /usr/local/var/postgres.old -D /usr/local/var/postgres -j 8` exited with 1.`

**Comment by stevek123** [comment]
I'm actually having the same issue with two different errors:

> brew postgresql-upgrade-database
> ==> brew install postgresql@11
> ==> Downloading https://homebrew.bintray.com/bottles/postgresql@11-11.6.catalina.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/c9/c91e358723fd5f700f059a0a1beff478d3e4aaa2ec40a3a166e946ff130d9fd0?__gda__=exp=1574591536
> ######################################################################## 100.0%
> ==> Pouring postgresql@11-11.6.catalina.bottle.tar.gz
> ==> /usr/local/Cellar/postgresql@11/11.6/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@11
> ==> Caveats
> To migrate existing data from a previous major version of PostgreSQL run:
>   brew postgresql-upgrade-database
> 
> postgresql@11 is keg-only, which means it was not symlinked into /usr/local,
> because this is an alternate version of another formula.
> 
> If you need to have postgresql@11 first in your PATH run:
>   echo 'export PATH="/usr/local/opt/postgresql@11/bin:$PATH"' >> ~/.zshrc
> 
> For compilers to find postgresql@11 you may need to set:
>   export LDFLAGS="-L/usr/local/opt/postgresql@11/lib"
>   export CPPFLAGS="-I/usr/local/opt/postgresql@11/include"
> 
> 
> To have launchd start postgresql@11 now and restart at login:
>   brew services start postgresql@11
> Or, if you don't want/need a background service you can just run:
>   pg_ctl -D /usr/local/var/Formulary::FormulaNamespacea6ceaa77ba5ad5656e6f12a514598ab0::PostgresqlAT11 start
> ==> Summary
> 🍺  /usr/local/Cellar/postgresql@11/11.6: 3,191 files, 36.4MB
> ==> Upgrading postgresql data from 11 to 12...
> Stopping `postgresql`... (might take a while)
> ==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
> waiting for server to shut down............................................................... failed
> pg_ctl: server does not shut down
> ==> Moving postgresql data from /usr/local/var/postgres to /usr/local/var/postgres.old...
> The files belonging to this database system will be owned by user "user".
> This user must also own the server process.
> 
> The database cluster will be initialized with locale "en_US.UTF-8".
> The default database encoding has accordingly been set to "UTF8".
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> fixing permissions on existing directory /usr/local/var/postgres ... ok
> creating subdirectories ... ok
> selecting dynamic shared memory implementation ... posix
> selecting default max_connections ... 100
> selecting default shared_buffers ... 128MB
> selecting default time zone ... Europe/Budapest
> creating configuration files ... ok
> running bootstrap script ... ok
> performing post-bootstrap initialization ... ok
> syncing data to disk ... ok
> 
> initdb: warning: enabling "trust" authentication for local connections
> You can change this by editing pg_hba.conf or using the option -A, or
> --auth-local and --auth-host, the next time you run initdb.
> 
> Success. You can now start the database server using:
> 
>     /usr/local/opt/postgresql/bin/pg_ctl -D /usr/local/var/postgres -l logfile start
> 
> Performing Consistency Checks
> -----------------------------
> Checking cluster versions                                   ok
> Checking database user is the install user                  ok
> Checking database connection settings                       ok
> Checking for prepared transactions                          ok
> Checking for reg* data types in user tables                 ok
> Checking for contrib/isn with bigint-passing mismatch       ok
> Checking for tables WITH OIDS                               ok
> Checking for invalid "sql_identifier" user columns          ok
> Creating dump of global objects                             ok
> Creating dump of database schemas
>                                                             ok
> 
> lc_collate values for database "postgres" do not match:  old "C", new "en_US.UTF-8"
> Failure, exiting
> Error: Upgrading postgresql data from 11 to 12 failed!
> ==> Removing empty postgresql initdb database...
> ==> Moving postgresql data back from /usr/local/var/postgres.old to /usr/local/var/postgres...
> ==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
> Error: Failure while executing; `/usr/local/opt/postgresql/bin/pg_upgrade -r -b /usr/local/Cellar/postgresql@11/11.6/bin -B /usr/local/opt/postgresql/bin -d /usr/local/var/postgres.old -D /usr/local/var/postgres -j 8` exited with 1.

Then I ran it again, it showed a different error:

> brew postgresql-upgrade-database
> 
> ==> Upgrading postgresql data from 11 to 12...
> Stopping `postgresql`... (might take a while)
> ==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
> waiting for server to start....2019-11-24 11:25:49.875 CET [56766] LOG:  listening on IPv4 address "127.0.0.1", port 5432
> 2019-11-24 11:25:49.875 CET [56766] LOG:  listening on IPv6 address "::1", port 5432
> 2019-11-24 11:25:49.876 CET [56766] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
> 2019-11-24 11:25:49.887 CET [56767] LOG:  database system was shut down at 2019-11-24 11:24:14 CET
> 2019-11-24 11:25:49.891 CET [56766] LOG:  database system is ready to accept connections
>  done
> server started
> waiting for server to shut down...2019-11-24 11:25:50.006 CET [56766] LOG:  received fast shutdown request
> .2019-11-24 11:25:50.007 CET [56766] LOG:  aborting any active transactions
> 2019-11-24 11:25:50.008 CET [56766] LOG:  background worker "logical replication launcher" (PID 56773) exited with exit code 1
> 2019-11-24 11:25:50.008 CET [56768] LOG:  shutting down
> 2019-11-24 11:25:50.016 CET [56766] LOG:  database system is shut down
>  done
> server stopped
> ==> Moving postgresql data from /usr/local/var/postgres to /usr/local/var/postgres.old...
> The files belonging to this database system will be owned by user "user".
> This user must also own the server process.
> 
> The database cluster will be initialized with locales
>   COLLATE:  C
>   CTYPE:    C
>   MESSAGES: en_US.UTF-8
>   MONETARY: en_US.UTF-8
>   NUMERIC:  en_US.UTF-8
>   TIME:     en_US.UTF-8
> The default database encoding has accordingly been set to "SQL_ASCII".
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> fixing permissions on existing directory /usr/local/var/postgres ... ok
> creating subdirectories ... ok
> selecting dynamic shared memory implementation ... posix
> selecting default max_connections ... 100
> selecting default shared_buffers ... 128MB
> selecting default time zone ... Europe/Budapest
> creating configuration files ... ok
> running bootstrap script ... ok
> performing post-bootstrap initialization ... ok
> syncing data to disk ... ok
> 
> initdb: warning: enabling "trust" authentication for local connections
> You can change this by editing pg_hba.conf or using the option -A, or
> --auth-local and --auth-host, the next time you run initdb.
> 
> Success. You can now start the database server using:
> 
>     /usr/local/opt/postgresql/bin/pg_ctl -D /usr/local/var/postgres -l logfile start
> 
> Performing Consistency Checks
> -----------------------------
> Checking cluster versions                                   ok
> Checking database user is the install user                  ok
> Checking database connection settings                       ok
> Checking for prepared transactions                          ok
> Checking for reg* data types in user tables                 ok
> Checking for contrib/isn with bigint-passing mismatch       ok
> Checking for tables WITH OIDS                               ok
> Checking for invalid "sql_identifier" user columns          ok
> Creating dump of global objects                             ok
> Creating dump of database schemas
>                                                             ok
> 
> encodings for database "postgres" do not match:  old "UTF8", new "SQL_ASCII"
> Failure, exiting
> Error: Upgrading postgresql data from 11 to 12 failed!
> ==> Removing empty postgresql initdb database...
> ==> Moving postgresql data back from /usr/local/var/postgres.old to /usr/local/var/postgres...
> ==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
> Error: Failure while executing; `/usr/local/opt/postgresql/bin/pg_upgrade -r -b /usr/local/Cellar/postgresql@11/11.6/bin -B /usr/local/opt/postgresql/bin -d /usr/local/var/postgres.old -D /usr/local/var/postgres -j 8` exited with 1.

**Comment by kkzz8888** [comment]
I am experiencing a similar error, help is needed thanks!


......

The database cluster will be initialized with locales
  COLLATE:  C
  CTYPE:    C
  MESSAGES: en_US.UTF-8
  MONETARY: en_US.UTF-8
  NUMERIC:  en_US.UTF-8
  TIME:     en_US.UTF-8
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/postgres ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... America/New_York
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/local/opt/postgresql/bin/pg_ctl -D /usr/local/var/postgres -l logfile start

Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for tables WITH OIDS                               ok
Checking for invalid "sql_identifier" user columns          ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok

encodings for database "postgres" do not match:  old "UTF8", new "SQL_ASCII"
Failure, exiting
Error: Upgrading postgresql data from 11 to 12 failed!
==> Removing empty postgresql initdb database...
==> Moving postgresql data back from /usr/local/var/postgres.old to /usr/local/var/postgres...
Error: Failure while executing; `/usr/local/opt/postgresql/bin/pg_upgrade -r -b /usr/local/Cellar/postgresql@11/11.6/bin -B /usr/local/opt/postgresql/bin -d /usr/local/var/postgres.old -D /usr/local/var/postgres -j 4` exited with 1.

**Comment by Bo98** [comment]
@stevek123 @kkzz8888 Can you show me the output of:

```
/usr/local/opt/postgresql@11/bin/pg_ctl -D /usr/local/var/postgres start
/usr/local/opt/postgresql@11/bin/psql -l
/usr/local/opt/postgresql@11/bin/psql postgres -c "SELECT name, setting FROM pg_settings WHERE category ~ 'Locale';"
/usr/local/opt/postgresql@11/bin/pg_ctl -D /usr/local/var/postgres stop
```

**Comment by stevek123** [comment]
> [user:~]$ /usr/local/opt/postgresql@11/bin/pg_ctl -D /usr/local/var/postgres start
> waiting for server to start....2019-11-24 15:26:15.603 CET [88114] LOG:  listening on IPv4 address "127.0.0.1", port 5432
> 2019-11-24 15:26:15.603 CET [88114] LOG:  listening on IPv6 address "::1", port 5432
> 2019-11-24 15:26:15.603 CET [88114] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
> 2019-11-24 15:26:15.621 CET [88116] LOG:  database system was shut down at 2019-11-24 11:25:51 CET
> 2019-11-24 15:26:15.628 CET [88114] LOG:  database system is ready to accept connections
>  done
> server started
> [user:~]$ /usr/local/opt/postgresql@11/bin/psql -l
>                            List of databases
>      Name      | Owner | Encoding | Collate | Ctype | Access privileges 
> ---------------+-------+----------+---------+-------+-------------------
>  test-dtb-proj | user  | UTF8     | C       | C     | =Tc/user        +
>                |       |          |         |       | user=CTc/user
>  postgres      | user  | UTF8     | C       | C     | 
>  template0     | user  | UTF8     | C       | C     | =c/user         +
>                |       |          |         |       | user=CTc/user
>  template1     | user  | UTF8     | C       | C     | =c/user         +
>                |       |          |         |       | user=CTc/user
> (4 rows)
> 
> [user:~]$ /usr/local/opt/postgresql@11/bin/psql postgres -c "SELECT name, setting FROM pg_settings WHERE category ~ 'Locale';"
>             name            |      setting       
> ----------------------------+--------------------
>  client_encoding            | UTF8
>  DateStyle                  | ISO, MDY
>  default_text_search_config | pg_catalog.english
>  extra_float_digits         | 0
>  IntervalStyle              | postgres
>  lc_collate                 | C
>  lc_ctype                   | C
>  lc_messages                | C
>  lc_monetary                | C
>  lc_numeric                 | C
>  lc_time                    | C
>  server_encoding            | UTF8
>  TimeZone                   | Europe/Budapest
>  timezone_abbreviations     | Default
> (14 rows)
> 
> [user:~]$ /usr/local/opt/postgresql@11/bin/pg_ctl -D /usr/local/var/postgres stop
> waiting for server to shut down....2019-11-24 15:26:33.885 CET [88114] LOG:  received fast shutdown request
> 2019-11-24 15:26:33.886 CET [88114] LOG:  aborting any active transactions
> 2019-11-24 15:26:33.887 CET [88114] LOG:  background worker "logical replication launcher" (PID 88122) exited with exit code 1
> 2019-11-24 15:26:33.887 CET [88117] LOG:  shutting down
> 2019-11-24 15:26:33.896 CET [88114] LOG:  database system is shut down
>  done
> server stopped

**Comment by kkzz8888** [comment]
/usr/local/opt/postgresql@11/bin/pg_ctl -D /usr/local/var/postgres start
waiting for server to start....2019-11-24 09:26:07.004 EST [33031] LOG:  listening on IPv6 address "::1", port 5432
2019-11-24 09:26:07.004 EST [33031] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-11-24 09:26:07.005 EST [33031] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-11-24 09:26:07.088 EST [33032] LOG:  database system was shut down at 2019-11-24 09:12:46 EST
2019-11-24 09:26:07.094 EST [33031] LOG:  database system is ready to accept connections
 done
server started
(base) Kevins-iMac:opt kevinzheng$ /usr/local/opt/postgresql@11/bin/psql -l
                                List of databases
   Name    |   Owner    | Encoding | Collate | Ctype |     Access privileges     
-----------+------------+----------+---------+-------+---------------------------
 pega      | pegaadmin  | UTF8     | C       | C     | 
 postgres  | kevinzheng | UTF8     | C       | C     | 
 template0 | kevinzheng | UTF8     | C       | C     | =c/kevinzheng            +
           |            |          |         |       | kevinzheng=CTc/kevinzheng
 template1 | kevinzheng | UTF8     | C       | C     | =c/kevinzheng            +
           |            |          |         |       | kevinzheng=CTc/kevinzheng
(4 rows)

(base) Kevins-iMac:opt kevinzheng$ /usr/local/opt/postgresql@11/bin/psql postgres -c "SELECT name, setting FROM pg_settings WHERE category ~ 'Locale';"
            name            |      setting       
----------------------------+--------------------
 client_encoding            | UTF8
 DateStyle                  | ISO, MDY
 default_text_search_config | pg_catalog.english
 extra_float_digits         | 0
 IntervalStyle              | postgres
 lc_collate                 | C
 lc_ctype                   | C
 lc_messages                | C
 lc_monetary                | C
 lc_numeric                 | C
 lc_time                    | C
 server_encoding            | UTF8
 TimeZone                   | America/New_York
 timezone_abbreviations     | Default
(14 rows)

(base) Kevins-iMac:opt kevinzheng$ /usr/local/opt/postgresql@11/bin/pg_ctl -D /usr/local/var/postgres stop
waiting for server to shut down....2019-11-24 09:27:41.353 EST [33031] LOG:  received fast shutdown request
2019-11-24 09:27:41.353 EST [33031] LOG:  aborting any active transactions
2019-11-24 09:27:41.355 EST [33031] LOG:  background worker "logical replication launcher" (PID 33038) exited with exit code 1
2019-11-24 09:27:41.367 EST [33046] FATAL:  terminating autovacuum process due to administrator command
2019-11-24 09:27:41.405 EST [33033] LOG:  shutting down
2019-11-24 09:27:41.454 EST [33031] LOG:  database system is shut down
 done
server stopped

**Comment by Bo98** [comment]
Thanks all. The information has been useful.

I have a pull request (#47123) open that should resolve a couple issues. I'll let you know if/when it is merged.

**Comment by stevek123** [comment]
I manually updated the script, and It works! Thank you so much!
