### ISSUE TITLE
Set PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig for the Crystal programming language

### ISSUE THREAD

**Issue by ndbroadbent** [Homebrew/homebrew-core#47515]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

CC @bcardiff 

## What you were trying to do (and why)

I was trying to run the `crystal` binary for the [Crystal programming language](https://crystal-lang.org/).

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

ld: library not found for -lssl (this usually means you need to install the development package for libssl)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '/Users/ndbroadbent/.cache/crystal/crystal-run-eval.tmp'  -rdynamic  -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre /usr/local/Cellar/crystal/0.31.1/embedded/lib/libgc.a -lpthread /usr/local/Cellar/crystal/0.31.1/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/local/Cellar/crystal/0.31.1/embedded/lib -L/usr/lib -L/usr/local/lib`

  </pre>
</details>

## What you expected to happen

I expected to be able to use crystal without needing to [manually set the `PKG_CONFIG_PATH` for OpenSSL.](https://github.com/crystal-lang/crystal/issues/6875#issuecomment-424959060)

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install crystal
crystal eval 'require "http/client"; puts HTTP::Client.get("https://www.google.com/").status_code'
```

## Workaround

From https://github.com/crystal-lang/crystal/issues/6875#issuecomment-424959060:

```
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
```

Setting this `PKG_CONFIG_PATH` variable (e.g. in my `~/.bash_profile`) will fix this issue:

```
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
crystal eval 'require "http/client"; puts HTTP::Client.get("https://www.google.com/").status_code'
# 200
```

What is the best way to update the crystal brew package so that this manual step is no longer necessary?

## References

* https://github.com/crystal-lang/crystal-book/pull/312
* https://github.com/crystal-lang/crystal/issues/7209
* https://github.com/crystal-lang/crystal/issues/6875

**Comment by Bo98** [comment]
This seems expected. OpenSSL is deliberately keg-only as it might conflict with the system OpenSSL. This caveat is documented when you install OpenSSL:

```
==> Caveats
openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

However given how Crystal is used in comparison to C etc., I can understand how this behaviour may surprise some in this particular case since you aren't explicitly compiling against OpenSSL directly - it's something internal Crystal does.

Note though that Homebrew doesn't really have any involvement on how it behaves at runtime so has no control of `PKG_CONFIG_PATH` post-installation. We don't ever modify the user's environment and will never start messing with their `.bash_profile`. Is there a build-time flag which can be used to bake in a search path into Crystal?

**Comment by bcardiff** [comment]
@Bo98 would it be acceptable to have a wrapper script that will by default set the `PKG_CONFIG_PATH` before running the compiler itself.

Although Crystal support adding in the compiler compile time a fixed path to look up libraries my understanding is that that will not play nice with customs location of homebrew since the bottle will have an invalid path in this use cases.

Are there any suggestions/preference regarding how a wrapper script may have useful defaults but the user will be able to override them?

* If the wrapper script always append the openssl path, there is no way to remove it.
* If the wrapper script only sets it if PKG_CONFIG_PATH is unset I bet it will become somehow useless because there are many use cases that push users to have already a PKG_CONFIG_PATH set.

Are you aware of similar stories in other formulas in order to not reinvent the wheel?

**Comment by Bo98** [comment]
For example wrapper env scripts, search up `write_env_script` in this repository. I'm not sure what the general feeling is among maintainers on this approach - it's never been used for `PKG_CONFIG_PATH` before.

**Comment by RX14** [comment]
If macos has a system openssl, why is it not being found by the crystal compiler? I wish I had a mac to test what's actually going on here since the root cause seems to have never been actually found.

**Comment by Bo98** [comment]
I don't know but it's incredibly outdated and you really don't want to use it. 0.9.8 or something.

**Comment by RX14** [comment]
Okay, agree this is the best fix then.

**Comment by SMillerDev** [comment]
We can discuss this more in a pull request since it's unclear to me what you want to change (and homebrew policy doesn't allow for change requests in issues)
