### ISSUE TITLE
python3 failed to build on 10.11.6 with Xcode 8

### ISSUE THREAD

**Issue by ehlers** [Homebrew/homebrew-core#4809]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

After installing the new official Xcode 8 I tried to upgrade python3 from 3.5.2 to 3.5.2_1

```
/Users/behlers# brew upgrade
==> Upgrading 1 outdated package, with result:
python3 3.5.2_1
==> Upgrading python3
Warning: Building python3 from source:
  The bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

==> Using the sandbox
==> Downloading https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
######################################################################## 100,0%
==> Downloading https://bugs.python.org/file30805/issue10910-workaround.txt
Already downloaded: /Users/behlers/Library/Caches/Homebrew/python3--patch-c075353337f9ff3ccf8091693d278782fcdff62c113245d8de43c5c7acc57daf.txt
==> Patching
==> Applying issue10910-workaround.txt
patching file Include/pyport.h
Hunk #1 succeeded at 688 (offset -11 lines).
Hunk #2 succeeded at 711 (offset -11 lines).
==> ./configure --prefix=/usr/local/Cellar/python3/3.5.2_1 --enable-ipv6 --datar
==> make
Last 15 lines from /Users/behlers/Library/Logs/Homebrew/python3/02.make:
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /private/tmp/python3-20160914-26240-1d51p4y/Python-3.5.2/./Programs/_freeze_importlib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /private/tmp/python3-20160914-26240-1d51p4y/Python-3.5.2/./Programs/_freeze_importlib
  Expected in: /usr/lib/libSystem.B.dylib

/bin/sh: line 1: 33678 Trace/BPT trap: 5       ./Programs/_freeze_importlib ./Lib/importlib/_bootstrap.py Python/importlib.h
make: *** [Python/importlib.h] Error 133
make: *** Waiting for unfinished jobs....
/bin/sh: line 1: 33677 Trace/BPT trap: 5       ./Programs/_freeze_importlib ./Lib/importlib/_bootstrap_external.py Python/importlib_external.h
make: *** [Python/importlib_external.h] Error 133
```

gist-logs:
https://gist.github.com/c0e055813ac7904793fcd216146eb662

**Comment by chdiza** [comment]
Probably you need the CLT package for El Capitan that goes with Xcode 8; unfortunately, that's not yet available for download.

**Comment by DomT4** [comment]
I'm not even sure the CLT _by itself_ is going to be enough to resolve these problems at the moment, but yeah, we certainly won't know until the CLT release is pushed.

**Comment by ehlers** [comment]
Is there a way to check, which CLT is currently installed?

**Comment by DomT4** [comment]
`brew config` will tell you, i.e.
```
OS X: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
```

**Comment by ehlers** [comment]
Well, I haven't installed them. I thought that Xcode is enough.
```
OS X: 10.11.6-x86_64
Xcode: 8.0
CLT: N/A
```

**Comment by DomT4** [comment]
There's an "issue" (Apple considers it a feature) with the new Xcode, which happens as a consequence of Apple retaining the single SDK structure rather than having one SDK in Xcode for 10.11 and another for 10.12.

Apple created the single SDK this year with symbols _exclusive_ to system elements on macOS 10.12, but does something fairly clever around weak links which is represented like this:
```
symbols:         [ '$ld$weak$os10.11$_basename_r', '$ld$weak$os10.11$_clock_getres', 
                   '$ld$weak$os10.11$_clock_gettime', '$ld$weak$os10.11$_clock_settime', 
                   '$ld$weak$os10.11$_dirname_r', '$ld$weak$os10.11$_getentropy', 
                   '$ld$weak$os10.11$_mkostemp', '$ld$weak$os10.11$_mkostemps', 
```

However, this mostly seems to shunt the breakage from build time to runtime rather than stopping the breakage entirely. There doesn't seem to be a great solution currently that doesn't either A) move the breakage to runtime rather than resolving it entirely or B) Relies on every FOSS project suddenly handling Apple's single SDK sanely, and pigs may fly before B happens.

Allegedly using the CLT resolves some of the issues, which is what we're waiting to discover really.

If you're interested in the history here https://github.com/Homebrew/homebrew-core/issues/3727, https://github.com/Homebrew/homebrew-core/issues/2674 & https://github.com/Homebrew/brew/pull/782 go into the issue & failed attempts at a solution.

**Comment by ehlers** [comment]
Thanks for all your efforts with Xcode 8 on 10.11. But I've got the impression, that Xcode 8 is working quite poorly with 10.11 (not your fault). I prefer to have a stable development environment, so I decided to go back to Xcode 7.3.1, which (of course) solves my issue.

**Comment by DomT4** [comment]
Yeah, that's fine. We're not going to start nagging people to switch over to Xcode 8 until we're happy we've fixed this particularly annoying issue.

I'd generally urge people to hang back on a new major Xcode and wait to see how it behaves before updating, but since Apple pushes it out via MAS a lot of people presume it's a "safe" update, which these major bumps quite often it turns out not to be 😕.

**Comment by DomT4** [comment]
It should be mostly safe now, if you wish to update. We'll hold off nudging people for a short time to test out our fix.
