### ISSUE TITLE
geckodriver checksum mismatch

### ISSUE THREAD

**Issue by RazerM** [Homebrew/homebrew-core#48660]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install geckodriver from source

## What happened (include command output)

There's a checksum mismatch. I checked it with `curl | sha256sum` to rule out a network error and get the same one as reported by brew.

<details>
  <summary>Command output</summary>
  <pre>
==> Upgrading geckodriver
rm /usr/local/bin/geckodriver
rm /usr/local/bin/wires
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200107-72036-jcyy8q.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/geckodriver.rb --verbose
==> Downloading https://hg.mozilla.org/mozilla-central/archive/e9783a644016aa9b317887076618425586730d73.zip/testing/
Already downloaded: /Users/frazer/Library/Caches/Homebrew/downloads/f005f31f969623c7625ec4140642ab94f28b379f91d7479d23b650578f7e30e2--mozilla-central-e9783a644016aa9b317887076618425586730d73.zip
==> Verifying f005f31f969623c7625ec4140642ab94f28b379f91d7479d23b650578f7e30e2--mozilla-central-e9783a644016aa9b317887076618425586730d73.zip checksum
ln -s ../Cellar/geckodriver/0.25.0/bin/geckodriver geckodriver
ln -s ../Cellar/geckodriver/0.25.0/bin/wires wires
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 89f20b2d492b44b40ee049d0f0d4d91c52758b74dd7b5c7acad89a88ca1f177e
  Actual: fa13311fe4b18c2e22ebc904c1d229488c29253882f5aee78a0603af2b2d6671
  </pre>
</details>

**Comment by chrmoritz** [comment]
I can confirm that, but the commit is still there, so they probably just have changed the compression level used by the zip archive, which would explain the checksum change for that specific commit. However I unfortunately don't have a copy of the old archive anymore, so I can't confirm this assumption.

These changes are quite unfortunate, because I'd really like to avoid having to clone the whole giant mozilla central repository here (containing all the unrelated source code for firefox (mobile), thunderbird...).

**Comment by fxcoudert** [comment]
Fixed, thanks to @chrmoritz
