### ISSUE TITLE
feature request: add a patch to Emacs formula to enable emoji again

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew-core#5044]
In Emacs 25.1, the upstream Emacs developers decided to block rendering of color fonts on macOS: https://github.com/emacs-mirror/emacs/commit/9344612d3cd164317170b6189ec43175757e4231

I understand that Homebrew doesn't generally like carrying feature patches, but since this patch was specifically introduced to degrade the functionality of free software on macOS, and Homebrew's purpose is to provide a good user experience of free software *on* macOS, you might make an exception in this case.

Thank you for your consideration!

**Comment by tdsmith** [comment]
cc @dunn, friendly neighborhood emacs user and ethicist

**Comment by lvh** [comment]
It should also be noted that the way this bug shows itself is pretty user-hostile. (Sufficiently so that I'm pretty comfortable calling it a bug.). Under 24.4+, emoji render fine. Upgrade to 25.1, and every time a new emoji is rendered, you get a five-second freeze and no rendered emoji, with no useful information in `*Messages*`  or out of `describe-char`.

You can find the Symbola workaround (go install a new font) in the NEWS file, but you have to correctly diagnose the problem and know what you're looking for.

**Comment by dunn** [comment]
I love emoji so I would be fine carrying this patch (in fact I apply it in my experimental version of the Emacs formula: https://github.com/dunn/homebrew-yolo/blob/master/Formula/emacs-edge.rb).

But it would mark an exception, so let's get a few more opinions.

**Comment by MikeMcQuaid** [comment]
Happy to have this in external taps but not here, sorry!

**Comment by glyph** [comment]
For anyone else discovering this issue, https://github.com/railwaycat/homebrew-emacsmacport might be an interesting external tap to try; beyond just this minor issue, it tries to fully integrate with the mac as a platform.

**Comment by glyph** [comment]
(Also, thank you @dunn and @MikeMcQuaid for the prompt response here!)
