### ISSUE TITLE
Qt55 Failed to build on 10.12

### ISSUE THREAD

**Issue by pkraus138** [Homebrew/homebrew-core#5163]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I've been trying to `brew install qt55` for use with capybara-webkit for feature specs and have been having trouble all night getting it installed. 
- I've tried removing and reinstalling xcode and xcode-select to no avail :(
- Also worth noting that the *build* portion of the installation is taking about ~25 minutes

Qt55:
https://gist.github.com/b941dc2c7092605ff37989fc314b36ff

also tried Qt5 earlier although it's not what I need
https://gist.github.com/pkraus138/281e73b008a61df4d844c8a896db3fde

**Comment by kanekotic** [comment]
+1 same problem here. I think is related to this [issue](https://github.com/Homebrew/homebrew-core/issues/1957)

**Comment by kanekotic** [comment]
+1 same problem here. @pkraus138 I think is related to this #1957

**Comment by ilovezfs** [comment]
No version of Qt works on 10.12 yet except for the pre-release branches. Request a new release upstream.

**Comment by kanekotic** [comment]
@ilovezfs could you explain what you ment with that?. I started using brew literally yesterday so how can I access pre-release branch?. How to request an to whom a release upstream?

I manage to install QT creator and build without problem on the standalone version of QT inside mac OS sierra so this is not an issue of QT itself I can confirm that much. Why i am eager to install through Brew is that I have to get access to command line capabilities so i can run qmake from my command line for my CI.

there is also important i think that there are 2 pull requests (#4905 and #5162) regarding this as the command line says n the failing moment:
```
These open issues may also help:
Update qt5 urls https://github.com/Homebrew/homebrew-core/pull/4905
qwt: port qwt to qt5 https://github.com/Homebrew/homebrew-core/pull/5162
```

**Comment by ilovezfs** [comment]
@kanekotic current releases of Qt5 are 5.6.1 and 5.7.0. The first versions that will actually support Sierra are 5.6.2 and 5.7.1. So the current plan is to wait for either 5.6.2 or 5.7.1 to be released by upstream before proceeding with rolling out a new release of the Homebrew formula.

**Comment by kanekotic** [comment]
With upstream you mean QT?, never heard this word before ;).

**Comment by ilovezfs** [comment]
In this case upstream is The Qt Company:
https://www.qt.io/
https://code.qt.io/cgit/qt/qt5.git

In general:
https://en.wikipedia.org/wiki/Upstream_%28software_development%29

**Comment by rlugge** [comment]
Is there any way to install one of those pre-release branches via homebrew?

**Comment by kanekotic** [comment]
so I tried use pull request #4905 and di not work same error, even if its downloading 5.7.1.
 I am still confused where and how to ask upstream for an update, as there is no clear way to know whom is the sustainer and how to contact them? (would be cool as a new future feature for brew, similar to npm ownership)

**Comment by kanekotic** [comment]
as per @zmwangx and @DomT4 comments on #1957 , should this issue be reopen?

**Comment by DomT4** [comment]
This specific issue is in the wrong place, `qt55` isn't a core formula. I would be absolutely amazed if Qt had any interest in rescuing the Qt 5.5 branch for Sierra at this point though, there hasn't been a commit to that branch for 8 months now. If someone can get Qt to accept a patch for Sierra support on the 5.5 branch we'll accept that patch but otherwise it's likely dead.

The core `qt5` is still a work in progress. I've tried the 5.6 branch, the 5.7 branch and the dev branch and all have their own unique problems with Sierra. I'm hoping to come up with some mash that works in the coming days, but not having a ton of luck so far.

**Comment by kanekotic** [comment]
ok @DomT4 i understand your point from my part I dont care about 55 y want 5.6 or 5.7, i need them for my CI. qt5 is a core package and if you read throught we both tried to install qt5 core package with no luck, i also tried the pr open that brew related to this issue.
I think what i will do is to open a new issue with specific qt5 and link this one then as you can find the logs from both of us.

**Comment by rlugge** [comment]
My priority @DomT4 isn't QT55, or QT5, or QT6.  My priority is getting qmake available on my system so that Capybara can compile, so I can work on an app that has a capybara dependency.

**Comment by DomT4** [comment]
@kanekotic I did read through, which is why you got the clarification on `qt5` as well. If anyone else knows how to fix building from source on Sierra, we'd absolutely love a PR. Otherwise I'm doing the best I can with the behemoth that is the Qt5 codebase.

This is a problem every single year with new OS X/macOS releases and people who want stability from upstreams really should be hanging back on the prior release for a period. Otherwise it's a case of waiting for either upstream, us or you to fix it as quickly as possible to restore full availability.

**Comment by DomT4** [comment]
If you're determined, you could _try_: https://www.qt.io/download-open-source/. It's a huge installation & not completely sanely structured for development, but if all you need is `qmake` I suspect that ships it.

**Comment by rlugge** [comment]
@DomT4 I tried that, didn't install qmake for the terminal for some silly reason.

**Comment by kanekotic** [comment]
@DomT4 first please dont take it personal and thanks a lot to you and all the team of brew for having such a great project 👍 

Also thanks for your answer I completly understand your view and frustration as developer. I will say we need to tone down in some posts not take it as a fight, me personally I dont think is your fault i normally blame apple for their shitty job of retrocompatibility, so I am trying to help as much as possible share logs, open issues, try pull requests, and I will happily have a look at the compilation errors when I have a second. This is how we people can collaborate and this is why open source is so awesome.

PS. we all have our story on this case, mine is I would love to have used el capitan but this is a new second hand machine and I was only allowed to update to sierra from Lion (because stupid Apple don't even give margin in between releases). And yes that link that you shared works I had tried it, but the machine will be connected to Jenkins so I need the command line so I can build using a yml in 3 different platforms.

**Comment by kanekotic** [comment]
@rlugge that installation is standalone and will add all QT 5.7 to a folder under your user, this is not referenced on bin so it wont work on the command line (that is why brew is awesome and that installer not :P ). you could try to add the bin of that folder to your path (but I dont know how clean that solution will be neither if it will fully work).

**Comment by rleigh-codelibre** [comment]
Qt 5.6.2 has now been released.

**Comment by ilovezfs** [comment]
@rleigh-codelibre voilà https://github.com/Homebrew/homebrew-core/pull/5843.

**Comment by rleigh-codelibre** [comment]
@ilovezfs Thanks, I'll give it a test.
