### ISSUE TITLE
Add rustup?

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew-core#5263]
[home page](https://github.com/rust-lang-nursery/rustup.rs)

It's the replacement for multirust, it looks like, and seems like it'll be the recommended install method at some point.

This is more a question whether this should be added, or whether this is the appropriate time to do so. It sort of "bypasses" Homebrew in that it takes care of installation, etc., but there are other formulae (e.g. `opam`) which do the same, so hopefully it isn't a huge issue?

I can write this if it's something that users may be interested in

**Comment by zmwangx** [comment]
It's fine, we have version managers for multiple languages. Please open a PR.

**Comment by nomoon** [comment]
This might be tricky since Rustup either installs by compiled binary or compiles from an existing nightly version of Rust.

**Comment by aw1621107** [comment]
That's true... Now that I think about it, it's sort of like brew itself -- install from bottles or from source when bottles aren't available -- but the updating itself part is a good point

**Comment by nomoon** [comment]
Also similar to RVM (which I use separately from homebrew). RBenv and Pyenv, if I'm not mistaken, have a bit more "standard" release types, which is probably why they fit well into homebrew (where they can be tagged each release so that someone can come and update them).

**Comment by nomoon** [comment]
FWIW, thanks for pointing out its existence, though. Rustup, even if somewhat incompatible with Homebrew, is a much smoother system to use if you want more than just a generic up-to-date copy of Rust and Cargo (issues like #5194 notwithstanding).

**Comment by MikeMcQuaid** [comment]
Closing in favour of a PR.

**Comment by oherrala** [comment]
`rustup` is now the preferred way to install Rust ([source](https://blog.rust-lang.org/2016/12/22/Rust-1.14.html)):

> One of the biggest features in Rust 1.14 isn’t actually in the language or compiler: the rustup tool has reached a 1.0 release, and is now the recommended way to install Rust from the project directly. 

I couldn't find PR about this. Can this issue be opened until there's PR?

**Comment by bfontaine** [comment]
> I couldn't find PR about this. Can this issue be opened until there's PR?

Feel free to open a PR :wink:

**Comment by ilovezfs** [comment]
>It makes cross-compiling simpler with binary builds of the standard library for common platforms.

Though I wouldn't necessarily expect the PR to go anywhere if this is based on installing prebuilt stuff.

**Comment by jansol** [comment]
Please note that rustup can be built with self updating disabled. E.g. arch linux does this. That way you have a package manager -managed rustup and rustup-managed toolchains.

**Comment by ilovezfs** [comment]
Other than being new, what benefit would rustup provide that is not provided by the current formula? As far as I can tell, it does exactly the same thing we do, but would fail to cache its resources, and would re-download them every time the build runs. There may be a way to tweak it to use the Homebrew cache, and lack of caching is not necessarily a fatal objection, but so far I have yet to hear anything it will do for us that would be a net positive.

**Comment by jansol** [comment]
Which formula do you mean? Rustup is functionally almost the same as the now unmaintained multirust, for which there currently is a formula. Something that multirust IIRC didn't support that rustup does is installing the rustc sources alongside the toolchain, which is autocompletion tools need in order to complete standard library symbols. rustup is also effectively a drop-in replacement to multirust so there's hardly any risk of breakage.

As for why it'd be needed in the first place: for many projects one still needs a relatively recent nightly rustc (sadly, but the situation should improve a lot with 1.15 and the new "macros 1.1" feature). Additionally, as mentioned already, it drastically simplifies cross-compilation, as one only has to run a rustup command to switch to another toolchain. Tools such as the tokamak plugin to Atom even have integration for this.

Not having to wait for the worst case of two or more weeks between a rustc release and its availability on homebrew is also *extremely* nice. Anyway, I'm sure the cache stuff can be arranged, if that's what it takes to get this in. I don't know what is needed by the homebrew side, but it looks like there is an environment variable controlling the storage directory for downloads. If more features are needed, please don't hesitate to open an issue for that on https://github.com/rust-lang-nursery/rustup.rs

**Comment by nomoon** [comment]
Rustup would also provide the benefit(?) of off-loading resources from homebrew's build/bottles infrastructure to supply downloads for stable/beta/nightly/legacy downloads of Rust.

But it does function somewhat like RVM and various other version managers, so using it as an alternative to homebrew for rust instead of providing it through homebrew is certainly reasonable.
