### ISSUE TITLE
The description for openssl installation is misleading

### ISSUE THREAD

**Issue by daften** [Homebrew/homebrew-core#5291]
### Bug reports:

The caveat shows:
A CA file has been bootstrapped using certificates from the system
    keychain. To add additional certificates, place .pem files in ...

However, the only keychain used is the keychain /System/Library/Keychains/SystemRootCertificates.keychain which is NOT the system keychain. I myself interpret the system keychain as the "system" keychain, not the "system roots" keychain ...
### Formula Requests:

I'd suggest simply adapting the caveat to say system roots keychain instead of the system keychain. I'd like feedback on this before opening a PR.

**Comment by DomT4** [comment]
To be honest, I think we could call it the pineapple keychain and most people would shrug as long as it worked. I don't think the current description is particularly wide of the mark, but I can't say I care much either way. It's a hangover from when we did collect more from the keychain than we do now, but nobody has complained about the actual wording of that before this.

Happy to let other maintainers have their say on this.

**Comment by MikeMcQuaid** [comment]
> I'd suggest simply adapting the caveat to say system roots keychain instead of the system keychain. I'd like feedback on this before opening a PR.

If this is more accurate I'm happy for a PR to be opened to change the wording 👍

**Comment by ocean** [comment]
The recent update (September 22?) to OpenSSL 1.0.2i broke my `curl`'s ability to connect to **anything** (stopping me from doing any homebrew updates), due to the fact that I had my company's internal SSL-sniffing custom proxy CA certificates in my `/usr/local/etc/openssl/cert.pem`, which were overwritten by the `brew upgrade openssl` command.

I recreated my `/usr/local/etc/openssl/cert.pem` from the latest version of `cacert.pem` from https://curl.haxx.se plus my company's internal CA certificates, and everything was working fine. 

Until I `brew upgrade`d to OpenSSL 1.0.2j, which overwrote them again!

Has this only changed recently? Did the install recipe previously include importing of certificates from my `System.keychain` and `login.keychain` into the `cert.pem`? Because I've updated OpenSSL lots of times before and not had this problem.

**Comment by daften** [comment]
@DomT4 Yes, as long as it works, that's true. But this wording makes me believe that if I add the certs to the "System" keychain, and I reinstall openssl, those certs would be included, but they aren't, so for me, it doesn't work.

I'll create a PR, since this won't break anything, and could only make things clearer.

@ocean Yes: this changed, the System keychain used to be taken into account. I'm not sure when it changed, but it did change at some point. :)

**Comment by daften** [comment]
The PR has been opened, with 2 commits. The first commit just changes the keychain name. The second one has another addition that would have helped me greatly as well. Feel free to let me know if the second commit is too much.

**Comment by DomT4** [comment]
> Has this only changed recently? Did the install recipe previously include importing of certificates from my System.keychain and login.keychain into the cert.pem? Because I've updated OpenSSL lots of times before and not had this problem.

Not super recently, but yes we changed it because OpenSSL absolutely trusts that `.pem` even if the `.pem` is full of garbage.

If I stick a self-signed root in the login keychain for `mydomain.com`, even a self-signed root explicitly marked untrusted in that keychain & we import that to the `.pem`, as far as your command-line tools that link against OpenSSL will ever know that domain is perfectly safe to connect to and interact with. So you can make secure connections that are potentially anything but, disturbingly easily as you note in your own comment, which is intentional for you but may not be for someone else:

> due to the fact that I had my company's internal SSL-sniffing custom proxy CA certificates

To counter that possibility we scoped back our import to the system roots, which at least on recent OS X/macOS versions you can't add/delete certs from. There are ways to be more selective about it, but I haven't yet come up with one that doesn't turn OpenSSL's `postinstall` step into either a 5 minute process or a process where you could come out the other side with no `.pem`.

> I recreated my /usr/local/etc/openssl/cert.pem from the latest version of cacert.pem from https://curl.haxx.se plus my company's internal CA certificates, and everything was working fine.

No need to use curl's certs. Can pretty easily directly dump new certs on top of the existing `.pem` generated via `nano` or `cat` or whatever your preference is.

**Comment by ocean** [comment]
@DomT4 Ok, thanks for the explanation on what has changed. I don't totally agree with the way it works, but that's fine 😁   (I agree though that I can't really think of a better way that works for everyone).

I can't think of a time when I would put a certificate into my login keychain that I didn't want curl and other tools to use as well, but at least I see exactly what has happened now.

I'll take note of using the SystemRoot keychain certificates rather than the ones from the curl site, though the curl site ones seem to be more up to date. I guess macOS ones change fairly infrequently, only on software updates.

**Note:** For anyone else who might be in a similar situation to mine, I've discovered a tool called [openssl-osx-ca](https://github.com/raggi/openssl-osx-ca) by @raggi, which does almost everything I require.

It is installable as a Homebrew tap, and runs as a LaunchAgent background service, syncing any certificates in your Keychains across to the `/usr/local/etc/openssl/cert.pem` file every hour. The choice of keychains you want synced and the sync frequency are configurable.

@daften 👍  on both commits in the pull request, I think they are a nice clarification 😃

**Comment by raggi** [comment]
openssl-osx-ca used to be a cronjob, but now that I've ported it to use launchd's built in periodic scheduler, it no longer has weird uninstall woes, and could be adopted by homebrew proper. Sadly, the relationship from the last ticket on the topic didn't go so well, so I'm disinclined to open such a discussion myself, though I'll support anyone else who tries to make good things happen.

**Comment by MikeMcQuaid** [comment]
@raggi Looks like it could be a standalone formula in Homebrew?

**Comment by raggi** [comment]
Since moving it to launchd, yes, it could be.

**Comment by MikeMcQuaid** [comment]
Sounds like it could have a `plist` inside the formula and be setup with `brew services`.

**Comment by raggi** [comment]
Yes, the tap has worked that way for about a month

**Comment by MikeMcQuaid** [comment]
@raggi 👍 Looking at it I don't see anything that would cause major objections; just a few style tweaks.

**Comment by daften** [comment]
@MikeMcQuaid Is the last comment meant for my PR? Cause I'm not really following the discussion :)

**Comment by MikeMcQuaid** [comment]
@daften No, sorry, was about the `openssl-osx-ca` tool.

**Comment by daften** [comment]
Ok, no worries, just wanted to make sure ;)

**Comment by KDGNOR** [comment]
@MikeMcQuaid how did u install openssl-osx-ca tool?
```
$ brew search openssl-osx-ca
No formula found for "openssl-osx-ca".
==> Searching pull requests...
$
```

**Comment by ocean** [comment]
@KDGNOR Aha, looks like you've got a Catch-22 situation there. Are you behind a corporate proxy with SSL sniffing?

I already had OpenSSL installed (through Homebrew) before installing `openssl-osx-ca`.

I got my Homebrew install working by:

- having `http_proxy` and `https_proxy` environment variables set
- manually adding my work proxy's self-signed CA certificate to the all the Keychains
- ... maybe some other steps, will add if I remember, it's been so long 😄 

You might have to download the OpenSSL source file through a browser and then point Homebrew to it locally for a manual build.

**Comment by MikeMcQuaid** [comment]
Closing as there's no work ongoing on this issue, sorry.
