### ISSUE TITLE
mono: sandbox restrictions cause F# build to fail

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew-core#5302]
[Gist](https://gist.github.com/aw1621107/16735a63e35058bb407f4f8c62f7458e)

Build fails when NuGet tries to download some packages. It fails, as the normal NuGet config files are stored in my config directory, which is outside the sandbox boundary. I would guess that NuGet got that specific path because I have `XDG_CONFIG_HOME` set.

**Comment by ilovezfs** [comment]
@apjanke wonder if this would be fixed by that path cleansing you were doing?

**Comment by apjanke** [comment]
I don't think so: I wasn't dealing with `XDG_CONFIG_HOME`, IIRC. But I think this *would* be addressed by the "sanitize the whole environment" approach floated by Mike at https://github.com/Homebrew/brew/issues/932.

Even before we go sanitize-everything-but-whitelist, we should probably be re-setting or clearing `$XDG_CONFIG_HOME` in our sandbox, because that's baslcally like `$HOME`. Any value set by users will not be okay inside our sandbox.

**Comment by ilovezfs** [comment]
@apjanke Yup, that makes lots of sense.

**Comment by MikeMcQuaid** [comment]
Closing as there's no work ongoing on this issue, sorry.
