### ISSUE TITLE
Brew install of pipenv 2020.5.28 does not contain zsh completions

### ISSUE THREAD

**Issue by remidebette** [Homebrew/homebrew-core#55614]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

The brew installation of pipenv does not set zsh completions
(those completions are broken on both mac and linux)
(shared to the pipenv team on https://github.com/pypa/pipenv/issues/4300)

## What happened (include command output)

`$(brew --prefix)/share/zsh/site-functions/../../../Cellar/pipenv/2020.5.28/share/zsh/site-functions/_pipenv` file is empty

## What you expected to happen

The file should contain completions.

## Step-by-step reproduction instructions (by running `brew install` commands)

Simply install the latest version of pipenv with brew
`brew install pipenv`

To test completions, the system should have zsh installed and the following in .zshrc :
```bash
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi
```

brew doctor: 
```
brew doctor                      
Your system is ready to brew.
```

brew config: 
```
brew config       
HOMEBREW_VERSION: 2.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 77e09fc166f5fb7197b239d5e2727ddc0791c121
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: a4e505bdbfdfce4d18cae7723909d332e59c1a5e
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 4.19.104-microsoft-standard x86_64 GNU/Linux
OS: Ubuntu 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
glibc: N/A
gcc: N/A
xorg: N/A
```

**Comment by Rylan12** [comment]
It looks to me like the lines `Utils.popen_read("SHELL=bash #{libexec}/bin/pipenv --completion")` and `Utils.popen_read("SHELL=zsh #{libexec}/bin/pipenv --completion")` seem to return nothing.

According to https://github.com/pypa/pipenv/issues/1762, pipenv knows which shell to provide the completion code for based on the `SHELL` variable which is set by the `SHELL=bash` or `SHELL=zsh` command. This seems to be the case because running `SHELL=zsh pipenv --completions` prints the zsh completions while `SHELL=bash pipenv --completions` prints the bash completions.

It seems like when homebrew installs, pipenv uses a different indicator to determine the current shell (I think it's deciding on `sh`). If pipenv doesn't support this shell for completion, it will fail quietly and the `write` function writes nothing to the completion files.

I'm not sure exactly how to solve this but I'll look into it a little bit.

**Comment by Rylan12** [comment]
It looks like using ``output = `SHELL=bash #{libexec}/bin/pipenv --completion` `` instead of `Utils.popen_read("SHELL=bash #{libexec}/bin/pipenv --completion")` does the trick (note the backticks).

I'm not sure why the `popen_read` method doesn't work or why it was used instead of the backticks. It makes me think that the backticks are bad practice or being avoided for some reason (although it does pass `brew audit --strict`.

If no one has any suggestions here I'll open a PR tomorrow to make the change.

**Comment by Rylan12** [comment]
This has been resolved by #55682

**Comment by Rylan12** [comment]
It appears to work for me.

Make sure to read and follow the directions [here](https://docs.brew.sh/Shell-Completion), although it looks like you have the appropriate lines in your `.zshrc`.

Maybe try `rm -f ~/.zcompdump; compinit`?

From the linked documentation:

> You may also need to forcibly rebuild `zcompdump`:
> 
> ```sh
>   rm -f ~/.zcompdump; compinit
> ```

**Comment by remidebette** [comment]
Other brew I installed (like kubectl or exa) zsh complete without any issue (or additional .zshrc config from my end)
But if I do a "pipenv inst" and hit tab, nothing happens

**Comment by remidebette** [comment]
Oh indeed, only if I do a `rm -f ~/.zcompdump; compinit` after the terminal startup then it works (even though very slow the first time, but it might be [expected](https://github.com/pypa/pipenv/issues/1247))

Do you think this command should be added to the .zshrc itself?

**Comment by Rylan12** [comment]
No, I don't think so. My understanding is that `.zcompdump` serves as a "cache" to speed up `compinit` which manages the completion. Removing the file forces `compinit` to "reload" the completions, so you should only have to do it when completions are changed.

**Comment by Rylan12** [comment]
To clarify, now that you've removed `. zcompdump` once, you shouldn't have to do it every time you start a terminal session to use the completion.
