### ISSUE TITLE
sqlite 3.32.3 upgrade failures

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#56641]
From #56512

- `brew test --verbose agda`
- `brew test --verbose alure`
- `brew fetch --retry breezy`
- `brew test --verbose genometools`
- `brew test --verbose spdylay`
- `brew test --verbose yle-dl`

**Comment by miccal** [comment]
`genometools`  was bumped in https://github.com/Homebrew/homebrew-core/pull/55922 which has fixed its failing tests.

**Comment by miccal** [comment]
- `brew test --verbose agda` -- related to https://github.com/Homebrew/homebrew-core/issues/55253
- `brew test --verbose alure` -- [known failure?](https://github.com/Homebrew/homebrew-core/pull/55804#issuecomment-639865112)
- `brew fetch --retry breezy` -- [revision bump?](https://github.com/Homebrew/homebrew-core/pull/56512#issuecomment-647143884)
- `brew test --verbose genometools` -- fixed in https://github.com/Homebrew/homebrew-core/pull/55922
- `brew test --verbose spdylay` -- [revision bump?](https://github.com/Homebrew/homebrew-core/pull/52172)
- `brew test --verbose yle-dl` -- fixed in https://github.com/Homebrew/homebrew-core/pull/56600 perhaps?

**Comment by miccal** [comment]
`breezy`, `genometools` and `yle-dl` now pass, but: 
```
Error: 6 failed steps!
brew test --verbose agda
brew test --verbose alure
brew test --verbose percona-server
brew install root
brew test --verbose ship
brew test --verbose spdylay
```

**Comment by chenrui333** [comment]
new tracker #59707
