### ISSUE TITLE
Request to include Google Cloud SDK in homebrew core

### ISSUE THREAD

**Issue by aayushkapoor206** [Homebrew/homebrew-core#583]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by apjanke** [comment]
Do you mean this SDK? https://cloud.google.com/sdk/

Looks like it's already available via [Homebrew Cask](https://caskroom.github.io/).

```
$ brew cask info google-cloud-sdk
google-cloud-sdk: latest
Google Cloud SDK
https://cloud.google.com/sdk/
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-cloud-sdk.rb
==> Contents
  google-cloud-sdk/bin/bq (binary)
```

To install it:
```
brew tap caskroom/cask
brew cask install google-cloud-sdk
```

**Comment by aayushkapoor206** [comment]
@apjanke Yes! That's the one. Though I don't understand why it's under cask? It's a command line tool.

**Comment by apjanke** [comment]
Maybe because it's a "binary" distribution, where no compilation happens, and we just install the upstream OS-specific binary distribution. But since this is mostly a Python project, that doesn't seem too relevant. This looks like a good candidate for moving in to core Homebrew.

We also have an upcoming project to more closely integrate Cask and main Homebrew, so maybe this won't be an issue soon.

Let us know if you have any issues with using it from the Cask formula. And good luck!

**Comment by aayushkapoor206** [comment]
@apjanke Thanks! Cask solved it 😄  Is there more information on the upcoming project?

**Comment by apjanke** [comment]
It's just in the planning stages now. It is one of Homebrew's GSoC 2016 projects. https://github.com/Homebrew/Outreachy-and-Google-Summer-of-Code/issues/6
