### ISSUE TITLE
Is anyone working on a formual update for pypy3 v5.5.0?

### ISSUE THREAD

**Issue by cclauss** [Homebrew/homebrew-core#6122]
https://morepypy.blogspot.fr/2016/10/pypy3-550-released.html

**Comment by zmwangx** [comment]
https://bitbucket.org/pypy/pypy/downloads/pypy3.3-v5.5.0-alpha-src.tar.bz2 is an alpha release (alpha in the sense of alpha CPython 3.3 compatibility, but still I would call it an alpha). Feel free to submit a PR with `v5.5.0-alpha` as `devel` though.

However, I highly recommend using [pyenv](https://github.com/yyuu/pyenv) to install it, which is much more flexible.

Closing this issue in the meantime since the correct way to proceed is a PR.

**Comment by mistydemeo** [comment]
There's now a PR for this, in #6769.

**Comment by mistydemeo** [comment]
I've merged the 5.5.0 upgrade.
