### ISSUE TITLE
OpenJDK upgrade strategy

### ISSUE THREAD

**Issue by moonfruit** [Homebrew/homebrew-core#62786]
I noticed that the latest OpenJDK upgrade is always slow and painful.
And the issue #62201 **"Python 3.9 Migration"** gave me some inspirations.

Why not we make the formula `openjdk` is an alias for `openjdk@14`?
When OpenJDK 15 has been released, we should add a formula `openjdk@15` immediately.
And then slightly migrate other formulas from `openjdk@14` to `openjdk@15`.
And eventually, make the formula `openjdk` to point to `openjdk@15`.
Just like Python did.

**Comment by jonchang** [comment]
Please always fill out the issue template. The maintainers are aware of this problem and proposed solution already; as always, the best way to get openjdk updated to the newest version is to open pull requests to fix the build issues that are identified by CI.

In contrast to Python, where patch releases are common for past minor versions, non-LTS releases of openjdk are not supported immediately after the next major version is released. This is to be avoided per our [versioned formulae policy](https://docs.brew.sh/Versions). In addition, Python is special because almost all dependent formulae need to be revision bumped and rebuilt from source, which imposes a particularly brutal tax on our infrastructure in a way that openjdk updates don't.
