### ISSUE TITLE
Gnupg 2.1

### ISSUE THREAD

**Issue by maletor** [Homebrew/homebrew-core#637]
https://github.com/Homebrew/legacy-homebrew/issues/36104 references updating to 2.1 but the issue is closed and locked claiming that updating breaks backwards compatibility. 

...I mean, ya, that's sometimes that happens when software is updated. We shouldn't be afraid to update a package manager's software versions because the newest one doesn't work with the version before it.

Homebrew should package Gnupg 2.1 and, if necessary, provide a caveat about how migrating back to 2.0 would be painful and backups should be made. There are a great many improvements in 2.1 that users will want to take advantage of.

**Comment by DomT4** [comment]
It wasn't locked as a personal thing, one of the maintainers wrote a script using a GitHub API to lock a lot of old Issues because people would comment in them and we'd miss those notifications.

`brew install homebrew/versions/gnupg21` will get you what you want. It also comes shipped with a giant explanatory caveat. This has been [noted in the core formula](https://github.com/Homebrew/homebrew-core/blob/7e36b9d5885fd710eb3139de2acca506dea59301/Formula/gnupg2.rb#L1-L3). It'll likely take over the core formulae for `gnupg2` at some point but we are packaging `gnupg21` in the meantime.
