### ISSUE TITLE
--ignore-scripts no longer works for "npm pack"

### ISSUE THREAD

**Issue by zachauten** [Homebrew/homebrew-core#63798]
See #63627 for some previous discussion.

It appears brew was relying on the undocumented `--ignore-scripts` flag for `npm pack` to skip the `prepare` [lifecycle script](https://docs.npmjs.com/cli/v7/using-npm/scripts) (and perhaps other scripts?).

The npm 7 upgrade seems to have removed this functionality, causing builds to break because these scripts may use tools that aren't available to brew.

Recent examples:
#63513
#63514
#63515
#63627

Some possible solutions:
- Add a step to remove the prepare/lifecycle scripts before building npm formulae.
- Look for another way to rework our process or run `npm pack` without lifecycle scripts.
- Add missing tools/scripts required by lifecycle scripts as resources / make them available at build time.
- Open a PR to npm to add the --ignore-scripts flag back 😝

cc @chrmoritz

**Comment by chrmoritz** [comment]
Some more notes:

* The problem causing life cycle scripts here are just `prepare` and maybe `prepublish` (but [that's deprecated since `npm@4`](https://docs.npmjs.com/cli/v6/using-npm/scripts#prepare-and-prepublish) and shouldn't be used by any up to date package anymore).
* The 'normal usage' of the `npm pack` command is part of the `npm publish` process and intended to do some preprocessing (like transpiling ts -> js) and then creating a tarball of everything needed (=not ignored somehow) for publishing it to the (npm) registry. I doubt that there is a valid use case for `npm pack --ignore-scripts` except our hacky way to make the npm global workflow compatible with homebrew way to install stuff (aka the source of the main package is downloaded and verified by homebrew and then we use npm in that very specific way to create a global package installation into the formulae cellar).
* Manipulating the `package.json` to remove the `prepare` script could be easily done using rubys json parser and shouldn't be more complicated than what we already do for some 2-package formulae like [webpack](https://github.com/Homebrew/homebrew-core/blob/cb2119c6d033cf101f38cc952f935b64a9ddf795/Formula/webpack.rb#L35-L38) and [babel](https://github.com/Homebrew/homebrew-core/blob/cb2119c6d033cf101f38cc952f935b64a9ddf795/Formula/babel.rb#L33-L36)
* The alternative of reworking our code to not rely on `npm pack --ignore-scripts` would require reimplementing that global installation logic of npm in ruby. This would require parsing the `package.json` for the `main` field and the the arbitrary `bin` file mapping (eg. for `{ "bin" : { "myapp" : "./dist/cli.js" } }` we would need to create symlink in `bin` with the name `myapp` pointing to `libexec/dist/cli.js`) too.

**Comment by MikeMcQuaid** [comment]
> * Manipulating the `package.json` to remove the `prepare` script could be easily done using rubys json parser and shouldn't be more complicated than what we already do for some 2-package formulae like [webpack](https://github.com/Homebrew/homebrew-core/blob/cb2119c6d033cf101f38cc952f935b64a9ddf795/Formula/webpack.rb#L35-L38) and [babel](https://github.com/Homebrew/homebrew-core/blob/cb2119c6d033cf101f38cc952f935b64a9ddf795/Formula/babel.rb#L33-L36)
> * The alternative of reworking our code to not rely on `npm pack --ignore-scripts` would require reimplementing that global installation logic of npm in ruby. This would require parsing the `package.json` for the `main` field and the the arbitrary `bin` file mapping (eg. for `{ "bin" : { "myapp" : "./dist/cli.js" } }` we would need to create symlink in `bin` with the name `myapp` pointing to `libexec/dist/cli.js`) too.

Either of this sounds good to me. Would you be able to attempt a PR for these @chrmoritz?

**Comment by codeitram** [comment]
@MikeMcQuaid hey I am beginner and I would like to solve this issue can you give me some pointer on how to approach it ?

**Comment by MikeMcQuaid** [comment]
We can't provide any more help than the above and Homebrew's documentation, sorry!

**Comment by dtrodrigues** [comment]
I re-opened the affected PRs and they're successfully installing now: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Aopen+is%3Apr+author%3Adtrodrigues+label%3Anodejs
