### ISSUE TITLE
pkg-config breaks llvm-project builds

### ISSUE THREAD

**Issue by chadbrewbaker** [Homebrew/homebrew-core#65772]
pkg-config is still breaking builds on llvm-project.

https://forums.swift.org/t/is-anyone-else-getting-this-error-when-building-the-compiler-from-master-on-macos/36113/17

To reproduce:
```bash
brew install pkg-config
git clone https://github.com/llvm/llvm-project
cd llvm-project
mkdir build; cd build;
cmake ../llvm -DCMAKE_BUILD_TYPE=Release
make -j8
```

**Comment by jonchang** [comment]
Please always fill out the issue template, thanks. You were asked to do so when filing a new issue.

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.

This is not sufficient information to determine if this is actually a Homebrew bug, rather than e.g. LLVM's build system interacting poorly with having multiple macOS SDKs installed on Catalina with Xcode 12.
