### ISSUE TITLE
tensorflow is broken

### ISSUE THREAD

**Issue by kikaxa** [Homebrew/homebrew-core#66254]
- [x ] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- x[ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
use tensorflow

## What happened (include command output)
there is no tf

## Step-by-step reproduction instructions (by running `brew install` commands)
brew install python opencv
python3 --version
Python 3.9.0
pip3 install tensorflow
//opencv is used in python+tensorflow - not found/mismatched

Guys, i know, everyone loves bleeding edge stuff,  please tell me do you follow any release process?
Every time you update to some bleeding new version like python or opencv, something breaks until new release.
In this case tensorflow is impossible to install for 3 FULL MONTH or even longer.

--
I can downgrade python, thankfully - but i cant downgrade opencv or dozen other taps.

Is there anything you can do to improve this (recurring) situation? 
Is there anything users can do to use tensorflow?

**Comment by bayandin** [comment]
Use can use python from `python@3.8` formula and build `opencv` for it. Also use [`brew pin`](https://docs.brew.sh/FAQ#how-do-i-stop-certain-formulae-from-being-updated) to prevent formula to be updated.

An issue you're really facing is https://github.com/tensorflow/tensorflow/issues/44485.

Please always fill the template.

**Comment by kikaxa** [comment]
Thanks. Are there any guides how to build a formula for another formula?

**Comment by kikaxa** [comment]
The thing is, you don't know something is going to break until its too late.

**Comment by carlocab** [comment]
You don't need to build a formula. You just need to use `python@3.8` to build opencv. Check opencv's documentation for how to build it. They may have a pre-built package that works with Python3.8.

Alternatively, you can try the following (no guarantee it will work):
1. [create a tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap)
2. do `brew extract` on `opencv`
3. modify the `opencv` formula created in your tap by changing all the references to `python@3.9` back to `python@3.9`.

If you're lucky, doing `brew install` with your modified `opencv` formula will just work. If not, have a look at the build logs and fix the errors. You can also do `brew install -v` so that you see the output of the build process. This will also show you the errors without having to dig up the build logs (which will typically be at `~/Library/Logs/Homebrew`).

**Comment by kikaxa** [comment]
Thanks for the detailed workaround options.
What if i revert to earlier known good brew snapshot, install what i need and pin only these two formulas, will this keep all the dependencies pinned as well when installing/upgrading other formulas that depend on any of this dependencies in the future?

**Comment by carlocab** [comment]
It might. It might not. Even if you could get it to work initially, that set up is fragile and prone to subtle and vexing breakages over time. This is why Homebrew offers you the option of maintaining your own tap. Even if it's more involved, it's far less likely to break on you in ways that are unexpected and difficult to diagnose.
