### ISSUE TITLE
brew upgrade fails - error in dnsmasq on OSX 10.12.1

### ISSUE THREAD

**Issue by robinbowes** [Homebrew/homebrew-core#6677]
Pertinent error msg:

```
  brew upgrade
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/dnsmasq.rb:6:in `<class:Dnsmasq>'
```

Full traceback in gist.

`brew upgrade` output: https://gist.github.com/f0d0ff275273eccdbbe511367af32163

`brew config` https://gist.github.com/a435db00b99c30b060d3a6d6c2ac3912

`brew doctor` https://gist.github.com/cdace673ae75a028b464af836216ad09

**Comment by MikeMcQuaid** [comment]
This formula needs to be updated. It will have been printing a warning message for a long time.

**Comment by MikeMcQuaid** [comment]
To be clearer: this formula needs to be updated in Boxen rather than homebrew-core.

**Comment by robinbowes** [comment]
Did you specify in advance a date when you were going to remove this?

Did you bump homebrew major version number to reflect this change to the public API?

**Comment by MikeMcQuaid** [comment]
> Did you specify in advance a date when you were going to remove this?

No, we don't always specify dates but it's been deprecated since 20th March and printing messages since 16th July.

> Did you bump homebrew major version number to reflect this change to the public API?

You (and/or Boxen) are using the Homebrew `master` branch rather than tags. We haven't released 1.1.0 yet (it'll likely be later today) so `stable` users won't get this change until then.

**Comment by robinbowes** [comment]
> No, we don't always specify dates but it's been deprecated since 20th March and printing messages since 16th July.

You should specify a date for such disruptive changes, eg. "Formula.sha1 is deprecated and will be removed on November 6, 2016. Please update your recipes to use SHA256."

> We haven't released 1.1.0 yet (it'll likely be later today) 

This is a major, public-API-breaking change, so should be 2.0.0.

**Comment by MikeMcQuaid** [comment]
> You should specify a date for such disruptive changes, eg. "Formula.sha1 is deprecated and will be removed on November 6, 2016. Please update your recipes to use SHA256."

No, sorry. If this was paid software and I had a full-time team who were able to commit to these dates I'd agree. There's been a message printed out for months that hasn't been fixed in Boxen so the onus is not on us.

> This is a major, public-API-breaking change, so should be 2.0.0.

I disagree. It's making a previously announced deprecation into an error. That's not unheard of for minor releases. We'll save 2.0.0 for e.g. a new Formula DSL that requires _all_ formulae to be rewritten (which will likely never happen).

**Comment by robinbowes** [comment]
I'm not sure what being paid has to do with it? This is simple good practise for any/all software projects.

Regarding versioning, I suggest you review http://semver.org/ - specifically http://semver.org/#spec-item-8

**Comment by MikeMcQuaid** [comment]
> I'm not sure what being paid has to do with it?

I'm unable to commit to a date to perform a task in Homebrew 6 months in advance when I may be e.g. on holiday.

> Regarding versioning, I suggest you review http://semver.org/ - specifically http://semver.org/#spec-item-8

I'm aware of it. In this case, we'll agree to disagree on the version number.

**Comment by rnelson0** [comment]
You're not disagreeing with robinbowes, you're disagreeing with everyone who sees a semver-like version and has expectation that once you hit 1.0.0, major, non-backwards compatible changes do NOT happen in minor versions. Is there a reason you want to hoard major version numbers? You can use 3.0.0 or 4.0.0 or whatever when the new Formula DSL happens. It costs nothing to create a new major but costs a lot to put backwards incompatible changes in minor versions.

**Comment by MikeMcQuaid** [comment]
> You're not disagreeing with robinbowes, you're disagreeing with everyone who sees a semver-like version and has expectation that once you hit 1.0.0, major, non-backwards compatible changes do NOT happen in minor versions.

No, I'm disagreeing on the interpretation of that document (and disagreeing with that document as the formal definition of semantic versioning). To further justify my reasoning for why this is a minor not major change:

- This deprecation was announced and these methods removed/undocumented before 1.0.0 was tagged so arguably it was not part of the public API when 1.0.0 shipped.
- We have four levels of public API deprecation: 

1. a method is deprecated silently and moved to `compat`
2. a method is deprecated and starts warning people
3. a method is deprecated and fails at runtime but still allows the formula to be considered valid
4. a method is removed entirely and formulae using it will fail with a "method missing" or similar error. 

You both argue that a move from 2) to 3) is a major, breaking change. I disagree; I consider 3) to 4) to be a major, breaking change and I'd rather save major version bumps for cases like that (i.e. previous formulae that parsed will no longer parse). You could take the position that every `brew audit` change is a major, breaking change and then our version numbers will increase even more often. Ultimately, it's up to Homebrew how we perform our versioning.

> Is there a reason you want to hoard major version numbers? You can use 3.0.0 or 4.0.0 or whatever when the new Formula DSL happens. It costs nothing to create a new major but costs a lot to put backwards incompatible changes in minor versions.

Given `brew update` does not allow you to stay on a given major or minor version and all our taps are untagged I think whether this is 1.0.10, 1.1.0 or 2.0.0 is ultimately just a cosmetic matter. In this case I think there's a certain amount of backlash because people have been ignoring deprecation warnings for months and then when they are enforced they have to do work now that they've been delaying.

**Comment by robinbowes** [comment]
If you had removed this before 1.0.0 shipped then no problem - anything goes before 1.0.0. However, post-1.0.0, you are removing a previously supported method, ie. introducing a backwards incompatible change to the public API, which "MUST" result in a major version increment. 

> people have been ignoring deprecation warnings for months...

...because there was no formal removal date.

> ... and then when they are enforced they have to do work now that they've been delaying...

...because everything broke unexpectedly, because you did this on a whim, and didn't announce a formal removal date.

Sure, it's up to you how you do things, but don't be surprised if you get a backlash if you fly in the face of convention.

**Comment by ilovezfs** [comment]
@robinbowes has this personally caused you some sort of harm we should be made aware of?

**Comment by robinbowes** [comment]
> ..because everything broke unexpectedly, because you did this on a whim, and didn't announce a formal removal date.

**Comment by ilovezfs** [comment]
You do realize this is a one line change from something like this

```
  sha1 "14fa203500c8b14a7f620e89edd710e3bda6b549"
```
to something like this
```
  sha256 "51d93a29349332cafc78c67a0a262f68c97121595a2d4e4a798cf80e4ba08985"
```
right?

**Comment by robinbowes** [comment]
I do now, yes, but that is not the point.

**Comment by MikeMcQuaid** [comment]
> anything goes before 1.0.0

Again: it was deprecated and not a publicly documented API at 1.0.0.

> which "MUST" result in a major version increment.

According to that document and your interpretation of it, neither of which are binding. Furthermore, you opened this issue before the tag.

> ...because there was no formal removal date.

If you choose to ignore deprecation warnings because they have no dates attached to them then that's your fault not ours, I'm afraid. In this case had you done a little research you'd have seen that this is deprecated because SHA-1 has been broken in multiple ways as a checksum format so it's insecure and needs to be replaced in Homebrew.

Again: we won't announce dates because we can't commit to them as an understaffed, volunteer run project.

> ...because everything broke unexpectedly

Formulae from unofficial taps (and a project that wraps Homebrew rather than Homebrew itself) have been printing deprecations for months no longer allow you to install them without a trivial fix.

> because you did this on a whim

I did this because I was shipping other changes that were breaking so it made sense to clump them together.

> and didn't announce a formal removal date.

And again: we won't announce dates because we can't commit to them as an understaffed, volunteer run project.

> Your change caused my homebrew install to break unexpectedly

Alternatively: your ignoring of deprecation notices for months broke some unofficial formulae when Homebrew was updated. 

> and caused me to have to spend time investigating why it was broken and applying a fix.

This is time you always needed to spend and you're annoyed that it's now. I'd like to suggest that you should have not ignored these warnings for so long.

**Comment by robinbowes** [comment]
> I did this because I was shipping other changes that were breaking so it made sense to clump them together.

All without a major version bump? Breath-taking.

I'm done here.

**Comment by MikeMcQuaid** [comment]
> All without a major version bump? Breath-taking.

With respect, I'll not tell you how to run your open-source projects and you don't tell us how to run ours.

It seems what you want that's actually achievable in future is mainly to announce deprecation dates in advance which we aren't able or willing to do.

**Comment by MikeMcQuaid** [comment]
As this issue is getting some traffic: quoting @bfontaine from https://github.com/Homebrew/homebrew-core/issues/6693#issuecomment-258965843:

> The use of `sha1` was deprecated almost two years ago.
> 
> 1. In [February 2015](https://github.com/Homebrew/brew/commit/12861686b847f26f50af7d9a9024a0bc4d25b3bd) `brew audit --strict` started to show a warning and we updated all docs to advise not to use `sha1`.
> 2. In [June 2015](https://github.com/Homebrew/brew/commit/4f74e89) `brew audit` started to show the warning even without `--strict`.
> 3. In [March 2016](https://github.com/Homebrew/brew/commit/bd7e8543b3fba04a914f8f8c583652d6970d51db) `brew` started complaining about `sha1` in formulae.
> 4. We completely disabled it [yesterday](https://github.com/Homebrew/brew/commit/fcaa48d80b0c2989ca95528def6d0c8fbd65aa79).
