### ISSUE TITLE
[ansible] New python dependency needs --with-custom-python option like vim

### ISSUE THREAD

**Issue by claco** [Homebrew/homebrew-core#6728]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Now that the ansible formula has a dependency on homebrew python, any `brew upgrade ansible`, the only way to use your own python is to use `--build-from-source`. However, when a new version ansible is released, `brew upgrade ansible` will happily ignore the `--build-from-source` option, and instead try to download and install it's own python, which in the surface is undesired, and is by design in homebrew. `brew upgrade` will remember install options.

```
 → ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides

 → brew upgrade ansible
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
ansible 2.2.0.0_1
==> Upgrading ansible
==> Installing dependencies for ansible: sqlite, python, openssl@1.1
==> Installing ansible dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.15.1.el_capitan.bottle.tar.gz
^
```

This is the exact problem vim had, and so they added `--with-custom-python`, which `brew upgrade` does remember when new versions come out.  https://github.com/Homebrew/homebrew-core/issues/2767

https://github.com/Homebrew/homebrew-core/pull/5042#issuecomment-259161872

As a side effect, one has to drop, then reinstall ansible every time to use a custom python. IF you're using system automation (homebrew module in ansible ironically), or other package managers, you can't just simple ensure the latest is installed. Now you have to uninstall, reinstall to use the --build-from-source option.

https://gist.github.com/anonymous/c14962e724a329382699051ea56d69a1

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

Please add `--with-custom-python`, which was one of the options mentioned in the original evolution proposal iirc.

**Comment by MikeMcQuaid** [comment]
If you're using your own Python: why not `pip install ansible`?

**Comment by MikeMcQuaid** [comment]
Personally I'd rather we move away from supporting "use any Python you want" on packages, particularly those that are installable in other ways.

**Comment by claco** [comment]
@MikeMcQuaid Because that means sudo. I just want it to use system python, like it always has, ssl issues and all.

But aside from that, the problem remains. I've been giving a mechanism at install time that is not honored at upgrade time. That's more of the problem imo.

**Comment by MikeMcQuaid** [comment]
@claco It doesn't. `pip install --user ansible` will install into your home directory.

**Comment by claco** [comment]
Yes, but that defeats the purpose of using Homebrew itself. Again, for me, it that install and upgrade aren't congruent with options.

And when n% of forumles mean I have to pip install --user instead? What's the point of homebrew again?

**Comment by MikeMcQuaid** [comment]
Why do you need to use the system Python, out of interest?

**Comment by MikeMcQuaid** [comment]
> As time goes on, it's going to make brew installing things an unpredictable mess.

Also, it's the opposite: it's going to make installing things a lot more predictable because it's not randomly picking whatever `python` happens to be lying around. There's valid gripes with this approach but predictability is not one of them.

**Comment by claco** [comment]
Because as of 2 versions ago, brew install ansible used system python. Now it doesn't after brew upgrade.

Again, we keep focusing on why or why not I want to or should be, which isn't the issue. The issue is that 1) it's broken existing installs potentially, and 2) the workaround for those who wish to use whatever python they want, is not honored during brew upgrade. 

At the very least, a deprecation cycle, and a --with-custom-python would have been a nice practice.

I'm kicking a fresh system tonight, and I'm happy to now let the python dependency roll in. And if I brew install pyenv over top, what is 'system' python again?

**Comment by claco** [comment]
And for the other twist on this:  https://github.com/Homebrew/legacy-homebrew/issues/50424

**Comment by ilovezfs** [comment]
@claco no, that was fixed when the formula adopted the new virtualenv feature.

**Comment by claco** [comment]
@ilovezfs Good to know. Thanks!

**Comment by sigmavirus24** [comment]
So, a *real* reason to use System python on OSX (via brew) is that you may be installing ansible for use inside a laptop with a corporate image that has the corporate trust roots in it. System python uses the OSX trust store for certificates and will pull those out for validation (even if you provide your own certificate file, e.g., certifi). That means that if your ansible needs to validate certificates against your corporate trust chain, you now have to make your own cert bundle and include those certificates and inform ansible as to where to find that. That's far more work than was ever required before.

I get the argument for using brew's Python, but there are also valid reasons for not using it.

**Comment by ilovezfs** [comment]
I don't see why brew's python can't (or isn't already able) to use the OS X trust store. CC @tdsmith

**Comment by sigmavirus24** [comment]
@ilovezfs in my experience, people installing brew's python are also installing brew's openssl. At that point, brew's python relies on brew's openssl and you've lost the magical features of the OS X trust store

**Comment by ilovezfs** [comment]
Yes, brew's python depends on brew's openssl, but that pushes the question over to why the openssl formula cannot use the system trust store.

**Comment by sigmavirus24** [comment]
I'm not sure that it *can't* but it absolutely doesn't by default. Keep in mind, Apple is also deprecating their openssl 0.9.8 shim code and integrating with it is not something stable software like openssl would be able to keep up with.

**Comment by ilovezfs** [comment]
@sigmavirus24 will `pip install ansible` work with that use case?

**Comment by MikeMcQuaid** [comment]
> Because as of 2 versions ago, brew install ansible used system python. Now it doesn't after brew upgrade.
> 
> Again, we keep focusing on why or why not I want to or should be, which isn't the issue.

It is the issue because I'd like to understand why you'd be unhappy with e.g. every formula that uses Python using the Homebrew Python.

> The issue is that 1) it's broken existing installs potentially

We have enough actual bugs to fix that I'd rather not get side-tracked onto speculative ones.

> 2) the workaround for those who wish to use whatever python they want, is not honored during brew upgrade.
>
> At the very least, a deprecation cycle, and a --with-custom-python would have been a nice practice.

Again though: why do you want/need your Ansible to use the system Python?

**Comment by MikeMcQuaid** [comment]
> So, a real reason to use System python on OSX (via brew) is that you may be installing ansible for use inside a laptop with a corporate image that has the corporate trust roots in it.

@sigmavirus24 Thanks for elaborating, that's really helpful and, like @ilovezfs, I think that's something we could work on fixing.

**Comment by sigmavirus24** [comment]
@ilovezfs with the use case that you haven't installed brew python or ansible? I'm honestly not sure. Ansible recently started depending on cryptography. Cryptography has wheels which statically link to the latest known-secure versions of openssl. If they're also using cryptography for certificate verification that may be a moot point.

As for another reason why one might not want to automagically override an Apple provided Python installation, if someone has already installed a bunch of python software, it doesn't carry over to the brew installed Python version (if I remember correctly).

One other, more future looking reason, is that Ansible (prior to the purchase by Red Hat, and especially now after that purchase) has always been focused on customers with versions of Python that are very old (2.4 being the oldest version they *still* support to the best of my knowledge). For this reason they are very vocally resistant to ever adding Python 3 support. In 2020 when Python 2.7 is no longer supported, I'd expect Homebrew and Apple to change /usr/local/bin/python to be Python 3. If we then `brew install ansible`, we will likely end up with severely broken software unless we're very careful.

**Comment by tdsmith** [comment]
I have some opinions to share but I'm running a polling place today; I'll
comment after the election :)

**Comment by zmwangx** [comment]
> As for another reason why one might not want to automagically override an Apple provided Python installation, if someone has already installed a bunch of python software, it doesn't carry over to the brew installed Python version (if I remember correctly).

Unlike, say, Debian's default repository (with various `python-*` and `python3-` packages and the `dist-packages` structure which I always find annoying), homebrew/core is no pip replacement. If you need to import a Python module, use pip (preferably in a virtualenv). Our current approach to Python-based software in core (note that only standalone software is allowed) is to separate them as much as possible — each Python-based formula is in a separate virtualenv. `brew install` should not write to `/usr/local/lib/pythonx.y/site-packages/` in most cases.

> In 2020...

That's too much of a stretch. Of course something will be figured out by then if necessary.

**Comment by zmwangx** [comment]
> if someone has already installed a bunch of python software, it doesn't carry over to the brew installed Python version

If you actually need to access modules in `/usr/lib/python2.7/site-packages` from brewed Python, just set `PYTHONPATH`. I'm sure you already know that, though.

**Comment by sigmavirus24** [comment]
> I'm sure you already know that, though.

I do know that. I'm one person. To debug that would not be trivial even for me though. I wouldn't expect brew to automagically install Python for me in that case. And discovering that it had and that I had to fudge with something that I didn't have to for the last few years of using homebrew would be frustrating.

> That's too much of a stretch. Of course something will be figured out by then if necessary.

Yes, let's just kick that can down the road. And no, "just use pip" is not a suitable way to duck responsibility for people who don't know the differences between versions of Python and just want to use some software.

**Comment by zmwangx** [comment]
> To debug that would not be trivial even for me though. 

What's there to debug? If your Python-based software was properly installed, it should continue to use `/usr/bin/python` and work fine. If it has a `/usr/bin/env python` shebang, too bad, you need to either change that or re-satisfy dependencies. Which is simply part of the process of manually installing software.

> I wouldn't expect brew to automagically install Python for me in that case.

Your expectation is off then I'm afraid. Most package managers happen to install their own copy of things rather than pick up things you installed from other channels, especially when [other channels may have problems](https://github.com/Homebrew/brew-evolution/pull/12).

> Yes, let's just kick that can down the road.

What's being kicked down the road? Homebrew currently supports macOS up to 10.12, with `/usr/bin/python` being 2.7 and no `/usr/bin/python3`. Why do you expect current code to work with 10.16 or later?

> "just use pip" is not a suitable way to duck responsibility for people who don't know the differences between versions of Python and just want to use some software.

People who "just want to use ansible" (or whatever Python-based software from homebrew/core) should be served just fine. For people who declare themselves Python developers by importing ansible, or whatever other module or package, yes, they are actually responsible for knowing how to use pip and knowing the differences between versions of Python.

**Comment by sigmavirus24** [comment]
> What's there to debug?

Why does `python -m <application>` stop working? That's exactly what breaks. Yes a lot of people will use the convenience wrappers in their path, but when you have multiple versions of software installed for different versions of python, knowing `python -m` means that you'll always get the right version.

> Your expectation is off then I'm afraid. Most package managers happen to install their own copy of things rather than pick up things you installed from other channels.

My expectation was set by Homebrew. Homebrew broke that expectation.

> Why do you expect current code to work with 10.16 or later?

Your attempts at false equivalencies are funny. Really. It's not the current code I expect to work, it's the backwards approach to packaging things without regard to users expectations.

I have 0 particular love for system Python on Macs. On personal machines I tend to use it instead of System python for a variety of reasons. I still don't support this change that came without warning. The very least homebrew could have done was detect that a prior version was installed against System Python and provided a warning if being run with an interactive terminal.

**Comment by nickwph** [comment]
I am having the same issue that `Ansible` is using the macOS built-in `python` instead of the current `python` installed with `homebrew`. It caused an error on my machine when i tried to run a playbook.

The built-in `python` didn't install `lxml` so it crashed.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named lxml
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/w7/s3c0vq0130g9htn2_rny49p9hz4dh3/T/ansible_dNQWMv/ansible_module_maven_artifact.py\", line 24, in <module>\n    from lxml import etree\nImportError: No module named lxml\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by zmwangx** [comment]
> Why does python -m <application> stop working?

I don't have much experience dealing with users of Python-based software, but I doubt many run applications with `python -m`, which is at the very least very cumbersome. setuptools support console scripts that don't exhibit your problem, and I've yet to encounter a reasonably popular Python project with setuptools support that doesn't take advantage of that.

> when you have multiple versions of software installed for different versions of python

A clueless user won't have a setup like that. Such a user already knows how to find out the Python they're using, and use an absolute path if necessary; otherwise they wouldn't be able to select one of the installed versions in the first place. Moot point.

> My expectation was set by Homebrew. Homebrew broke that expectation.

There was never a promise that Homebrew would never automatically install Python 2.7, as far as I could tell. "Homebrew broke my expectation" can be said about every slightest change. Not a very strong argument.

> Your attempts at false equivalencies are funny. Really. It's not the current code I expect to work, it's the backwards approach to packaging things without regard to users expectations.

Thanks for the attempt to confuse. "Backwards approach to packaging things without regard to users expectations" — that's a different argument which has been addressed above, and what might happen in 2020 has absolutely nothing to do with it. It isn't hard to realize the current `python.rb` and `python3.rb` won't work when Python 3 becomes the default, whenever that happens; and when it does happen, the Python formulae will be adjusted, maybe to `python.rb` and `python2.rb`. "False equivalence"? There was no equivalence, I was simply stating a fact. "If we then `brew install ansible`, we will likely end up with severely broken software unless we're very careful." No. Period.

**Comment by nickwph** [comment]
@claco @MikeMcQuaid i tried `pip install --user ansible` and it's showing the same error.

**Comment by zmwangx** [comment]
> Backwards approach to packaging things without regard to users expectations

Not to mention if we follow your train of thought, when Python 3 becomes the default, and when Python 2.7 is finally dropped, to keep up with your "expectation" we'll need to suddenly stop depending on brewed Python 3, and suddenly make brewed Python 2.7 mandatory. You can still claim expectation broken in that case. Might as well depend on brewed Python 2.7/3 unconditionally to set the right expectations and make future transitions smoother.

**Comment by tdsmith** [comment]
The philosophy I've adopted with respect to Homebrew's packaging of Python applications is:

* Installing the application should not affect the system's global Python environment.
* The global Python environment should not change the function of applications installed with Homebrew.

I consider it a feature that packages installed to any other environment do not affect ansible's behavior or capabilities. If your expectations are incompatible with that design goal, my opinion is that you should not use Homebrew to install your application.

It is interesting that system Python has different behavior with respect to trust stores than any other Python and it is unfortunate that it is difficult to obtain that behavior otherwise but I do not think that changes the calculus that a networking stack that includes openssl 0.9.8 is inappropriate for the modern internet. I do not expect that Homebrew's python will attain the same behavior; those changes would need to be adopted by cpython and it seems especially unlikely that those changes will appear on the 2.7 branch. ;¯\\\_(ツ)\_/¯

If it is really necessary for individual consumers to extend ansible's functionality by installing additional packages, I think it is feasible to create a persistent e.g. `var/ansible/site-packages` that people can manually `pip install --target` into. So far, nobody's said this would be useful.

I don't understand how ansible's support matrix is relevant to which distribution of python 2.7 is used to execute ansible.

@sigmavirus24, I respect your judgement but I'm not sure I understand what you would like us to do differently. Ansible switched to virtualenv encapsulation several weeks ago; why is this an issue now? Can you elaborate on the expectation that you felt that we created and then violated?

**Comment by MikeMcQuaid** [comment]
> Yes, let's just kick that can down the road. And no, "just use pip" is not a suitable way to duck responsibility for people who don't know the differences between versions of Python and just want to use some software.

@sigmavirus24 Please help us figure it out. We're not intentionally kicking any can down the road, we're going on the information we have and without detailed reproduction instructions on issues it's very hard to make fixes.

**Comment by tdsmith** [comment]
Looking at the earlier discussion, I agree that we have poor UX in the case that someone wishes to maintain an installation of a Python application and does not wish to install Homebrew's python distribution.

There are some weird edge cases with the `--with-custom-python` option, e.g.: https://github.com/Homebrew/homebrew-core/issues/3938

One potentially tractable solution would to be for the `Virtualenv` module to add a no-op `with-custom-python` option on the Formula class it's mixed in to, much as we currently add a virtualenv resource.

**Comment by tdsmith** [comment]
— Or we should stop pretending that the build-from-source behavior is a useful way to solve this problem, add explicit `"python"` dependencies, and declare that we don't support using distributions other than Homebrew's for applications, which I think is Mike's preference.

**Comment by tdsmith** [comment]
cf https://github.com/Homebrew/brew/pull/1471

**Comment by tuzla0autopilot4** [comment]
I'm unclear what the status of this issue is. I have had ansible installed for quite a while. `ansible --version` is 2.1.2.0. I've been trying to upgrade it since this issue was opened. I've tried brew update and upgrade and --build-from-source and doctor and I forget what all else, but I'm unclear on what magical combination will allow me to upgrade ansible. This is the only package of about 100 installed that is failing to upgrade. I know I can create my own virtualenv and pip install ansible myself, but I'd like to use the (upgraded) homebrew package.

**Comment by tdsmith** [comment]
Please open a new issue with the result of `brew gist-logs ansible` if you're having trouble upgrading ansible; this ticket does not address any issues that should prevent an ansible upgrade from succeeding.

**Comment by tracyone** [comment]
```
brew install vim --HEAD --with-override-system-vi --with-lua

if_python.c:67:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
make[1]: *** [objects/if_python.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
[ansible] New python dependency needs --with-custom-python option like vim https://github.com/Homebrew/homebrew-core/issues/6728

```

**Comment by tdsmith** [comment]
I have no plans to advance this proposal further.
