### ISSUE TITLE
Zile formula is shipping a beta version but marking it as stable

### ISSUE THREAD

**Issue by rrthomas** [Homebrew/homebrew-core#67379]
# Bug report

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

https://formulae.brew.sh/formula/zile

Lists the current version as "stable", and "2.6.0.90". But 2.6.0.90 is a beta release. See:

https://mail.gnu.org/archive/html/bug-zile/2020-12/msg00000.html

It is clearly marked as a beta.

Please downgrade to 2.4.15.

I am the upstream maintainer of Zile. Thanks for packaging Zile!

**Comment by carlocab** [comment]
Thanks for the report. 

I was the one who updated Zile to 2.6.0.90, but I don't subscribe to your mailing list. Currently, the only way we can tell if Zile is outdated is by checking https://ftp.gnu.org/gnu/zile/, and it's not at all clearly marked as beta there, nor is it identified as a beta on your homepage.

Is it possible for you to identify beta releases more clearly on those sources? A download URL that says `-beta.tar.gz` would be ideal. This way tools we have for automating the checking of newer versions (`brew livecheck`) work properly.

**Comment by rrthomas** [comment]
Thanks for getting back to me, @carlocab. The release type is clearly marked in `NEWS`. I think what I should probably do is copy Emacs, mark these releases as "alpha", and then they will be uploaded to `alpha.gnu.org` and your automatic check won't find them. Does that sound OK?

**Comment by rrthomas** [comment]
(I think the reason I've not had this problem before is precisely because when I made some previous prereleases in 2011 I marked them alpha.)

**Comment by carlocab** [comment]
Do you mean `NEWS` in your tarball? That's unlikely to be looked at when it's updated on Homebrew, unfortunately. It's also not easy to automate checking a `NEWS` file for updates, for very many reasons -- but I'm sure you already know that.

Any solution that doesn't have pre-releases available at https://ftp.gnu.org/gnu/zile/ should work. Or, if you prefer to make them available there, then it would help if they indicated that they were a pre-release right next to the version.

Otherwise, I'm afraid we may run into this issue again, as I'm not sure how to fix `brew livecheck` so it doesn't pick up your pre-releases. (Though someone more creative than me may wish to take a crack at it.)

Also, I've opened a PR to revert the version bump back to your stable release: https://github.com/Homebrew/homebrew-core/pull/67380

**Comment by rrthomas** [comment]
`NEWS` in tarball, exactly. It has a strict format, so it's easy to check. I agree though that the GNU packaging standards in this regard don't make things easy for automated systems. I could add "beta" to the version and hence tarball name, but I'd rather not do things differently from Emacs, which seems simply never to mark releases as "beta", and sticks to purely numeric versions.

Thanks for the PR!

**Comment by carlocab** [comment]
Do you know how closely GNU software comply with standards on the `NEWS` file? i.e. do most of them have it, and follow the requirements regarding machine-readability of the version line?

If most do it might be worth looking into incorporating a check into some of the `brew` automation.

**Comment by carlocab** [comment]
That's unfortunate. I'm afraid we'll probably run into this issue again at some point. I'll make a mental note to check the `NEWS` file in your tarball if I ever update it again. However, anyone is free to open a PR to update any package here, and maintainers may forget to check whether Zile is a pre-release in the `NEWS` file.

If/when that happens, feel free to open a PR just like the one I did.

**Comment by carlocab** [comment]
Actually, maybe there is a simpler way to do this. Is there a stable URL where your releases are announced?

**Comment by Rylan12** [comment]
@rrthomas we've reverted back to the stable version.

Because it's impossible for us to tell whether a new version is stable to not without a maintainer manually inspecting the tarball, we've removed the ability to automatically detect new versions. This means that maintainers are less likely to update `zile` in the future because it won't be automated. Of course, any user is encouraged to open a PR to update `zile` when new stable versions are released. If you have a website that lists the latest stable version, we can use that to re-enable this.

**Comment by rrthomas** [comment]
@carlocab, @Rylan12, as I said above, I will only make stable releases via ftp.gnu.org in future, so you can use the same auto-detection you used before: if there's a new release `pub/gnu/zile`, it's a stable release. All other releases will go to `alpha.gnu.org`.

**Comment by rrthomas** [comment]
@Rylan12: thanks for the reversion! Although shipping the beta did get me my first and so far only bug report!

**Comment by carlocab** [comment]
>I will only make stable releases via ftp.gnu.org in future

Great! Apologies for the misunderstanding. I'll open a PR to re-enable auto-detection.

**Comment by carlocab** [comment]
Wait, having checked https://ftp.gnu.org/gnu/zile/, it seems your bug-fix patch appears to still have made it there.

I'm reluctant to re-enable it for now as someone might take it as a signal to upgrade Homebrew's version to 2.0.91. I'll keep an eye on Zile and re-enable it when 2.0.91 is stable. Feel free to also ping me here (or open a PR yourself) if I forget.

Do you have a rough timeline for when you were planning to do this?

**Comment by rrthomas** [comment]
Thanks for letting me know, clearly a bug in my release procedure, I'll look into it.

**Comment by rrthomas** [comment]
I have fixed the release procedure and removed the incorrectly-released files, so you should be able to resume automatic updates of Zile.

**Comment by carlocab** [comment]
I've opened a PR to re-enable that functionality.

Thanks again for working with us on this one!

**Comment by rrthomas** [comment]
@carlocab, a pleasure, I got two bug fixes out of it, so thank YOU!

**Comment by carlocab** [comment]
Glad something good came out of it then. Please extend my apologies to those who reported bugs for shipping them a pre-release under the guise of a stable version.

**Comment by rrthomas** [comment]
@carlocab, done!

**Comment by Rylan12** [comment]
Thanks, @rrthomas and @carlocab! Glad we got this resolved!
