### ISSUE TITLE
`brew install libmongoc`: Error: The `brew link` step did not complete successfully

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#7291]
```
==> Pouring libmongoc-1.4.2.el_capitan.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /Users/timothee/homebrew
Could not symlink include/libbson-1.0/bcon.h
Target /Users/timothee/homebrew/include/libbson-1.0/bcon.h
is a symlink belonging to libbson. You can unlink it:
  brew unlink libbson

To force the link and overwrite all conflicting files:
  brew link --overwrite libmongoc

To list all files that would be deleted:
  brew link --overwrite --dry-run libmongoc

Possible conflicting files are:
/Users/timothee/homebrew/include/libbson-1.0/bcon.h -> /Users/timothee/homebrew/Cellar/libbson/1.4.0/include/libbson-1.0/bcon.h
/Users/timothee/homebrew/include/libbson-1.0/bson-atomic.h -> /Users/timothee/homebrew/Cellar/libbson/1.4.0/include/libbson-1.0/bson-atomic.h
/Users/timothee/homebrew/include/libbson-1.0/bson-clock.h -> /Users/timothee/homebrew/Cellar/libbson/1.4.0/include/libbson-1.0/bson-clock.h

```

```
brew upgrade libbson
Error: libbson 1.4.0 already installed
```

```
brew gist-logs libmongoc
Error: No logs. 
```
(the `no logs` may be caused by https://github.com/Homebrew/legacy-homebrew/issues/44706 Unable to do `brew gist-logs` for certain formulas)

**Comment by timkuijsten** [comment]
Fixed, as in the error should be nicer:

$ brew install libmongoc
Error: Cannot install libmongoc because conflicting formulae are installed.

  libbson: because libmongoc comes with a bundled libbson

Please `brew unlink libbson` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

**Comment by MikeMcQuaid** [comment]
Will be fixed in https://github.com/Homebrew/homebrew-core/pull/7352.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-core/pull/7352 was merged so this is addressed now.
