### ISSUE TITLE
Bottled gopass contains unnecessary binaries

### ISSUE THREAD

**Issue by arren-ru** [Homebrew/homebrew-core#73243]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

[brew config and gopass cellar tree](https://gist.github.com/arren-ru/3cce956b077a6c420afd18579dfa5a3c)
No logs, brew doctor complains about unlinked gopass (which I had to do to get man working)

### 

- [x] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Trying to Install gopass, but it also install release helper binaries which included into bottled archive (checked by manually downloading and looking inside).

### What happened (include all command output)?

Brew installs unnecessary binaries, where one of them covers man command.
As a result man command does not work and points to unknown man binary which belongs to Cellar/.../gopass/bin path.

### What did you expect to happen?

Only gopass binary installed

### Step-by-step reproduction instructions (by running `brew` commands)

```sh
brew update
brew install gopass
```

**Comment by carlocab** [comment]
Thanks for the report. That's very strange. It seems to have happened sometime between 1.11 and 1.12.

These are the contents of `bin` for 1.11:
```
Permissions Size User     Date Modified Name
.r-xr-xr-x   17M carlocab 12 Jan 12:05  gopass
.r-xr-xr-x   14M carlocab 12 Jan 12:05  gopass-git-credentials
.r-xr-xr-x   14M carlocab 12 Jan 12:05  gopass-hibp
.r-xr-xr-x   15M carlocab 12 Jan 12:05  gopass-jsonapi
.r-xr-xr-x   14M carlocab 12 Jan 12:05  gopass-summon-provider
```
For 1.12, however:
```
Permissions Size User     Date Modified Name
.r-xr-xr-x  1.6M carlocab 11 Feb 14:18  changelog
.r-xr-xr-x   14M carlocab 11 Feb 14:18  gopass
.r-xr-xr-x  3.1M carlocab 11 Feb 14:18  release
```
I guess no one caught it until it started shadowing `man`.

**Comment by dominikschulz** [comment]
`gopass` used to ship different binaries but decided to split them off to separate repositories. That's why the `go install ./...` did work in the past - it would just install all binaries.

Later on we have added some release tooling helpers which are not supposed to be used on it's own. They are not useful to anyone using the formula. The formula should really only install the main `gopass` binary - nothing else.

I'm not very familiar with homebrew formulas, but our [own](https://github.com/gopasspw/homebrew-gopass/blob/master/gopass.rb#L42) should be correct and can be used as an inspiration.

We were not aware that there was a `gopass` formula in homebrew-core (we're either building from source or using our formula). Otherwise we would have reached out proactively.

**Comment by carlocab** [comment]
Well, someone at gopass knew there was a formula in homebrew/core: https://github.com/gopasspw/gopass/blob/master/docs/setup.md#macos-1

Either that or whoever wrote that line didn't understand how taps worked.

I'll try to adapt what you're doing in your tap, but I haven't yet since we're trying to stop using `GOPATH` in homebrew/core now.

**Comment by dominikschulz** [comment]
Hmm, we used to have the step to add our custom formula in there. But I can't find the commit removing it right now.

I'm not sure I can follow the part about `GOPATH`.

Is running `make install` not acceptable?
Or just run `go install` without the `./...`?

Is there anything we can do to accomodate your requirements better?

**Comment by SMillerDev** [comment]
`GOPATH` usage is deprecated in go itself so we're trying to get rid of it in homebrew core. If we can just run make commands that's a good alternative.

**Comment by carlocab** [comment]
Opened #73247. Couldn't use `make`; it lead to a build error while (I believe) building the completions. (At least, the error message said something about completions.)

**Comment by carlocab** [comment]
Oh, and this is the commit you're looking for: https://github.com/gopasspw/gopass/commit/311c0d8b4500b42ad0496e486e2f416857d43586

**Comment by AnomalRoil** [comment]
Wouldn't it be best to also package the gopass summon provider, gopass bridge and other "old" binaries in the same formula? 

Because we didn't hear a lot from our (Gopass) users since the split of these packages into their own repositories, but if this formula is used a lot it could be disruptive for many people.
