### ISSUE TITLE
The usage of `pth` files is inconsistent across formulae, even harmful in some cases

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-core#73875]
When doing some changes to `python@3.9`'s posinstall, I noticed that `pip` is being picked up from multiple locations, one being sip's `libexec` directory, which is added as a site directory in `homebrew-sip.pth`.

It seems we are inconsistent in the way we are dealing with this. This can be branched out to two discussion points:

## The use of virtualenvs

Sip's problem comes because it creates a virtualenv. I believe this is an incorrect way to do it. We should not be running `site.addsitedir` on directories that are from a virtualenv.

I think we should separate these out into separate formulae, and depend on them instead.

We can alternatively just do the same resource vendoring without the virtualenv stuff. This will work but does have issues if you have two formulae using the same approach with the same Python packages - which version is used?

## prefix vs libexec

Some formulae install directly to the prefix, like `py3cairo`: https://github.com/Homebrew/homebrew-core/blob/e2c833d326c45d9aaf4e26af6dd8b2f31564dc04/Formula/py3cairo.rb#L22

Some install into `libexec` and then use a `pth` file to add that to the site path, like `pybind11`: https://github.com/Homebrew/homebrew-core/blob/e2c833d326c45d9aaf4e26af6dd8b2f31564dc04/Formula/pybind11.rb#L26-L32

This is inconsistent, and I see no reason for it to be.

There's pros & cons (depending on your viewpoint) for both cases:

* Using libexec
  - Won't cause a `brew link` conflict if the package is already installed via `pip`.
  - Unclear which version will be used if installed via both `brew` and `pip`.
* Using prefix
  - Opposite of above

In both cases, `pip` _can_ tamper with the installation. For prefix installs, this is an effective `brew unlink`. For libexec installs, this actually removes Cellar files. Other package managers avoid this problem by patching pip.

**Comment by carlocab** [comment]
`prefix` seems like a better option to me. It keeps formulae simpler (though I guess we can write some methods into `Language::Python` for writing `.pth` files... but do we really want to do that?), and avoids this:

> - Unclear which version will be used if installed via both brew and pip. 

which I think makes problems arising from these formulae more difficult to debug. I suspect these would be more difficult to deal with than `brew link` conflicts, which are much easier to spot.

**Comment by Bo98** [comment]
> This also sounds pretty bad

I kinda wish pip had a way to add "do not touch" directories without patching `is_local`, though it seems patching is what they expect to be done in a few places.

**Comment by carlocab** [comment]
I'm wondering about formulae that do this:

https://github.com/Homebrew/homebrew-core/blob/acc12fd244cdc4664a57469a4ee7d2471bfc3f52/Formula/name-that-hash.rb#L56-L61

This seems to expose all of the resources to the global environment. Does that defeat the purpose of installing into `libexec` in the first place?

**Comment by Bo98** [comment]
A bit yes. We shouldn't be linking to virtualenvs at all (since things like pip etc will also be there), and beyond that it's the libexec vs prefix argument.

**Comment by Bo98** [comment]
Depends on what `import name_that_hash` requires at runtime. It might well need some of those dependencies in the path too (which is a potential argument for a separate formula for them).

**Comment by carlocab** [comment]
Thinking about this some more, and I agree with this:

>I think we should separate these out into separate formulae, and depend on them instead.

I guess the difficulty here is how to do this in a way that works well with `brew update-python-resources`.

Currently, we have a few formulae (e.g. `scipy`, `numpy`, `python-tabulate`) that could be downloaded from PyPI as a resource but aren't because they're standalone formulae. We manage these by putting them under `exclude_packages` in [`pypi_formula_mappings.json`](https://github.com/Homebrew/homebrew-core/blob/master/pypi_formula_mappings.json).

I suppose we could just keep adding them there, but I suspect at some point it'll become too unwieldy. Ideally `update-python-resources` should just understand there are resources it should just exclude because they're already satisfied by the formula's dependencies.

**Comment by SMillerDev** [comment]
Maybe we can have it exclude all formulae it depends on?

**Comment by alebcay** [comment]
We should probably adjust docs at https://docs.brew.sh/Python-for-Formula-Authors if we're planning to allow more Python libraries into core (in the past, we've taken a pretty firm stance against it).

If we're choosing to go down this path, I'd also like to suggest that we consider adding `Pillow` as a standalone formula, mostly because it has a somewhat awkward building process and right now this gets shoehorned into any formula that uses `Pillow`.

**Comment by carlocab** [comment]
We might want to do `cryptography` too. I imagine it's not great for Rust PRs that each CI node has to build cryptography 40+ times instead of only once.

**Comment by Bo98** [comment]
There's also the case to consider where some formulae may require version pinning.

(I'll give a proper response tomorrow - just been busy getting GitHub Packages out the door, and now preparing for ops work today.)
