### ISSUE TITLE
zsh-git-prompt is not longer updated

### ISSUE THREAD

**Issue by rfalke** [Homebrew/homebrew-core#73961]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/ac2a4ccf354c693a43430c5a7886f434
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I want to use this package, it installs correct but when use you find that there are a lot of old unfixed issues in the base repo (https://github.com/olivierverdier/zsh-git-prompt). I ran for example into https://github.com/olivierverdier/zsh-git-prompt/issues/103 which was opened in 2017 and is still unfixed.

### What happened (include all command output)?

See above.

### What did you expect to happen?

Update the formulas to a maintained repo. Maybe https://github.com/zsh-git-prompt/zsh-git-prompt.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

**Comment by SMillerDev** [comment]
Is there a note in the repo saying it moved? Otherwise the other repository should really be a different formula. We want to avoid a situation where `brew install x` installs project x one day and project y the next.

**Comment by mitchblank** [comment]
The history of this package's forking is complicated -- the original program by @olivierverdie, then the fork by @starcraftman (which still says "[Active Fork]" in its gh description, but seems to be quiet for almost 3 years) and now this more recent fork apparently by @thomasrebele.  Since this latest one is hosted under the "zsh-git-prompt" gh organization it looks more "official", but I don't see anything in the other repos pointing to it as a designated successor repo or anything.  Perhaps the developers involved can comment what the best project for homebrew to track would be?

Making it more complicated from homebrew's perspective, only the original project ever did actual tagged "releases" (the tags they have are from before the first fork happened) so it's unlikely that homebrew would have updated to a newer "version" even if one of the more recently-active forks were to be considered the project's `head`/`homepage`

**Comment by carlocab** [comment]
Might help to ask one of these zsh-git-prompt forks to tag a release. Failing that, we might want to just deprecate the formula.

**Comment by thomasrebele** [comment]
I've created the fork in the zsh-git-prompt organization, as the other forks were not maintained anymore. I'm not sure about the backwards-compatibility of the fork. I just created a release: https://github.com/zsh-git-prompt/zsh-git-prompt/releases/tag/v0.6

If someone wants to join the organization, please let me know: https://github.com/zsh-git-prompt/zsh-git-prompt/issues/15

**Comment by rfalke** [comment]
Cool. This looks like some progress.
