### ISSUE TITLE
Expose Dovecot's `imap` binary as `/usr/local/libexec/dovecot/imap` ?

### ISSUE THREAD

**Issue by stig** [Homebrew/homebrew-core#755]
I use Dovecot for local on-demand IMAP from OfflineIMAP and Gnus by invoking its `imap` binary like this:

```
/usr/local/Cellar/dovecot/2.2.21/libexec/dovecot/imap -o mail_location=maildir:~/Mail/Personal
```

Would it be possible to link the imap binary outside Cellar? (I would suggest `/usr/local/libexec/dovecot/imap`.)

Would a PR that added this have any chance of being accepted? I would be willing to try adding it myself, but won't bother if it has no chance of being included.

**Comment by UniqMartin** [comment]
What's the issue with using that path? We don't link `libexec` directories of individual formulae into `/usr/local/libexec` because we consider these private to individual formulae and as things stand right now, linking them all in this location would probably create more issues than it solves.

Does the version number in the path bother you? If so, you can also use `/usr/local/opt/dovecot/libexec/dovecot/imap` which will remain stable across formula updates. Does that solve the issue for you?

**Comment by stig** [comment]
> Does the version number in the path bother you? 

Indeed, my mail setup breaking unnecessarily every time dovecot upgrades is my concern.

> If so, you can also use `/usr/local/opt/dovecot/libexec/dovecot/imap` which will remain stable across formula updates.

That's the piece I was missing! Thank you, this completely solves my issue.
