### ISSUE TITLE
Checking for `sudo` access (which may request your password)

### ISSUE THREAD

**Issue by solstin** [Homebrew/homebrew-core#76079]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Terminal Input:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Terminal output:
==> Checking for `sudo` access (which may request your password).
Password:
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install Homebrew on to a:
Latest MacBook Air M1
macOS Big Sur 11.3
Installed the latest Xcode Ver. 12.5
Pasted the following into the terminal:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

The terminal screen outputs the following.  I understand HomeBrew does not need sudo.
==> Checking for `sudo` access (which may request your password).
Password:

### What happened (include all command output)?

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

### What did you expect to happen?

Install Homebrew onto my new MacBook Air M1

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
In terminal I run the following copy and paste installation command from brew.sh

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Terminal output:
==> Checking for `sudo` access (which may request your password).
Password:
```

**Comment by Bo98** [comment]
You're correct that Homebrew does not need `sudo` when used). The installer however does so that it an create the necessary directory `/opt/homebrew` and set up its permissions. The installer also uses sudo to install and setup the Xcode Command Line Tools if it is not installed. Once installed, Homebrew no longer requires sudo ever again.

If you can't use sudo to install Homebrew, you still can install it without! Check here for alternative install instructions: https://docs.brew.sh/Installation#untar-anywhere. Note however that if you can't install Homebrew to the default location (`/opt/homebrew`) due to permissions then you won't be able to use some pre-built bottles and as such installing some formulae may build from source (which is a lot slower and more prone to errors).
