### ISSUE TITLE
Issue with gnupg.rb

### ISSUE THREAD

**Issue by mileslauridsen** [Homebrew/homebrew-core#76136]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Formula/gnupg.rb

Lines 82-94 appear like they shouldn't be there. Breaks usage of keycards.

__END__
diff --git a/tests/openpgp/defs.scm b/tests/openpgp/defs.scm
index 768d479aa..86d312f82 100644
--- a/tests/openpgp/defs.scm
+++ b/tests/openpgp/defs.scm
@@ -338,6 +338,7 @@
   (create-file "common.conf"
 	       (if (flag "--use-keyboxd" *args*)
 		   "use-keyboxd" "#use-keyboxd")
+	       (string-append "keyboxd-program " (tool 'keyboxd))
 	       )

   (create-file "gpg.conf"
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run gnupg

### What happened (include all command output)?

Outputs wrong keycard to insert

### What did you expect to happen?

Ask for correct keycard to insert

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
install this bad 2.3.1 gnupg.rb. Fail to connect to keycard.
Rolling back to 2.27.1 fixes the issue.
```

**Comment by nandahkrishna** [comment]
Please take a look at https://github.com/Homebrew/homebrew-core/pull/75755#issuecomment-825381930 and the one below it.

**Comment by cho-m** [comment]
@mileslauridsen  The patch is purely for GnuPG's own test suite.
It cannot impact GnuPG behavior as it is never used by any of the compiled binaries.
It only deals with build checks performed via `make check`.

**Comment by mileslauridsen** [comment]
Thanks @nandahkrishna and @cho-m . That info and workaround for the upstream issue fixes this.

**Comment by mileslauridsen** [comment]
Actually, this upstream fix doesn't solve the issue for me. Will leave open for now.

**Comment by carlocab** [comment]
Is this a problem with Homebrew `gnupg` in particular, or does it affect even non-Homebrew `gnupg` 2.31?

**Comment by cho-m** [comment]
@mileslauridsen Also, try getting some of the debug logs and analyze where the issue is happening.
It may also be useful to discuss with upstream GnuPG devs as they would be more familiar triaging the logs.

Currently, there isn't enough information here to provide further help.

---

The biggest change in Formula is going from gnupg 2.2.x to 2.3.x

From Homebrew side, majority of the build settings are the same with a few minor changes based on gnupg2.3 requirements:
- `symcryptrun` is no longer supported by GnuPG
- Homebrew's `sqlite` is needed for Mojave and older due to features GnuPG keyboxd uses.

Neither of these seem to be related to your issue.

**Comment by mileslauridsen** [comment]
@nandahkrishna's comment above points to the issue. Is an upstream issue with gnupg itself. Unfortunately the workaround suggested there doesn't work, so anyone using cards with gnupg may want to roll back to the 2.27.1 release here until that upstream issue is fixed.

**Comment by carlocab** [comment]
Ok, since this is an upstream issue, then it needs to be reported and tracked upstream instead of here. This issue tracker is for homebrew/core-specific issues.

**Comment by cho-m** [comment]
One thing to note is that GnuPG has classified the linked task as expected behavior and not a bug.
So, currently, GnuPG has no plans to "fix" the code.

The `disable-ccid` config is only a workaround to the user fix of modifying USB device permissions.

If you are still seeing an issue, you should continue discussion upstream with GnuPG devs so that they can provide further advice.

**Comment by jasonkarns** [comment]
PR to have gnupg formula configure `disable-ccid` automatically during installation https://github.com/Homebrew/homebrew-core/pull/77606
