### ISSUE TITLE
PyPy header files are not linked into /usr/local/include

### ISSUE THREAD

**Issue by tbodt** [Homebrew/homebrew-core#7689]
The header files for pypy can be found in /usr/local/Cellar/libexec/include, but they aren't linked into /usr/local/include.

**Comment by MikeMcQuaid** [comment]
This is intentional but we'd accept a PR to improve it. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
