### ISSUE TITLE
brew install ntfs-3g

### ISSUE THREAD

**Issue by jackeyxiang** [Homebrew/homebrew-core#77932]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
# brew install ntfs-3g
Error: ntfs-3g has been disabled because it requires FUSE!
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install ntfs-3g

### What happened (include all command output)?

# brew install ntfs-3g
Error: ntfs-3g has been disabled because it requires FUSE!

### What did you expect to happen?

# brew install ntfs-3g
Error: ntfs-3g has been disabled because it requires FUSE!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# brew install ntfs-3g
Error: ntfs-3g has been disabled because it requires FUSE!
```

**Comment by nandahkrishna** [comment]
There are similar previous issues and discussions related to formulae disabled because they require FUSE (https://github.com/Homebrew/homebrew-core/pull/64491, https://github.com/Homebrew/homebrew-core/issues/75656, https://github.com/Homebrew/discussions/discussions/1497), which is not open-source (and thus not suitable for inclusion in homebrew/core). You may want to check an external tap such as https://github.com/gromgit/homebrew-fuse instead.
