### ISSUE TITLE
vim (with lua) failed to build on 10.12.1

### ISSUE THREAD

**Issue by marcweil** [Homebrew/homebrew-core#7997]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

I had vim 8 installed already but wanted to re-install it with Lua support enabled. So I unlinked vim and tried to install vim with the `--with-lua` option, and it reports what appear to be syntax errors in libdispatch's headers.

gist-logs output: https://gist.github.com/anonymous/5832704d68b239268bfaec108a88c97f

**Comment by SteveJobzniak** [comment]
@marcwell I built my own vim with the faster luajit engine:

`brew install vim --with-luajit --with-override-system-vi`

Try that. Perhaps only `--with-lua` fails (I haven't tried the plain `--with-lua`).

**Comment by DomT4** [comment]
The problem seems to be `/usr/local/include/dispatch/legacy.h`.

The system file `/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h` includes a `#include <dispatch/dispatch.h>` line, which drags in your custom installation there instead of presumably the intended/desired `/usr/include/dispatch/dispatch.h` or Xcode-only equivalent. Move `/usr/local/include/dispatch` elsewhere temporarily and try again.

**Comment by MikeMcQuaid** [comment]
> Ran brew doctor, fixed as many issues as possible and retried your prior step?

@marcweil Let me know if this can still be reproduced after you've removed all the files it warns about.
