### ISSUE TITLE
Wrong SHA256 hash for Fossil 2.16 source archive

### ISSUE THREAD

**Issue by lifepillar** [Homebrew/homebrew-core#80994]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.1-70-g5659d74
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5659d74ff59414d22e285d77a7fcfcd3c1bf0614
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 222f5d42461207b3b58a8410b4102f50b20ece25
Core tap last commit: 69 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.mr90KE3aEK/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install Fossil from source.

### What happened (include all command output)?

```
Error: SHA256 mismatch
Expected: fab37e8093932b06b586e99a792bf9b20d00d530764b5bddb1d9a63c8cdafa14
  Actual: ec2d28d6d53b8c2f1410dad3c93df00b675cdf6019c13df71a88e6a2393f09dc
```

### What did you expect to happen?

The hash should have matched.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install -s fossil
```

**Comment by gromgit** [comment]
Checking with upstream, stay tuned: https://fossil-scm.org/forum/forumpost/b736737d47

**Comment by sqlite** [comment]
I changed the delivery model for the most recent Fossil release such that the source tarballs are computed on-the-fly rather than being precomputed.  This means there is the possibility that the cryptohash of the tarball might change from one download to the next, due to differences in compression, even though the content is identical.

I'll change it back so that the source tarballs are recomputed and hence the cryptohash is always the same.  But it will be 8-10 hours before I will have an opportunity to do that.

**Comment by sqlite** [comment]
Upon further investigation, I think the reason the hash changed is because I changed the name of
the tarball from "fossil-2.16.tar.g" to "fossil-src-2.16.tar.gz".  The additional "-src" in the name also
changes the name of the top-level directory into which it unpacks, which of course changes the hash.

The on-the-fly computed tarball is cached.  So the hash shouldn't be changing.  Furthermore, the
on-the-fly computed tarball name contains an unforgeable SHA3-256 hash of the check-in that is the release:

>  `https://fossil-scm.org/home/tarball/7aedd5675883d4412cf20917d340b6985e3ecb842e88a39f135df034b2d5f4d3/fossil-src-2.16.tar.gz`

Fossil will always generate the correct content tarball for such a URL.  There is no way to change the content by adding tags or make other alterations to the repository. So the tarball content will be consistent.  The only way that the tarball should change is if you recompile Fossil using a different version of zlib that somehow does a slightly different compression and you clear the cache.  I'm not planning to do either of those things moving forward.  So the current tarball hash should be invariant.  Again - I think the change occurred because I fixed a typo in the name by adding the "-src" component to the filename.

**Comment by gromgit** [comment]
> `https://fossil-scm.org/home/tarball/7aedd5675883d4412cf20917d340b6985e3ecb842e88a39f135df034b2d5f4d3/fossil-src-2.16.tar.gz`

While the hashed URL is stable, it's also somewhat tricky to revision-bump via Homebrew's current tools.

I'm not sure where I came across it, but I noticed that `https://fossil-scm.org/home/tarball/release/fossil-src-2.16.tar.gz` also resolves to the same contents as the above URL. Is this `release`-tagged URL considered stable and tied to the corresponding version-tagged commit in the Fossil repo?

**Comment by sqlite** [comment]
The "/release/" tarball is currently identical to the "/7aedd5675883d4412cf20917d340b6985e3ecb842e88a39f135df034b2d5f4d3/" because that hash is the latest release.  However, this will change at the next release.

You can always fetch "https://fossil-scm.org/home/tarball/release/fossil-src-latest.tar.gz" and it will always return the most recent check-in that is tagged with "release", but the specific check-in returned will change whenever a new check-in tagged with "release" is added to the source tree.  Note that
you can change the filename at the end, and Fossil will generate a new tarball with whatever top-level directory name you ask for.

You can also use "https://fossil-scm.org/home/tarball/version-2.16/sometarballname.tar.gz" and that will get you a tarball of the most recent check-in tagged with "version-2.16".  That one will not change, unless one of the committers on the project goes rogue and alters the "version-2.16" tag.  That probably will never happen in practice, but it could happen in theory.  That's why I recommend using the full SHA3 hash name for the official 2.16 release.

**Comment by gromgit** [comment]
OK, thanks much for the clarification!
