### ISSUE TITLE
brew install dmd should use a dmd.conf symlink

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#8160]
@NfNitLoop 
See https://issues.dlang.org/show_bug.cgi?id=17022 for context

Related: https://github.com/Homebrew/legacy-homebrew/pull/37663

**Comment by zmwangx** [comment]
This is by design. `SYSCONFDIR` is set to `#{etc}`, that is, `#{HOMEBREW_PREFIX}/etc` instead of `#{prefix}/etc` (see [Formula Cookbook](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#variables-for-directory-locations) for details), so that modifications to config files in `$(brew --prefix)/etc/` aren't lost upon upgrade. This is how most people expect their config files to behave.

>     $homebrew_D/Cellar/dmd/2.071.1/bin/dmd
>     $homebrew_D/Cellar/dmd/2.072.1/bin/dmd

Unfortunately, Homebrew isn't designed to be completely isolated version sandboxes. Different versions use the same system configurations, just like they would use the same user configurations.

What you could do is to have multiple Homebrew installations.

**Comment by ilovezfs** [comment]
Yes, what Mr. W said.
