### ISSUE TITLE
meson fails because it uses python3.6 instead of python3.5

### ISSUE THREAD

**Issue by aleb** [Homebrew/homebrew-core#8418]
The meson formula has been changed recently to not use a virtualenv, see https://github.com/Homebrew/homebrew-core/pull/8129 for details. It worked fine afterwards, but since the python3 formula has been updated to version 3.6, meson fails in a very similar way:

```
➜  git clone https://github.com/pitivi/gst-transcoder.git
➜  cd gst-transcoder
➜  ./configure
➜  grep python3 mesonbuild/build.ninja 
 command = "/usr/local/opt/python3/bin/python3.6" "/usr/local/Cellar/meson/0.37.1_1/libexec/bin/meson" --internal symbolextractor $in $out $CROSS
```
The grep command shows /usr/local/opt/python3/bin/python3.6 instead of ../python3.5.
Because of this, meson later fails because it can't find a module of its own:
```
"/usr/local/opt/python3/bin/python3.6" "/usr/local/Cellar/meson/0.37.1_1/libexec
/bin/meson" --internal symbolextractor subprojects/gst-transcoder/libgsttranscod
er-1.0.dylib 'subprojects/gst-transcoder/gsttranscoder-1.0@sha/subprojects/gst-t
ranscoder/libgsttranscoder-1.0.dylib.symbols' 
Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.37.1_1/libexec/bin/meson", line 17, in <module>
    from mesonbuild import mlog, mesonmain, mesonlib
ModuleNotFoundError: No module named 'mesonbuild'
```

I suggest to rebuild the meson formula so it installs its files in `/usr/local/lib/python3.6` instead of `/usr/local/lib/python3.5`.

**Comment by aleb** [comment]
Could you please also rebuild numpy and matplotlib? My formula built on python3.6 cannot use them.. is this reason good enough?

**Comment by ilovezfs** [comment]
@tdsmith do you have a usual policy about revision bumps when python3 is a second-class, optional citizen?

**Comment by tdsmith** [comment]
"Accept breakage," so far. We could probably mine analytics to see if/where
python3 is a popular option  and make those recommended so they get bumped
but I don't have any other ideas right now.

**Comment by kmayoral** [comment]
I'm also experiencing this issue. Any suggestions for a workaround?

**Comment by aleb** [comment]
Maybe install it like this: `brew install meson --HEAD`

**Comment by kmayoral** [comment]
Thanks for your suggestion @aleb! 

Turns out, I was victim of another issue caused by brew installs on Mac OS High Sierra not allowing for chown to be called on /usr/local directory. I recently upgraded from Yosemite to High Sierra and this was the first time using homebrew since. 

While attempting to install meson, one of the dependencies (python) required symlinking into the non existent /usr/local/Frameworks directory. When this failed, I was still getting a successful response to python being installed so I didn't notice it at first. 

To fix, I had to manually create the Frameworks directory with correct ownership set to my current user and then reinstall python and meson via brew. Once I did that, this error stopped appearing. 

Thanks!
