### ISSUE TITLE
youtube-dl update breaks upgrade and clean installation

### ISSUE THREAD

**Issue by blogabe** [Homebrew/homebrew-core#8420]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

It appears that the https://github.com/Homebrew/homebrew-core/commit/f38df92782b68a132fcb1c374f98157815291b6d update now forces the pandoc dependency for youtube-dl which has been problematic for me.

One of pandoc's dependencies is ghc which take over a gig and takes anywhere from 2-3 hours to install.  Pandoc itself cannot complete it's installation showing the below error message:
```
==> Installing youtube-dl dependency: pandoc
==> Downloading https://hackage.haskell.org/package/pandoc-1.19.1/pandoc-1.19.1.
Already downloaded: /Users/me/Library/Caches/Homebrew/pandoc-1.19.1.tar.gz
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=4 --max-backjumps=100000 --only-dependencies
Last 15 lines from /Users/arajab/Library/Logs/Homebrew/pandoc/03.cabal:
PreExisting filepath-1.4.1.1 (filepath-1.4.1.1)
PreExisting ghc-boot-th-8.0.1.20161213 (ghc-boot-th-8.0.1.20161213)
PreExisting ghc-prim-0.5.0.0 (ghc-prim-0.5.0.0)
PreExisting integer-gmp-1.0.0.1 (integer-gmp-1.0.0.1)
PreExisting pretty-1.1.3.3 (pretty-1.1.3.3)
PreExisting process-1.4.3.0 (process-1.4.3.0)
PreExisting rts-1.0 (rts)
PreExisting template-haskell-2.11.1.0 (template-haskell-2.11.1.0)
PreExisting time-1.6.0.1 (time-1.6.0.1)
PreExisting transformers-0.5.2.0 (transformers-0.5.2.0)
PreExisting unix-2.7.2.1 (unix-2.7.2.1)

CallStack (from HasCallStack):
error, called at ./Distribution/Client/Dependency.hs:658:33 in
main:Distribution.Client.Dependency

READ THIS: https://git.io/brew-troubleshooting
```

Is there anyway to install youtube-dl without these dependencies as in prior to the update?

Given the frequent update of youtube-dl, I'd prefer to skinny the installation as much as possible (yes, I understand pandoc, ghc, and cabal will only upgrade when they are updated).

Maybe grab the bottle rather than build from source?  This was not an issue prior to the above mentioned update.  Is anyone else seeing this?

**Comment by woodruffw** [comment]
There should be a bottle available for `youtube-dl`, and it should be selected by default over a source build unless you're passing some overriding option.

That being said, I don't know why we've made `pandoc` a mandatory build dependency - depending on the entire Haskell stack for a (relatively) small python project seems a bit overkill.

Pinging @zmwangx for elucidation on this.

**Comment by blogabe** [comment]
Yes.  I'm using the bottle hopefully as a temp workaround since I do prefer to compile directly from source.  But for reason you state, this is hugely overkill for such a relatively small project to force onto users.  I'm unsure if this is a new requirement upstream.  Looks like the specific piece of code that changed in the update was to avoid a build error that was happening in the original pull request.

**Comment by zmwangx** [comment]
I was surprised to see @nijikon push a640294 to #8361 too (not complaining; he was correcting my mistake), but since I have pandoc (and the Haskell stack) anyway I didn't think too much about it.

Now that I looked into it, there was something wrong with their 2016.12.31 release. `youtube-dl.1` depends on `README.md`, and `README.md` depends on `youtube_dl/*.py youtube_dl/*/*.py`, etc. Now all those *.py files are newer than `README.md`, so make decides to regen `README.md` and `youtube-dl.1`. I hope they're not doing the packaging by hand, but maybe they are... 😱 

Since this only applies to 2016.12.31, I opened #8424 to fix this.

In our defense, there weren't much we could do. The tarball was screwed up, so we basically had three options at that point:

1. Drop the man page / make it optional — more destructive than adding a somewhat hefty build dependency;
2. Do some shady touching after unpacking (didn't check if the man page was actually up-to-date);
3. What we did.

3. was the best for the great majority of users. Thanks @blogabe for bringing this up, now we should be back on track.

For the record, pandoc was in there for HEAD since https://github.com/Homebrew/legacy-homebrew/pull/29360.

**Comment by blogabe** [comment]
Hey, thanks @zmwangx   Glad to hear it's a simple enough fix.

I'll go ahead and close this now.

**Comment by nijikon** [comment]
Sorry guys for any issues on this 😿

**Comment by MikeMcQuaid** [comment]
Please provide your `brew config` and `brew doctor` output for future issues.
