### ISSUE TITLE
Segfault with Mesos 1.1.0 formula when using the Docker image provider

### ISSUE THREAD

**Issue by aaronjwood** [Homebrew/homebrew-core#8707]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

Currently when you run `mesos-slave --master=127.0.0.1:5050 --work_dir=/tmp/slave --containerizers=mesos --image_providers=docker` you will immediately get a segfault:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0110 13:32:58.590873 2100015104 main.cpp:243] Build: 2016-11-16 18:56:50 by brew
I0110 13:32:58.591126 2100015104 main.cpp:244] Version: 1.1.0
I0110 13:32:58.593508 2100015104 containerizer.cpp:200] Using isolation: posix/cpu,posix/mem,filesystem/posix
*** Aborted at 1484073178 (unix time) try "date -d @1484073178" if you are using GNU date ***
PC: @        0x10a29a9ca std::__1::__tree<>::__assign_multi<>()
*** SIGSEGV (@0x0) received by PID 47913 (TID 0x7fff7d2bb000) stack trace: ***
    @     0x7fff899b252a _sigtramp
    @     0x7fdb13029530 (unknown)
    @        0x10a29a96c flags::FlagsBase::operator=()
    @        0x10a299924 mesos::uri::fetcher::Flags::operator=()
    @        0x10a298902 mesos::uri::fetcher::create()
    @        0x10a284fd3 mesos::internal::slave::docker::Store::create()
    @        0x10a24841f mesos::internal::slave::Store::create()
    @        0x10a22f25a mesos::internal::slave::Provisioner::create()
    @        0x10a1a2c6f mesos::internal::slave::MesosContainerizer::create()
    @        0x10a141426 mesos::internal::slave::Containerizer::create()
    @        0x109cb8d80 main
    @     0x7fff9a3995ad start
Segmentation fault: 11
```

This seems to be caused from an issue with libc++ with clang++ 3.8. There's an open issue about this here https://issues.apache.org/jira/browse/MESOS-5745
If you look at a few of the comments further down you'll see that it should be fixed with clang 3.9.

Can Mesos be built with the newest version of clang? If not, can gcc be used instead? I wouldn't mind contributing any changes that are needed.

What is everyone's thought on this?

**Comment by haosdent** [comment]
mac don't support unified containerizer + docker image. have to use `--containerizers=docker`

**Comment by aaronjwood** [comment]
@haosdent I believe Ben Bannier said that he got everything to work on OS X (successfully launched containers through Marathon).

**Comment by haosdent** [comment]
Hi, @aaronjwood unified containerizer + docker image depends on linux features (filesystem, mount, cgroups) It should never work in osx. Because unified containerizer never depend on docker daemon.

**Comment by aaronjwood** [comment]
Ah, I see. I guess he must have been using the docker containerizer then. I'll close this issue out. Thanks for clarifying!

**Comment by bbannier** [comment]
@aaronjwood :The stack trace you are seeing is a strong indication that the unusable homebrew Mesos binary is due to the same issue as https://issues.apache.org/jira/browse/MESOS-5745. The underlying issue there was that around 3.8 clang started to optimize undefined behavior in libcxx C++ standard library containers which are used e.g., in Mesos' `flags::FlagsBase` class.

I believe the Mesos binary produced by homebrew should be rebuilt with at least clang-3.9, please reopen this issue.

In order to detect whether a certain libcxx/clang combination is affected the test case listed in https://llvm.org/bugs/show_bug.cgi?id=28469 can be used.

**Comment by haosdent** [comment]
thx @bbannier and @aaronjwood . It looks like use default clang to compile mesos in homebrew https://github.com/Homebrew/homebrew-core/blob/master/Formula/mesos.rb  .

**Comment by aaronjwood** [comment]
Thanks for the follow up guys! I've reopened this so at least users will not get the segfault when fixed.

**Comment by MikeMcQuaid** [comment]
> I believe the Mesos binary produced by homebrew should be rebuilt with at least clang-3.9, please reopen this issue.

If Mesos cannot be built with the default Clang on macOS it'll need to be removed from Homebrew. Is there no other workaround?

**Comment by bbannier** [comment]
@MikeMcQuaid: A possible workaround would be to build Mesos without optimizations (i.e., with `-O0`). This would lead to clang not optimizing on libcxx's undefined behavior. The performance of the produced executable would likely be bad, so such a fix should carry a staunch warning (e.g., including the likes of `this build of Mesos is intended for exploration and NOT FIT FOR PRODUCTION WORKLOADS`).

**Comment by MikeMcQuaid** [comment]
Again, carrying that warning points towards this software not being suitable for Homebrew.

**Comment by bbannier** [comment]
Just to put my comment into perspective: I believe the motivation to provide Mesos with Homebrew is so that people can experiment with e.g., Mesos APIs while developing for larger setups. I don't realistically anticipate people to run Mesos built from Homebrew on installations large enough that performance would play a significant role.

@MikeMcQuaid: Do you happen to know Homebrew's policies regarding bottling of non-optimized builds? The Mesos formula doesn't explicitly enable optimizations, so I suspect that the build might end up optimized due to settings from e.g., a `CONFIG_SITE` (Mesos is built with autotools), or a similar setting. Disabling optimizations in the Mesos formula (e.g., by passing `-O0` in `CXXFLAGS`) would likely make this issue go away; the bundled test suite can be used to confirm that the produced executables work (`make check`). Would this be an acceptable solution?

In the end this problem is due to Apple still shipping a broken libcxx. Mesos just was unlucky enough to hit a code pattern leading to broken executables. There is little Mesos can do to work around this undefined behavior in the used C++ standard library, and I suspect there are other tools built with the default Apple libcxx which are similarly affected.

**Comment by MikeMcQuaid** [comment]
@bbannier I'd want it confirmed as a definite workaround before we adopt it. We enable optimisations by default (like most from-source packagers) but they can be disabled if necessary but that's considered an upstream bug.

> In the end this problem is due to Apple still shipping a broken libcxx. Mesos just was unlucky enough to hit a code pattern leading to broken executables. There is little Mesos can do to work around this undefined behavior in the used C++ standard library, and I suspect there are other tools built with the default Apple libcxx which are similarly affected.

We have many thousands of formulae and Mesos is the only one that seems to be affected so far. I'd suggest that you take whatever workarounds you can, little or not, if you want to consider your software ported to macOS. That's the approach we at Homebrew have to take as we don't work at Apple and thus can't control this stuff either.

**Comment by tillt** [comment]
So this has become rather interesting now. The referenced https://github.com/Homebrew/homebrew-core/issues/9014 which introduces the configuration flag `--disable-optimize` does not fix the problem of me - see below - did I miss something? Will try to look into that...

After having patched `mesos.rb`;

```bash
brew install --build-from-source mesos
==> Using the sandbox
==> Downloading https://www.apache.org/dyn/closer.cgi?path=mesos/1.1.0/mesos-1.1.0.tar.gz
Already downloaded: /Users/till/Library/Caches/Homebrew/mesos-1.1.0.tar.gz
==> ./configure --disable-python --prefix=/usr/local/Cellar/mesos/1.1.0 --disable-optimize --disable-silent-rules --with-svn=/usr/local/opt/subversion
==> make
[…}
```

```
$ mesos-agent --master=127.0.0.1:5050 --work_dir=/tmp --containerizers=mesos --image_providers=DOCKER
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0118 05:30:13.539319 3131106240 main.cpp:243] Build: 2017-01-18 05:18:59 by till
I0118 05:30:13.539497 3131106240 main.cpp:244] Version: 1.1.0
I0118 05:30:13.542608 3131106240 containerizer.cpp:200] Using isolation: posix/cpu,posix/mem,filesystem/posix
*** Aborted at 1484713813 (unix time) try "date -d @1484713813" if you are using GNU date ***
PC: @        0x103942527 std::__1::__tree<>::__assign_multi<>()
*** SIGSEGV (@0x0) received by PID 87812 (TID 0x7fffbaa0e3c0) stack trace: ***
    @     0x7fffb1dcebba _sigtramp
    @     0x7fffb1d434ca szone_malloc_should_clear
    @        0x1039424c8 flags::FlagsBase::operator=()
    @        0x103940dba mesos::uri::fetcher::Flags::operator=()
    @        0x10393fd89 mesos::uri::fetcher::create()
    @        0x10392c78b mesos::internal::slave::docker::Store::create()
    @        0x1038f0fa3 mesos::internal::slave::Store::create()
    @        0x1038d687c mesos::internal::slave::Provisioner::create()
    @        0x10384b9eb mesos::internal::slave::MesosContainerizer::create()
    @        0x1037ebbf9 mesos::internal::slave::Containerizer::create()
    @        0x1025b21ec main
    @     0x7fffb1bc1255 start
    @                0x5 (unknown)
Segmentation fault: 11
```

**Comment by ilovezfs** [comment]
brew install --build-from-source mesos

that will still pass -Os and -march=native regardless of how you've tweaked configure
