### ISSUE TITLE
Failed to install mpv

### ISSUE THREAD

**Issue by tleunen** [Homebrew/homebrew-core#8731]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

Installing or updating mpv now fails

```
~ ❯ brew install mpv --with-bundle
==> Using the sandbox
==> Downloading https://github.com/mpv-player/mpv/archive/v0.23.0.tar.gz
Already downloaded: /Users/tleunen/Library/Caches/Homebrew/mpv-0.23.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/05/25/7b5484aca5d46915493f1fd4ecb63c38c333bd32aa9ad6e19da8d08895ae/docutils-0.13.1.tar.gz
Already downloaded: /Users/tleunen/Library/Caches/Homebrew/mpv--docutils-0.13.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/mpv-20170111-82932-226sf9/mpv-0.23.0/vendor --single-version-externally-managed --record=installed.txt
==> ./bootstrap.py
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/0.23.0_2 --enable-zsh-comp --enable-libmpv-shared --enable-html-build --confdir=/usr/local/etc/mpv --datadir=/usr/local/Cellar/mpv/0.23.0_2/share/mpv --mand
==> python3 waf install
Last 15 lines from /Users/tleunen/Library/Logs/Homebrew/mpv/04.python3:
[439/444] Linking build/mpv
+ install /usr/local/Cellar/mpv/0.23.0_2/lib/libmpv.1.24.0.dylib (from build/libmpv.dylib)
[441/444] Compiling TOOLS/zsh.pl
[442/444] Symlinking build/libmpv.dylib
+ install /usr/local/Cellar/mpv/0.23.0_2/bin/mpv (from build/mpv)
dyld: Library not loaded: /usr/local/opt/libass/lib/libass.5.dylib
  Referenced from: /usr/local/opt/ffmpeg/lib/libavutil.55.dylib
  Reason: Incompatible library version: libavutil.55.dylib requires version 9.0.0 or later, but libass.5.dylib provides version 7.0.0
Couldn't find any options at /private/tmp/mpv-20170111-82932-226sf9/mpv-0.23.0/TOOLS/zsh.pl line 13.

Waf: Leaving directory `/private/tmp/mpv-20170111-82932-226sf9/mpv-0.23.0/build'
Build failed
 -> task in '_mpv' failed (exit status 255): 
        {task 4529653800: _mpv zsh.pl -> _mpv}
' "/usr/bin/perl" "/private/tmp/mpv-20170111-82932-226sf9/mpv-0.23.0/TOOLS/zsh.pl" "/private/tmp/mpv-20170111-82932-226sf9/mpv-0.23.0/build/mpv" > "etc/_mpv" '
```

https://gist.github.com/f0434a466414e0adbd851d2cd3cbc96b

**Comment by Argon-** [comment]
Fix it with `brew reinstall ffmpeg`.
The problem here is brew updated libass but will not trigger a rebuild of ffmpeg (which is using libass). Unfortunately this happens frequently and is imo a limitation of brew.

**Comment by tleunen** [comment]
Indeed, it does fix the issue.

Thanks for the explanation.

**Comment by johnhawkinson** [comment]
> `brew reinstall ffmpeg` will fix this.

**Can we get a Caveats section explaining this?**

I had a similar issue with `mpv` today, and ended up rebuilding it from source rather than reinstalling `ffmpeg`:

```
$ mpv 'http://what/ev/er'  
ffmpeg library versions:
   libavutil       55.34.101 (runtime 55.17.103)
   libavcodec      57.64.101 (runtime 57.24.102)
   libavformat     57.56.101 (runtime 57.25.100)
   libswscale      4.2.100 (runtime 4.0.100)
   libavfilter     6.65.100 (runtime 6.31.100)
   libswresample   2.3.100 (runtime 2.0.101)
ffmpeg version: 3.0.1

mpv was compiled against a different version of FFmpeg/Libav than the shared
library it is linked against. This is most likely a broken build and could
result in misbehavior and crashes.

mpv does not support this configuration and will not run - rebuild mpv instead.

Exiting... (Fatal error)
```

It would be helpful if there were a Caveats section in the `mpv` recipe that explained what's going on.
Thanks.
I have a bunch of ffmpeg versions installed (including a HEAD) and I tried `brew switching` between them before giving up and rebuilding `mpv` from source.

**Comment by Argon-** [comment]
That's not mpv's fault, more like a short-coming of brew. It can happen with many dependency "chains" like that.

**Comment by johnhawkinson** [comment]
> That's not mpv's fault, more like a short-coming of brew. It can happen with many dependency "chains" like that.

Sure, but the intention isn't to assign blame. It's to give the user some guidance on what to do to solve their problem quickly and easily with as little fuss as possible.
And if we want to be picky, since mpv has special-case code to address this case rather than printing the standard operating system error message, it is appropriate for the mpv formula to have special handling for this as well.

Or am I wrong?

I suppose another argument is there should be a runtime postinstall test for all packages where this is likely. We may not be able to solve the problem easily, but we can detect it and give better guidance to improve the user experience.

**Comment by Argon-** [comment]
Well, other package management systems recompile dependencies (or the program using one) upon upgrade (or allow you to specify this should happen) and that would've fixed you issue (which is not the same as the original btw, just the solution is similar and the cause is kinda as well). That's why I said "limitation of brew". 

The difference here is that mpv insists on the correct ffmpeg version. This is strictly not a necessity but it decreased the amount of problems a lot. Ffmpeg is unfortunately not exactly stable and software is often only compatible with a limited set of ffmpeg versions (depending on how involved it's using it). When paired with an incompatible version you get undefined/incorrect behavior at best, a crash in the worst case. 

A caveat in mpv's formula is the wrong way to adress this imo because rebuilding mpv won't do much harm. Your specific problem arises when you upgrade ffmpeg and this doesn't trigger a rebuild of software depending on it (libass and mpv).

**Comment by johnhawkinson** [comment]
> A caveat in mpv's formula is the wrong way to adress this imo because rebuilding mpv won't do much harm

So what is a better way to address it?

**Comment by ilovezfs** [comment]
Something like Gentoo's `revdep-rebuild` https://wiki.gentoo.org/wiki/Gentoolkit#revdep-rebuild

**Comment by Argon-** [comment]
> So what is a better way to address it?

Well, obviously the best way to deal with this is by extending brew, making it aware of the problem and capable enough to deal with it.

**Comment by johnhawkinson** [comment]
I'm sorry, perhaps I wasn't clear.
We should not let "best be the enemy of good."

It seems unlikely that a true fix to Homebrew's shared library dependency problems is coming along anytime soon. So in the absence of that, as an interim step, isn't a caveat an appropriate workaround for this formula, which is both more likely to encounter the problem than most, and also presents a different error message than any other tool would show?

Thanks.

**Comment by ilovezfs** [comment]
This is not the sort of thing we use caveats for but thank you for the suggestion.

**Comment by Argon-** [comment]
> It seems unlikely that a true fix to Homebrew's shared library dependency problems is coming along anytime soon. So in the absence of that, as an interim step, isn't a caveat an appropriate workaround for this formula

This problem can (and eventually will) happen to all programs using ffmpeg whenever you upgrade ffmpeg without also upgrading all programs using it (assuming they updated to changes - it is entirely possible that some program does not support any current version of ffmpeg). It's just that mpv is one of the only programs warning you about this, all the others will simply crash or work incorrectly.
If you want to put a note then put it into ffmpeg's formula and ask a user to verify if all programs in `brew uses ffmpeg --installed` support this version of ffmpeg you just installed and rebuild them.

However, I would also vote for not putting such a caveat because of the nature of this issue. It's kind of a natural thing and it can happen whenever you upgrade a library while also having programs installed that depend on it. This is not a problem unique to ffmpeg/mpv.

**Comment by johnhawkinson** [comment]
> However, I would also vote for not putting such a caveat because of the nature of this issue. It's kind of a natural thing and it can happen whenever you upgrade a library while also having programs installed that depend on it. This is not a problem unique to ffmpeg/mpv.

That just doesn't seem convincing.

We know there is a problem, we know it occurs with some frequency with `ffmpeg` and `mpv`, and we have a mechanism to provide some documentary diagnostic guidance to users that could help them find and resolve these problems. But we don't want to use that mechanism because it is not perfect, because some other programs can also have the same problem (even though they do not see it as often), and least convincingly, "this is not the sort of thing we use caveats for."

**Really?**

(Also, saying "this is not the sort of thing we do" is at all a helpful answer. Perhaps there are [good] reasons not to do so, but "Because I said so" cannot be one.)

**Comment by MikeMcQuaid** [comment]
> "Because I said so" cannot be one

As a brief tangent: when we're maintaining the open source project: yes, it can be. We don't (and can't) justify every decision and time spent justifying is time not spent improving the project.

**Comment by johnhawkinson** [comment]
Respectfully, Mike, it can be something you say because you don't have time to explain the real reason. And that decision can be reasonable in the face of abuse, annoying, harassing, or just plain annoying cases. I hope I'm not in that category, but it's not my judgment to make.

But that does not make it a "good reason" -- it just makes it something you can say because it is too expensive to explain the real reason. And that's OK. But please don't pretend it is in fact a good reason or the real reason on its own. That's just not so. It makes the project look bad, discouraging users and contributors both.

**Comment by JCount** [comment]
I know that this is not a real solution, but I find using a script like this to help smooth out some of Homebrew's rough edges:
```
#!/usr/bin/env bash
brew update
brew upgrade --fetch-HEAD ffmpeg 2>/dev/null && brew test ffmpeg && {
	(brew upgrade --fetch-HEAD mpv 2>/dev/null || brew reinstall mpv) &&
	brew test mpv && echo "FFmpeg and mpv updated to current HEAD"
} || echo "FFmpeg already on current HEAD"
```
(note that I am well aware that probably everyone who sees this will be able do the same or something much better 😁)
