### ISSUE TITLE
hhvm --HEAD failed to build on OSX 10.11.6

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [Homebrew/homebrew-core#8754]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

While building hhvm --HEAD the operation finalizes abruptly with an `undefined method` exception in `inreplace`.

Logs: https://gist.github.com/FranciscoE-Hudl/4ccd751bfff4412637f363463d4ee8fa
Brew gist-logs hhvm: https://gist.github.com/pakoito/efa3833fcd1f046d320c8a0479f9676e

**Comment by ilovezfs** [comment]
The undefined method part is a brew bug. But it's triggered by a formula bug, which you should report to hhvm/hhvm tap. The correct error message is
```
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
Utils::InreplaceError: inreplace failed
Benchmark.cpp:
  expected replacement of "detail::DEFAULT_CLOCK_ID" with "(clockid_t)detail::DEFAULT_CLOCK_ID"
Benchmark.h:
  expected replacement of "detail::DEFAULT_CLOCK_ID" with "(clockid_t)detail::DEFAULT_CLOCK_ID"
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

The string replacement should be inside a conditional `if build,stable? ... end` and if the bug isn't fixed in head, an appropriate string replacement added for that case too.
