### ISSUE TITLE
Can't install crystal-lang formula on Sierra (~/.brew)

### ISSUE THREAD

**Issue by yyyc514** [Homebrew/homebrew-core#9242]
The issue:
```
% brew install crystal-lang
==> Using the sandbox
==> Downloading https://github.com/crystal-lang/crystal/archive/0.20.5.tar.gz
Already downloaded: /Users/jgoebel/Library/Caches/Homebrew/crystal-lang-0.20.5.tar.gz
==> Downloading https://github.com/crystal-lang/crystal/releases/download/0.20.4/crystal-0.20.4-1-darwin-x86_64.tar.gz
Already downloaded: /Users/jgoebel/Library/Caches/Homebrew/crystal-lang--boot-0.20.4.tar.gz
==> make crystal release=true
Last 15 lines from /Users/jgoebel/Library/Logs/Homebrew/crystal-lang/01.make:

make
crystal
release=true

Using /Users/jgoebel/.brew/opt/llvm/bin/llvm-config [version=3.9.1]
clang++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/Users/jgoebel/.brew/opt/llvm/bin/llvm-config --cxxflags`
clang -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
./bin/crystal build --release  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.1.dylib
  Referenced from: /private/tmp/crystal-lang-20170124-56700-o39psm/crystal-0.20.5/boot/embedded/bin/crystal
  Reason: image not found
/private/tmp/crystal-lang-20170124-56700-o39psm/crystal-0.20.5/boot/bin/crystal: line 102: 56841 Abort trap: 6           "$INSTALL_DIR/embedded/bin/crystal" "$@"
make: *** [.build/crystal] Error 134

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [dunno] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

I'm not sure if the problem is a brew problem or a formulae problem.  I've had 0 issues with any other formula.  Yes, I'm aware my install is in `.brew`.  This has not been a serious problem with any other packages in the past and I'm hoping this also can be resolved.

brew doctor:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/jgoebel/.rbenv/shims/passenger-config
  /usr/local/CrossPack-AVR/bin/libusb-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  llvm35-patched
  mongodb
  mysql-connector-c
  v8

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
```

brew config:
```
HOMEBREW_VERSION: 1.1.8-24-g35045b2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 35045b2934d94eabe302693a05b12fb530827454
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 32b9d6937ef4131706b24e9aac4127db746da3e5
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /Users/jgoebel/.brew
HOMEBREW_REPOSITORY: /Users/jgoebel/.brew
HOMEBREW_CELLAR: /Users/jgoebel/.brew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/jgoebel/.brew/bin/python => /Users/jgoebel/.brew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/jgoebel/.rbenv/shims/ruby => /Users/jgoebel/.rbenv/versions/2.2.2/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

brew git-logs crystal-lang:
```
https://gist.github.com/f468b380106d74e8c689de2cf329613c
```

**Comment by yyyc514** [comment]
I also tried linking `.brew/opt` to `/usr/local/opt` (which didn't exist) but as far as I can determine that resulted in just infinite CPU spin in crystal.  I gave it like 10-15 minutes.  I don't think it should take that long to compile, should it?

**Comment by yyyc514** [comment]
Seems even stranger since the built binary INCLUDES these libraries in the `embedded/lib` folder.  Seems it should be looking for them there, not ins `/usr/local`

**Comment by MikeMcQuaid** [comment]
> I'm not sure if the problem is a brew problem or a formulae problem. I've had 0 issues with any other formula. Yes, I'm aware my install is in .brew. This has not been a serious problem with any other packages in the past and I'm hoping this also can be resolved.

Just a note that it seems likely that this is the issue and as a non-default configuration this may not be a high priority for us to fix.

**Comment by halostatue** [comment]
I have had previous problems with the crystal-lang formula that I have not had with other formulae on Homebrew, because the folks behind crystal-lang have not apparently heard of relocatable builds (I was not happy with the last interaction I had with them relating to a link issue because I install to a different location than they assume I should, although I think that they may have fixed the problem—but I can’t be sure since I now can’t build crystal-lang anymore).

I currently have 0.20.0 installed (built successfully on Sierra) and the following are the changes for crystal-lang (not counting bottle changes, generated with `git log -- crystal-lang.rb | grep '0\.20' | grep -v bottle | sed '1!G;h;$!d'`):

07d65469d 2016-11-22 | crystal-lang 0.20.0 [Ary Borenszweig]
a997839f4 2016-12-05 | crystal-lang 0.20.1 [Ary Borenszweig]
50ee6b8e3 2016-12-23 | crystal-lang 0.20.3 [Ary Borenszweig]
2ce44f9c3 2017-01-06 | crystal-lang 0.20.4 [Ary Borenszweig]
fe7fa7593 2017-01-20 | crystal-lang 0.20.5 [Ary Borenszweig]

Of interest, a997839f4 (0.20.1) and 50ee6b8e3 (0.20.3) change `ENV["CRYSTAL_CONFIG_PATH"]`:

```diff
-    ENV["CRYSTAL_CONFIG_PATH"] = prefix/"src:libs:lib" # 0.20.0
+    ENV["CRYSTAL_CONFIG_PATH"] = prefix/"src:lib:libs" # 0.20.1
+    ENV["CRYSTAL_CONFIG_PATH"] = prefix/"src:lib" # 0.20.3
```

These changes look potentially suspicious and not related to the changing of the source code. I don’t have time or desire to debug this further at this point (I have other things to accomplish in the next few days that have greater value; I won’t get back to this for a couple of weeks at least), but it would be worth seeing if varying these values makes a difference when building in `~/.brew`.

**Comment by ilovezfs** [comment]
>dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.1.dylib

This is caused by the fact that you're using a non-standard prefix and the bootstrap binary assumes that brew is installed in /usr/local.

We can work around this, just as I did for libevent here https://github.com/Homebrew/homebrew-core/pull/9389, by vendoring bdw-gc during the build.

Upstream may look into making this more robust in the future possibly by using static linking. See https://github.com/Homebrew/homebrew-core/pull/9389#issuecomment-275889827.

CC @asterite

**Comment by ilovezfs** [comment]
I've opened https://github.com/Homebrew/homebrew-core/pull/9499 vendoring bdw-gc.

**Comment by ilovezfs** [comment]
@yyyc514 @halostatue it should be fixed now.

**Comment by halostatue** [comment]
Thank you.
