### ISSUE TITLE
sha256sum mismatch when building netcdf from source

### ISSUE THREAD

**Issue by ipatch** [Homebrew/homebrew-core#95915]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

https://gist.github.com/ipatch/9740fefd0a4753e31df7bbd3bb2365d7

```shell
Error: SHA256 mismatch
Expected: 6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445
  Actual: fb49efac53117e7760662f9d6654d616a3a304a3bdcaf4d794dfd040ee6475b9
    File: /Users/capin/Library/Caches/Homebrew/downloads/60008bd4a4b82237539c0853d7d66598828980676475b9ae07459297ffd9d888--netcdf
To retry an incomplete download, remove the file above.
```

it wouldn't happen for most, as most would just install the bottle and not build a package from source but using the below command can reproduce the error

```
brew install netcdf -v -s
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

trying to build/install netcdf from source

### What happened (include all command output)?

```
Error: SHA256 mismatch
Expected: 6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445
  Actual: fb49efac53117e7760662f9d6654d616a3a304a3bdcaf4d794dfd040ee6475b9
    File: /Users/capin/Library/Caches/Homebrew/downloads/60008bd4a4b82237539c0853d7d66598828980676475b9ae07459297ffd9d888--netcdf
To retry an incomplete download, remove the file above.
```

### What did you expect to happen?

the correct sha256sums to match

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install netcdf -v -s
```

**Comment by cho-m** [comment]
Upstream has changed download URL for resource, so it is fetching an HTML webpage instead: https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-cxx4-4.3.1.tar.gz

The mirror is still correct, but it didn't fallback to this since the main URL did respond (even if it redirected to a webpage rather than a Tarball file).

The correct URL is now https://downloads.unidata.ucar.edu/netcdf-cxx/4.3.1/netcdf-cxx4-4.3.1.tar.gz

We can probably fix it along with `livecheck` issue in #95849
