### ISSUE TITLE
kibana 5.2.0 formula doesn't work properly

### ISSUE THREAD

**Issue by salvob41** [Homebrew/homebrew-core#9770]
Kibana is now at its 5.2.0 version.
Even if `homebrew` after a `brew update/brew upgrade` command says that the kibana package is upgraded to 5.2.0 it is actually still at its 5.0.0 version as shown in [kibana formula link](http://brewformulas.org/Kibana).

The error that made me realise is shown in this [issue](https://github.com/elastic/kibana/issues/10240)

**Comment by ilovezfs** [comment]
@jasontedor I'm not sure how to interpret this issue, let alone the remarks here: https://github.com/elastic/kibana/issues/10240#issuecomment-278450895 which would usually be sufficient reason to remove kibana from Homebrew entirely.

**Comment by jasontedor** [comment]
See the discussion on Homebrew/legacy-homebrew#46593 for more context. My preference has always been that Homebrew just distribute the officially-packaged versions of Kibana but my understanding is that that is not possible because it's considered a binary release (I guess because of the packaged node.js?). Perhaps we should reconsider migrating this to a cask if including it in core is not possible. Do you mind weighing in on this again @DomT4?

**Comment by DomT4** [comment]
> Even if homebrew after a brew update/brew upgrade command says that the kibana package is upgraded to 5.2.0 it is actually still at its 5.0.0 version as shown in kibana formula link.

I'm not sure this is correct? That website isn't an official one. If the formula is using a correct 5.2.0 tag & respective hash it should be 5.2.0.

> Do you mind weighing in on this again @DomT4?

I left the project, so essentially it's @ilovezfs's ball to decide where to hit. To be honest Homebrew already bends its own rules on the no binaries, `heroku` embeds or downloads-at-initial-run its own `node` to run against. I remain unconvinced that's ever an ideal position for Homebrew to be in because if a security issue, for example, pops up Homebrew is at the mercy of upstream in releasing a fix rather than simply being a case of add patch, bump revision, problem fixed.

The Cask probably isn't a bad compromise, if they'll take it, for what my opinion is worth sans power.

**Comment by ilovezfs** [comment]
Moving it to ask when it can be built from source is usually not OK but that may be where we ultimately land.

That said, I'm confused by what's been said so far. As far as I can tell, we use the correct hash for this version and we use the correct version of node, installed in libexec, at run time. What am I missing?

**Comment by epixa** [comment]
Kibana has two executables at the moment: one to run the server and the other to manage plugins. The homebrew formula changes the path to node in `bin/kibana` to use the node binary that it compiled from source, but `bin/kibana-plugin` still points to the path from the release builds, which doesn't exist here. Purely for development purposes, if node isn't at the expected location, the binary will use whatever node is available on the current PATH, which is what the users were encountering in the linked Kibana issue.

So the homebrew formula needs to be updated to change the node path in the plugin executable as well.

And unrelated to homebrew, Kibana really shouldn't be shipping with this development fallback, so the CLI tools would flat out error on missing node binaries rather than using a fallback with unexpected results.  I'll file an issue for that now.

**Comment by jasontedor** [comment]
>That said, I'm confused by what's been said so far. As far as I can tell, we use the correct hash for this version and we use the correct version of node, installed in libexec, at run time. What am I missing?

It's a bug in the formula for the plugin script. It's easy to fix but I was hoping to just shift to the official binaries to avoid this maintenance burden.

**Comment by jasontedor** [comment]
Thanks @epixa. I agree.

**Comment by jasontedor** [comment]
For now I've opened #9770 but I would like to come to resolution on just distributing the official binaries. It looks to me like the Heroku formula indeed embeds node.js exactly as @DomT4 said which is exactly what I want to do with the Kibana formula. Therefore, I'd like to propose a PR for Kibana to do the same. I have a counter to the security argument: Homebrew would have to wait for upstream to release a fix anyway (Elastic has responsible disclosure policies and would not disclose the issue before a fix is available) before it can bump anything so it shouldn't matter if it's a tag bump or a bump to the new version built from the tag.

**Comment by jasontedor** [comment]
> I left the project

Thanks for weighing in @DomT4, I appreciate it. Thanks for all of your help on past Homebrew issues and I wish you the best of luck in your future endeavors.

**Comment by ilovezfs** [comment]
@jasontedor I'm not sure about all the circumstances with Heroku, but if we can continue to build Kibana from source correctly, then we should.

**Comment by MikeMcQuaid** [comment]
Agreed with @ilovezfs. Similarly we should nudge/work on making Heroku do the same.

Thanks @jasontedor, as usual.

**Comment by DomT4** [comment]
> I'm not sure about all the circumstances with Heroku

Initially it was just a gem IIRC, and the transition to Node wasn't announced when we accepted the PR which changed that, and then nobody cared enough to fix it essentially. Working off memory though, and you remember how bad that is 😉.

> Thanks for weighing in @DomT4, I appreciate it. Thanks for all of your help on past Homebrew issues and I wish you the best of luck in your future endeavors.

Thanks for the kind words @jasontedor. These `kibana` formulae were not always easy to keep within Homebrew conventions and I appreciate how much patience & respect you had dealing with both that & me trying to enforce that.

**Comment by DomT4** [comment]
It looks like a from-source `heroku` would need both `node` and `go` to [build](https://github.com/heroku/cli/blob/a1bddc792fa32f3e6079c51a7422dac50bf9b0a5/Makefile). There be dragons.

**Comment by ilovezfs** [comment]
I assume it could use the go formula though, no?

**Comment by DomT4** [comment]
Looks like it. Looking at that file it doesn't care which `go` is used, although the flags respect the newer strict syntax which is a good sign.

Looks like it'd want a custom `node` though, which it would need to keep to run against presumably in the same way `kibana` here does, and there are `node` and `npm` downloads in the `Makefile` that I guess you'd want to trick or `inreplace` out for the sake of caching/checksumming/etc.

**Comment by ilovezfs** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/9777.

**Comment by salvob41** [comment]
still same error appears after a `kibana-plugin install x-pack`
why is this happening? Do I need to update something in particular? Do I need to wait till the next release of `brew`?

**Comment by jasontedor** [comment]
@salvob41 I opened #11360.

**Comment by dickeyxxx** [comment]
To be clear, our v6 CLI we recently launched no longer installs node on first run and does not use go at all. Node is packaged inside the tarball that is downloaded with brew.

**Comment by ilovezfs** [comment]
@dickeyxxx regardless, Heroku, like everything else in Homebrew, will need to be built from source.

**Comment by dickeyxxx** [comment]
Now that it's all in node that should be much easier to do. The CLI in general is far simpler now than it was last year. I may take a rough stab in the morning to figure out how we might be able to have it work with --build-from-source

**Comment by ilovezfs** [comment]
Thanks @dickeyxxx!
