### ISSUE TITLE
CI: stop using workaround for cache issue

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/homebrew-core#98676]
We have this line in our CI scripts:
https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/publish-commit-bottles.yml#L41-L42

Unfortunately, that PR is rejected so we'll need to find a better way to resolve the issue we had that prompted this PR.

**Comment by SMillerDev** [comment]
Related to: https://github.com/actions/toolkit/pull/580 and https://github.com/Homebrew/homebrew-cask/pull/121525

**Comment by Bo98** [comment]
I think this requires some changes to Homebrew/actions/setup-homebrew - it's just been low priority for me. The workaround isn't needed on our self-hosted runners due to the already different logic for them.

Backwards compatibility is a considerable concern when performing any changes to that action due to the widescale usage of it in third-party taps.

**Comment by dawidd6** [comment]
We can always scope new changes just to official core tap.

**Comment by cho-m** [comment]
Is there anything left here after https://github.com/Homebrew/homebrew-core/commit/b40fb364e234e598291f8ec7d869da07a57ce539?

**Comment by Bo98** [comment]
There shouldn't be. If there is, it'll be outright broken now.
